from pathlib import Path
import hashlib,json,datetime
r=Path(__file__).resolve().parents[4]
sha=lambda p:hashlib.sha256((r/p).read_bytes()).hexdigest()
rows=[
('01','Nightglass Courier',['NG04-F1'],['Thin controlled contour lines, angular hair locks and sharply bounded planes on clothing are retained, alongside gently shaded faces. Broad navy values and selective cyan edge light support the same digital anime drawing treatment.','Surface finishing reduces architecture/leaf/ground microdetail while keeping the contact and face hierarchy.'],['Bodies are more muscular and heavily shaded than the slender original; not just a palette change, but not exact line economy either. Persistent ray motif is not evidence of medium fidelity.'],'Substantial treatment continuity'),
('02','Sunbreak Lancer',['SB01-F1'],['Crisp outer contours, flat warm sun/shadow planes and painterly cut-shape masonry retain the original illustrated character/world relationship. Bright clean sky and large cloth color shapes remain.'],['New cloth and metal use more smooth volume shading; painterly abrasion is reduced. Faceted cat and flag colors alone would be insufficient evidence.'],'Substantial treatment continuity'),
('05','Iron Orchard',['IO01-F1'],['Earthy opaque paint shapes, subdued sky, matte cloth and grouped foliage remain distinct from glossy anime. Broad rust patches and blocked shadow masses preserve an illustrated-industrial look.'],['Mechanical cylinders and muscle volumes are more smoothly modeled than original rough gouache-like broken planes. Medium recovery is partial even though rust/orchard/machine motifs match strongly.'],'Moderate-to-substantial, with smoother volume drift'),
('06','Floodline Detective',['FL01-F1'],['Large solid blacks, white cutouts, sparse hot-pink field and rough ink-edge marks retain a graphic ink language. Simplified water has fewer competing reflection flecks.'],['Glossy trousers and detailed mechanical monster rim use smoothly modeled highlights; the original face/clothes were more visibly brush-scraped. Brush marks in frame corners alone do not establish full medium recovery.'],'Partial-to-substantial graphic ink continuity'),
('13','Red Current',['RC01-F1'],['Strong black/white silhouette separation and a localized red impact accent remain; thin structural contours still give a drawn edge.'],['Original had pervasive purposeful pen hatch shading on face, body and clothes. New muscles, trousers and creature are much smoother and shinier with fewer directional pen strokes. Palette and shark geometry transfer more strongly than actual hatching medium.'],'Partial; meaningful medium drift'),
('15','Cathedral Engine',['CE01-P','CE01-F1'],['Primary preserves dense contour-following engraved hatching, fine architectural linework and ink-on-sepia-paper character. This is actual mark-making correspondence, not merely bronze palette/bell motifs.'],['F1 removes much of this line-based tone from bell, shield, clothing and distant structures, replacing it with broad smooth gradients. Quieter surface is real, but it weakens engraving identity substantially. P has stronger medium fidelity despite its visually tiring density; neither is an unqualified resolution of both demands.'],'Primary strong; finish noticeably weaker medium fidelity'),
('17','Hollow Cartographer',['HC01-F1'],['Thin consistent outlines, broad flat terracotta architecture, warm restrained shadow planes and simplified expressive face survive into a new action composition. More than palette/tortoise association.'],['Roots and armor have added soft volume shading, but overall hand-drawn storybook contour/shape hierarchy remains. Some vines still carry busy repeated small leaves.'],'Substantial treatment continuity'),
('18','Soft Thunder',['ST03-P'],['Expressive thick eyebrows/mouth, rounded drawn contours and opaque block-painted clouds/body surfaces carry over. Deliberately elastic body/face design is distinct from NG/BP.'],['Ram surface has many individually shaded wool lobes, denser than original serpent large broad color patches. Heroine closely resembles anchor appeal cues, so this is medium evidence, not proof of new identity originality. F1 unavailable at this audit freeze.'],'Substantial treatment continuity with surface-density drift'),
('19','Black Petal',['BP04-F1'],['Fine hair edges, softly modeled pale face, restrained desaturated values and controlled dark silhouette retain the original gothic portrait illustration medium. Broadening petal/moss surfaces does not turn it into cel-shaded anime.'],['New skin is somewhat sharper and coat more faceted; dense silver crown structure remains. Glasshouse/flower recurrence is motif transfer and should not be counted as sufficient style evidence by itself.'],'Substantial treatment continuity')]
records=[]
for n,name,aids,observations,caveats,verdict in rows:
 ap=f'production/anchor-return/references/anchor-{n}.png'
 images=[]
 for aid in aids:
  p=f'production/anchor-return/candidates/{aid}.png'; cp=f'production/anchor-return/calls/{aid}.json'
  call=json.loads((r/cp).read_text())
  images.append({'attempt_id':aid,'path':p,'sha256':sha(p),'call_path':cp,'call_sha256':sha(cp),'actual_call_references':call['references'],'native_inspected':True})
 records.append({'direction':name,'original_anchor':{'path':ap,'sha256':sha(ap),'native_inspected':True},'new_images':images,'medium_observations':observations,'limits':caveats,'reviewer_assessment':verdict,'owner_approval':None})
payload={'schema':'AnchorReturnMediumFidelityReview/1','reviewer':'combat_reference_research','reviewed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'method':'Actual native originals and representative new images inspected directly. Compares contour character, mark-making, tonal construction and edges, separately from palette/motifs. Medium terms describe visible treatment; no claim of physical production medium. No web research, no image generation, no preferences inferred.','summary':'Nine drawing directions remain visibly differentiated. NG, SB, HC, ST and BP show substantial treatment continuity; IO and FL retain strong traits with smoother rendering. RC hatching recedes. CE primary has clear engraving treatment, but F1 trades much of it for smooth tonal surfaces: calmer does not automatically mean faithful.','records':records}
(r/'research/anchor-return/control-review/transfer/anchor-medium-fidelity.json').write_text(json.dumps(payload,indent=2)+'\n')
