from write_review import freeze
freeze('batch-02-NG-BP.json',{
'NG05-P':{'transferred':['High tilted view, low evasive hero, actual RIGHT pommel to right-rail anchor line, clear gap below missed spear. Left seam tear persists.'],'gaps':['Only high oblique rather than true overhead; hero large in foreground and rear foot/support partly obscured. Line passes behind torso, but both visible endpoints match.'],'priority':'No causal repair priority.'},
'NG08-P':{'transferred':['No tether, separated cast, right doorway and ray/city return. Rear three-quarter viewpoint.'],'gaps':['Hero occupies nearly full image height, losing extreme-wide small-figures control. Injury on anatomical RIGHT sword shoulder, not planned LEFT; he protects right with left hand.'],'priority':'Scale/state caveat, not preferred over fixing active power causality.'},
'BP01-P':{'transferred':['One botanical root with thorn foot visibly suspended above floor; small heroine versus giant bloom, left bright door, intact coat and correct right saber/left guard.'],'gaps':['Root rendered as tightly braided strands within one trunk; fine petal veining and moss texture dominate surfaces.'],'priority':'Opening causal state clear.'},
'BP02-P':{'transferred':['Supported lunge and metal edge meets front petal; narrower partially closed flower compared with opening.'],'gaps':['Root thorn foot visibly touches floor, one beat earlier than planned plant. Saber held in anatomical LEFT hand wearing forearm guard; right arm behind. Center remains open rather than armored fully closed.'],'priority':'Early state and hand-role failure; localized root lift alone would leave hand failure.'},
'BP03-P':{'transferred':['Thorn foot grounded, single trunk bends under heavy flower, heroine steps away with correct right saber and left guard, coat intact.'],'gaps':['Bloom silhouette remains frontal and expanded; committed windup direction inferred more from sequence than clearly loaded petal pose.'],'priority':'Broad state transfer works.'},
'BP04-P':{'transferred':['Dynamic close forward duck, left guarded hand near head, right saber low forward; petal crosses behind upper back and torn rear coat is visible. Root planted.'],'gaps':['Petal tip approaches head/upper back while cloth tear occurs farther back; exact petal-to-tail contact is less clear than the overall near miss. Foot support partly cropped by intended close view.'],'priority':'Strong movement transfer; do not mistake readable dodge for exact tail-contact proof.'},
'BP05-P':{'transferred':['High overhead view, heroine on left flank near white doorway, separated reachable root lane and grounded root, no new weapon contact.'],'gaps':['Bloom again faces viewer; without a distinctive side/back it is hard to verify fixed facing relative to old target. Damage appears on multiple tail strips rather than one specific left corner.'],'priority':'Geography improved; rotation lock remains unproven.'},
'BP06-P':{'transferred':['Low wide supported advance, right arm crosses torso into saber, left guarded arm protects ribs; root intact and planted.'],'gaps':['Blade tip visually touches root; there is no handspan gap for the planned pre-impact frame. Coat now shredded across multiple tails, inflating damage beyond prior single corner. Creature retains frontal presentation.'],'priority':'Timing gap: do not caption as visibly short of contact.'},
'BP07-P':{'transferred':['Clear actual air gap between severed root and planted stump; blade through gap, heavy bloom tilted, two grounded spread legs; no gore.'],'gaps':['Saber now in anatomical LEFT guarded hand, reversing prior frame. Stance is wide planted finish rather than visibly skidding both boots. Extra loose leaves add surface activity.'],'priority':'Strong sever consequence despite hand continuity failure; no repair priority ahead of missing causal path.'},
'BP08-P':{'transferred':['Collapsed petals resting on floor, oval center visible, physically separate upright stump, heroine kneels with right saber tip grounded and left guard visible. Shaken/downward gaze.'],'gaps':['Tears spread across multiple tail strips and extend below knees; damage is more extensive than initial corner. Creature/root does not rejoin stump.'],'priority':'Strong aftermath transfer.'}
},'Ten further native primaries inspected with exact referenced controls verified. BP sever and collapse read clearly; root timing, saber hand and precise flank lock are inconsistent. NG05 transfers power endpoints; NG08 loses extreme-wide scale and planned injury side. No owner preference inferred.')
