from pathlib import Path
import json
R=Path(__file__).resolve().parents[2];P=R/'production/nightglass-refinement'
s=json.loads((P/'selected.json').read_text());s['selected'].update({'S05':'S05-R1','A04':'A04-R1'});(P/'selected.json').write_text(json.dumps(s,indent=2)+'\n')
by={c['attempt_id']:c for c in json.loads((P/'candidates.json').read_text())['candidates']}
notes={
'T01':['Grouped paving reflections and fewer stray ribbon marks make the same leap easier to separate from the city. Character, fox, ledges and deep gap remain.','Brightness/reflections also changed, so this is not isolated causal proof about texture. Some window and paving detail remains; the travel rule is still less explicit than the leap.'],
'T02':['The same giant Regent is described with broad armor and throat shapes instead of a crack mosaic; both adults, weapons and inhabited scale survive.','It looks more polished and graphic, with less granular material richness. Dark or occluded leg origins remain uncertain.'],
'T03':['The adult face, crooked smile, swept silver hair and saber remain recognizable with cleaner hair, cloth and background grouping.','This is a matched finish study of existing Riven, not a new cast choice. The narrow ledge and old stance remain inherited.'],
'T04':['Broad shoulder and head plates replace much of the bright crack mosaic while four paws, pale jaw and predatory weight remain.','The material is smoother and more polished; some limb and ground marks persist. Whether this balance is comfortable is still your decision.'],
'S01':['The dawn arch gives the world horizontal scale and preserves recognizable Riven and Senn with their weapons. The displayed repair gives Senn an actual lance grip.','Salt chips and reflection detail remain substantial; terrain quieting is only partial. Both attempts remain in history.'],
'S02':['Iria’s empty palm, small smile and the hare’s lifted paw carry a clear quiet interaction. Her Wraithlock stays holstered.','The shore still has many small chips and the water/cliffs retain texture. The fantasy hare has a more elongated, canine-like build than an ordinary rabbit.'],
'S03':['Warm outlined drawing, a broad ramp and monumental seal give this scene a clear focal hierarchy and room to breathe. Elowen and her undrawn bow remain recognizable.','Broad wall mottling remains. The regional warm treatment is a comparison, not approved canon; bow-tip string attachment is not fully resolved.'],
'S04':['Senn, her connected two-hand lance and the toad’s mouth-source blast form a readable counterattack with a genuine pre-contact gap.','Spray, mottled skin and rocky/cloud texture remain busy. The forward landing destination and obscured hindquarters are not fully demonstrated.'],
'S05':['The displayed redraw replaces dense snow flecks and crag marks with broad wind and snow shapes, retaining Neris, Dax’s right gauntlet and the protective stance.','The weather looks more stylized and ribbon-like. Some snow hides lower support points; this is a visual concept, not validated combat choreography.'],
'S06':['Recognizable Riven and Iria overlook a dam threatened by the huge serpent, with their established saber and holstered gun.','Clouds, ripples and creature fronds remain busy. The serpent retains fine projections and uncertain rear-body overlap from its source instead of the planned smooth body.'],
'C01':['Neris has a calm expressive face, clear white/teal costume masses and a connected shield grip. The same design recurs in the snow and counter scenes.','She is slimmer than the broad-athlete brief; wet paving and the architectural backdrop remain more elaborate than intended.'],
'C02':['Kellan’s grin, curls and sand/cobalt silhouette differ from the other adults. Both sword hands stay behind the guard.','Background reflections and hair detail remain fairly dense. His ice ability is provisional, with no owner selection inferred.'],
'C03':['Elowen’s alert expression, braid and long silhouette read clearly; the same bow and identity recur in warm discovery and an ability shot.','Bow string attachment near the lower tip remains uncertain. Freckles are intentional facial design; other surfaces still carry some detail.'],
'C04':['Corven’s mature face, strong black/white costume and held dagger preserve the graphic Floodline treatment.','Scratch work remains pervasive on face, beard and cloth. This comparison does not fully meet the calmer-surface target.'],
'G01':['The repair isolates the complete navy crescent shield and attached rear mounting, making the equipment much easier to judge.','The short forearm fades out mid-image rather than entering an edge. This is a partial presentation repair.'],
'G02':['The repaired sword is complete and both hands are now on the pommel side of the guard; the primary’s blade contact is removed.','Hands overlap closely rather than occupying clearly separated grip zones. Material finish is deliberately simple.'],
'G03':['The repair removes the copied Sunbreak character and market, leaving the new ivory/green bow for independent review.','The lower string termination and wrist route remain unclear. This is an unresolved construction detail, not a fully validated bow.'],
'W01':['The four-legged Salt Hare has a cautious lifted paw, long ears, dark feet and a clear small-resident role in its habitat.','Fur tufts, salt chips and cloud marks remain. Its elongated fantasy anatomy should be judged separately from drawing appeal.'],
'M01':['The toad’s planted weight, visible mouth and inflated throat suggest a readable inhale-and-blast encounter.','The pale throat has a conspicuous crack/vein network and the skin is heavily mottled. The far hindlimb is occluded; this is a significant remaining texture weakness.'],
'M02':['The serpent and low dam create impressive scale with a clear warm/cool dusk relationship.','Fine fronds, throat facets and busy reflections depart from the planned smooth legless form. Rear arc/tail continuity is partly hidden.'],
'A01':['Kellan’s two-hand hilt grip, blade-water contact, rising ice line and tilted training weight give the ability a readable causal chain.','Water and ice retain many small highlights. A still image suggests the stop; it does not demonstrate the entire moving sequence.'],
'A02':['Elowen’s released-shot pose, one undrawn string and one arrow at the toad’s forefoot are visible.','The solid anchor and arrested forward pitch are not clearly established; the toad looks seated. This remains an incomplete ability demonstration with dense skin and ground texture.'],
'A03':['Corven, one dagger, a bright source and a dimmer downstream target give some evidence of interrupted magical supply.','The blade lies along the connection and the small break is near its tip; at phone size it can read as emission or interception rather than a clear cut.'],
'A04':['The displayed retry removes the huge rear spray and reduces mottling, retaining Neris’s counter and the toad’s recoil.','The shield repair FAILED: the grip remains on the creature/contact side while her arm approaches from the other side. The crescent is narrower and the arm more exposed. Selected for texture relief only; construction and action are not accepted.']}
assert set(notes)==set(s['selected'])
out={'schema':'NightglassRefinementReviewNotes/1','experiment_id':'NR-20260908-01','owner_approval':None,'entries':{id:{'attempt_id':s['selected'][id],'sha256':by[s['selected'][id]]['sha256'],'observations':n} for id,n in notes.items()}}
(P/'review-notes.json').write_text(json.dumps(out,indent=2)+'\n')
Path(R/'research/nightglass-refinement/final-repair-adjudication.md').write_text('Display S05-R1 for substantial texture relief with retained two-adult acting, right Dax gauntlet and functional shield brace. Its weather is more stylized/ribbon-like but depth and identity remain. Display A04-R1 solely for removed spray and reduced mottling; the shield front/back repair FAILED. Hardware still faces the toad while the adult reaches from the opposite side, and the crescent became narrower. Do not count it as a corrected action or construction. Both root and independent reviewer inspected exact native and390px history outputs; all prior attempts retained. Generation is closed at24P+6R. No owner choices or canon inferred.\n')
print('24 source-bound notes, six displayed repairs (some partial/failed target)')
