from pathlib import Path
import json, hashlib, collections
out=Path(__file__).resolve().parent
entries=[]
def add(id,category,style_id,title,caption,visual_brief,related_ids=(),dependency_ids=(),**extra):
    entries.append(dict(id=id,category=category,style_id=style_id,title=title,caption=caption,visual_brief=visual_brief,related_ids=list(related_ids),dependency_ids=list(dependency_ids),**extra))
def power(name,description,limitation,growth):return dict(name=name,description=description,limitation=limitation,growth=growth)
def weapon(name,description):return dict(name=name,description=description)
saber=weapon('Seam Saber','One long single-edged dark saber with one uninterrupted cyan groove, a solid conventional guard and one black grip. All parts physically connected; no floating guard, spare blade or orbiting copy.')
lance=weapon('Crownfall Lance','One continuous dark shaft with two unobstructed grip zones and one broad ivory spearhead containing a single deep central notch. The head remains one connected part; no extra side weapons or loose rings.')
pistol=weapon('Wraithlock','One large fantasy pistol with a single rectangular barrel, one ordinary angled grip, one trigger guard, one ivory side plate and a small cyan chamber. No second barrel, second gun or detachable floating component.')
gauntlet=weapon('Thunderheart','One enlarged ivory armored RIGHT gauntlet with articulated knuckle shell and one continuous forearm cuff. Clearly attached to his right forearm; his left hand remains ordinary and uncovered. No hammer, second powered glove or detached fist.')
axe=weapon('Dawn Hew','One two-handed battle axe with ONE broad green crescent head on a continuous short dark shaft. Solid center attachment and two grip areas. No rear blade, extra spear point or second axe.')
greatsword=weapon('Black Verdict','One broad black greatsword with one stepped point, a solid white guard and continuous handle/tang; one short pink line near the blade root. No chain, second edge assembly or floating ornaments.')
p1=power('Between Steps','Opens a narrow passage between two nearby visible fault seams, letting him cross the intervening gap in one committed step.','He must see an intact landing seam and commit his whole body; he cannot hover or change destination midway.',['Cross one broken walkway.','Carry momentum through a seam into a precisely timed counter.','Pass a guarded spatial boundary by recognizing its hidden continuation.'])
p2=power('Royal Weight','A clean lance strike marks a target with oppressive weight, driving a charging body toward the ground.','Requires a planted stance and real weapon contact; resisting a heavier target strains her own legs and shaft control.',['Halt one charging predator.','Shift the burden to one limb and force a kneeling opening.','Redirect the balance of a colossal creature without becoming weightless herself.'])
p3=power('Named Shot','One deliberate hit leaves a spirit-brand; a later shot can pursue the marked quarry through concealment.','Only one quarry can be named at a time; the first shot still needs a clear aim and the follow-up cannot ignore solid cover without a passage.',['Track one hidden quarry.','Distinguish a marked true body from decoys.','Borrow a defeated quarry’s tracking instinct as one brief spectral companion.'])
p4=power('Second Heart','Stores lightning in his armored right fist and releases it as a single directed concussive strike.','Stored charge drains while he hesitates; an uncontrolled release numbs his own striking arm.',['Break one obstacle with a precise thunder punch.','Convert a falling landing into a directed ground shock.','Sustain a brief storm-body state while maintaining a readable physical stance.'])
p5=power('Sunwake','Absorbs sunlight into the axe edge and spends it on one bright cutting plane.','Needs accumulated light and a committed physical swing; extended shade leaves the weapon ordinary.',['Release one sunlit cleave.','Hold a reserve through a dungeon descent.','Kindle a brief phoenix-shaped protective flare at the end of a successful swing.'])
p6=power('Quiet Oath','Uses the broad blade to cut a narrow dead zone in an incoming pressure wave, protecting someone directly behind him.','Protection depends on his planted stance and blade orientation; moving his feet or being flanked breaks the corridor.',['Shelter one person directly behind the blade.','Widen the protected corridor while holding the same ground.','Maintain a longer corridor against a sustained pressure wave without chasing the attack.'])
char_common=' One new adult, same identity throughout. Show an expressive face and complete combat-ready body with one signature weapon and a quiet, spatially believable setting. No extra character, alternate costume, decorative weapon inventory or baked text. Clean modern tailoring and armor with a clear protective purpose; full feet and full weapon within frame.'
characters=[
('C01','01','Riven Hale',27,'man','A relaxed duelist who commits to impossible crossings.','Tall lean long-legged build; a narrow face with heavy-lidded eyes and a restrained crooked smile; collar-length silver hair swept backward. Deep petrol cropped combat jacket over fitted charcoal high-neck layer, one practical black shoulder shell, straight tapered trousers and flat armored boots. Stand lightly on the front foot, saber carried low outside the body with one clearly wrapped hand; the other hand relaxed. His hair, face and dark cropped jacket must differ from the original black-haired white-jacket courier and the platinum-bob Aster.','Narrow adult face, heavy-lidded eyes, straight nose, restrained crooked smile.','Collar-length silver hair swept backward, not a bob.','Tall, lean, long-legged athletic adult.','Petrol cropped combat jacket; charcoal fitted high-neck layer; one black shoulder shell; tapered trousers; flat armored boots.',saber,p1,['G01','A01','S01','S06'],['G01'],'Light cool complexion.'),
('C02','01','Senn Ardent',29,'woman','A commanding lance fighter who brings charging giants to their knees.','Tall powerful broad-hipped athlete with a long square face, strong nose, heavy brows and a warm challenging grin. Chestnut hair in a high thick ponytail with shaved nape. Fitted navy longline combat vest and rigid ivory breastplate, bare muscular arms, black trousers broad at the thigh and tapered into heavy greaves. Wide planted guard, both hands clearly wrapping separated zones of the lance; uninterrupted shaft outside the torso. No dress or cape.','Long square face, strong nose, heavy brows, warm challenging grin.','Chestnut high thick ponytail with shaved nape.','Tall powerful athlete, strong shoulders and broad hips.','Navy longline combat vest; ivory protective breastplate; bare muscular arms; black tapered combat trousers; heavy greaves.',lance,p2,['G02','A02','S04','S06'],['G02'],'Light neutral complexion.'),
('C03','01','Iria Noct',25,'woman','A precise hunter whose second shot remembers its quarry.','Petite compact athlete with a rounder face, wide alert eyes, straight dark brows and a small purposeful mouth. Blue-black straight hair in a low ponytail with a blunt short fringe. Oxblood asymmetric zip jacket, black fitted trousers, silver forearm guard on the gun side. Focused level stare and composed three-quarter guard, single pistol held safely low outside silhouette with finger visibly outside the trigger. Her other hand is empty.','Rounder adult face, wide alert eyes, straight brows, small purposeful mouth and focused stare.','Blue-black low ponytail with short blunt fringe.','Petite compact athletic adult.','Oxblood asymmetric zip jacket; black fitted trousers; silver weapon-side forearm guard; plain dark boots.',pistol,p3,['G03','A03','S03'],['G03'],'Light olive complexion.'),
('C04','01','Dax Verran',39,'man','A controlled heavyweight whose armored fist holds a second heartbeat.','Heavy athlete with a square weathered face, thick neck, short straight salt-and-pepper hair and a trimmed angular beard. Tight restrained smile, not a jolly open grin. Sleeveless charcoal tailored battle coat ending at the hip, broad teal armored chest, fitted dark trousers and pale substantial boots. Grounded compact boxer stance; the enlarged RIGHT ivory gauntlet is held forward clear of his chest, ordinary uncovered LEFT hand guards his ribs. No copper curls, youthful round face, massive cape or second weapon.','Square weathered adult face, firm brows, trimmed angular beard and tight restrained smile.','Short straight salt-and-pepper hair.','Heavy trained athlete with thick neck and powerful grounded legs.','Hip-length sleeveless charcoal tailored battle coat; teal armored chest; fitted dark trousers; pale substantial boots.',gauntlet,p4,['A04','S05'],[],'Light neutral complexion.'),
('C05','02','Solene Varo',28,'woman','A fierce sunlit axe fighter who carries daylight below ground.','Medium-tall sinewy athlete with LIGHT warm-tan skin, broad nose, high cheekbones and lively long eyes. Short dense black curls with a clean side part. Ochre cropped military jacket, fitted blue armored torso, cream split riding panels over dark trousers, green shin guards. Fierce teeth-bared delight and a forward-driving balanced stance; both hands clearly wrap the one short axe shaft. Distinct from the copper-braided spear anchor.','Broad nose, high cheekbones, lively long eyes and fierce teeth-bared delight.','Short dense black curls with a clean side part.','Medium-tall sinewy athletic adult.','Ochre cropped military jacket; blue armored torso; cream split riding panels; dark trousers; green shin guards.',axe,p5,['G04','S02'],['G04'],'LIGHT warm-tan complexion.'),
('C06','06','Vale Sorn',30,'man','A quiet greatsword guardian who cuts shelter out of an incoming wave.','Very tall narrow-waisted swimmer build, long angular face, deep-set eyes and full lower lip. Jaw-length dark-blond center-parted straight hair, clean shaven. White close-fitted high-collar armored vest beneath a black single-shoulder rain mantle, narrow black trousers and substantial white boots. Grave direct gaze. Both feet visibly planted, one broad sword held in a stable two-hand guard with a clean gap from the body. Do not turn him into the older buzz-cut Floodline detective or a shadow-summoning defeated-spirit collector.','Long angular face, deep-set eyes, full lower lip, clean shaven, grave direct gaze.','Jaw-length dark-blond center-parted straight hair.','Very tall narrow-waisted muscular swimmer build.','White fitted high-collar armored vest; black single-shoulder rain mantle; narrow black trousers; substantial white boots.',greatsword,p6,['S03'],[],'Light neutral complexion.')]
for id,sty,name,age,gender,cap,vis,face,hair,build,costume,weap,powr,related,deps,complexion in characters:
 add(id,'character',sty,name,cap,vis+char_common,related,deps,age=age,gender=gender,face=face,hair=hair,build=build,costume=costume,weapon=weap,power=powr,complexion=complexion)
gear=[('G01','01',saber,'A clean blade that makes a missing step feel possible.',['C01','A01','S01','S06']),('G02','01',lance,'A giant-stopping spear with an unmistakable continuous silhouette.',['C02','A02','S04','S06']),('G03','01',pistol,'A single deliberate shot, a quarry that cannot simply disappear.',['C03','A03','S03']),('G04','02',axe,'A broad sun-fed axe made for one committed cleave.',['C05','S02'])]
for id,sty,w,cap,rel in gear:
 add(id,'equipment',sty,w['name'],cap,w['description']+' Show one complete desirable finished combat object on a quiet material surface, with one small close detail of the SAME object only if useful. Main view must include every endpoint and the real grip/contact surface. Product-like lighting with material depth, no exploded view, detached parts, magical orbit, labels or blueprint marks. Keep geometry simple enough to reproduce in a held character view.',rel,weapon=w)
add('W01','wildlife','01','Glassback Fox','Harmless seam-grazers reveal which crossings still carry a safe current.','One fox-sized wild animal with exactly FOUR legs and ONE tail, ordinary opaque dark head and legs, alert ears and one translucent smooth shoulder/back plate. All four paws separable in a natural three-quarter stance. It lowers its muzzle toward an intact faintly lit seam on a moss-edged urban ledge; its body casts a real shadow and paws touch the surface. Only the single back plate transmits cool light. No glass spikes, collars, jewelry, extra legs or particle halo. Wide enough to show its small scale within the route.', ['S01'],[],anatomy={'legs':4,'tails':1},behavior='Grazes harmless stored charge along intact fault seams; avoids freshly broken glowing edges.')
add('W02','wildlife','06','Sill Heron','A dry nesting ledge can matter more than another weapon.','One long-necked wild bird with exactly TWO legs and TWO folded wings, broad white feathers and a blunt black bill. Stand on a dry sill above shallow dark floodwater, toes visibly contacting stone, one folded wing near and the far one anatomically plausible rather than an extra limb. Quiet black-white masses with a restrained pink reflection in water. A simple small nest and dry sill demonstrate its habitat; no umbrellas, insect body, mechanical joints or luminous feather forest.', ['S03'],[],anatomy={'legs':2,'wings':2},behavior='Nests above the flood line and probes harmless seam algae, indicating sheltered ledges.')
add('M01','monster','01','Rift Hound','Broken seams draw something heavy enough to turn a crossing into a fight.','One bull-sized low FOUR-legged ambush predator with one heavy wedge-shaped head, blunt opaque black-glass shoulder plates and ONE muscular tail. Strong organic shoulders, coherent forelegs and hindlegs, all four paws countable in three-quarter full-body view. Pale lower jaw gives the face readable intent. Crouch beside a freshly broken transit seam with weight on the forefeet, preparing a bodily lunge. No extra mouths, tendrils, mechanical hinges, crystal spike forest or effects cloud.', ['S04','A02'],[],anatomy={'legs':4,'heads':1,'tails':1},behavior='Feeds on pressure leaking from fresh fractures; attacks with a committed shoulder-led lunge.')
add('M02','monster','01','Hollow Regent','A living weight beneath the city’s highest routes.','One enormous ORGANIC QUADRUPED with exactly FOUR load-bearing legs: two powerful forelegs and two hindlegs. Broad smooth split-crown head, thick living neck, opaque black glassy back plates, pale throat, long muscular single tail. Animal musculature and continuous living joints; no human armor, mechanical joints, upright torso, robot hands, tentacles or horn forest. A low-angle full creature view between widely spaced ruined towers, with its feet and tail route readable enough to establish bodily scale. Back plates are smooth broad masses, not small decorative shards. It draws charge from a damaged transit spine and turns its massive head toward the disturbance.', ['S06'],[],anatomy={'legs':4,'heads':1,'tails':1,'posture':'organic quadruped'},behavior='Draws charge from broken transit spines; its shifting body threatens whole routes even before it attacks.')
add('A01','ability','01','Between Steps','A visible landing is the difference between a shortcut and a fall.','Riven Hale demonstrates ONE seam-step across a short broken walkway. Show one whole body emerging at a visible landing seam with a clear leading foot planted and the trailing leg completing the step; a narrow departure slit across the gap is enough to imply the origin. No duplicate complete bodies or floating feet. His single saber remains held. Spatial depth and the actual gap stay legible; cyan effect confined to two narrow seams, no tunnel of rings. One current skill only, not all future upgrades.', ['C01','G01','S01'],['C01','G01'],power=p1)
add('A02','ability','01','Royal Weight','A grounded lance strike forces a heavier enemy to yield.','Senn Ardent plants both greaved feet and grips Crownfall Lance with TWO separated hands. The one continuous shaft leads to a visible controlled contact at the Rift Hound’s armored shoulder; the four-legged creature buckles its near foreleg under the weight. Keep the contact and her full body in frame, clear negative space between arms and torso. One restrained cyan pressure trace at the shoulder and compressed ground shadow express the skill. No floating weapon, extra animal legs, duplicate spear or giant diagram arrows.', ['C02','G02','M01','S04'],['C02','G02','M01'],power=p2)
add('A03','ability','01','Named Shot','One mark makes a hidden quarry traceable.','Iria Noct aims her single Wraithlock pistol at ONE partly concealed Rift Hound beyond a simple cracked concrete screen. Her firing hand clearly wraps the grip, finger at trigger and other hand safely bracing; one barrel only. One small spirit-brand remains visible on the animal’s shoulder. A SINGLE subtle cyan projectile path bends through an existing opening in the screen toward that mark; it does not pass through solid concrete. Keep her face, full stance, gun and opening readable; no multiple muzzle flashes, spectral pets, exploded anatomy or simultaneous progression forms.', ['C03','G03','M01'],['C03','G03','M01'],power=p3)
add('A04','ability','01','Second Heart','An armored fist spends its stored storm on one precise impact.','Dax Verran alone in a compact planted stance, RIGHT ivory gauntlet visibly attached to his forearm and striking one heavy upright fallen slab. His ordinary uncovered LEFT hand guards his ribs and is clearly separate. A narrow directional lightning release follows the punch into one splitting crack; two major separated stone pieces reveal the actual result. Retain his entire body, planted boots, face and the right shoulder-elbow-wrist chain. No second gauntlet, extra actor, giant detached fist, radial effects cloud or labels.', ['C04','S05'],['C04'],power=p4)
scene_common=' This is a complete cinematic scene, not a portrait/full-body split board or isolated component card. Prioritize inhabitable depth, clear routes, appealing adult faces when readable, coherent scale and a decisive visual moment. No captions or lettering baked into the artwork. Keep foreground action clean, background detail subordinate, effects localized. These are exploratory moments, not a frozen canonical plot.'
add('S01','scene','01','The Missing Span','The city offers a route only to someone willing to commit.','Wide dramatic three-quarter view down a rain-dark elevated transit cut between vertical towers. Riven Hale commits to one Between Steps crossing across a clearly visible broken span; departure ledge and safe landing ledge both in frame, one narrow cyan seam at each, no duplicate complete actor. His single saber and cropped petrol silhouette remain readable. One small Glassback Fox already stands safely on the landing ledge. Wet dark glass, pale concrete, brushed rails, a few distant window lights and moss at sheltered edges make an inhabited city; no crowd or extra giant creature.'+scene_common,['C01','G01','W01','A01'],['C01','G01','W01'])
add('S02','scene','02','Daylight Below','The bright terraces end at a door that was buried from the inside.','Solene Varo alone at the discovery of a broad black-glass fault descending from warm upper terraces into a buried stone hall. Her whole body and one Dawn Hew axe appear in the foreground, sunlight on her short curls and expressive face as she looks down with fierce curiosity. One obvious lit entrance and a broad descending stair form a usable route; one distant sealed object or doorway gives a destination. Ochre walls, blue open sky and green weapon accent; warm outlined painting with tactile planes. No crowded market, flag forest, duplicate axe or pile of treasure icons.'+scene_common,['C05','G04'],['C05','G04'])
add('S03','scene','06','A Narrow Refusal','Two fighters can turn one dry stair into contested ground.','Vale Sorn blocks a flooded stair mouth with Black Verdict held in a stable guard, facing Iria Noct across a shallow reflecting channel; Iria holds one Wraithlock lowered but ready. Exactly TWO adults, both grounded on visible ledges, clear space between them and one unobstructed side route indicating an alternative to the confrontation. Show distinct body scales and faces without turning them into the original detective. One small Sill Heron may stand on a high dry sill, subordinate to the two-person tension. Black-white brush masses, concrete depth, restrained pink reflected light. No attack yet, no summoned champion, no extra guns or swords.'+scene_common,['C06','C03','G03','W02'],['C06','C03','G03','W02'])
add('S04','scene','01','Hold the Crossing','A lance meets a charging shoulder before the route gives way.','Senn Ardent braces against ONE Rift Hound on a broad damaged elevated platform. Full-body three-quarter combat composition: both of her boots visibly on the platform, both hands wrapping separated zones of the one uninterrupted lance shaft, spearhead making an unambiguous contact with the animal’s black shoulder plate. The bull-sized four-legged predator drives forward with a clear wedge head and one tail; keep all leg origins anatomically readable. A broken edge beyond the combatants establishes danger without hiding the contact. Cool urban depth and one restrained cyan weight cue; no gore, additional fighters, airborne spare limbs or weapon copies.'+scene_common,['C02','G02','M01','A02'],['C02','G02','M01'])
add('S05','scene','01','One Stored Storm','He opens the blocked route with a single controlled strike.','Dax Verran ALONE in a ruined transit approach, right Thunderheart gauntlet striking ONE fallen slab that blocks a broad doorway. Readable right shoulder-elbow-wrist contact chain, his full body and both planted boots in frame, ordinary left hand guarding his torso. A narrow directional thunder release drives through the contact and separates the slab into two large pieces, showing a newly usable passage behind it. His weathered bearded face remains concentrated with a tight expression, not a broad laugh. No Iria or any other person, no extra slab targets, radial lightning cloud or floating fist.'+scene_common,['C04','A04'],['C04'])
add('S06','scene','01','The City Has a Larger Resident','Their best route crosses the path of something that can move the skyline.','Riven Hale and spear-bearing Senn Ardent stand fully readable on an intact high walk in the foreground, looking toward ONE enormous organic Hollow Regent moving between widely spaced towers beyond. Exactly two foreground adults, Riven’s single saber and Senn’s continuous lance visible without obscuring their bodies. Regent has four powerful animal legs, a broad smooth split-crown head, pale throat, opaque black glassy back plates and one long muscular tail; no robot limbs, human torso, upright pose or tentacle forest. Use a visible distant street and building floors to prove its scale, with at least a legible fore/hind leg separation and believable ground contact. Leave an open continuation of the high walk so danger and possible traversal coexist. Glossy dark mass, sparse cyan reflections and pale architectural planes, no competing giant creature.'+scene_common,['C01','C02','G01','G02','M02'],['C01','C02','G01','G02','M02'])
order=['S01','S02','S03','S04','S05','S06','C01','C02','C03','C04','C05','C06','G01','G02','G03','G04','W01','W02','M01','M02','A01','A02','A03','A04']
by={e['id']:e for e in entries}; entries=[by[i] for i in order]
world={'working_title':'The Verge Districts','status':'Exploratory shared vocabulary; no canon, character pairing or owner style winner inferred.','premise':'A sleek vertical city surrounds black-glass fault seams. Its abandoned transit cuts lead naturally through basalt wilderness into buried halls.','material_vocabulary':['opaque black glass with restrained reflections','pale concrete and broad stone planes','brushed dark metal with functional joints','small sheltered moss or vegetation patches','controlled cyan seam light, not universal luminous ornament'],'ecological_rule':'Intact seams hold usable charge and draw harmless seam-grazers. Fresh fractures leak pressure that attracts predators; ancient broken transit spines can feed something colossal.','social_rule':'Combatants contest safe crossings and access to deeper charged ruins; competence, restraint and protective choices can be visible without assigning mundane occupations or a fixed party.','progression_rule':'Desirable weapons channel clear present abilities with physical commitments; deeper seams promise stronger powers but do not remove stance, contact or route constraints.','comparison_styles':{'01':'Dominant Nightglass: refined adult faces, crisp silhouette, limited soft modeling, wet vertical-city depth and selective cyan edge light.','02':'Sunbreak comparison: warm outlined painting with expressive faces and broad ochre/blue/green sunlit planes; dry upper terraces.','06':'Floodline comparison: graphic black-white brush masses with restrained hot pink; flooded lower cuts and clear concrete depth.'},'character_direction':'Six new magnetic adult combat identities; modern clean tailoring plus purposeful armor, varied expressive faces and bodies. Predominantly light complexions are project appearance preferences, never quality scores. No reskinned anchor or previous cast.','scene_direction':'Six complete environments carrying traversal, discovery, confrontation, combat, power and larger-threat moments. No component-board framing for scenes.','power_display':'One present action or cue per image; progression promises remain separate text, not several simultaneous forms.'}
payload={'schema':'WorldCombatDesignDraft/1','experiment_id':'WC-20260908-01','status':'frozen author draft for root adaptation; not production prompt freeze or owner approval','world':world,'entries':entries,'expected_counts':{'total':24,'category':{'scene':6,'character':6,'equipment':4,'wildlife':2,'monster':2,'ability':4},'style_id':{'01':18,'02':3,'06':3}},'lead_revisions_applied':['Dax: 39, square weathered face, short straight salt-and-pepper hair, trimmed angular beard, restrained smile; no copper curls/jolly heavyweight repeat.','Solene: LIGHT warm-tan complexion.','Vale: Quiet Oath planted-stance pressure-wave shelter, not defeated-shadow summoning.','S05: Dax alone, one directional impact on one slab.','Hollow Regent: organic quadruped, four animal legs, smooth split-crown head, black back plates, pale throat and long muscular tail; no mech anatomy.','S06: Riven and lance-bearing Senn readable on foreground high walk against distant Regent.']}
assert len(entries)==24 and len(by)==24
assert dict(collections.Counter(e['category'] for e in entries))==payload['expected_counts']['category']
assert dict(collections.Counter(e['style_id'] for e in entries))==payload['expected_counts']['style_id']
for e in entries:
 assert all(i in by and i!=e['id'] for i in e['related_ids']+e['dependency_ids'])
def visit(i,stack):
 assert i not in stack,stack+[i]
 for d in by[i]['dependency_ids']:visit(d,stack+[i])
for i in by:visit(i,[])
p=out/'world-combat-draft-v1.json'
with p.open('x') as f:json.dump(payload,f,indent=2);f.write('\n')
notes='''# The Verge Districts — exploratory design vocabulary

A sleek vertical city surrounds black-glass seams, with abandoned transit cuts leading into basalt wilderness and buried halls. Intact seams carry useful charge and attract harmless wildlife; broken seams leak predatory pressure. This makes routes, creatures, combat and progression part of the same visual promise without declaring a canonical plot or compulsory party.

Nightglass dominates 18 of 24 images. Three Sunbreak and three Floodline images test the same connected vocabulary under warm terrace light and graphic flooded-depth treatment. This allocation is an experiment, not an owner-selected style winner. Scenes are complete inhabited compositions, not portrait/component boards.

Six adults have distinct faces, silhouettes, expressions and one simple signature weapon apiece. Dax uses the approved older salt-and-pepper/bearded identity; Vale protects through Quiet Oath rather than summoning defeated shadows. Solene has the approved light warm-tan complexion. Complexion is never a review score.

The six scenes separately explore traversal, discovery, confrontation, direct combat, one controlled power impact and a much larger organic threat. S05 contains Dax alone. The Hollow Regent is a living four-legged animal, never a generic robot or upright armored person. S06 keeps both Riven and lance-bearing Senn readable on the foreground high walk.

Production prompts and generation remain root-owned. This author draft is frozen for adaptation; all earlier workspaces and cast remain untouched. Dependencies define useful optional source order, while related IDs express connections without forcing every related asset into every image. Keep reference counts bounded when root freezes actual jobs.
'''
with (out/'world-notes.md').open('x') as f:f.write(notes)
receipt={'schema':'WorldCombatDraftChecks/1','draft_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'entries':len(entries),'category_counts':dict(collections.Counter(e['category'] for e in entries)),'style_counts':dict(collections.Counter(e['style_id'] for e in entries)),'all_ids_and_dependencies_resolve':True,'dependency_graph_acyclic':True,'all_six_lead_revisions_applied':True,'production_written':False}
with (out/'draft-checks.json').open('x') as f:json.dump(receipt,f,indent=2);f.write('\n')
print(json.dumps(receipt,indent=2))
