from pathlib import Path
import json,hashlib,collections
root=Path.cwd(); out=root/'research/nightglass-refinement/design'
manifest=json.loads((root/'production/nightglass-refinement/previous-world/manifest.json').read_text())
prior={e['id']:e for e in manifest['sources']}
originals={e['id']:e for e in json.loads((root/'production/nightglass-refinement/references.json').read_text())}
def wc(id):
 e=prior[id];return {'kind':'prior_identity_or_object','id':'WC:'+id,'path':e['path'],'sha256':e['sha256'],'role':'Retain named face/body/costume or object geometry only; do not inherit the old pervasive surface texture, composition or extra subjects.'}
def fresh(id):return {'kind':'new_candidate_after_registration','id':id,'role':'Use only the registered new source for the named subject/object; hash must be frozen by root before the dependent call.'}
def p(name,description,limitation,growth):return dict(name=name,description=description,limitation=limitation,growth=growth)
def w(name,description):return dict(name=name,description=description)
shield=w('Stillwall','One solid elongated crescent shield, opaque navy face, pale rim and one actual rear forearm grip. Broad uninterrupted surfaces; no hole, segmented lattice, filigree or floating plates.')
sword=w('Winterline','One broad straight dark sword with uninterrupted ivory cutting edge, plain oval guard and ordinary two-hand hilt. One connected blade, no slots, runic network or second tip.')
bow=w('Daystring','One warm ivory recurve bow with two smooth green limb tips, one continuous string and one center grip. No holes, extra strings, floating limbs or etched ornament.')
knife=w('Null Thorn','One triangular black dagger attached to a solid small white guard and ordinary long enough grip. Plain broad blade faces; no chain, second blade or floating parts.')
pn=p('Quiet Harbor','Captures one incoming pressure front in a braced shield; the held force can be returned through one close-range shield counter.','Must face and brace against the pressure. Only one stored front; an open flank or broken stance spills the stored force.',['Shelter one person and return one short counter.','Widen the protected wedge without abandoning the ground.','Hold a brief still pocket in a larger storm, then spend it in one decisive shield drive.'])
pk=p('Deep Winter','The sword freezes a narrow line of existing moisture into a solid restraint or barrier.','Needs a wet contacted surface and a continuous physical blade stroke; cannot freeze distant dry air or entire crowds at once.',['Arrest one pursuing foot on a wet floor.','Raise one short ice barricade from a contacted water line.','Control a stronger charge by building a precise ice ramp or restraint, with crossings as a secondary use.'])
pe=p('Sun Anchor','An arrow fixes a creature’s shadow/contact point to the terrain it actually strikes, briefly arresting that part of the body.','One active anchor; the arrow must hit existing terrain in contact with the target’s shadow/foot. A fully airborne target has no ground contact to pin.',['Stop one charging forefoot for a heartbeat.','Hold a stronger foe briefly by choosing its loaded contact point.','Redirect a charge through one well-placed anchor; rescue or crossing anchors remain secondary applications.'])
pc=p('Severance','A real dagger cut interrupts one visible active magical connection.','Connection must be visible and within blade reach; ordinary armor and solid walls do not vanish.',['Interrupt one charging tether.','Release one ally from an active binding.','Cut a temporary opening in a maintained barrier, before its source can reconnect.'])
entries=[]
def add(id,cat,sty,title,caption,brief,refs=(),related=(),**extra):
 treatment={'kind':'drawing_treatment','id':'APPROVED_NIGHTGLASS_SIMPLIFICATION' if sty=='01' else 'SIMPLIFIED_COMPARISON:'+sty,'role':'Rendering guidance only; never import reference characters, scenery, poses or equipment. Root binds one actual reference after proof gate.','original_benchmark_path':originals[sty]['path'],'original_benchmark_sha256':originals[sty]['sha256']}
 entries.append(dict(id=id,category=cat,style_id=sty,title=title,caption=caption,visual_brief=brief,design_references=list(refs),drawing_treatment_reference=treatment,related_ids=list(related),dependency_ids=[x['id'] for x in refs if x['kind']=='new_candidate_after_registration'],max_actual_references=len(refs)+1,**extra))
character_presentation=' Calm 3:2 two-view board: left expressive head/shoulders portrait, right complete SAME adult in a purposeful combat-ready pose with one weapon. Quiet broad background, complete feet and weapon; no alternate costume or extra person. Keep face construction and costume silhouette rich while surfaces stay broad and nearly untextured.'
add('C01','character','01','Neris Vell','An unruffled defender who returns the force she survives.','Adult woman31, broad athletic shoulders, oval face, strong nose and heavy-lidded eyes; calm almost amused expression. Dark-brown shoulder-length waves tied into a loose low knot, light olive complexion. Short ivory armored shoulder cape, fitted deep-teal sleeveless tunic, black narrow trousers and substantial dark boots. Three broad costume masses. Stillwall held on one forearm with a visible real rear grip; free hand open and separate, grounded diagonal stance.'+character_presentation,[fresh('G01')],['G01','S05','A04'],age=31,gender='woman',face='Oval, strong nose, heavy lids; calm almost amused.',hair='Dark-brown shoulder-length waves, loose low knot.',build='Broad athletic shoulders and powerful grounded legs.',costume='Short ivory armored shoulder cape; deep-teal fitted sleeveless tunic; black trousers; dark boots.',complexion='Light olive.',weapon=shield,power=pn)
add('C02','character','01','Kellan Rusk','A fast duelist who turns a wet battlefield against its pursuers.','Adult man27, lean compact sprinter, sharply triangular face, large dark eyes, short dense black curls and a purposeful teeth-showing smile; light warm complexion. Sand cropped double-breasted battle jacket with one cobalt chest insert, dark trousers broad at thigh and tapered at ankle, pale boots. Winterline held in a real two-hand hilt grip, blade clear of his face and torso; low poised turn rather than a static vertical carry.'+character_presentation,[fresh('G02')],['G02','A01'],age=27,gender='man',face='Triangular, large dark eyes, purposeful teeth-showing smile.',hair='Short dense black curls.',build='Lean compact adult sprinter.',costume='Sand cropped double-breasted battle jacket; cobalt chest insert; dark tapered trousers; pale boots.',complexion='Light warm.',weapon=sword,power=pk)
add('C03','character','01','Elowen Marr','One well-placed arrow can turn a charging monster’s strength against it.','Adult woman26, very tall lean archer, long heart-shaped face, straight brows, wide hazel eyes and an alert impatient expression; light freckled complexion. One thick strawberry-blond braid over a shoulder. Slate-blue fitted hip-length coat, ivory chest shell, black leggings, plain long blue gloves and practical boots. Hold Daystring undrawn by its real center grip, free hand empty at hip; no phantom arrow or spare bow.'+character_presentation,[fresh('G03')],['G03','S03','A02'],age=26,gender='woman',face='Long heart shape, straight brows, wide hazel eyes; alert impatience.',hair='Single thick strawberry-blond braid over shoulder.',build='Very tall lean trained archer.',costume='Slate-blue fitted hip coat; ivory chest shell; black leggings; plain blue gloves; practical boots.',complexion='Light with a few readable freckles, no pervasive skin stippling.',weapon=bow,power=pe)
add('C04','character','06','Corven Ash','A grim duelist who attacks the connection sustaining a threat.','Adult man35, tall broad chest and narrow waist, long straight nose, deep-set eyes and a hard unsmiling mouth; light cool complexion. Long black hair in a low tie with clean undercut. White high-neck sleeveless armored torso, fitted black waist and trousers, one short asymmetric black mantle and plain white shin guards. One Null Thorn held outside the body in a clear wrapped hilt grip, empty hand raised in a restrained warding gesture. Simplified graphic noir: decisive black-white planes and one tiny pink accent, clean edges instead of pervasive scratch marks.'+character_presentation,[],['A03'],age=35,gender='man',face='Long straight nose, deep-set eyes, hard unsmiling mouth.',hair='Long black hair in low tie, clean undercut.',build='Tall broad-chested, narrow-waisted adult fighter.',costume='White high-neck sleeveless armored torso; fitted black waist/trousers; short asymmetric black mantle; white shin guards.',complexion='Light cool.',weapon=knife,power=pc)
for id,sty,weap,cap,rel,brief in [
 ('G01','01',shield,'A shield whose mass and grip make its promise believable.',['C01','S05','A04'],'One whole shield in a three-quarter angle with a short cropped adult forearm engaged in the actual rear grip. Turn enough to show the grip attachment without a duplicate-object inset. No free-floating wrist or hidden grip. Navy face, pale rim, one broad highlight.'),
 ('G02','01',sword,'A clean cutting silhouette built for a deliberate two-hand stroke.',['C02','A01'],'One whole sword carried horizontally by two cropped adult hands around the actual hilt, fingers clearly separated from the blade. Complete tip and pommel, dark blade with continuous ivory edge and one soft reflection; no hand touching sharp edge.'),
 ('G03','02',bow,'A single arrow’s anchor starts with a simple, credible bow.',['C03','S03','A02'],'One whole undrawn bow held by one cropped adult hand at its center grip. Single string connects the two limb tips in one continuous taut line. Warm ivory body and two green tips, warm Sunbreak outlined planes. No drawing hand, nocked arrow, spare string or inventory inset.')]:
 add(id,'equipment',sty,weap['name'],cap,weap['description']+' '+brief+' Quiet material backdrop and one support shadow. No text, dimension marks, exploded parts or etched decoration.',[],rel,weapon=weap)
add('W01','wildlife','01','Salt Hare','A cautious small resident of the reservoir’s dry shelves.','One small four-legged mammal with two long broad ears, one short tail and a compact hare-like body. Pale opaque coat rendered with smooth values, dark blue feet and ear tips, a few purposeful facial lines; no individually drawn fur strands. All four leg origins readable in a quiet three-quarter habitat pose on a broad dry salt ledge beside still reservoir water. It tests the shore with one forepaw. One nearby reed clump and soft distant arch, not bare empty studio blocks or dense foliage.',[],['S02'],anatomy={'legs':4,'ears':2,'tails':1},behavior='Lives on dry salt shelves and taps uncertain water edges before jumping; shares safe margins with travelers.')
add('M01','monster','01','Basin Toad','Its planted inhale becomes one sudden, dangerous water blast.','One ox-sized squat amphibian, exactly four limbs: two strong small forelegs and two large folded hindlegs. One immense blunt mouth, two small high-set eyes, smooth indigo back and pale throat. Organic weight and broad silhouette; no carapace facets, tooth forest, extra mouth or tentacles. Show it planted at a shallow reservoir edge, throat expanded before release; a low ridge and one broad dam mass establish habitat. No full water effect obscuring anatomy in this component image.',[],['S04','A02','A04'],anatomy={'limbs':4,'heads':1,'mouths':1},behavior='Draws shallow water in during a planted inhale, then releases one broad pressure-driven blast. Brief recharge between blasts gives a combat opening.')
add('M02','monster','01','Horizon Serpent','A migrating body can threaten a dam without ever hunting its people.','One colossal LEGLESS aquatic animal, one head, one continuous body and one tapering tail, no limbs or paired fins. Smooth dark dorsal mass and broad pale underside. A single rising body arc above still water, the remaining length indicated by one connected wake; never multiple disconnected coils. Low dam, layered hills and a few tiny structures establish scale. Warm dusk sky and large cool water planes, a single broad reflection; no segmented scales, glass spikes, horn forest or thousands of glitter flecks.',[],['S06'],anatomy={'legs':0,'heads':1,'continuous_bodies':1,'tails':1,'fins':0},behavior='Migrates along submerged charged seams; displacement and wake threaten the reservoir’s dams.')
scene_rule=' Complete cinematic 3:2 scene, not a portrait split or component card. Build richness from several well-staged architectural/terrain masses, believable depth, expressive acting and controlled light. Keep hands, weapons, faces and action hierarchy legible. Broad surfaces, selective soft modeling, sparse reflection accents; no all-over cracks, grain, tiny facets or floating effect debris.'
add('S01','scene','01','White Distance','The next route lies beyond the familiar skyline.','WC Riven and WC Senn walk toward one monumental tilted transit arch across pale salt flats at blue dawn. Low wide camera, two complete foreground figures with readable three-quarter profiles; Riven carries the SAME single Seam Saber low and Senn her SAME Crownfall Lance. Riven wears his silver hair/petrol cropped jacket, Senn her chestnut ponytail/navy vest/ivory breastplate and bare muscular arms. Long clean shadows, a distant city strip and layered pale salt shelves convey vast horizontal distance. Their expressions are quietly determined. No gap leap, portal, Regent or new weapon.'+scene_rule,[wc('C01'),wc('C02')],['S06'],linked_subjects=['WC:Riven','WC:Senn','WC:Seam Saber','WC:Crownfall Lance'])
add('S02','scene','01','A Small Trust','She lowers her guard long enough for a smaller life to approach.','WC Iria crouches on a broad dry reservoir ledge offering one EMPTY open hand to the Salt Hare. Her SAME single Wraithlock is securely holstered and visible by its familiar ivory side/cyan chamber, not held. Preserve her dark ponytail/blunt fringe, oxblood jacket and silver forearm armor. A gentle unexpected smile and the animal’s cautious lifted forepaw carry the moment; leave a small clear gap between palm and muzzle, no forced contact. Early morning light, still water, one large arch reflection, a few reed silhouettes and receding stone shelves establish a lived shore.'+scene_rule,[wc('C03'),fresh('W01')],['W01','S06'],linked_subjects=['WC:Iria','WC:Wraithlock','W01'])
add('S03','scene','02','The Noon Door','For a moment, even an impatient fighter has to look up.','Elowen stands inside one immense pale monolith split by a vertical shaft of noon light, looking up in open wonder at one suspended circular seal. Complete figure and full Daystring bow held undrawn by the center grip; no arrow fired and no alternate weapon. A broad ascending ramp, two deep wall recesses and the circular seal create a usable route and strong hierarchy. Warm outlined Sunbreak planes in limited ochre/blue/green; smooth stone, no carved ornament carpet, treasure inventory or repeated stair-discovery composition.'+scene_rule,[fresh('C03'),fresh('G03')],['C03','G03','A02'],linked_subjects=['C03','G03'])
add('S04','scene','01','Over the Breaking Water','She commits to the counter while the blast spends itself below her.','Decisive combat at a shallow reservoir: ONE Basin Toad on the right releases ONE broad horizontal water blast from its visibly open mouth toward the lower left. WC Senn leaps laterally from a visible low stone island, her whole body clearly ABOVE the blast, both hands wrapping separated parts of her SAME continuous Crownfall Lance. She drives the spear forward into a countering line toward the toad’s upper face, with a CLEAR AIR GAP before contact: freeze just before impact, no fake spark. Keep all spear endpoints in frame. Her legs tuck into one readable airborne silhouette and a visible dry landing shelf lies along her trajectory beyond the spent blast. Source mouth, single water shape, safe path and opposing threat stay separable; three-quarter side view, pale overcast sky and calm broad water outside the blast. Exactly one adult and one four-limbed animal; no extra weapons, copied leap portals or particle spray storm.'+scene_rule,[wc('C02'),fresh('M01')],['M01','A02','A04'],linked_subjects=['WC:Senn','WC:Crownfall Lance','M01'],action_chain={'source':'One visibly open toad mouth','action':'One low broad horizontal water blast; Senn makes a lateral airborne spear counter above it','target':'Senn is the blast target; the toad is her counter target','consequence':'Blast misses below; her counter approaches with explicit pre-contact air gap and a visible safe landing shelf'})
add('S05','scene','01','A Shelter in the Gale','Protection is a choice made with both feet on the ground.','Neris plants Stillwall on a snowy ridge while WC Dax crouches behind her in its clear lee. Two readable adult faces convey concentrated protection and grudging trust; Dax keeps his established salt-and-pepper hair, angular beard, teal chest armor and RIGHT gauntlet resting inactive on his knee. Neris braces with the real shield grip. One broad stream of wind-driven snow splits around the solid shield, leaving a calm wedge behind it. Layered ridge, one half-buried arch and a distant pass give an inhabited route; no punch, slab breaking, spare fist or old hall composition. High-key snow and cool shadows with small warm skin accents.'+scene_rule,[fresh('C01'),fresh('G01'),wc('C04')],['C01','G01','A04'],linked_subjects=['C01','G01','WC:Dax','WC:Thunderheart'])
add('S06','scene','01','Below the Horizon','The still water begins to move for something much larger.','WC Riven and WC Iria stand on a reservoir overlook at dusk, both readable in three-quarter profile, looking toward ONE Horizon Serpent raising one continuous arc far beyond a low dam. Riven retains the SAME single Seam Saber held low outside his body, silver hair and petrol cropped jacket; Iria retains her oxblood jacket, dark ponytail and SAME Wraithlock holstered. Their expressions show apprehension, not combat grins. Layered hills, dam face and a few clustered tiny lights prove scale; warm sky against deep blue water, one long unbroken reflection. The serpent is legless with one head/body/tail, not the Regent or original manta. No vertical-city creature tableau, ready spear partner, rain texture or hundreds of tiny lights.'+scene_rule,[wc('C01'),wc('C03'),fresh('M02')],['M02','S01','S02'],linked_subjects=['WC:Riven','WC:Iria','WC:Seam Saber','WC:Wraithlock','M02'])
ability_rule=' One present ability demonstration, not a multi-stage infographic. Entire adult action silhouette and relevant weapon contacts remain visible. Future growth belongs in separate copy. Clean contour and broad material planes, no text, arrows, particle clouds or repeated body copies.'
add('A01','ability','01','Deep Winter: The Closing Line','A precise stroke turns shallow water into a barrier.','Kellan stands on the dry edge of a shallow flooded court and draws Winterline through the existing water with two hands visibly on the hilt. The blade edge ACTUALLY touches the water at one clear point. From that point a short smooth opaque blue-white ice barrier rises across the path of ONE sliding stone training weight, which visibly tips and stops against it. Keep the weight simple, whole and clearly separate from the adult; wet floor, blade stroke, resulting barrier and halted target in one oblique frame. No intricate ice crystals, distant magical freezing, extra sword or hand around the blade.'+ability_rule,[fresh('C02'),fresh('G02')],['C02','G02'],power=pk,action_chain={'source':'Blade edge contacting existing shallow water','action':'A continuous physical sword stroke freezes one short line','target':'One sliding stone training weight','consequence':'A smooth ice barricade arrests and tips the weight'})
add('A02','ability','01','Sun Anchor: Arrested Charge','The arrow reaches the ground before the charging foot can leave it.','Elowen has just released ONE arrow from Daystring: bow hand still clearly at the center grip, string returned toward rest, drawing fingers open beside her cheek. The ONE arrow is already embedded in wet stone immediately beside the Basin Toad’s loaded near forefoot. One small solid pale anchor joins the actual contact shadow/foot to that struck ground; the toad’s body pitches forward while that forefoot visibly cannot advance. Whole adult, full bow, single arrow landing and four coherent animal limb origins; no arrow simultaneously nocked and flying, extra strings or swarm of anchors. Low side view across a broad wet arena, clean sunlight and big cast shadows.'+ability_rule,[fresh('C03'),fresh('G03'),fresh('M01')],['C03','G03','M01','S04'],power=pe,action_chain={'source':'One released bow shot with the arrow now visibly embedded','action':'Sun Anchor fixes the struck ground/contact shadow','target':'One loaded toad forefoot','consequence':'Foot stays pinned briefly while the charging body pitches forward'})
add('A03','ability','01','Severance: Broken Charge','He cuts what feeds the attack rather than striking its armor.','Corven enters a compact close guard beside two broad stone pylons. ONE taut pale-cyan magical connection runs from the left source pylon toward a single charged stone target on the right. His Null Thorn blade physically meets that connection within arm’s reach; leave a clear short break exactly at the cutting edge. The target’s single bright center dims beyond the break while the source-side segment remains bright. One whole Corven, one connected dagger, one interrupted connection and one target; no severed body, extra daggers, exploding pylons or diagram arrows. Render this ability in the dominant simplified Nightglass treatment while preserving his exact Floodline-designed face, hair and costume.'+ability_rule,[fresh('C04')],['C04'],power=pc,action_chain={'source':'One bright pylon supplies one visible magical connection','action':'Real dagger edge cuts the connection at a visible point','target':'One charged stone target beyond the cut','consequence':'Source-side connection stays bright; downstream segment and target dim'})
add('A04','ability','01','Quiet Harbor: Returned Force','What she catches becomes the counter that breaks its balance.','Neris steps into ONE close shield counter against the Basin Toad on a dry stone arena margin. Her forearm stays visibly secured to Stillwall’s real rear grip, both feet grounded. The broad solid shield face makes unmistakable contact with the toad’s pale upper chest, driving its body backward and lifting ONE near forefoot off the ground; other limbs remain anatomically connected. One restrained broad pressure crescent compressed at the shield face expresses release of held force, not an aura around the whole body. Show a short residual water trail behind the toad indicating the spent blast she caught, not a second active blast. No lance, detached shield, human figure behind her or false contact spark. Three-quarter close action view, warm side light on large pale/navy masses.'+ability_rule,[fresh('C01'),fresh('G01'),fresh('M01')],['C01','G01','M01','S05'],power=pn,action_chain={'source':'Held pressure visibly concentrated at the connected shield face','action':'One physical close-range shield counter releases it','target':'Basin Toad upper chest','consequence':'Body driven back, one forefoot lifted and balance broken'})
order=[*(f'S{i:02}' for i in range(1,7)),*(f'C{i:02}' for i in range(1,5)),*(f'G{i:02}' for i in range(1,4)),'W01','M01','M02',*(f'A{i:02}' for i in range(1,5))]
by={e['id']:e for e in entries};entries=[by[i] for i in order]
for e in entries:
 assert e['max_actual_references']<=5
 assert all(x in by for x in e['dependency_ids'])
def visit(i,anc):
 assert i not in anc,anc+[i]
 for d in by[i]['dependency_ids']:visit(d,anc+[i])
for i in by:visit(i,[])
counts=dict(collections.Counter(e['style_id'] for e in entries));assert counts=={'01':17,'02':2,'06':1};assert len(entries)==20
payload={'schema':'NightglassRefinementNewDesignDraft/1','experiment_id':'NR-20260908-01','status':'Frozen author draft for root adaptation; no production prompt or approval state written','scope':'20 genuinely new images only. Root owns T01-T04 matched composition surface-only studies. All new generation waits for root proof-output gate.','rendering_rule':'Broad material planes, decisive contours and selective soft shading. Preserve attractive adult face construction, meaningful armor and readable functional combat. Sparse reflected accents, no pervasive cracks/facets/grain, etched filigree or dense glitter. Richness comes from shape, acting, layered staging, large architectural masses and light rather than repetitive surface marks. Do not flatten the world into empty block diagrams.','world_extension':'Outer Verge: salt flats, reservoir shores, snow-bright ridges, sunlit monoliths and a low nocturnal arena connect to the liked city through transit arches, shared materials and charged terrain. No canon or compulsory party.','reference_policy':{'design_vs_treatment':'Separated per entry. Existing WC images preserve named subjects/equipment only; approved simplified proof supplies drawing treatment. New candidates supply design only after source hash registration.','actual_reference_cap':5,'typical_actual_reference_count':'1–4, never feed every related ID','new_output_gate':'No new20 image generation until root judges matched simplification proof sufficient.','wc_source_manifest_sha256':hashlib.sha256((root/'production/nightglass-refinement/previous-world/manifest.json').read_bytes()).hexdigest()},'counts':{'new_total':20,'new_style':counts,'matched_studies_root_owned':{'total':4,'style_id':'01'},'final_total':24,'final_style':{'01':21,'02':2,'06':1}},'entries':entries,'owner_approval':None}
pth=out/'new20-draft-v1.json'
with pth.open('x') as f:json.dump(payload,f,indent=2);f.write('\n')
checks={'schema':'NightglassNewDraftChecks/1','draft_sha256':hashlib.sha256(pth.read_bytes()).hexdigest(),'new_entries':20,'category_counts':dict(collections.Counter(e['category'] for e in entries)),'new_style_counts':counts,'final_style_counts':{'01':21,'02':2,'06':1},'max_actual_reference_count':max(e['max_actual_references'] for e in entries),'dependencies_resolve_and_acyclic':True,'all_four_abilities_have_source_action_target_consequence':all(set(e['action_chain'])=={'source','action','target','consequence'} for e in entries if e['category']=='ability'),'riven_same_saber_full_scenes':['S01','S06'],'decisive_combat_full_scene':'S04','production_written':False}
with (out/'draft-checks.json').open('x') as f:json.dump(checks,f,indent=2);f.write('\n')
notes='''# New Nightglass refinement — design rationale

Twenty genuinely new images extend the liked city into salt flats, reservoir shores, a bright monolith, a snowy ridge and a broad arena. Four matched surface-only studies are root-owned and separate. The twenty contain 17 Nightglass, two Sunbreak and one Floodline; adding four Nightglass studies gives exactly 21/2/1 across 24 primaries.

Quiet surfaces do not mean empty scenes. Large terrain and architectural masses, atmosphere, deliberate silhouettes, facial acting and a small number of reflections carry richness. Pervasive cracks, facets, cloth grain, hairline etching and glitter are excluded. Adult face appeal, clean tailoring, protective armor and weapon function remain priorities.

Riven carries his same Seam Saber in two new full scenes, S01 and S06. Senn supplies a decisive airborne counter in S04, not another ready pose or a retry of old spear contact. Iria receives a gentle wildlife moment. Dax appears as a protected partner rather than repeating his old punch. Neris and Elowen also anchor complete scenes; all four new adults have a combat power and one signature weapon.

Daystring now leads with combat control: an arrow fixes a real terrain contact point and briefly arrests a charged forefoot. Quiet Harbor has a close shield counter as well as shelter. Four abilities each specify visible source, action, target and consequence, with bounded limits and growth in separate copy. Existing bad action details are not smuggled into the new budget as corrections.

Design references and drawing-treatment references are explicitly separate. WC references preserve subjects and equipment while approved simplified proof guides rendering; no imported old texture or extra cast. Planned actual reference counts are one to four, below the five-reference cap. Dependencies are acyclic and await registered hashes. Root alone owns the proof gate, production freeze and image generation.
'''
with (out/'rationale.md').open('x') as f:f.write(notes)
print(json.dumps(checks,indent=2))
