from __future__ import annotations


CHAPTER_TITLES = {
    1: "The Bridge That Bites",
    2: "Choose the Crack",
    3: "Breath Has Teeth",
    4: "The Wrong Victory",
    5: "Inventory of Ash",
    6: "Verdigris Sump",
    7: "Rift Temperer",
    8: "The Guild's Short Cut",
    9: "Crownshaft Assault",
    10: "Strike the Silence",
}

CHAPTER_ZONES = {
    1: "Ember Vault chain bridge",
    2: "Ember Vault Chainworks and bell lift",
    3: "survey vestibule and Glass Gallery",
    4: "Verdigris seal gate",
    5: "abandoned kiln refuge",
    6: "Verdigris Sump upper pump",
    7: "collapsed Verdigris sluice",
    8: "Resonance Cistern",
    9: "Crownshaft forge and ascent",
    10: "Bell Regent chamber and public lift",
}

CHAPTER_BEATS = {
1: [
"The Ember Vault drops beneath one chain bridge; Elian and Mira are tiny adult silhouettes crossing toward the sealed bell lift.",
"Elian pauses in mature profile with one hand on the hooked shortblade while his weak starting status hangs in reserved negative space.",
"Elian and Mira trade a dry warning; the failing bridge anchor remains visible between their adult faces.",
"The ivory Belljaw Warden climbs onto the far platform and opens its bell-shaped jaw seam.",
"Side-on geography fixes Belljaw at the right bridge mouth, Mira center-left, Elian behind, and one intact anchor below.",
"Belljaw charges right-to-left and kicks bridge boards upward behind its foreclaws.",
"Mira plants the split shield and drives her spear into the charge line.",
"Belljaw clamps Mira's spear and wrenches it sideways while her planted boot skids.",
"Elian extends one hand; a single ember fault line reveals the boss's ankle seam.",
"Elian slides left-to-right beneath the jaw, using the chain rail as one step toward the ankle.",
"A ceramic forelimb backhands Elian into a hanging chain before his hookblade lands.",
"Elian hangs alone from the chain, guarding his cracked left rib as the collarbone ember fissure closes.",
"In an extreme close-up, Elian crushes his only Spark Talisman while two Iron Seals remain untouched at his belt.",
"Breath Seed II opens as one restrained ember ring; Elian coils against the chain with a newly stable breath.",
"Mira pins the bell jaw while Elian's Fault Step launches bottom-to-top through the ankle seam in one clear impact.",
"Belljaw lies collapsed inside the vault; Elian sits injured, Mira stands watch, and the Rare Cinder-Key rests in front.",
"Mira kneels to bind Elian's ribs while he tries and fails to stand without her help.",
"The intact anchor hums above the void as both adults assess the cost of retreating through unstable chainworks.",
"The Cinder-Key wakes a narrow class terminal showing two paths without selecting either one.",
"Elian studies the safer Kiln Appraiser option while Mira watches his breathing rather than the menu.",
"Mira presses one Iron Seal back into Elian's palm instead of letting him spend it on pain relief.",
"A distant bell pulse travels upward through the vault cables toward the public surface lift.",
"Elian and Mira step into the rising bell lift together, damaged gear and adult silhouettes clean against the pale door.",
"The lift closes on a new Ledger offer: choose a class and reach the Hollow Meridian crown before the Bell Regent ascends.",
],
2: [
"The bell lift opens into vast Chainworks where suspended gears and three broken spans frame a narrow route downward.",
"Elian's L4 status and two class paths appear beside his injured stance, with XP and class prerequisites clearly visible.",
"Mira compares the Appraiser's safety to the Adept's combat risk while tightening Elian's rib binding.",
"Elian binds the Cinder-Key into the Faultline Adept seal; one ember fracture motif crosses his short coat.",
"A quiet close-up shows his hookblade hand settling into a lower diagonal class stance.",
"Fault Hook I appears as a narrow skill card with cost, cooldown, legal targets, and acquisition source.",
"A trapped adult delver calls from a dangling maintenance cage while a rescue quest opens.",
"Three ivory Cinder Mites sever the cage chain pins and race along separate links.",
"Wide geography fixes the cage below, Mira on the central beam, Elian above, and the mites moving toward the final pin.",
"Mira wedges her split shield under the cage chain and bears its weight.",
"Elian reads the single pin that carries the cage and marks the safe chain fault above it.",
"A mite cuts the marked chain early, dropping the cage and reversing Elian's plan.",
"Elian fires Fault Hook into the overhead fault, pulling his own body across the falling gap.",
"He swings beneath the beam with the hookblade held clear of the rescued delver.",
"Elian catches the cage latch as Mira redirects its weight into her shield anchor.",
"One Iron Seal sits in Elian's open palm beside the unstable span and the unspent second seal.",
"He drives the seal into the chain socket; the rescued delver reaches stable footing.",
"The mites flee through a vertical gear throat as Elian and Mira chase along rotating chain teeth.",
"Fault Step redirects Elian around one turning gear and into the lead mite's path.",
"Mira closes the escape with a flat shield strike; the remaining mites collapse in one readable line.",
"Three carapaces and a tempered Chainspool lie in a clean loot arrangement.",
"The rescued delver identifies an Ash Crown shortcut and refuses Elian's attempt to call the rescue incidental.",
"The next bell lift opens toward the Glass Gallery, its pale mineral ribs visible below.",
"Quest completion, Free Delvers reputation, inventory, and 130/140 XP reconcile in a compact end-state menu.",
],
3: [
"The Glass Gallery descends through dark mineral ribs and pale echo planes toward a brass survey vestibule.",
"Orin Pell, a broad light-complexioned adult forge-medic, scans Elian's cracked rib through a brass-rimmed monocle.",
"Orin tells Elian that surviving badly is not a build while Mira inventories the remaining medical stock.",
"A Resin Suture closes the fracture under Orin's gloved hands; the item counter falls to zero.",
"The Ledger offers Three Breaths: hold Pressure Breath through a live resonance without abandoning formation.",
"Orin demonstrates collarbone, sternum, and diaphragm timing with three restrained hand taps.",
"A cultivation menu shows Breath Seed II, the three-phase gate, 32 Qi cost, Glass Lung risk, and 52 max Qi.",
"Elian's first practice breath breaks on the second phase and he coughs into his wrapped hand.",
"Mira quietly resets his shoulders while Orin refuses to reduce the gate.",
"Training completion tips Elian across Level 5; one unspent point remains visibly unallocated.",
"A six-legged Glassback Skitter drops from a mineral rib, its transparent wedge carapace catching one pale edge.",
"Wide geometry fixes the Skitter ahead, Mira at the brass rail, Elian left, and Orin behind cover.",
"The Skitter emits the first of three flat resonance arcs through the narrow gallery.",
"Mira angles her shield so the arc exits into an empty mineral bay.",
"Elian reads a bright fault beneath the carapace, but it shifts with the creature's second note.",
"His hookblade strikes empty glass as the weak point migrates to the opposite leg.",
"The third resonance shatters the rail and slices Elian's right palm through his glove.",
"Elian holds the injured hand closed and matches the three-note cadence with Pressure Breath.",
"Breath Seed III opens in one thin collarbone-to-sternum line while glass fragments hang in quiet negative space.",
"Rift Draw I unlocks with exact cost, cooldown, fault condition, and Seed III source.",
"Elian waits through the first two notes and draws the hookblade only when the third exposes the fixed rear joint.",
"One clean ember arc crosses the rear joint; the Glassback collapses away from Mira and Orin.",
"The Rare Glass Lens and two Verdigris Acid Glands appear beside Elian's bloodied palm wrap.",
"Level 5, 85/190 XP, Seed III, zero Qi, injuries, loot, and quest completion reconcile before the descent.",
],
4: [
"A monumental oxidized gate overlooks the Verdigris Sump, with one moving ivory seal suspended above dark teal water.",
"Sable Renn, a fair-complexioned adult Pathcutter in black-plum gear, stands beside a Level 7 Ash Crown status card.",
"Sable offers Elian a race to the seal and treats the public lift as acceptable collateral.",
"Claim the Verdigris Seal opens with one winner, no shared reward, and a visible reputation stake.",
"A Crownspike Bailiff's chest sigil slides from shoulder to sternum before the guardian fully wakes.",
"Sable cuts a straight Severing Lane across the first moving platform.",
"Elian and Mira sprint the lower route while Orin follows behind the shield line.",
"Mira vaults a turning pump arm and plants the split shield against the landing.",
"The tall ivory Bailiff drops between both routes and drives its crown spike into the platform.",
"Wide geography shows Sable above, Elian's party below, the seal beyond, and the Bailiff controlling the center.",
"Fault Sight marks the guardian's chest sigil at its first position.",
"Elian commits Rift Draw toward that static mark while Mira anchors the approach.",
"The sigil migrates to the opposite shoulder before contact, leaving no verified fault under the blade.",
"The Bailiff catches the hookblade wrist and rotates Elian into Mira's spear line.",
"Mira turns the spear to save Elian; the shaft bends against the crown spike.",
"The Bailiff hammers Elian shoulder-first into the oxidized gate.",
"A close view shows Elian conscious but unable to raise his left arm, with the Glass Lens cracked at his belt.",
"Sable uses the opening to take the Verdigris Seal as the guardian returns to its post.",
"The race quest changes to FAILED with no reward and a Free Delvers reputation loss.",
"Sable admits the shortcut was built to consume slower delvers and leaves anyway.",
"Orin reaches Elian and immobilizes the scapula while Mira stares at her bent spear.",
"Equipment condition cards show cracked Glass Lens, bent spear, intact hookblade, and severe shoulder injury.",
"Mira carries Elian through the kiln refuge door while Orin drags the bent spear behind them.",
"The end-state Ledger records 12/62 HP, 2/58 Qi, quest failure, faction shifts, and no unearned level-up.",
],
5: [
"An abandoned kiln refuge surrounds the injured party with one cold forge, simple shelves, and broad charcoal walls.",
"Elian's inventory, injuries, damaged gear, and 12/62 HP appear without hiding his braced shoulder.",
"Orin explains that the only Stitchfire Ampoule can heal the fracture or remain for a deeper-floor emergency.",
"A resource menu compares the ampoule, cracked Glass Lens, final Iron Seal, Chainspool, and acid glands.",
"Mira makes Elian choose aloud which future risk they will accept rather than letting him spend everything silently.",
"Orin injects Stitchfire along the shoulder brace; the ampoule counter reaches zero.",
"Elian raises the arm through pain; the fracture clears but a narrow shoulder scar persists.",
"Orin lays out two build paths: preserve rare parts for sale or commit them to damaged fighting gear.",
"Elian places the cracked Glass Lens beside the hooked shortblade and confirms the irreversible sacrifice.",
"He strips the hookblade to its black-steel tang while Orin prepares the lens channel.",
"The forge flashes once as the Glasshook emerges with a pale sight groove and restrained ember edge.",
"Mira sets her bent spear beside the last Iron Seal and asks Elian not to call her weapon expendable either.",
"The last Iron Seal and Chainspool lock into the spear shaft as permanent ingredients.",
"Mira tests the new Anchorfork Spear against her split shield in one clean planted rotation.",
"Elian attempts the Breath Channel gate too early beside the cold forge.",
"The pressure reverses at his sternum and throws him to one knee without a breakthrough.",
"Breath Deviation appears as a real debuff with reduced regeneration rather than decorative fire.",
"Mira tells Elian that shared timing is a strategy, while solitary sacrifice is only a habit.",
"Orin refines three carapaces and two acid glands into three compact Verdigris Filters.",
"One bag of inert Shell Dust remains as a low-rarity byproduct occupying a real slot.",
"A comparison menu shows Glasshook, Anchorfork Spear, empty consumables, filters, and persistent scar state.",
"Inventory of Ash completes with 60 XP and a party-trust increase.",
"Elian, Mira, and Orin stand in a three-role formation for the first time.",
"The final status holds at L5 165/190 XP with Breath Deviation, repaired loadouts, and no false cultivation gain.",
],
6: [
"The Verdigris Sump opens around towering oxidized pumps, dark teal water, and one pale pump heart far below.",
"Keep the Pump Heart opens beside Elian's L5 status, filter count, faction reward, and failure consequence.",
"Elian and Mira fit two Verdigris Filters while Orin seals his kiln satchel.",
"The three adults agree on a retreat signal and which pump column must remain intact.",
"A quiet vertical view isolates the pale pump heart inside a broad ring of dark water.",
"Three reed-bodied Mire Choir constructs rise with a shared Level 4–6 threat card.",
"Side-on geography fixes the pump heart center, party left, Choir right, and two incoming water lanes.",
"The first Choir sends a flat acid-water lane toward Orin's position.",
"Mira anchors Rampart Thrust and redirects the lane around the pump heart.",
"Elian Fault Hooks to the oxidized column rather than pulling the living enemy.",
"Orin fires Suture Pulse across the safe line and closes Elian's reopened palm wound.",
"The second Choir breaks the lower sluice, flooding the space between Mira and Elian.",
"Elian lands on a turning pump blade with the exit route now behind the enemy.",
"His fifth verified Fault Step crosses one seam, but the next safe seam turns away mid-stride.",
"Fault Step II unlocks, adding one linked pivot with exact increased cost and reduced cooldown.",
"Elian pivots at the second fault and reaches Mira's shield side without crossing the acid lane.",
"Rampart Thrust III and Bastion Arc I appear after Mira learns the pump's anchored flow.",
"Mira opens a debris cone while Elian hooks the lead Choir into the empty lane.",
"Latch and Lance converges hook and spear on the Choir's shared breath joint in one restrained spectacle.",
"The three constructs collapse downstream, leaving the pump heart intact and the secondary sluice unstable.",
"Mob XP crosses Level 6; HP/Qi maximums and two unspent points update once.",
"A Rare Sumpglass Coil and weightless Pump Token rise from the restored pump housing.",
"A remote Free Delvers notice calls the party useful, and Elian finally accepts the word.",
"Quest ADVANCED, 70/250 XP, Free Delvers reputation, filters, skills, and pump state reconcile.",
],
7: [
"The lower Verdigris sluice hangs beneath a cracked ceiling, with the pump heart visible through one distant arch.",
"The active pump quest and hidden three-catastrophe condition sit beside Elian's L6 Seed III status.",
"Orin checks his kiln satchel straps while warning that the ceiling fault is moving against the water load.",
"A Level 8 Collapse Hound steps onto the central beam, its counterweight tail reading the same ceiling crack.",
"Wide geography fixes the Hound above the secondary sluice, Mira below, Orin near the heart line, and Elian opposite.",
"The Hound bites a load-bearing seam and pulls the ceiling fracture toward the pump heart.",
"Elian reads the complete bite-pull-release pattern instead of striking the exposed jaw.",
"Mira braces the first falling slab away from Orin's route.",
"The Hound releases its counterweight tail and reverses the slab toward Mira.",
"Orin throws his kiln satchel clear of Mira; it falls into the acid water and burns away.",
"A whole ceiling plate begins to descend between the party and the pump heart.",
"Elian abandons the killing angle and Fault Steps to the seam that can divert the plate from Mira.",
"The three Pressure Breath circuits align from collarbone through sternum under the falling weight.",
"Breath Channel I opens as two controlled pulses route the moving fault away from the pump heart.",
"The Ledger offers Rift Temperer after three observed catastrophic patterns and the completed protection choice.",
"Elian accepts; Rift Mark I appears with its survive-pattern prerequisite, 22 Qi cost, 45s cooldown, and four-second duration.",
"He creates one temporary fault on the Hound's ceramic counterweight after surviving its full pattern.",
"Mira uses Bastion Arc to drive falling debris toward the temporary fault instead of across the party.",
"The ceiling breaks along Elian's marked line and buries the Hound while leaving the pale pump heart untouched.",
"The Hound's rear leg remains visible and still, while the secondary sluice collapses into dark water.",
"Keep the Pump Heart becomes COMPLETED_WITH_LOSS; the heart survives and the secondary sluice is permanently gone.",
"A Relic Rift Nail and Tempered Survey Bracer remain in the Hound's broken counterweight.",
"Mira tells Elian the class changed because his decision changed first; Orin mourns the lost satchel without melodrama.",
"L6 210/250 XP, Channel I, Rift Temperer, new gear, faction gain, and environmental loss reconcile.",
],
8: [
"The Resonance Cistern forms a vast brass throat above deep green water, with Sable alone on the opposite ring.",
"Sable's Level 7 Pathcutter status exposes six Ash Debt stacks and an imminent cultivation default.",
"Elian confronts Sable about the shortcut while Mira keeps the damaged Survey Bracer in view.",
"Rescue the Debtor appears as an optional quest with no XP promise and an Ash Crown hostility warning.",
"Two masked Ash Crown agents cut the return cable and display the party's Surface-Route Token before escaping upward.",
"The empty token slot and sealed return door make the theft irreversible.",
"The Level 10 Brass Maw rises from the central throat and opens three concentric jaw arcs.",
"Wide geography fixes party and Sable on opposite ring segments, Brass Maw center, and the only exit above.",
"The first jaw closes on a low note, sending one flat ring across the cistern.",
"Sable cuts Severing Lane through the ring but gains a seventh debt stack.",
"Mira catches Sable behind the split shield as the pathcutter's knees fail.",
"Elian survives the full low-middle-high jaw pattern and reads where the throat will be nonliving and exposed.",
"Rift Mark places a four-second temporary fault across the throat ring.",
"Brass Maw reverses the high note and throws the marked ring toward Elian.",
"Elian takes the edge across his chest and falls to 29 HP while keeping the mark active.",
"Orin reaches for the kiln satchel that is no longer there; the missing gear changes the medical choice.",
"Sable rejects another Severing Lane and instead braces Mira's shield from the open side.",
"Elian spends the final Verdigris Filter to cross the acid mist beneath the rotating jaw.",
"Mira and Sable hold the throat ring while Elian waits for its resonant joint to align with Rift Draw.",
"One ember line passes through the marked joint; the three brass jaws separate in a clear vertical spectacle.",
"Brass Maw sinks motionless and boss XP crosses Elian into Level 7.",
"Rift Draw II unlocks from the survived resonance with exact new cost, cooldown, and one-joint carry rule.",
"The Relic Brass Maw Core and Rare Tuning-Fork Key appear, while the Surface-Route Token remains lost.",
"Rescue completes, hidden conspiracy advances, factions shift, and L7 170/320 XP reconciles.",
],
9: [
"The Crownshaft forge hangs beside a seemingly endless ivory lift spine, with the Bell Regent's yoke far above.",
"Inventory shows relic ingredients, damaged Survey Bracer, obsolete Shell Dust, no filters, and the missing route token.",
"Elian discards the inert Shell Dust to free the slot required for a final-floor loadout.",
"Orin proposes a single irreversible forge: one weapon strong enough for the Regent or several parts safe enough to sell.",
"Glasshook, Rift Nail, and Brass Maw Core combine into the dark Relic Regentbreaker Edge.",
"Anchorfork, Sumpglass Coil, and Tuning-Fork Key combine into Mira's pale Crownfork Spear.",
"A loadout comparison shows consumed ingredients, repaired Survey Bracer, rebuilt compact Kiln Satchel, and both Relic weapons.",
"Crownshaft Assault opens beside L7 170/320 XP, party trust, and the public-lift survival condition.",
"The four adults ascend a narrow platform along the Crownshaft cable with three branching guard rails above.",
"Ivory Crown Guards drop onto the upper rail and cut the lift brake line.",
"Elian completes his tenth verified read on the guards' linked knee and cable faults.",
"Fault Sight II replaces rank I with two linked faults, 14 Qi cost, 18s cooldown, and eight-second duration.",
"Elian marks knee and cable while Sable cuts a safe movement lane between them.",
"Fault Step II pivots from the guard knee to the severed brake housing.",
"A guard blade cuts Mira's left upper arm before she can anchor the Crownfork.",
"Sable takes Mira's exposed side without asking for forgiveness or command.",
"Orin's rebuilt Kiln Satchel powers Suture Pulse and closes the fresh arm wound without erasing strain.",
"Mira binds Elian and Sable into Lockstep Brace as the platform drops.",
"Fault Bastion: Crosslock drives linked faults into the brake housing and throws the guards clear of the lift.",
"The platform catches on one cable; Mira's arm hangs bound while the public lift remains far below.",
"Guard XP and ascent progress bring Elian to 300/320 without an early level-up.",
"The Crownshaft cap opens and reveals the underside of the enormous Bell Regent.",
"The Regent wakes early and tears one complete platform ring from the shaft.",
"Strike the Silence replaces the incomplete assault: defeat the Regent before it reaches the public lift.",
],
10: [
"The Bell Regent towers through the final chamber, four long legs spanning ivory platforms above the public lift cable.",
"Opening status shows Elian L7 300/320, 28/75 HP, 12/76 Qi, Channel I, injuries, Relic loadout, and active quest.",
"Elian assigns Mira the yoke, Sable the escape lane, Orin the lift cable, and himself the hostile note.",
"Wide geography fixes the Regent above, party on three platforms, public cable center, and the fourth-meridian door behind.",
"The Regent sounds one visible ring that bends every free cable toward its hollow face.",
"The central platform folds, forcing Mira and Sable onto opposite sides of the public cable.",
"Mira drives Crownfork into the crown yoke while Sable opens a Severing Lane under her injured arm.",
"The Regent lifts one leg and uses the skewed yoke to throw Mira across the cable.",
"Mira catches the cable with her shield hand; the bound left arm cannot lift the spear.",
"Elian reads two linked faults, one in the yoke and one in the note-distorted platform.",
"Two Crown Guards enter the lane; their defeat supplies 35 XP and crosses the Level 8 threshold once.",
"Level 8 raises HP/Qi maximums, grants one point, and carries 15/400 XP without clearing injuries.",
"Sable spends one controlled debt stack to cut a lane from Mira to Orin rather than toward the boss.",
"Orin anchors the rebuilt kiln line to the public cable and sends Suture Pulse to Elian.",
"After surviving the complete hostile note, Elian places Rift Mark on the Regent's nonliving yoke joint.",
"The Regent stamps through Elian's platform and breaks his route to the marked yoke.",
"Elian falls beside the public cable with the mark expiring above him.",
"Inside the second hostile note, Elian accepts its cadence and opens Breath Channel II in two restrained ember arcs.",
"A cultivation menu records the hostile-resonance gate, 76→86 max Qi, captured restoration, and Meridian Shear risk avoided.",
"Fault Step II follows the bent cable to Mira, then pivots at the linked yoke fault.",
"Mira, Sable, and Orin lock the cable and yoke so Elian's two-stage draw has one unambiguous target.",
"Rift Draw III severs the yoke and carries through the linked crown joint in the volume's clearest vertical spectacle.",
"The Bell Regent collapses away from the public cable; Crown Shard, Meridian Seal, and Sponsor Writ resolve with boss credit.",
"A CH01→CH10 comparison closes over the surviving lift as the sealed fourth-meridian door opens behind the adult party.",
],
}

ACTION_ORDERS = {
    1: set(range(5, 12)) | {14, 15},
    2: set(range(8, 16)) | {18, 19, 20},
    3: set(range(11, 19)) | {21, 22},
    4: set(range(7, 18)),
    5: {10, 11, 14, 15, 16, 17},
    6: set(range(8, 15)) | {16, 18, 19, 20},
    7: set(range(6, 13)) | {14, 16, 17, 18, 19, 20},
    8: set(range(8, 16)) | {17, 18, 19, 20},
    9: set(range(10, 19)) | {20, 22, 23},
    10: set(range(5, 10)) | set(range(13, 18)) | {20, 21, 22},
}

HIGH_ORDERS = {1:{1,15},2:{1,18},3:{1,19},4:{1,18},5:{1,11},6:{1,19},7:{1,19},8:{1,20},9:{1,19},10:{1,18,22}}
MODERATE_ORDERS = {1:{4,8,12,18,21,24},2:{4,8,12,16,21,24},3:{4,8,12,16,21,24},4:{4,8,12,16,21,24},5:{4,8,15,18,21,24},6:{4,8,12,16,21,24},7:{4,8,12,15,18,24},8:{4,8,12,16,21,24},9:{4,8,12,16,22,24},10:{4,8,11,15,20,24}}

SYSTEM_PANELS = {
    1: {2: ("status", ["ELIAN VOSS · LV 3", "XP 60 / 100", "CLASS · SALVAGER", "HP 44 / 52 · QI 31 / 40", "BREATH SEED I"]), 9: ("skill", ["FAULT SIGHT I", "ACTIVE · −12 QI · CD 20s", "ONE VERIFIED FAULT · 6s"]), 14: ("cultivation", ["BREATH SEED II", "GATE · BROKEN BREATH COMPLETED", "QI MAX 40 → 48 · +8 RESTORE", "FAULT STEP I UNLOCKED"]), 16: ("delta", ["LEVEL 4 · XP 45 / 140", "HP 20 / 56 · QI 3 / 48", "CINDER-KEY · RARE ×1", "QUEST COMPLETED · CLASS OPTIONS OPEN"]), 24: ("quest", ["CHOOSE THE CRACK · OFFERED", "SELECT A CLASS PATH", "REACH THE HOLLOW MERIDIAN CROWN", "BELL REGENT ASCENT · ACTIVE"])},
    2: {2: ("status", ["LEVEL 4 · XP 45 / 140", "CLASS OPTIONS · 2", "UNSPENT POINTS · 1", "INJURY · CRACKED RIB"]), 6: ("skill", ["FAULT HOOK I", "ACTIVE · −10 QI · CD 12s", "SELF / UNSECURED OBJECT ONLY", "SOURCE · FAULTLINE ADEPT"]), 16: ("inventory", ["IRON SEAL ×2", "STABILIZE SPAN?", "COST · 1 SEAL · IRREVERSIBLE", "CONFIRM · YES"]), 24: ("delta", ["FAULTLINE ADEPT · ACTIVE", "XP 130 / 140", "IRON SEAL ×1 · CARAPACE ×3", "FREE DELVERS +4 · TRUST +2"])},
    3: {4: ("inventory", ["RESIN SUTURE · TEMPERED", "FRACTURE TREATMENT · +24 HP", "QUANTITY 1 → 0", "SOURCE · ORIN PELL"]), 7: ("cultivation", ["BREATH SEED II", "GATE · THREE PRESSURE PHASES", "COST · 32 QI", "FAILURE · GLASS LUNG"]), 20: ("skill", ["RIFT DRAW I", "ACTIVE · −16 QI · CD 30s", "VERIFIED FAULT REQUIRED", "SOURCE · BREATH SEED III"]), 24: ("delta", ["LEVEL 5 · XP 85 / 190", "BREATH SEED III · QI 0 / 58", "PALM CUT · ACTIVE", "GLASS LENS · RARE ×1"])},
    4: {2: ("enemy", ["SABLE RENN · LV 7", "ASH CROWN PATHCUTTER", "SEVERING LANE II", "ASH DEBT · 4"]), 4: ("quest", ["CLAIM VERDIGRIS SEAL · ACCEPTED", "ONE WINNER · NO SHARED REWARD", "REPUTATION AT RISK"]), 19: ("quest", ["CLAIM VERDIGRIS SEAL · FAILED", "REWARD · NONE", "FREE DELVERS −2 · ASH CROWN +5"]), 24: ("delta", ["HP 12 / 62 · QI 2 / 58", "FRACTURED SCAPULA · ACTIVE", "GLASS LENS · CRACKED", "MIRA SPEAR · BENT"] )},
    5: {2: ("status", ["LEVEL 5 · XP 105 / 190", "HP 12 / 62 · QI 2 / 58", "FRACTURED SCAPULA", "BREATH SEED III"]), 9: ("inventory", ["CRAFT GLASSHOOK?", "CONSUME · CRACKED GLASS LENS", "BASE · HOOKED SHORTBLADE", "IRREVERSIBLE · CONFIRM"]), 17: ("cultivation", ["BREATH CHANNEL I · FAILED", "QI −20 · BREATH DEVIATION", "GATE NOT SATISFIED", "NO CAPACITY GAIN"]), 24: ("delta", ["XP 165 / 190", "GLASSHOOK · ANCHORFORK EQUIPPED", "VERDIGRIS FILTER ×3", "PARTY TRUST +8"] )},
    6: {2: ("quest", ["KEEP THE PUMP HEART · ACCEPTED", "HEART MUST SURVIVE", "REWARD · XP + REPUTATION", "FAILURE · CROWNSHAFT FLOOD"]), 15: ("skill", ["FAULT STEP II", "ACTIVE · −10 QI · CD 7s", "ONE LINKED PIVOT", "CONDITION · FIVE VERIFIED USES"]), 17: ("skill", ["RAMPART THRUST III", "−20 STAMINA · CD 10s", "ANCHORED FORCE REDIRECT", "BASTION ARC I · ACQUIRED"]), 24: ("delta", ["LEVEL 6 · XP 70 / 250", "FILTER ×1 · SUMPGLASS COIL ×1", "FREE DELVERS +10", "QUEST · ADVANCED"] )},
    7: {2: ("status", ["LEVEL 6 · XP 70 / 250", "BREATH SEED III", "THREE CATASTROPHES · 2 / 3", "PUMP HEART · ACTIVE"]), 14: ("cultivation", ["BREATH CHANNEL I", "PROTECTION GATE · SATISFIED", "QI MAX 60 → 72", "BREATH DEVIATION · CLEARED"]), 16: ("skill", ["RIFT MARK I", "ACTIVE · −22 QI · CD 45s", "TEMPORARY NONLIVING FAULT · 4s", "SURVIVED PATTERN REQUIRED"]), 24: ("delta", ["RIFT TEMPERER · ACTIVE", "XP 210 / 250", "RIFT NAIL · RELIC ×1", "QUEST · COMPLETED WITH LOSS"] )},
    8: {2: ("enemy", ["SABLE RENN · LV 7", "ASH DEBT · 6", "DEFAULT AT 7 STACKS", "STATUS · UNSTABLE"]), 4: ("quest", ["RESCUE THE DEBTOR · OPTIONAL", "XP REWARD · NONE", "ASH CROWN HOSTILITY +15", "ACCEPT · YES"]), 22: ("skill", ["RIFT DRAW II", "ACTIVE · −18 QI · CD 26s", "CARRY THROUGH ONE RESONANT JOINT", "SOURCE · BRASS MAW PATTERN"]), 24: ("delta", ["LEVEL 7 · XP 170 / 320", "BRASS MAW CORE · RELIC", "SURFACE TOKEN · LOST", "SABLE · PROVISIONAL ALLY"] )},
    9: {2: ("inventory", ["SLOTS 6 / 7 · WEIGHT 10 / 10", "SHELL DUST · COMMON ×1", "FINAL LOADOUT REQUIRES 1 SLOT", "DISCARD? · YES"]), 7: ("inventory", ["REGENTBREAKER EDGE · RELIC", "CROWNFORK SPEAR · RELIC", "SURVEY BRACER · REPAIRED", "INGREDIENTS · CONSUMED"]), 12: ("skill", ["FAULT SIGHT II", "ACTIVE · −14 QI · CD 18s", "TWO LINKED FAULTS · 8s", "CONDITION · TEN VERIFIED READS"]), 24: ("quest", ["STRIKE THE SILENCE · ACCEPTED", "XP 300 / 320", "PUBLIC LIFT · AT RISK", "BELL REGENT · LV 12"] )},
    10: {2: ("status", ["ELIAN VOSS · LEVEL 7", "XP 300 / 320", "HP 28 / 75 · QI 12 / 76", "RIFT TEMPERER · CHANNEL I"]), 12: ("delta", ["LEVEL 8", "XP CARRY · 15 / 400", "HP MAX 75 → 83 · QI MAX 76 → 80", "UNSPENT POINTS +1"]), 19: ("cultivation", ["BREATH CHANNEL II", "HOSTILE CADENCE · ACCEPTED", "QI MAX 80 → 90 · +46 RESTORE", "MERIDIAN SHEAR · AVOIDED"]), 24: ("comparison", ["CH01 → CH10", "LEVEL 3 → 8 · XP 60/100 → 295/400", "SALVAGER → RIFT TEMPERER", "SEED I → CHANNEL II", "HOOKBLADE → REGENTBREAKER", "FREE DELVERS 0 → 58"] )},
}

DIALOGUE = {
1: [
(1,"Elian","caption","tl","The Hollow Meridian was not scheduled to wake for another six years. The chains disagree with the schedule."),
(3,"Mira","soft","tl","That anchor is singing. Tell me you still have both Iron Seals before the bridge decides to become a ladder."),
(3,"Elian","soft","br","Both seals. One bad rib. And a professional opinion that we should stop standing on the thing that is singing."),
(4,"Mira","open","bl","Professional opinion revised. The bridge has a landlord, and it looks offended by our rent."),
(5,"Elian","butted","tl","One intact anchor behind us. One boss ahead. If it reaches the center, the bridge twists and the lift stays sealed."),
(6,"Mira","soft","tr","Then it never reaches center. Read the legs; I will make the head believe I am the problem."),
(7,"Mira","open","br","Now, Elian. I can redirect the charge, not negotiate with it."),
(9,"Elian","soft","br","The ankle seam is real, but it only stays loaded for six seconds. That is less generous than I hoped."),
(10,"Mira","butted","tl","Six seconds is a career in salvage. Move before the profession changes its mind."),
(11,"Elian","distress","tr","Contact never happened. Forelimb changed angle after the jaw clamp—remember that when it comes again."),
(12,"Mira","soft","tl","Stop turning injuries into field notes. Your breath is folding at the collarbone, and I cannot shield you from inside."),
(12,"Elian","distress","br","You can shield the bridge. I need one complete pattern and something hot enough to force the second circuit."),
(13,"Mira","open","br","That talisman was our exit plan."),
(13,"Elian","butted","tl","It was a possibility. You are an actual person holding a boss by the teeth. I am spending the possibility."),
(14,"Elian","caption","bl","Three broken breaths taught me where the fourth one had to go."),
(15,"Mira","open","tl","Jaw pinned. Fault exposed. Take the line I made and finish what you started."),
(16,"Elian","soft","tl","We kept the anchor, lost the talisman, and gained a key that wants to redesign my career. That feels aggressively fair."),
(16,"Mira","soft","br","Fair would include a medic. Stand slowly, or I will count carrying you as another inventory decision."),
(17,"Mira","soft","tl","The rib is not a metaphor. You cannot breathe around it forever just because the Ledger has not objected yet."),
(17,"Elian","soft","br","I was hoping the dignified silence would imply recovery. Apparently it only implies poor medical judgment."),
(18,"Elian","caption","tl","Retreat meant crossing the same broken chain with less Qi, fewer options, and a waking bell below us."),
(20,"Mira","soft","tl","Do not choose the dangerous class because pain made the safer one feel cowardly. Choose it only if it changes the next fight."),
(20,"Elian","soft","br","The Appraiser would tell us what the ruins are worth. The Adept might tell us where the ruins intend to kill us."),
(21,"Mira","soft","tl","Keep the seal. I would rather fight with a bent plan than watch you purchase one clean minute."),
(22,"Elian","open","bl","That pulse is climbing toward the city."),
(22,"Mira","soft","tr","Then our volume problem is no longer getting out. It is reaching the crown before the bell does."),
(23,"Elian","soft","tl","You know the lift may refuse a classless Salvager at the next gate."),
(23,"Mira","soft","br","Then choose after you can see the price clearly. For once, let tomorrow make its own bad decision."),
],
2: [
(1,"Elian","caption","tl","The Chainworks had been built to move bells the size of houses. Today they were moving people like loose change."),
(3,"Mira","soft","tl","Kiln Appraiser gives you safer refinement, better sale values, and no reason to put your ribs near another charging animal."),
(3,"Elian","soft","br","Faultline Adept gives us a route through a dungeon designed by someone who considered stairs a moral weakness."),
(4,"Mira","soft","tl","That is not an answer about survival."),
(4,"Elian","soft","br","It is. I am choosing the class that turns survival into something the whole party can use."),
(5,"Elian","caption","bl","The seal did not make me stronger. It made every weak thing in the room suddenly honest."),
(7,"Delver","butted","tr","Do not cut the cage free. The little white bastards chewed the brake pins first, and the lower chain is carrying everything."),
(7,"Mira","soft","bl","We heard you. Keep both hands inside and give us your name after gravity loses interest."),
(9,"Elian","butted","tl","Three mites, four pins, one live chain. Mira, if I move the cage, can you own the weight for five seconds?"),
(9,"Mira","soft","br","I can own it for eight. Use six and leave me two for regretting the arithmetic."),
(12,"Elian","open","tl","It cut early. The marked chain is no longer the safe one."),
(12,"Mira","soft","br","Then stop chasing the mark. Chase the person falling under it."),
(13,"Elian","caption","tl","Fault Hook could not pull a living target. It could pull the idiot willing to meet one halfway."),
(15,"Delver","distress","bl","If this is the rescue plan, I preferred not knowing it."),
(15,"Elian","soft","tr","That makes two of us. Hold the latch; Mira is about to make the rest look intentional."),
(16,"Mira","soft","tl","The seal is our last clean bridge repair after this. Spend it only if you accept what cannot be repaired later."),
(16,"Elian","soft","br","A future bridge is hypothetical. The adult hanging from this one has already introduced himself."),
(18,"Mira","open","tl","Mites entering the gear throat. Left rotation, rising teeth, no room for another heroic swing."),
(18,"Elian","butted","br","Good. I have recently developed a professional relationship with narrow mistakes."),
(20,"Mira","soft","tl","Lead mite down. Two pinned against the brake plate."),
(20,"Elian","soft","br","Then do not smash the carapaces. Orin can turn intact shells into something less determined to murder us."),
(22,"Delver","soft","tl","Ash Crown opened a private line through Verdigris. They call it a shortcut because 'planned structural betrayal' lacks charm."),
(22,"Elian","soft","br","Which means the Regent waking early is not an accident. It is somebody's extraction schedule."),
(23,"Mira","soft","tl","Class selected, civilian breathing, one seal left. Try to enjoy an outcome before cataloging the next disaster."),
(23,"Elian","open","br","I will enjoy it in the lift. Quietly, where the chains cannot hear confidence."),
],
3: [
(2,"Orin","soft","tr","Cracked rib, improvised binding, and enough heat damage to season a pan. Which of you called this a successful descent?"),
(2,"Mira","soft","bl","He did. I called it the minimum evidence required to keep yelling at him."),
(3,"Elian","soft","tl","I survived, completed the quest, and brought a medically interesting key."),
(3,"Orin","soft","br","Surviving badly is not a build. It is a debt with symptoms."),
(4,"Orin","butted","tl","This suture is my last fracture treatment. It closes the rib; it does not refund whatever lesson you refuse to learn."),
(5,"Mira","soft","tl","Three live resonance phases while injured? That training quest reads like malpractice with a progress bar."),
(5,"Orin","soft","br","Correct. Which is why he practices here, and not while something is chewing through you."),
(6,"Orin","open","tl","Collarbone receives. Sternum carries. Diaphragm releases. If you force phase two, the pressure returns through the lung."),
(8,"Elian","distress","br","Second phase keeps collapsing when I protect the rib."),
(8,"Mira","soft","tl","The rib is repaired. Your body has not received the paperwork. Give it a slower first breath."),
(9,"Orin","soft","tr","She is right, which I record only because it irritates both of us efficiently."),
(10,"Elian","caption","bl","The level arrived because I finished the gate, not because the pain looked dramatic."),
(11,"Mira","butted","tl","Glassback above the third rib. Six legs, one shell, and a gallery built to repeat every mistake."),
(12,"Elian","soft","tl","It pulses in threes. Orin, stay behind the brass rail. Mira, give the first note somewhere empty to go."),
(12,"Mira","soft","br","You get one read before the echo returns. Make it useful, not beautiful."),
(15,"Elian","open","tl","The fault moved with the note. The shell is not armor; it is a rotating map."),
(16,"Mira","soft","br","Then stop attacking the map before it finishes turning."),
(17,"Orin","butted","tr","Palm cut. Tendons still moving. Close the hand and do not donate more blood to the acoustics."),
(18,"Elian","soft","tl","The creature has three notes. My breath has three phases. I do not need to outrun the pattern."),
(18,"Mira","soft","br","You need to survive long enough to answer on the third."),
(21,"Elian","caption","tl","First note: receive. Second: carry. Third: release through the joint that finally stayed still."),
(22,"Mira","open","bl","Contact. Rear joint separated. Hold formation until every leg stops."),
(23,"Orin","soft","tl","Rare Glass Lens, two acid glands, one ruined glove. The dungeon remains a terrible employer with excellent inventory."),
(23,"Elian","soft","br","Keep the lens. If the next fault moves, I would like better evidence before I embarrass myself again."),
],
4: [
(1,"Elian","caption","tl","Verdigris began where the dungeon stopped pretending its machinery was dead and started charging admission."),
(3,"Sable","soft","tr","The seal admits one path. Ash Crown paid for the route, so we will take the reward and leave you the educational debris."),
(3,"Mira","soft","bl","You did not pay for the route. You paid someone to break every public alternative."),
(4,"Elian","soft","tl","One winner, no shared credit. You designed a quest that turns rescue teams into opponents."),
(4,"Sable","soft","br","No. I accepted the quest that was already here. Moral editing does not improve completion rates."),
(5,"Elian","open","tl","The guardian's chest mark is moving before activation."),
(5,"Orin","soft","br","Then record movement, not weakness. A lens can make a wrong answer look exceptionally sharp."),
(7,"Mira","butted","tl","Lower route rotates clockwise. Elian, stay inside my spear. Orin, two platforms back and no arguments."),
(8,"Elian","soft","br","Sable is taking the upper lane faster than the structure can settle."),
(8,"Mira","soft","tl","Let her race the architecture. We are racing the consequence."),
(10,"Elian","butted","tl","Bailiff controls center. Seal beyond. Sable above. If we force left, Mira gets one anchored thrust before the platform turns."),
(10,"Mira","soft","br","One is enough if your mark remains where you put it."),
(13,"Elian","open","tl","It moved. The chest fault moved after commitment."),
(13,"Orin","soft","br","Abort the draw. A false line is worse than no line because your body believes it."),
(14,"Mira","soft","tl","Too late. I am turning the spear—protect your shoulder."),
(16,"Elian","distress","br","Left arm offline. Lens cracked. Guardian reset in four beats."),
(16,"Mira","soft","tl","You are not a status report. Stay conscious and let us carry the facts."),
(18,"Sable","butted","tr","You made the opening. I took the objective. Hate the contract after you live through it."),
(20,"Elian","distress","tl","Was the shortcut always meant to feed the slow teams into that guardian?"),
(20,"Sable","soft","br","It was meant to feed somebody. I was told competence would decide who."),
(21,"Orin","soft","tl","Scapula fracture. No arm load, no cultivation push, and no clever wording that makes either restriction optional."),
(21,"Mira","soft","br","You heard the medic. Save the analysis until I no longer need both hands to carry you."),
(23,"Elian","caption","tl","The wrong victory was still a victory. That was the part of Sable's answer I could not dismiss."),
(23,"Mira","open","br","Kiln door ahead. We lost the seal, not the volume. Breathe until that distinction becomes useful."),
],
5: [
(1,"Elian","caption","tl","The refuge had one cold forge, no spare miracles, and walls thick enough to contain an honest inventory."),
(3,"Orin","soft","tr","The ampoule repairs the fracture. The scar stays, your strength returns slowly, and we enter the next floor without reserve medicine."),
(3,"Elian","soft","bl","If we save it, I cannot hold a weapon. If we use it, you cannot repair the next person."),
(5,"Mira","soft","tl","Say which risk you choose. Do not hide a sacrifice inside the word 'efficient' and expect us to thank the arithmetic."),
(5,"Elian","soft","br","We repair the shoulder. Then we spend rare parts on the party, not on a future sale none of us may reach."),
(6,"Orin","butted","tl","Stitchfire going in. The heat is treatment, not proof of character. You are allowed to hate every second."),
(7,"Elian","distress","br","Arm moves. Pain remains professionally committed."),
(7,"Mira","soft","tl","Good. Pain can file a complaint after you stop treating your body like rented equipment."),
(8,"Orin","soft","tr","The cracked lens can become a sight groove. The acid glands can become filters. The last seal can straighten Mira's load path."),
(8,"Elian","soft","bl","And every choice destroys the option we did not take."),
(9,"Mira","soft","tl","That is inventory. If nothing is lost, it was only decoration."),
(11,"Elian","caption","bl","The Glasshook kept the old blade's reach and replaced certainty with a channel for better questions."),
(12,"Mira","soft","tl","My spear is not worth your last seal if the seal keeps us alive later."),
(12,"Elian","soft","br","Your spear keeps us alive now. The seal does not get sentimental priority because it is still unused."),
(14,"Mira","open","br","Anchorfork balanced. Shield line stable. I can redirect force without asking the bent shaft for permission."),
(15,"Orin","soft","tl","Do not attempt Channel I. You have capacity, but the gate requires a protected line under real load."),
(15,"Elian","soft","br","Waiting for danger to cultivate feels like leaving an argument unfinished."),
(16,"Mira","butted","tl","Danger is not a tutor you summon for office hours."),
(17,"Orin","distress","br","Pressure reversed. Breath Deviation active. Congratulations: the Ledger agrees with both of us."),
(18,"Mira","soft","tl","Shared timing is a strategy. Spending yourself before anyone can object is a habit. I need you to know the difference."),
(18,"Elian","soft","br","Then object sooner. I am apparently building a class around information delivered under hostile conditions."),
(19,"Orin","soft","tr","Three filters. Each survives one concentrated exposure. Two for the Sump, one for the mistake we have not met."),
(20,"Elian","open","bl","And one bag of shell dust, occupying a slot out of spite."),
(23,"Mira","soft","tl","Three roles, two repaired weapons, one medic without reserve medicine. We move only while all three can name the retreat signal."),
(23,"Orin","soft","br","The retreat signal is 'Orin was right.' I expect crisp diction under pressure."),
],
6: [
(1,"Elian","caption","tl","Verdigris Sump was a drowned machine still trying to complete a shift nobody had survived to cancel."),
(3,"Orin","soft","tr","Filters seat under the collar. If the ceramic turns black, leave the water even if the Ledger calls the objective recoverable."),
(3,"Mira","soft","bl","And if the heart fails?"),
(4,"Elian","soft","tl","We retreat on two shield strikes. The west column stays standing. Nobody crosses an acid lane alone."),
(4,"Orin","soft","br","A complete plan with verbs and limits. The class may yet become employable."),
(5,"Mira","open","bl","Pump heart is clean. Secondary sluice already carries too much pressure."),
(6,"Elian","butted","tl","Three Choir bodies, one breath rhythm. Levels differ, so the shared joint matters more than individual armor."),
(7,"Mira","soft","tl","Heart center. Two lanes incoming. Orin behind my left edge; Elian owns the oxidized column."),
(7,"Elian","soft","br","If the column moves, the whole room changes direction. I will ask before improving it."),
(9,"Mira","open","tr","Rampart set. Sending the lane around the heart."),
(10,"Elian","soft","bl","Hooking myself, not the Choir. The skill refuses living targets, and today I appreciate its ethics."),
(11,"Orin","butted","tl","Palm reopened. Suture Pulse crossing on Mira's safe line—twelve health, no miracle, keep the glove closed."),
(12,"Mira","soft","tr","Lower sluice broken. Water divides us in three seconds."),
(12,"Elian","soft","bl","Then I cross in two and leave the third for being wrong."),
(14,"Elian","caption","tl","The fifth step reached the seam. The new rank began when the seam stopped being enough."),
(16,"Mira","soft","tl","You turned in the middle of Fault Step."),
(16,"Elian","soft","br","Linked fault. Higher cost, shorter recovery. The Ledger finally priced indecision as a feature."),
(17,"Orin","soft","tr","Mira, the pump accepted your anchor pattern. Two skill changes; neither one excuses testing them beside my face."),
(18,"Mira","butted","tl","Bastion Arc opens the water. Fault Hook brings the lead body into the empty lane. On my third breath."),
(18,"Elian","soft","br","And Orin keeps the heart alive while we pretend this was always a three-person technique."),
(19,"Mira","open","tl","One. Two. Latch and Lance."),
(20,"Elian","soft","br","Shared joint separated. Wait for the water to clear before celebrating anything with more legs."),
(22,"Orin","soft","tr","Sumpglass Coil, intact. Pump Token, weightless. Reputation, somehow heavier than both."),
(23,"Elian","soft","tl","They called us useful without adding 'disposable.' I am trying not to inspect the wording for traps."),
(23,"Mira","soft","br","Try accepting one good line before Fault Sight finds a crack in it."),
],
7: [
(1,"Elian","caption","tl","The lower sluice had one stable truth: every route to the pump heart passed beneath something ready to fall."),
(3,"Orin","soft","tr","Ceiling fault is migrating with water load. If it reaches the pale arch, the heart drowns under its own housing."),
(3,"Mira","soft","bl","Keep the satchel closed and your route shorter than mine."),
(4,"Elian","butted","tl","Collapse Hound. Level eight. It is reading the ceiling with its tail, which feels like professional theft."),
(5,"Mira","soft","tl","Hound above the sluice. Heart through the far arch. Orin stays below my shield; you watch the bite pattern."),
(5,"Elian","soft","br","I watch the whole pattern. No early draw, even when the jaw offers one."),
(6,"Orin","open","tr","It is not attacking us. It is attacking the room that contains us."),
(7,"Elian","caption","tl","Bite loaded the fault. Pull aimed it. Release decided who the ceiling would kill."),
(8,"Mira","soft","bl","First slab redirected. The tail is moving—Elian, tell me which direction belongs to us."),
(9,"Elian","soft","tr","None yet. It reversed the counterweight after your brace."),
(10,"Orin","butted","tl","Satchel clear. Mira, down."),
(10,"Mira","soft","br","Orin, no—your whole medical kit is on that strap."),
(11,"Orin","open","bl","Equipment can drown without becoming a patient."),
(12,"Elian","soft","tl","Killing angle is open. So is the line that takes the plate away from Mira. I cannot choose both."),
(12,"Mira","soft","br","You can. Choose the person first and let the class catch up."),
(13,"Elian","caption","tl","Collarbone received. Sternum carried. The falling ceiling supplied the pressure I had tried to counterfeit."),
(14,"Orin","soft","tr","Channel is open. Two pulses, stable. Do not spend the capacity before the structure answers."),
(15,"Mira","soft","tl","Rift Temperer. The requirement was never three kills; it was three complete patterns and one changed decision."),
(16,"Elian","soft","br","Rift Mark creates a weakness only after I survive the enemy's grammar. Expensive, conditional, and finally honest."),
(18,"Mira","butted","tl","Mark on the counterweight. I will send the debris through it; you keep the break away from the heart."),
(19,"Elian","open","br","Temporary fault holding. Break now."),
(21,"Orin","soft","tr","Heart survives. Secondary sluice does not. Completion with loss is still completion, despite what proud people call it."),
(23,"Mira","soft","tl","Your class changed after your choice did. Remember the order when power tries to rewrite the story."),
(23,"Elian","soft","br","I will. And we will rebuild your satchel before you start treating injuries with disapproval alone."),
],
8: [
(1,"Elian","caption","tl","The Cistern carried every voice twice. Sable's arrived first as a warning and second as something close to fear."),
(2,"Mira","soft","bl","Six debt stacks. The seventh defaults through the sternum. How long have you been calling that a resource?"),
(3,"Sable","soft","tr","Long enough to reach the crown. Not long enough to pretend Ash Crown will forgive a failed delivery."),
(3,"Elian","soft","bl","The shortcut fed teams to the Bailiff, and you still delivered the seal."),
(4,"Sable","butted","tl","Rescue quest offers no XP. You can finally prove your principles when the Ledger refuses to applaud them."),
(4,"Elian","soft","br","Accepted. Not for applause, and not because your argument improved while you were collapsing."),
(5,"Mira","open","bl","Return cable cut. Two agents ascending with our route token."),
(6,"Orin","soft","tr","Then the door is sealed and my missing satchel remains tactically relevant. I dislike consistency."),
(7,"Elian","butted","tl","Brass Maw. Three jaws, three notes. Nobody crosses center until we know which note closes which ring."),
(8,"Mira","soft","tl","Sable opposite us. Exit above. Maw center. I can bridge one ring if she stops spending debt like stamina."),
(8,"Sable","soft","br","Debt is the only stat Ash Crown lets us carry past failure."),
(10,"Sable","distress","tr","Severing Lane open—debt seven. That should have cleared the ring."),
(10,"Elian","soft","bl","It cleared your path and defaulted your breath. Those are different results."),
(11,"Mira","butted","tl","Behind my shield. You can resent the rescue after your knees remember their job."),
(12,"Elian","caption","bl","Low jaw loaded the water. Middle jaw turned the ring. High jaw exposed the throat it expected nobody to survive."),
(13,"Elian","soft","tl","I have the full pattern. Marking the throat, four seconds only."),
(14,"Mira","soft","br","The high note reversed. Your mark is coming back at you."),
(15,"Elian","distress","tl","Chest cut, twenty-nine health. Mark still active."),
(16,"Orin","soft","br","No satchel, no Suture Pulse. Pressure and cloth are the available medicine; choose quickly and without romance."),
(17,"Sable","soft","tr","I can add another Lane."),
(17,"Mira","soft","bl","No. Add your shoulder. A person is allowed to contribute without becoming fuel."),
(18,"Elian","butted","tl","Final filter spent. When I cross, hold the throat ring exactly where the third note wants it."),
(19,"Sable","soft","tr","You trust me on the ring after the gate?"),
(19,"Elian","soft","bl","No. I trust the decision you are making while it costs you something."),
(20,"Mira","open","tl","Throat locked. Draw through the joint."),
(23,"Orin","soft","tr","Relic core, tuning key, sealed return. We gained the weapon and lost the road home in the same minute."),
],
9: [
(1,"Elian","caption","tl","Crownshaft offered one final forge and no polite way to carry every version of ourselves upward."),
(3,"Mira","soft","tl","Discarding shell dust should not require a council."),
(3,"Elian","soft","br","It occupies one slot and proves we once had material to waste. Sentiment has terrible weight efficiency."),
(4,"Orin","butted","tr","The forge consumes Glasshook, Rift Nail, and Maw Core. No reversals, no spare relic, no second attempt if the channel cracks."),
(4,"Elian","soft","bl","Build the Regentbreaker. A safe collection of parts cannot stop the thing those parts taught us to understand."),
(5,"Sable","soft","tr","Ash Crown would sell that core and let the city negotiate with gravity."),
(5,"Mira","soft","bl","You are welcome to discover a better former employer after we save it."),
(6,"Mira","soft","tl","Crownfork carries the Sumpglass rhythm through the old Anchorfork line. My injured arm may not carry the return stroke."),
(6,"Orin","soft","br","Then Lockstep supplies the return. Equipment changes tactics; it does not erase anatomy."),
(7,"Elian","caption","bl","Nothing in the loadout was free. That was how we knew it belonged to this story."),
(8,"Mira","soft","tl","Final rules: public cable survives, Regent stays below the city, and nobody converts themselves into an unnamed consumable."),
(8,"Sable","soft","br","Ash Crown did not include the third rule."),
(9,"Elian","butted","tl","Three guard rails above. Brake housing right. If the platform drops, the center cable is our only shared line."),
(10,"Orin","soft","tr","Guards cutting the brake. Their knees and the cable joints are pulsing together."),
(11,"Elian","open","bl","Tenth verified read. The linked faults are finally visible at once."),
(13,"Sable","soft","tr","Lane open from knee to housing. No debt added."),
(13,"Elian","soft","bl","Good. Keep the lane; I will turn inside it."),
(15,"Mira","distress","tl","Left arm cut. Crownfork still anchored, but I cannot recover the spear alone."),
(16,"Sable","soft","br","Then I take the exposed side. Do not mistake useful timing for an apology."),
(16,"Mira","soft","tl","I will schedule forgiveness after we stop falling."),
(17,"Orin","butted","tr","Suture Pulse crossing. Wound closed, arm strained, twelve health accounted. Please remain attached to the platform."),
(18,"Elian","soft","tl","Lockstep all four. Mira anchors, Sable clears, Orin holds cable, I carry the faults into the brake."),
(19,"Mira","open","br","Crosslock. On the cable's second recoil."),
(22,"Sable","distress","tr","That is not a mechanism above us."),
(22,"Elian","soft","bl","No. It is the Bell Regent's underside, and it just heard the forge."),
(23,"Mira","butted","tl","Platform ring gone. Regent descending. Whatever assault we planned has become a deadline."),
],
10: [
(1,"Elian","caption","tl","The Regent had no throne. It had four legs, a city beneath it, and a note that made every structure kneel."),
(3,"Elian","soft","tl","Mira owns the yoke. Sable owns the escape lane. Orin owns the public cable. I take the note and return a fault."),
(3,"Mira","soft","br","You take the note only after it finishes. No early draw, no private sacrifice, no improvising a funeral into the plan."),
(4,"Sable","butted","tr","Fourth-meridian door behind the rear leg. Ash Crown wanted the Regent core, but the sponsor wanted whatever that door seals."),
(4,"Orin","soft","bl","Excellent. We can investigate institutional greed after the building-sized bell stops descending."),
(5,"Elian","open","tl","First note bends free cable toward the face aperture. Anchor anything you need to keep."),
(6,"Mira","soft","br","Central platform folding. Sable, opposite side; give me a lane under the injured arm."),
(7,"Sable","soft","tr","Lane open. One controlled debt stack, no default."),
(7,"Mira","soft","bl","Crownfork entering the yoke. Elian, wait for the load to settle."),
(8,"Elian","butted","tl","The Regent is using her anchor as a lever. Mira, release before it throws you across the cable."),
(9,"Mira","distress","br","Too late. Shield hand on cable. Left arm will not lift the spear."),
(10,"Elian","soft","tl","Two linked faults: yoke joint and distorted platform. Neither remains valid through the whole note."),
(11,"Orin","soft","tr","Guards entering Sable's lane. Clear them quickly; the Ledger will level you without healing what the boss breaks."),
(12,"Elian","caption","bl","Level eight expanded the vessel. It did not refill courage, forgive injuries, or choose the next step."),
(13,"Sable","soft","tr","I can cut toward the Regent."),
(13,"Mira","soft","bl","Cut toward Orin. Saving the cable is the fight, even when the boss is louder."),
(14,"Orin","butted","tl","Cable anchored. Suture Pulse to Elian, twelve health. That is the last clean heat cycle in the rebuilt satchel."),
(15,"Elian","soft","br","Full hostile pattern survived. Rift Mark on the nonliving yoke—four seconds from contact."),
(16,"Mira","soft","tl","Platform gone. Your marked route is gone with it."),
(17,"Elian","distress","br","Not gone. Bent into the public cable."),
(18,"Elian","caption","tl","I had tried to defeat the bell by holding my own rhythm. Channel II opened when I accepted its cadence without surrendering mine."),
(19,"Orin","soft","tr","Two stable arcs. Ninety maximum Qi. Meridian Shear avoided by an amount I refuse to call comfortable."),
(20,"Elian","butted","tl","Fault Step follows the bent cable, pivots at the yoke. Mira, I need your anchor for the second draw."),
(20,"Mira","soft","br","You have it. Sable clears the return; Orin locks the city line. Nobody carries this alone."),
(21,"Sable","soft","tr","Escape lane closed. Attack lane open. For once, the difference is voluntary."),
(21,"Orin","soft","bl","Cable tension stable. Do the spectacular thing before my equipment develops another opinion."),
(22,"Mira","open","tl","Crosslock complete. Strike the silence."),
(23,"Elian","soft","tl","Boss credit confirmed. Public cable intact. Mira, please tell me the enormous bell is finished moving."),
(23,"Mira","soft","br","It is. Sit down before the Ledger mistakes standing for consent to another quest."),
(24,"Sable","soft","tr","The fourth door is opening, and the sponsor's writ carries a city seal."),
(24,"Elian","soft","bl","Then the next volume begins with evidence. This one ends with everyone still here to read it."),
],
}
