"""Build append-only final local CH05 owner review hub r9 over r8."""
from __future__ import annotations
import hashlib, html, json, os
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; R8=ROOT/"experiments/review-packets/ch05-owner-review-index-r8/owner-review-index-r8-packet.json"; OUT=ROOT/"experiments/review-packets/ch05-owner-review-index-r9"; INDEX=OUT/"index.html"; PACKET=OUT/"owner-review-index-r9-packet.json"
LINKS=[("index_r8","Complete visual review hub r8","HTML","experiments/review-packets/ch05-owner-review-index-r8/index.html","All art, sequence, cadence, lettering, continuity, provenance, and response-contract links."),("closeout_r3","Final overnight closeout r3","TEXT","docs/research/ch05-overnight-closeout-r3.md","Current counts, ranked engineering route, limitations, integrity, and remaining owner boundary."),("candidate_worksheet","Fourteen-candidate visual worksheet","TEXT","docs/research/ch05-strongest-candidate-disposition-guide-r1.md","Eight review checks per candidate with visual-only advance/hold/repair/reject dispositions."),("consistency","Final handoff consistency audit","TEXT","docs/research/ch05-final-handoff-consistency-matrix-r1.md","Twelve consensus facts, zero unexplained conflicts, and one expected source-lineage delta."),("release_r12","Final review integrated release r12","TEXT","docs/research/evidence/ch05-final-review-integrated-release-r12.json","Eighty-four effective checks and zero provider, ingestion, or promotion activity."),("safe_source_r4","Final safe-source parity r4","TEXT","docs/research/evidence/ch05-final-safe-source-parity-r4.json","Commit-pinned 934-path safe inventory excluding generated pixels and prohibited material." )]
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def relative(path): return Path(os.path.relpath(path,OUT)).as_posix()
def main():
    OUT.mkdir(parents=True,exist_ok=True); items=[]
    for item_id,title,kind,path_text,summary in LINKS:
        source=ROOT/path_text
        if not source.is_file(): raise SystemExit(f"missing review link: {source}")
        items.append({"id":item_id,"title":title,"kind":kind,"path":path_text,"sha256":sha(source),"href":relative(source),"summary":summary})
    cards=[f'<article><a href="{html.escape(item["href"])}"><div class="type">LOCAL {item["kind"]}</div><h2>{html.escape(item["title"])}</h2></a><p>{html.escape(item["summary"])}</p><code>{item["sha256"]}</code></article>' for item in items]; page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CH05 owner review index r9</title><style>body{margin:0;background:#10151c;color:#edf1f5;font:15px/1.45 system-ui,sans-serif}header,main,footer{max-width:1480px;margin:auto;padding:26px}header{background:#18202a;border-bottom:1px solid #33404f}h1{margin:0 0 10px}.boundary{color:#ffd18a}.stats{display:flex;gap:12px;flex-wrap:wrap}.stats span{background:#253140;border-radius:8px;padding:8px 12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:18px}article{background:#19222d;border:1px solid #33404f;border-radius:12px;padding:14px;overflow:hidden}.type{width:100%;height:230px;display:grid;place-items:center;background:#0e1319;border-radius:8px;color:#8ecbff;font-size:26px;font-weight:800}a{color:#91ceff;text-decoration:none}code{display:block;color:#8794a3;font-size:10px;overflow-wrap:anywhere}footer{color:#97a2af}</style></head><body><header><h1>North Garden CH05 · final owner review index r9</h1><p class="boundary">Local-only review entry. Visual disposition is not acceptance, rights clearance, exact-base selection, or production execution.</p><div class="stats"><span>29 candidates</span><span>14 strongest</span><span>112 worksheet checks</span><span>128 prior links</span><span>84 release checks</span><span>0 ingested</span></div></header><main><div class="grid">'''+"".join(cards)+'''</div></main><footer>R9 extends immutable r8 · local files only · no network code · no upload · no recorded owner disposition</footer></body></html>'''; INDEX.write_text(page,encoding="utf-8",newline="\n"); prior=json.loads(R8.read_text(encoding="utf-8"));
    if prior.get("record_id")!="ng-ch05-owner-review-index-r8": raise SystemExit("unexpected r8 lineage")
    packet={"record_type":"CH05OwnerReviewIndexPacket","schema_version":"9.0","record_id":"ng-ch05-owner-review-index-r9","state":"LOCAL_FINAL_OWNER_REVIEW_HUB_DISPOSITIONS_ABSENT","extends":{"path":R8.relative_to(ROOT).as_posix(),"sha256":sha(R8),"prior_effective_link_count":128},"link_count":6,"image_link_count":0,"html_link_count":1,"text_link_count":5,"links":items,"artifact_count":1,"index":{"path":INDEX.relative_to(ROOT).as_posix(),"sha256":sha(INDEX),"bytes":INDEX.stat().st_size},"summary":{"candidates":29,"strongest_candidates":14,"worksheet_checks":112,"prior_review_links":128,"release_checks":84,"safe_paths":934,"visual_dispositions":0,"owner_decisions_ingested":0,"accepted":0,"commercially_cleared":0,"executable":0,"provider_calls":0,"uploads":0,"cost_usd":0,"human_review_minutes":None},"animation_shot_plan":None,"e_conte":None,"boundary":"Append-only local hub; r8, pixels, null worksheet, absent owner inputs, and production state remain unchanged."}; PACKET.write_text(json.dumps(packet,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"CH05 owner review index r9: 6 links / 1 artifact; index {sha(INDEX)} packet {sha(PACKET)}"); return 0
if __name__=="__main__": raise SystemExit(main())
