"""Build append-only local CH05 owner review hub r5 over r4."""
from __future__ import annotations
import hashlib,html,json,os
from pathlib import Path
from PIL import Image,ImageOps
ROOT=Path(__file__).resolve().parents[2]; R4=ROOT/"experiments/review-packets/ch05-owner-review-index-r4/owner-review-index-r4-packet.json"; CONTRACT=ROOT/"production/comic/review/ch05-owner-decision-contract-r1.json"; OUT=ROOT/"experiments/review-packets/ch05-owner-review-index-r5"; INDEX=OUT/"index.html"; PACKET=OUT/"owner-review-index-r5-packet.json"
LINKS=[("index_r4","Complete owner hub r4","HTML","experiments/review-packets/ch05-owner-review-index-r4/index.html","All art, cadence, lettering, continuity, readiness, reference, sequence, and chapter-map review links."),("pilot_unlock","Six-decision P010–P013 unlock checklist","TEXT","docs/research/ch05-p010-p013-owner-unlock-checklist-r1.md","Exact route, density, lettering, finish, and copy roots; broad approval is not structured acceptance."),("chapter_lifecycle","12-batch chapter lifecycle map","IMAGE","experiments/review-packets/ch05-chapter-batch-lifecycle-r1/ch05-chapter-batch-lifecycle-map-r1.png","Fifty plans, 12 batches, waves, lifecycle entry, reusable contracts, and batch-specific evidence."),("prompt_blueprint","Four non-executable prompt blueprints","TEXT","production/comic/run-manifests/ch05-p010-p013-prompt-blueprint-r1.json","Exact draft hashes, continuity, causal mechanics, quiet zones, and authorized reference hypotheses."),("prerender_packet","Pre-render packet blueprint","TEXT","production/comic/review/ch05-p010-p013-prerender-packet-blueprint-r1.json","Four missing candidates, five NOT_BUILT artifacts, 44 checks, safe zones, and density targets."),("pilot_lifecycle","Pilot lifecycle state machine","TEXT","production/comic/run-manifests/ch05-p010-p013-lifecycle-state-machine-r1.json","Eleven legal edges, 110 illegal state pairs, bounded repair, and rights separation."),("reproducer","Final seven-domain reproducer matrix","TEXT","docs/research/evidence/ch05-final-evidence-reproducer-matrix-r1.json","Release, delivery, source, frozen, scope, cost, and remote-lineage reproduction.")]
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p): return Path(os.path.relpath(p,OUT)).as_posix()
def main():
    OUT.mkdir(parents=True,exist_ok=True); thumbs=OUT/"thumbnails"; thumbs.mkdir(exist_ok=True); items=[]
    for item_id,title,kind,path_text,summary in LINKS:
        source=ROOT/path_text
        if not source.is_file(): raise SystemExit(f"missing review link {source}")
        row={"id":item_id,"title":title,"kind":kind,"path":path_text,"sha256":sha(source),"href":rel(source),"summary":summary,"thumbnail_path":None,"thumbnail_sha256":None}
        if kind=="IMAGE":
            with Image.open(source) as opened: thumb=ImageOps.contain(opened.convert("RGB"),(900,520),Image.Resampling.LANCZOS)
            canvas=Image.new("RGB",(920,540),(26,32,40)); canvas.paste(thumb,((920-thumb.width)//2,(540-thumb.height)//2)); target=thumbs/f"{item_id}.png"; canvas.save(target,optimize=False,compress_level=9); row["thumbnail_path"]=target.relative_to(ROOT).as_posix(); row["thumbnail_sha256"]=sha(target); row["thumbnail_href"]=rel(target)
        items.append(row)
    cards=[]
    for row in items:
        visual=f'<img src="{html.escape(row.get("thumbnail_href",""))}" alt="{html.escape(row["title"])}">' if row["kind"]=="IMAGE" else f'<div class="type">LOCAL {row["kind"]}</div>'
        cards.append(f'<article><a href="{html.escape(row["href"])}">{visual}<h2>{html.escape(row["title"])}</h2></a><p>{html.escape(row["summary"])}</p><code>{row["sha256"]}</code></article>')
    page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CH05 owner review index r5</title><style>body{margin:0;background:#10151c;color:#edf1f5;font:15px/1.45 system-ui,sans-serif}header,main,footer{max-width:1480px;margin:auto;padding:26px}header{background:#18202a;border-bottom:1px solid #33404f}h1{margin:0 0 10px}.boundary{color:#ffd18a}.stats{display:flex;gap:12px;flex-wrap:wrap}.stats span{background:#253140;border-radius:8px;padding:8px 12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:18px}article{background:#19222d;border:1px solid #33404f;border-radius:12px;padding:14px;overflow:hidden}article img,.type{width:100%;height:230px;object-fit:contain;background:#0e1319;border-radius:8px}.type{display:grid;place-items:center;color:#8ecbff;font-size:26px;font-weight:800}a{color:#91ceff;text-decoration:none}code{display:block;color:#8794a3;font-size:10px;overflow-wrap:anywhere}footer{color:#97a2af}</style></head><body><header><h1>North Garden CH05 · owner review index r5</h1><p class="boundary">Local-only. Art remains unaccepted and commercially uncleared; pilot prompts and review artifacts remain nonexecutable/NOT_BUILT.</p><div class="stats"><span>29 candidates</span><span>50 plans</span><span>12 batches</span><span>6 pilot roots open</span><span>49 release checks</span><span>0 executable</span></div></header><main><div class="grid">'''+''.join(cards)+'''</div></main><footer>R5 extends immutable r4 · no remote assets · no network code · no upload · no recorded owner decision</footer></body></html>'''; INDEX.write_text(page,encoding="utf-8",newline="\n")
    r4=json.loads(R4.read_text(encoding="utf-8")); contract=json.loads(CONTRACT.read_text(encoding="utf-8")); artifacts=[{"path":INDEX.relative_to(ROOT).as_posix(),"sha256":sha(INDEX),"bytes":INDEX.stat().st_size}]+[{"path":x["thumbnail_path"],"sha256":x["thumbnail_sha256"],"bytes":(ROOT/x["thumbnail_path"]).stat().st_size} for x in items if x["thumbnail_path"]]
    packet={"record_type":"CH05OwnerReviewIndexPacket","schema_version":"5.0","record_id":"ng-ch05-owner-review-index-r5","state":"LOCAL_PILOT_AND_CHAPTER_REVIEW_HUB_EXTENDS_R4_OWNER_PENDING","extends":{"path":R4.relative_to(ROOT).as_posix(),"sha256":sha(R4),"link_count":r4["link_count"]},"contract":{"path":CONTRACT.relative_to(ROOT).as_posix(),"sha256":sha(CONTRACT),"completed_decisions":contract["summary"]["completed_decisions"],"events":contract["summary"]["events"],"human_review_minutes":contract["summary"]["human_review_minutes"]},"link_count":len(items),"image_link_count":sum(x["kind"]=="IMAGE" for x in items),"html_link_count":sum(x["kind"]=="HTML" for x in items),"text_link_count":sum(x["kind"]=="TEXT" for x in items),"links":items,"artifact_count":len(artifacts),"artifacts":artifacts,"index":{"path":INDEX.relative_to(ROOT).as_posix(),"sha256":sha(INDEX),"bytes":INDEX.stat().st_size},"owner_decisions":0,"accepted_candidates":0,"provider_calls":0,"uploads":0,"cost_usd":0,"boundary":"Append-only local hub; r4, empty decision contract, generated pixels, and production state remain unchanged."}; PACKET.write_text(json.dumps(packet,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"CH05 owner review index r5: 7 links / {len(artifacts)} artifacts; index {sha(INDEX)} packet {sha(PACKET)}"); return 0
if __name__=="__main__": raise SystemExit(main())
