"""Build append-only local CH05 owner review hub r7 over r6."""
from __future__ import annotations
import hashlib,html,json,os
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; R6=ROOT/"experiments/review-packets/ch05-owner-review-index-r6/owner-review-index-r6-packet.json"; CONTRACT=ROOT/"production/comic/review/ch05-owner-decision-contract-r1.json"; OUT=ROOT/"experiments/review-packets/ch05-owner-review-index-r7"; INDEX=OUT/"index.html"; PACKET=OUT/"owner-review-index-r7-packet.json"
LINKS=[("index_r6","Complete owner hub r6","HTML","experiments/review-packets/ch05-owner-review-index-r6/index.html","All prior art, lettering, continuity, lifecycle, capacity, and delivery links."),("owner_defaults","Exact engineering decision defaults","TEXT","docs/research/ch05-owner-decision-defaults-r1.md","Six pilot defaults plus four deferred recommendations, evidence, risks, and unfilled response template."),("final_reproducer","Current seven-domain reproducer r2","TEXT","docs/research/evidence/ch05-final-evidence-reproducer-matrix-r2.json","Release, delivery, source, frozen, scope, cost, and remote-lineage reproduction."),("safe_source","Current pushed safe-source capture r2","TEXT","docs/research/evidence/ch05-overnight-safe-source-parity-r2.json","Commit-pinned 835-path inventory proving ignored pixels and prohibited material are absent from Git."),("release_r10","Current integrated release r10","TEXT","docs/research/evidence/ch05-overnight-integrated-release-gate-r10.json","Sixty-six effective checks across current delivery hardening with zero provider or promotion activity.")]
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p): return Path(os.path.relpath(p,OUT)).as_posix()
def main():
    OUT.mkdir(parents=True,exist_ok=True); items=[]
    for item_id,title,kind,path_text,summary in LINKS:
        source=ROOT/path_text
        if not source.is_file(): raise SystemExit(f"missing review link {source}")
        items.append({"id":item_id,"title":title,"kind":kind,"path":path_text,"sha256":sha(source),"href":rel(source),"summary":summary})
    cards=[f'<article><a href="{html.escape(x["href"])}"><div class="type">LOCAL {x["kind"]}</div><h2>{html.escape(x["title"])}</h2></a><p>{html.escape(x["summary"])}</p><code>{x["sha256"]}</code></article>' for x in items]
    page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CH05 owner review index r7</title><style>body{margin:0;background:#10151c;color:#edf1f5;font:15px/1.45 system-ui,sans-serif}header,main,footer{max-width:1480px;margin:auto;padding:26px}header{background:#18202a;border-bottom:1px solid #33404f}h1{margin:0 0 10px}.boundary{color:#ffd18a}.stats{display:flex;gap:12px;flex-wrap:wrap}.stats span{background:#253140;border-radius:8px;padding:8px 12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:18px}article{background:#19222d;border:1px solid #33404f;border-radius:12px;padding:14px;overflow:hidden}.type{width:100%;height:230px;display:grid;place-items:center;background:#0e1319;border-radius:8px;color:#8ecbff;font-size:26px;font-weight:800}a{color:#91ceff;text-decoration:none}code{display:block;color:#8794a3;font-size:10px;overflow-wrap:anywhere}footer{color:#97a2af}</style></head><body><header><h1>North Garden CH05 · owner review index r7</h1><p class="boundary">Local-only current handoff. Art, rights, exact-base status, and production execution remain unapproved.</p><div class="stats"><span>29 candidates</span><span>50 plans</span><span>117 prior links</span><span>66 release checks</span><span>10 defaults</span><span>0 executable</span></div></header><main><div class="grid">'''+''.join(cards)+'''</div></main><footer>R7 extends immutable r6 · no remote assets · no network code · no upload · no recorded owner decision</footer></body></html>'''; INDEX.write_text(page,encoding="utf-8",newline="\n")
    r6=json.loads(R6.read_text(encoding="utf-8")); contract=json.loads(CONTRACT.read_text(encoding="utf-8")); artifacts=[{"path":INDEX.relative_to(ROOT).as_posix(),"sha256":sha(INDEX),"bytes":INDEX.stat().st_size}]; packet={"record_type":"CH05OwnerReviewIndexPacket","schema_version":"7.0","record_id":"ng-ch05-owner-review-index-r7","state":"LOCAL_FINAL_EVIDENCE_REVIEW_HUB_EXTENDS_R6_OWNER_PENDING","extends":{"path":R6.relative_to(ROOT).as_posix(),"sha256":sha(R6),"link_count":r6["link_count"]},"contract":{"path":CONTRACT.relative_to(ROOT).as_posix(),"sha256":sha(CONTRACT),"completed_decisions":contract["summary"]["completed_decisions"],"events":contract["summary"]["events"],"human_review_minutes":contract["summary"]["human_review_minutes"]},"link_count":len(items),"image_link_count":0,"html_link_count":1,"text_link_count":4,"links":items,"artifact_count":1,"artifacts":artifacts,"index":{"path":INDEX.relative_to(ROOT).as_posix(),"sha256":sha(INDEX),"bytes":INDEX.stat().st_size},"owner_decisions":0,"accepted_candidates":0,"executable_panels":0,"provider_calls":0,"uploads":0,"cost_usd":0,"boundary":"Append-only local hub; r6, empty decision contract, generated pixels, and production state remain unchanged."}; PACKET.write_text(json.dumps(packet,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"CH05 owner review index r7: 5 links / 1 artifact; index {sha(INDEX)} packet {sha(PACKET)}"); return 0
if __name__=="__main__": raise SystemExit(main())
