"""Compile exact CH05 engineering defaults without ingesting owner decisions."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; UNLOCK=ROOT/"production/comic/review/ch05-p010-p013-owner-unlock-contract-r1.json"; MATRIX=ROOT/"production/comic/review/ch05-route-review-decision-matrix-r1.json"; NONCANON=ROOT/"production/comic/review/future-litrpg-visual-concepts-review-r1.json"; OUTPUT=ROOT/"production/comic/handoff/ch05-owner-decision-defaults-packet-r1.json"; MARKDOWN=ROOT/"docs/research/ch05-owner-decision-defaults-r1.md"; EVIDENCE=ROOT/"docs/research/evidence/ch05-owner-decision-defaults-packet-r1.json"
RISKS={"route_role_aware_hybrid":"Role-aware finishes can create visible style jumps if density and palette are not sequence-gated.","c005_transition_density":"Current foliage density competes with the trail clue at phone size.","c014_action_punctuation":"Keeping the pulse preserves energy but accepts the largest measured adjacent appearance jump.","lettering_semantics":"Silence isolates causal evidence but may postpone necessary narrative clarification.","p010_p013_finish_rhythm":"Four role-aware finishes maximize information but cannot prove uniform chapter continuity.","p010_p013_copy":"A silent causal test cannot validate final dialogue or caption layout.","lettering_visual_arm":"Role-dependent backing is more flexible but needs final copy, tail, localization, and accessibility review.","strongest_candidate_shortlist":"Group-level taste approval cannot establish candidate-specific exact-base or rights status.","noncanon_litrpg_direction":"Kit continuity across the equipment sheets and Mireback scene is untested because new concept outputs were not re-uploaded.","commercial_and_exact_base":"Provider rights, reproducibility, and exact-base suitability remain separate from visual quality."}
FORWARD={"lettering_visual_arm":"Use 88% in-art translucent backing only where protected content remains clear; use the light outside-art band for captions; keep dark direct gutter text as comparison only.","strongest_candidate_shortlist":"Review all 14 individually; preserve engineering shortlist status without accepting as a group.","noncanon_litrpg_direction":"Advance Soren's oatmeal work-derived warden kit, Sigrid's plaid-preserving pathfinder kit, and the peat/root/slate Mireback together into a separate future-canon proposal, not a CH05 revision.","commercial_and_exact_base":"Remain open pending candidate-specific visual review and an explicit rights/commercial decision."}
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(p): return {"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)}
def main():
    unlock=json.loads(UNLOCK.read_text(encoding="utf-8")); matrix=json.loads(MATRIX.read_text(encoding="utf-8")); by={x["decision_id"]:x for x in matrix["decisions"]}; artifact={x["decision_id"]:x["artifact"] for x in unlock["exact_required_decisions"]+unlock["deferred_decisions"]}; roots={x["decision_id"]:x for x in unlock["exact_required_decisions"]}; rows=[]
    for order,item in enumerate(matrix["decisions"],1):
        did=item["decision_id"]; root=roots.get(did); rows.append({"order":order,"decision_id":did,"class":item["class"],"pilot_unlock_required":root is not None,"question":item["question"],"engineering_default":item["engineering_default"],"development_recommendation":FORWARD.get(did,item["engineering_default"]),"evidence":artifact[did],"risk":RISKS[did],"consequence":item["consequence"],"allowed_pilot_values":root["allowed_decisions"] if root else None,"owner_decision":None,"reviewer":None,"human_review_minutes":None,"resolved":False})
    response={"record_type":"CH05OwnerDecisionResponseTemplate","valid_for_ingestion":False,"reason":"Template is intentionally unfilled; copy exact values into the established owner-decision workflow after review.","required_pilot_roots":[{"decision_id":x["decision_id"],"recommended_value":x["engineering_default"],"allowed_values":x["allowed_decisions"],"owner_decision":None} for x in unlock["exact_required_decisions"]],"deferred_decisions":[{"decision_id":x["decision_id"],"engineering_default":by[x["decision_id"]]["engineering_default"],"owner_decision":None} for x in unlock["deferred_decisions"]]}
    packet={"record_type":"CH05OwnerDecisionDefaultsPacket","schema_version":"1.0","record_id":"ng-ch05-owner-decision-defaults-packet-r1","state":"ENGINEERING_DEFAULTS_READY_OWNER_DECISIONS_UNINGESTED","medium":"comic","inputs":[bind(UNLOCK),bind(MATRIX),bind(NONCANON)],"summary":{"decisions":10,"pilot_roots":6,"deferred":4,"recommended_defaults":10,"resolved":0,"owner_decisions":0,"review_events":0,"human_review_minutes":None,"production_prompts":0,"renders":0,"accepted":0,"commercially_cleared":0,"executable":0},"rows":rows,"response_template":response,"recommendation":"Use all six exact pilot defaults for the smallest high-information silent causal test. Keep the four deferred choices open except advance the three non-canon LitRPG motifs only into a separate future-canon proposal.","animation_shot_plan":None,"e_conte":None,"boundary":"Engineering recommendations only. This packet does not ingest approval, unlock production, revise ComicPanelPlans, accept art, clear rights, or select an exact production base."}; OUTPUT.parent.mkdir(parents=True,exist_ok=True); OUTPUT.write_text(json.dumps(packet,indent=2)+"\n",encoding="utf-8",newline="\n")
    lines=["# CH05 owner decision defaults r1","","These are engineering recommendations, not recorded owner decisions. All ten decision fields remain null.","","## Recommended pilot defaults",""]
    for row in rows[:6]: lines += [f"### {row['order']}. `{row['decision_id']}`", "",f"Recommended exact value: `{row['engineering_default']}`",f"Evidence: [{Path(row['evidence']['path']).name}]({row['evidence']['absolute_path']})",f"Why: {row['consequence']}",f"Risk: {row['risk']}",""]
    lines += ["## Deferred recommendations",""]
    for row in rows[6:]: lines += [f"### {row['order']}. `{row['decision_id']}`","",f"Engineering default: `{row['engineering_default']}`",f"Recommendation: {row['development_recommendation']}",f"Evidence: [{Path(row['evidence']['path']).name}]({row['evidence']['absolute_path']})",f"Risk: {row['risk']}",""]
    lines += ["## Exact six-root response template","","If you want to unlock prompt compilation later, review and return these exact values through the established decision workflow:",""]+[f"- `{x['decision_id']}` → `{x['recommended_value']}`" for x in response["required_pilot_roots"]]+["","This does not cover candidate acceptance, commercial clearance, or exact-base selection."]
    MARKDOWN.write_text("\n".join(lines)+"\n",encoding="utf-8",newline="\n"); evidence={"record_type":"CH05OwnerDecisionDefaultsPacketEvidence","schema_version":"1.0","record_id":"ng-ch05-owner-decision-defaults-packet-evidence-r1","state":"PASS_OWNER_PENDING","packet":bind(OUTPUT),"markdown":bind(MARKDOWN),"inputs":packet["inputs"],"summary":packet["summary"],"artifact_count":10,"response_template_valid_for_ingestion":False,"animation_shot_plan":None,"e_conte":None}; EVIDENCE.parent.mkdir(parents=True,exist_ok=True); EVIDENCE.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n"); print("CH05 owner defaults: 10 decisions = 6 pilot + 4 deferred; 0 resolved/ingested/prompts/renders"); return 0
if __name__=="__main__": raise SystemExit(main())
