"""Compile final post-r13 owner start-here and delivery audit."""
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];R13=ROOT/"docs/research/evidence/ch05-final-integrated-release-r13.json";SAFE=ROOT/"docs/research/evidence/ch05-post-reproducer-safe-source-parity-r5.json";COMPLETION=ROOT/"docs/research/evidence/ch05-completion-readiness-audit-r1.json";HUB=ROOT/"experiments/review-packets/ch05-owner-review-index-r9/index.html";LINKS=ROOT/"docs/research/ch05-review-links-r7.md";WORKSHEET=ROOT/"docs/research/ch05-strongest-candidate-disposition-guide-r1.md";STARTER=ROOT/"docs/research/ch05-final-review-session-starter-r1.md";RESPONSE=ROOT/"docs/research/ch05-owner-response-guide-r1.md";CLOSEOUT=ROOT/"docs/research/ch05-overnight-closeout-r3.md";OUTPUT=ROOT/"production/comic/handoff/ch05-post-r13-final-delivery-audit-r1.json";GUIDE=ROOT/"docs/research/ch05-final-owner-review-start-here-r1.md";EVIDENCE=ROOT/"docs/research/evidence/ch05-post-r13-final-delivery-audit-r1.json"
INPUTS=[R13,SAFE,COMPLETION]
def git(*args):return subprocess.run(["git",*args],cwd=ROOT,check=True,capture_output=True,text=True).stdout.strip()
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def bind(path,absolute=False):
    row={"path":path.relative_to(ROOT).as_posix(),"sha256":sha(path)}
    if absolute:row["absolute_path"]=path.resolve().as_posix()
    return row
def main():
    r13,safe,completion=[json.loads(path.read_text(encoding="utf-8")) for path in INPUTS];head=git("rev-parse","HEAD");origin=git("rev-parse","origin/main");steps=[("open_visual_hub",HUB,"Review art, sequences, cadence, continuity, lettering, and diagnostics."),("open_all_links",LINKS,"Use the exact 134-resource inventory for every contact sheet, packet, overlay, and strongest candidate."),("fill_candidate_worksheet",WORKSHEET,"Record eight visual checks and one disposition for each of 14 strongest candidates; no acceptance is implied."),("review_closeout",CLOSEOUT,"Review measured results, route recommendation, limitations, and remaining decisions."),("start_six_root_session",STARTER,"Follow the live-timed six-root dependency order."),("fill_strict_root_response",RESPONSE,"Create and validate ignored local response/timer files only during actual review."),("verify_completion",ROOT/"docs/research/ch05-completion-readiness-audit-r1.md","Confirm all requested delivery categories are present before any later ingestion milestone."),("verify_final_release",R13,"Reproduce the final 9-command/18-domain integrated gate."),("verify_safe_source",SAFE,"Confirm the pushed source frontier excludes generated pixels and prohibited material." )]
    audit={"record_type":"CH05PostR13FinalDeliveryAudit","schema_version":"1.0","record_id":"ng-ch05-post-r13-final-delivery-audit-r1","state":"PASS_FINAL_POINTER_READY_OWNER_REVIEW_PENDING","medium":"comic","inputs":[bind(path) for path in INPUTS],"review_order":[{"order":index,"id":item_id,"resource":bind(path,True),"action":action} for index,(item_id,path,action) in enumerate(steps,1)],"summary":{"steps":9,"candidates":29,"strongest_candidates":14,"worksheet_checks":112,"plans":50,"batches":12,"review_links":134,"priority_links":67,"completion_deliverables":12,"release_commands":9,"release_domains":18,"safe_paths":971,"zero_cost_milestones":91,"remaining_decisions":10,"owner_inputs":0,"owner_decisions_ingested":0,"visual_dispositions":0,"accepted":0,"commercially_cleared":0,"executable":0,"provider_calls":0,"uploads":0,"paid_spend_usd":0,"human_review_minutes":None},"source":{"compile_head":head,"origin_main":origin,"remote_parity":head==origin,"safe_capture":safe["captured_commit"],"safe_capture_ancestor":subprocess.run(["git","merge-base","--is-ancestor",safe["captured_commit"],head],cwd=ROOT).returncode==0},"release_state":r13["state"],"completion_state":completion["state"],"animation_shot_plan":None,"e_conte":None,"boundary":"Final navigation and delivery audit only. No response, disposition, decision, ingestion, acceptance, clearance, exact base, plan revision, upload, or production execution is created."};OUTPUT.parent.mkdir(parents=True,exist_ok=True);OUTPUT.write_text(json.dumps(audit,indent=2)+"\n",encoding="utf-8",newline="\n")
    lines=["# North Garden CH05 — final owner review: start here","",f"1. [Open the final visual hub]({HUB.resolve().as_posix()})",f"2. [Open all 134 exact review links]({LINKS.resolve().as_posix()})",f"3. [Review and fill the 14-candidate visual worksheet]({WORKSHEET.resolve().as_posix()})",f"4. [Read final closeout r3]({CLOSEOUT.resolve().as_posix()})",f"5. [Follow the six-root live review starter]({STARTER.resolve().as_posix()})",f"6. [Use the strict owner response guide]({RESPONSE.resolve().as_posix()})",f"7. [Check completion readiness]({(ROOT/'docs/research/ch05-completion-readiness-audit-r1.md').resolve().as_posix()})",f"8. [Inspect final integrated release r13]({R13.resolve().as_posix()})",f"9. [Inspect post-reproducer safe source r5]({SAFE.resolve().as_posix()})","","Visual dispositions are review inputs only. Candidate acceptance, commercial clearance, exact-base selection, route authority, and ComicPanelPlan revision remain separate explicit decisions."];GUIDE.write_text("\n".join(lines)+"\n",encoding="utf-8",newline="\n");evidence={"record_type":"CH05PostR13FinalDeliveryEvidence","schema_version":"1.0","record_id":"ng-ch05-post-r13-final-delivery-evidence-r1","state":"PASS_OWNER_REVIEW_PENDING","audit":bind(OUTPUT),"guide":bind(GUIDE),"inputs":audit["inputs"],"summary":audit["summary"],"source":audit["source"],"animation_shot_plan":None,"e_conte":None};EVIDENCE.parent.mkdir(parents=True,exist_ok=True);EVIDENCE.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n");print(f"CH05 post-r13 delivery: 9 steps/134 links/14 candidates/10 decisions; parity {head==origin}; authority 0");return 0
if __name__=="__main__":raise SystemExit(main())
