"""Compile cross-record consistency audit for the final CH05 handoff."""
from __future__ import annotations
import hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; HUB=ROOT/"docs/research/evidence/ch05-owner-review-index-r8.json"; LINKS=ROOT/"production/comic/review/ch05-review-artifact-link-manifest-r6.json"; CLOSEOUT=ROOT/"production/comic/handoff/ch05-overnight-closeout-bundle-r3.json"; RELEASE=ROOT/"docs/research/evidence/ch05-final-review-integrated-release-r12.json"; SAFE=ROOT/"docs/research/evidence/ch05-final-safe-source-parity-r4.json"; PROVENANCE=ROOT/"docs/research/evidence/ch05-final-model-license-provenance-audit-r1.json"; STARTER=ROOT/"production/comic/handoff/ch05-final-review-session-starter-r1.json"; PREFLIGHT=ROOT/"production/comic/review/ch05-owner-ingestion-preflight-contract-r1.json"; COST=ROOT/"docs/research/evidence/ch05-production-cost-ledger-r29.json"; OUTPUT=ROOT/"production/comic/handoff/ch05-final-handoff-consistency-matrix-r1.json"; GUIDE=ROOT/"docs/research/ch05-final-handoff-consistency-matrix-r1.md"; EVIDENCE=ROOT/"docs/research/evidence/ch05-final-handoff-consistency-matrix-r1.json"
INPUTS=[HUB,LINKS,CLOSEOUT,RELEASE,SAFE,PROVENANCE,STARTER,PREFLIGHT,COST]
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def bind(path): return {"path":path.relative_to(ROOT).as_posix(),"sha256":sha(path)}
def main():
    hub,links,closeout,release,safe,provenance,starter,preflight,cost=[json.loads(path.read_text(encoding="utf-8")) for path in INPUTS]
    rows=[
        {"fact":"candidate_count","values":{"hub":hub["summary"]["candidate_count"],"closeout":closeout["measured_result"]["candidates"],"release":release["effective_state"]["candidates"],"provenance":provenance["summary"]["records"]},"expected":29,"state":"CONSISTENT"},
        {"fact":"comic_panel_plans","values":{"hub":hub["summary"]["plan_count"],"closeout":closeout["chapter_pipeline"]["plans"],"release":release["effective_state"]["comic_panel_plans"]},"expected":50,"state":"CONSISTENT"},
        {"fact":"sequence_batches","values":{"closeout":closeout["chapter_pipeline"]["batches"],"release":release["effective_state"]["sequence_batches"]},"expected":12,"state":"CONSISTENT"},
        {"fact":"review_links","values":{"links":links["effective_unique_artifact_count"],"closeout":closeout["review_links"]["effective_total"],"release":release["effective_state"]["review_links"]},"expected":128,"state":"CONSISTENT"},
        {"fact":"priority_direct_links","values":{"hub":hub["summary"]["priority_review_links"],"closeout":closeout["review_links"]["direct_total"],"release":release["effective_state"]["direct_closeout_links"]},"expected":67,"state":"CONSISTENT"},
        {"fact":"pilot_roots","values":{"hub":hub["summary"]["pilot_roots"],"closeout":closeout["remaining_decisions"]["pilot_roots"],"release":release["effective_state"]["pilot_roots"],"starter":starter["summary"]["pilot_root_subjects"]},"expected":6,"state":"CONSISTENT"},
        {"fact":"zero_cost_milestones","values":{"closeout":closeout["final_integrity"]["zero_cost_milestones"],"release":release["effective_state"]["zero_cost_milestones"],"cost":cost["revision_summary"]["total_local_milestones"]},"expected":82,"state":"CONSISTENT"},
        {"fact":"release_checks","values":{"closeout":closeout["final_integrity"]["release_checks"],"release":release["summary"]["effective_command_count"]},"expected":84,"state":"CONSISTENT"},
        {"fact":"provenance_records","values":{"closeout":closeout["final_integrity"]["provenance_records"],"provenance":provenance["summary"]["records"]},"expected":29,"state":"CONSISTENT"},
        {"fact":"owner_inputs","values":{"hub_response":hub["summary"]["response_files"],"hub_events":hub["summary"]["event_logs"],"closeout_response":closeout["remaining_decisions"]["response_files"],"closeout_events":closeout["remaining_decisions"]["event_logs"],"starter_response":starter["summary"]["response_files_present"],"starter_events":starter["summary"]["event_logs_present"]},"expected":0,"state":"CONSISTENT"},
        {"fact":"authority_activity","values":{"ingested":closeout["activity"]["owner_decisions_ingested"],"accepted":closeout["activity"]["accepted"],"cleared":closeout["activity"]["commercially_cleared"],"executable":closeout["activity"]["executable"],"preflight_eligible":int(preflight["current"]["eligible_for_future_ingestion"])},"expected":0,"state":"CONSISTENT"},
        {"fact":"provider_activity","values":{"calls":closeout["activity"]["provider_calls"],"uploads":closeout["activity"]["uploads"],"paid_spend_usd":closeout["activity"]["paid_spend_usd"],"cost_requests":cost["revision_summary"]["external_requests"],"cost_uploads":cost["revision_summary"]["external_uploads"]},"expected":0,"state":"CONSISTENT"},
    ]
    temporal=[{"fact":"safe_source_capture_paths","earlier_release_snapshot":release["effective_state"]["safe_source_capture_paths"],"later_safe_r4":safe["summary"]["tracked_paths"],"later_closeout_r3":closeout["final_integrity"]["safe_paths"],"delta":safe["summary"]["tracked_paths"]-release["effective_state"]["safe_source_capture_paths"],"state":"EXPECTED_APPEND_ONLY_LINEAGE","explanation":"Release r12 immutably binds safe-source r3 (873); safe-source r4 and closeout r3 were compiled later (934)."}]
    output={"record_type":"CH05FinalHandoffConsistencyMatrix","schema_version":"1.0","record_id":"ng-ch05-final-handoff-consistency-matrix-r1","state":"PASS_NO_UNEXPLAINED_CONFLICTS_OWNER_INPUTS_ABSENT","medium":"comic","inputs":[bind(path) for path in INPUTS],"summary":{"input_records":9,"consensus_facts":12,"consistent_facts":12,"unexplained_conflicts":0,"expected_temporal_differences":1,"candidates":29,"plans":50,"batches":12,"review_links":128,"priority_links":67,"pilot_roots":6,"release_checks":84,"safe_paths_current":934,"zero_cost_milestones":82,"owner_inputs":0,"owner_decisions_ingested":0,"accepted":0,"commercially_cleared":0,"executable":0,"provider_calls":0,"uploads":0,"paid_spend_usd":0,"human_review_minutes":None},"consensus":rows,"temporal_lineage":temporal,"route_consistency":{"closeout_route":closeout["recommended_route"],"state":"ONE_CURRENT_ENGINEERING_RECOMMENDATION_OWNER_UNRESOLVED","uniform_finish_selected":False,"visual_appeal_only_selection":False},"limitation_consistency":{"unavailable_service_fields_per_record":6,"records":29,"commercial_status":"OPEN_PENDING_EXPLICIT_REVIEW","generation_reproducibility":"UNPROVEN","generated_pixels_tracked":False,"owner_inputs_absent":True},"animation_shot_plan":None,"e_conte":None,"boundary":"Cross-record audit only. Expected temporal lineage is explicit; no source record is rewritten and no owner decision, ingestion, acceptance, right, exact base, or production authority is created."}; OUTPUT.parent.mkdir(parents=True,exist_ok=True); OUTPUT.write_text(json.dumps(output,indent=2)+"\n",encoding="utf-8",newline="\n")
    lines=["# CH05 final handoff consistency matrix r1","","Result: 12/12 consensus facts agree across nine current records. There are zero unexplained conflicts.","","One expected temporal difference is retained: release r12 records the earlier 873-path safe-source r3 snapshot; later safe-source r4 and closeout r3 record 934 paths. The 61-path increase is append-only lineage, not a rewritten release.","","Owner inputs, decisions, acceptance, commercial clearance, executable panels, provider calls, uploads, and paid spend remain zero/null.","","The current engineering recommendation remains the role-aware hybrid route; it is not an owner acceptance or a commercial/exact-base conclusion."]; GUIDE.write_text("\n".join(lines)+"\n",encoding="utf-8",newline="\n"); evidence={"record_type":"CH05FinalHandoffConsistencyEvidence","schema_version":"1.0","record_id":"ng-ch05-final-handoff-consistency-evidence-r1","state":"PASS_OWNER_INPUTS_ABSENT","matrix":bind(OUTPUT),"guide":bind(GUIDE),"inputs":output["inputs"],"summary":output["summary"],"animation_shot_plan":None,"e_conte":None}; EVIDENCE.parent.mkdir(parents=True,exist_ok=True); EVIDENCE.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n"); print("CH05 handoff consistency: 12/12 facts; 0 unexplained conflicts; 1 expected lineage delta (873->934); authority 0"); return 0
if __name__=="__main__": raise SystemExit(main())
