"""Compile corrected append-only CH05 final push record r2."""
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];R1=ROOT/"docs/research/evidence/ch05-final-push-record-r1.json";R13=ROOT/"docs/research/evidence/ch05-final-integrated-release-r13.json";POINTER=ROOT/"docs/research/ch05-final-owner-review-start-here-r1.md";OUTPUT=ROOT/"docs/research/evidence/ch05-final-push-record-r2.json";SUMMARY=ROOT/"docs/research/ch05-final-push-record-r2.md";EXPECTED=["GITIGNORE_RECOMMENDED.txt","assets/","batch_generate.py","benchmarks/","garden/","get_ipadapter.cmd","run_batch.cmd","run_comfy.cmd","trainer/"];PENDING=["docs/research/ch05-final-push-record-r2.md","docs/research/evidence/ch05-final-push-record-r2.json","src/north_garden/compile_ch05_final_push_record_r2.py","src/north_garden/validate_ch05_final_push_record_r2.py"]
def git(*args):return subprocess.run(["git",*args],cwd=ROOT,check=True,capture_output=True,text=True).stdout.strip()
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def bind(path):return {"path":path.relative_to(ROOT).as_posix(),"sha256":sha(path)}
def main():
    prior=json.loads(R1.read_text(encoding="utf-8"));r13=json.loads(R13.read_text(encoding="utf-8"));head=git("rev-parse","HEAD");origin=git("rev-parse","origin/main");raw=sorted(line[3:].replace("\\","/") for line in git("status","--short").splitlines() if line.startswith("?? "));untracked=[item for item in raw if item not in PENDING];output={"record_type":"CH05FinalPushRecord","schema_version":"2.0","record_id":"ng-ch05-final-push-record-r2","state":"PASS_CORRECTED_FINAL_PUSH_OWNER_REVIEW_PENDING","supersedes":bind(R1),"preserved_failed_attempt":{"recorded_commit":prior["source"]["recorded_commit"],"recorded_untracked_count":prior["source"]["unrelated_untracked_count"],"validator_failure":"source boundary invalid because pending ADR-0169 was misclassified as unrelated","containing_commit":"7842cce"},"inputs":[bind(R13),bind(POINTER)],"source":{"recorded_commit":head,"origin_main":origin,"branch":git("branch","--show-current"),"remote":git("remote","get-url","origin"),"remote_parity":head==origin,"tracked_paths":len(git("ls-files").splitlines()),"unrelated_untracked_items":untracked,"unrelated_untracked_count":len(untracked),"pending_r2_files":sorted(item for item in raw if item in PENDING)},"summary":{"release_commands":9,"release_domains":18,"review_steps":9,"review_links":134,"candidates":29,"plans":50,"worksheet_checks":112,"remaining_decisions":10,"provider_calls":0,"uploads":0,"owner_decisions_ingested":0,"visual_dispositions":0,"accepted":0,"commercially_cleared":0,"executable":0,"paid_spend_usd":0,"human_review_minutes":None},"animation_shot_plan":None,"e_conte":None,"boundary":"Corrected final pushed record. R1 failure is preserved; nine user-owned items remain excluded and no authority is granted."};OUTPUT.write_text(json.dumps(output,indent=2)+"\n",encoding="utf-8",newline="\n");SUMMARY.write_text(f"# CH05 final push record r2\n\nCorrected pushed ancestor: `{head}`; parity `{head==origin}`; tracked {output['source']['tracked_paths']}; unrelated untracked {len(untracked)}.\n\nR1's pending-ADR misclassification is preserved. R13 remains 9/9 commands across 18 domains; owner authority remains zero/null.\n",encoding="utf-8",newline="\n");print(f"CH05 final push r2: {head[:7]}; parity {head==origin}; tracked {output['source']['tracked_paths']}; unrelated {len(untracked)}; r1 failure preserved");return 0
if __name__=="__main__":raise SystemExit(main())
