"""Compile a concise owner entry point for three complete CH05 route drafts."""
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[2]
ASSEMBLY=ROOT/"production/comic/run-manifests/ch05-complete-chapter-clear-line-watercolor-assembly-r1.json";COMPARE=ROOT/"docs/research/evidence/ch05-three-route-comparison-r1.json";TRIAGE=ROOT/"docs/research/evidence/ch05-complete-chapter-clear-line-watercolor-agent-triage-r1.json";OUTPUT=ROOT/"docs/research/evidence/ch05-three-route-owner-review-start-r1.json";MARKDOWN=ROOT/"docs/research/ch05-three-route-owner-review-start-here-r1.md"
ARTIFACTS=[
("clear_line_lettered_phone","experiments/review-packets/ch05-complete-chapter-clear-line-watercolor-r1/lettered/ch05-complete-chapter-clear-line-watercolor-lettered-r1-phone-390px.png"),("clear_line_contact","experiments/review-packets/ch05-complete-chapter-clear-line-watercolor-r1/review/ch05-complete-chapter-contact-sheet.png"),("clear_line_triage","experiments/review-packets/ch05-complete-chapter-clear-line-watercolor-r1/review/ch05-complete-chapter-clear-line-watercolor-triage-sheet.png"),("clear_line_continuity","experiments/review-packets/ch05-complete-chapter-clear-line-watercolor-r1/review/ch05-complete-chapter-clear-line-watercolor-continuity-sheet.png"),("clear_line_safe_contact","experiments/review-packets/ch05-complete-chapter-clear-line-watercolor-r1/review/ch05-complete-chapter-contact-sheet-lettering-overlay.png"),("clear_line_clean_phone","experiments/review-packets/ch05-complete-chapter-clear-line-watercolor-r1/review/ch05-complete-chapter-phone-390px.png"),("clear_line_lettered_full","experiments/review-packets/ch05-complete-chapter-clear-line-watercolor-r1/lettered/ch05-complete-chapter-clear-line-watercolor-lettered-r1.png"),("three_route_phone","experiments/review-packets/ch05-three-route-comparison-r1/ch05-three-route-lettered-phone-comparison.png"),("three_route_all_50","experiments/review-packets/ch05-three-route-comparison-r1/ch05-three-route-all-50-contact-sheet.png"),("three_route_anchors","experiments/review-packets/ch05-three-route-comparison-r1/ch05-three-route-semantic-anchors.png"),("alt_lettered_phone","experiments/review-packets/ch05-complete-chapter-alt-graphic-r1/lettered/ch05-complete-chapter-alt-graphic-lettered-r1-phone-390px.png"),("alt_triage","experiments/review-packets/ch05-complete-chapter-alt-graphic-r1/review/ch05-complete-chapter-alt-graphic-triage-sheet.png"),("r6_lettered_phone","experiments/review-packets/ch05-complete-chapter-draft-r6/lettered/ch05-complete-chapter-lettered-phone-390px-r1.png")]
STRONG=[2,6,10,17,19,20,29,36,41,44,48,50]
def sha256(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(kind,rel):
 p=ROOT/rel
 with Image.open(p) as im:w,h=im.size
 ignored=subprocess.run(["git","check-ignore","--quiet","--",rel],cwd=ROOT).returncode==0
 if not ignored:raise ValueError(f"artifact not ignored: {rel}")
 return {"kind":kind,"path":rel,"sha256":sha256(p),"width":w,"height":h,"bytes":p.stat().st_size,"repository_state":"IGNORED_LOCAL_REVIEW_ARTIFACT"}
def main():
 assembly=json.loads(ASSEMBLY.read_text(encoding="utf-8"));entries=assembly["entries"];artifacts=[bind(*x) for x in ARTIFACTS];strong=[]
 for n in STRONG:
  e=entries[n-1];strong.append({"panel_id":e["panel_id"],"candidate_id":e["candidate_id"],**bind(f"clear_line_p{n:03d}",e["source"]["path"])})
 doc={"record_type":"CH05ThreeRouteOwnerReviewStart","schema_version":"1.0","record_id":"ng-ch05-three-route-owner-review-start-r1","state":"OWNER_REVIEW_READY_NO_DECISIONS_RECORDED","medium":"comic","planning_structure":"ComicPanelPlan","animation_shot_plan":None,"e_conte":None,"inputs":[{"path":p.relative_to(ROOT).as_posix(),"sha256":sha256(p)} for p in (ASSEMBLY,COMPARE,TRIAGE)],"summary":{"complete_chapter_routes":3,"panels_per_route":50,"new_complete_chapter_arms":2,"new_sequence_outputs":22,"new_panel_crops":100,"review_artifacts":len(artifacts),"strong_clear_line_candidates":len(strong),"clear_line_triage":{"pass":45,"warn":2,"fail":3},"direct_paid_api_cloud_spend_usd":0.0,"built_in_product_cost_usd":None,"human_reviewed":0,"accepted":0,"commercially_cleared":0,"exact_production_base":0},"review_order":["clear_line_lettered_phone","clear_line_triage","three_route_anchors","three_route_phone","clear_line_continuity","clear_line_safe_contact","three_route_all_50"],"artifacts":artifacts,"strongest_clear_line_candidates":strong,"recommendations":["Use r6 as the current semantic base.","Use clear-line watercolor as the leading style-development arm.","Do not promote alternate graphic wholesale.","Resolve P001 departure, P039 three-mark composition, and P043 map possession before a clear-line production-base decision."],"owner_decisions":{"visual_dispositions":None,"canon_revisions":None,"commercial_clearance":None,"exact_production_base":None},"boundary":"Review navigation only; no visual, canon, rights, acceptance, or exact-base decision is inferred."}
 OUTPUT.write_text(json.dumps(doc,indent=2,ensure_ascii=False)+"\n",encoding="utf-8",newline="\n")
 rows="\n".join(f"- [{a['kind']}](../../{a['path']}) — {a['width']}×{a['height']}" for a in artifacts)
 strongest="\n".join(f"- [{x['panel_id']}](../../{x['path']}) — {x['width']}×{x['height']}" for x in strong)
 MARKDOWN.write_text("# CH05 three-route owner review: start here\n\nStart with the clear-line lettered phone scroll, then its triage sheet and the three-route semantic anchors. R6 remains the strongest semantic base; clear-line watercolor is the leading style-development arm. All art is unaccepted review evidence.\n\n## Review packets\n\n"+rows+"\n\n## Strong clear-line candidates\n\n"+strongest+"\n\n## Open visual decisions\n\nReview P001 departure direction, P032 far-bank toe/heel direction, P039 three-mark count, and P043 map possession. Visual preference does not grant commercial clearance or exact-base status.\n",encoding="utf-8",newline="\n")
 print(json.dumps({"output":OUTPUT.relative_to(ROOT).as_posix(),"sha256":sha256(OUTPUT),**doc["summary"]},sort_keys=True));return 0
if __name__=="__main__":raise SystemExit(main())
