"""Compile a zero-prompt, fail-closed preflight contract for CH05 P010-P013."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont

ROOT=Path(__file__).resolve().parents[2]
PLANS=ROOT/"production/comic/ch05-sc01-panel-plans-v1.json";ASSERTIONS=ROOT/"production/comic/continuity/ch05-character-assertion-manifest-r1.json";SCALE=ROOT/"production/comic/layout/ch05-panel-scale-cadence-policy-r1.json";REPAIRS=ROOT/"production/comic/review/ch05-failure-class-repair-matrix-r1.json";DECISIONS=ROOT/"production/comic/review/ch05-owner-decision-contract-r1.json";PROFILE=ROOT/"production/comic/continuity/ch05-fictional-adult-visual-profile-r1.json"
OUTPUT=ROOT/"production/comic/repair-readiness/ch05-p010-p013-preflight-contract-r1.json";CHART=ROOT/"experiments/review-packets/ch05-p010-p013-preflight-contract-r1/ch05-p010-p013-preflight-storyboard-r1.png";EVIDENCE=ROOT/"docs/research/evidence/ch05-p010-p013-preflight-contract-r1.json";FONT=Path("C:/Windows/Fonts/arialbd.ttf")
HYPOTHESES={
 10:{"style_id":"cel_painted","format_role":"medium_character_clue","target_width_px":820,"reference_ids":["p040_sigrid_face"],"reason":"facial listening beat needs mature expression, tied dark hair, and quiet negative space"},
 11:{"style_id":"clear_line_watercolor","format_role":"small_causal_clue","target_width_px":640,"reference_ids":["p050_dual_identity_action"],"reason":"line hierarchy should isolate Soren's oatmeal sleeve, hand, soot twine, and thorn without extra texture"},
 12:{"style_id":"limited_ink_flat","format_role":"small_silent_object_insert","target_width_px":560,"reference_ids":[],"reason":"no-person taut-twine direction is the intentional low-density cadence valley"},
 13:{"style_id":"clear_line_watercolor","format_role":"wide_directional_reentry","target_width_px":1040,"reference_ids":["p050_dual_identity_action"],"reason":"wide rear re-entry tests dual wardrobe silhouettes and literal creek-following direction"},
}
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def canonical(x)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":")).encode()).hexdigest()
def chart(rows:list[dict])->None:
 w,h=1700,950;im=Image.new("RGB",(w,h),(232,236,241));d=ImageDraw.Draw(im);title=ImageFont.truetype(str(FONT),29);body=ImageFont.truetype(str(FONT),17);small=ImageFont.truetype(str(FONT),14)
 d.text((25,18),"CH05 P010–P013 · zero-prompt continuity microsequence preflight",font=title,fill=(20,27,36));d.text((25,60),"Four adjacent ComicPanelPlans · hypotheses only · no generated pixels, upload, provider call, acceptance, or execution authority",font=body,fill=(99,50,50))
 x_positions=[25,445,865,1285]
 for x,row in zip(x_positions,rows):
  d.rounded_rectangle((x,120,x+390,800),15,fill=(248,249,251),outline=(66,105,142),width=4);d.text((x+20,143),f"P{row['display_order']:03d}",font=title,fill=(25,34,45));d.text((x+20,188),row["style_id"].replace("_"," "),font=body,fill=(49,104,150));d.text((x+20,220),f"{row['format_role'].replace('_',' ')} · {row['target_width_px']}px",font=small,fill=(64,75,87));d.multiline_text((x+20,270),"\n".join(__import__('textwrap').wrap(row["narrative_beat"],42)),font=body,fill=(34,43,53),spacing=5);d.text((x+20,360),"Visible cast",font=small,fill=(85,94,104));d.text((x+20,386)," + ".join(row["visible_adult_cast"]) or "NO PEOPLE",font=body,fill=(36,45,55));d.text((x+20,435),"Continuity / causality check",font=small,fill=(85,94,104));checks=row["manual_preflight_checks"]
  d.multiline_text((x+20,465),"\n".join("□ "+c for c in checks),font=small,fill=(52,61,72),spacing=6);d.text((x+20,650),"Reference hypothesis",font=small,fill=(85,94,104));d.multiline_text((x+20,680),"\n".join(row["reference_ids"]) if row["reference_ids"] else "TEXT ONLY",font=small,fill=(52,61,72),spacing=5);d.text((x+20,752),"PROMPT: NULL · EXECUTABLE: FALSE",font=small,fill=(157,61,58))
 d.text((25,850),"Repair slots (maximum two): trigger only after an exact single-class failure; never broad-reroll the four-panel chain.",font=body,fill=(47,57,69));CHART.parent.mkdir(parents=True,exist_ok=True);im.save(CHART,optimize=False)
def main()->int:
 plans=json.loads(PLANS.read_text(encoding="utf-8"));assertions=json.loads(ASSERTIONS.read_text(encoding="utf-8"));scale=json.loads(SCALE.read_text(encoding="utf-8"));profile=json.loads(PROFILE.read_text(encoding="utf-8"));decision=json.loads(DECISIONS.read_text(encoding="utf-8"));plan_by={p["display_order"]:p for p in plans["plans"]};assert_by={p["display_order"]:p for p in assertions["plans"]};scale_by={p["display_order"]:p for p in scale["rows"]};rows=[]
 for order in range(10,14):
  p=plan_by[order];hyp=HYPOTHESES[order];checks=[]
  if p["visible_adult_cast"]:checks.append("hair and canonical wardrobe")
  if len(p["visible_adult_cast"])==2:checks.append("literal lead/follow and re-entry order")
  checks.extend(["one readable causal clue","safe zone protects people/hands/object","phone silhouette and density role"])
  rows.append({"display_order":order,"panel_id":p["panel_id"],"plan_revision_id":p["plan_revision_id"],"plan_canonical_sha256":canonical(p),"narrative_beat":p["narrative_beat"],"composition_intent":p["composition_intent"],"visible_adult_cast":p["visible_adult_cast"],"continuity_assertions":assert_by[order]["role_assertions"],"scale_policy_role":scale_by[order]["scale_role"],"scale_policy_range_px":scale_by[order]["width_range_px"],**hyp,"manual_preflight_checks":checks,"final_copy":None,"prompt":None,"prompt_sha256":None,"source_path":None,"reference_uploads":0,"owner_accepted":False,"commercially_cleared":False,"execution_ready":False,"comic_panel_plan_revision_created":False})
 chart(rows)
 repair_slots=[{"slot_id":"repair-1","state":"UNALLOCATED","trigger":"exact safe-zone, cast-order, or single-object causal failure in one row","allowed_change":"one literal spatial/causal constraint cluster","broad_reroll":False},{"slot_id":"repair-2","state":"UNALLOCATED","trigger":"one remaining exact continuity, density, or phone-readability failure after repair-1 evidence","allowed_change":"one isolated constraint cluster; preserve passing rows","broad_reroll":False}]
 contract={"record_type":"ComicMicrosequencePreflightContract","schema_version":"1.0","record_id":"ng-ch05-p010-p013-preflight-contract-r1","state":"REVIEW_READY_ZERO_PROMPT_FAIL_CLOSED","medium":"comic","comic_panel_plan_collection":{"path":PLANS.relative_to(ROOT).as_posix(),"sha256":sha(PLANS)},"inputs":[{"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)} for p in (ASSERTIONS,SCALE,REPAIRS,DECISIONS,PROFILE)],"summary":{"plan_count":4,"initial_candidate_hypotheses":4,"maximum_repair_slots":2,"maximum_candidate_envelope":6,"prompt_count":0,"reference_hypothesis_uses":sum(len(r["reference_ids"]) for r in rows),"reference_uploads":0,"final_copy_bound":0,"owner_decisions_bound":0,"execution_ready_rows":0,"plan_revisions":0},"rows":rows,"row_root_sha256":canonical(rows),"repair_slots":repair_slots,"preflight_gates":{"owner_decision_contract_sha256":sha(DECISIONS),"owner_completed_decisions":decision["summary"]["completed_decisions"],"current_candidate_and_style_review_complete":False,"microsequence_style_cadence_approved":False,"final_copy_or_silence_bound":False,"exact_reference_selection_approved_for_execution":False,"provider_metadata_available":False,"commercial_clearance":False,"all_required_to_compile_prompts":True,"prompts_may_be_compiled_now":False},"authorized_reference_catalog":[{"reference_id":r["reference_id"],"sha256":r["sha256"],"role":r["role"]} for r in profile["authorized_references"]],"reference_use_boundary":"Hypothesis IDs are metadata only. This contract performs zero uploads and grants no future execution authority.","animation_shot_plan":None,"e_conte":None,"boundary":"ComicPanelPlan-only preflight; no prompts, pixels, provider calls, uploads, spend, acceptance, plan revision, or commercial conclusion."}
 OUTPUT.parent.mkdir(parents=True,exist_ok=True)
 with OUTPUT.open("w",encoding="utf-8",newline="\n") as h:h.write(json.dumps(contract,indent=2)+"\n")
 evidence={"record_type":"CH05P010P013PreflightContractEvidence","schema_version":"1.0","record_id":"ng-ch05-p010-p013-preflight-contract-evidence-r1","state":"FOUR_PLAN_PREFLIGHT_FAIL_CLOSED","contract":{"path":OUTPUT.relative_to(ROOT).as_posix(),"sha256":sha(OUTPUT),"row_root_sha256":contract["row_root_sha256"]},"summary":contract["summary"]|{"repair_slots_unallocated":2,"provider_calls":0,"uploads":0,"external_cost_usd":0,"human_review_minutes":None},"gate_state":contract["preflight_gates"],"chart":{"path":CHART.relative_to(ROOT).as_posix(),"sha256":sha(CHART),"bytes":CHART.stat().st_size},"limitations":["Style, width, and reference choices are hypotheses pending owner review.","No exact prompt exists, so provider preflight and output behavior cannot be evaluated.","The four-plan chain does not test mill interiors, dialogue balloons, combat, armor, weapons, or monsters.","Built-in product model, endpoint, seed, usage, and cost would remain unavailable unless exposed later."],"activity":{"prompts":0,"renders":0,"provider_calls":0,"uploads":0,"spend_usd":0,"plans_revised":0,"acceptances":0},"boundary":contract["boundary"]}
 with EVIDENCE.open("w",encoding="utf-8",newline="\n") as h:h.write(json.dumps(evidence,indent=2)+"\n")
 print("CH05 P010-P013 preflight: 4 plans / 4 hypotheses / 2 unallocated repair slots / 0 prompts")
 print("reference hypotheses 3, uploads/calls/spend 0/0/$0; decisions/copy/executable rows 0/0/0")
 return 0
if __name__=="__main__":raise SystemExit(main())
