"""Compile a measured, nonexecutable production envelope for CH05's remaining 36 plans."""
from __future__ import annotations
import hashlib,json,math
from collections import Counter,defaultdict
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
ROOT=Path(__file__).resolve().parents[2];COVERAGE=ROOT/"production/comic/coverage/ch05-remaining-panel-priority-r1.json";POLICY=ROOT/"production/comic/layout/ch05-panel-scale-cadence-policy-r1.json";EFFORT=ROOT/"docs/research/evidence/ch05-tier-a-effort-scenarios-r1.json";REPAIRS=ROOT/"production/comic/review/ch05-failure-class-repair-matrix-r1.json";PREFLIGHT=ROOT/"production/comic/repair-readiness/ch05-p010-p013-preflight-contract-r1.json";DECISIONS=ROOT/"production/comic/review/ch05-owner-decision-contract-r1.json";OUTPUT=ROOT/"production/comic/run-manifests/ch05-chapter-scale-production-envelope-r1.json";CHART=ROOT/"experiments/review-packets/ch05-chapter-scale-production-envelope-r1/ch05-chapter-scale-production-envelope-r1.png";EVIDENCE=ROOT/"docs/research/evidence/ch05-chapter-scale-production-envelope-r1.json";FONT=Path("C:/Windows/Fonts/arialbd.ttf")
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def canonical(x)->str:return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(",",":")).encode()).hexdigest()
def timing(n:int,basis:dict)->dict:return {"candidate_count":n,"p10_generation_seconds":round(n*basis["p10_seconds"],3),"median_generation_seconds":round(n*basis["median_seconds"],3),"p90_generation_seconds":round(n*basis["p90_seconds"],3),"queue_review_layout_seconds_included":False,"monetary_cost_usd":None,"human_review_minutes":None}
def chart(scenarios:list[dict],roles:dict[str,int])->None:
 w,h=1600,980;im=Image.new("RGB",(w,h),(235,238,242));d=ImageDraw.Draw(im);title=ImageFont.truetype(str(FONT),29);body=ImageFont.truetype(str(FONT),17);small=ImageFont.truetype(str(FONT),14)
 d.text((25,18),"CH05 remaining-36 chapter-scale production envelope",font=title,fill=(20,27,36));d.text((25,60),"Observed generation-only timing · monetary cost and human review time unavailable · no prompt or execution authority",font=body,fill=(104,52,52));y=125;colors=[(57,128,180),(55,145,105),(189,132,43)]
 max_sec=max(x["timing"]["p90_generation_seconds"] for x in scenarios)
 display_names={"one_initial_per_remaining_plan":"INITIAL COVERAGE","one_initial_plus_bounded_repairs":"BOUNDED REPAIR ENVELOPE","two_arms_per_remaining_plan":"TWO-ARM COMPARISON"}
 for color,s in zip(colors,scenarios):
  d.text((30,y),display_names[s["scenario_id"]],font=body,fill=(32,40,50));d.text((30,y+32),f"{s['candidate_count']} candidates",font=small,fill=(70,80,92));x0=390
  for label,key,offset in (("p10","p10_generation_seconds",0),("median","median_generation_seconds",32),("p90","p90_generation_seconds",64)):
   sec=s["timing"][key];length=round(sec/max_sec*850);d.text((300,y+offset),label,font=small,fill=(74,84,96));d.rounded_rectangle((x0,y+offset+2,x0+length,y+offset+18),7,fill=color);d.text((x0+length+12,y+offset),f"{sec:.1f}s",font=small,fill=(42,51,61))
  y+=145
 d.text((25,570),"Remaining-plan conditional cadence roles",font=title,fill=(20,27,36));y=625;max_count=max(roles.values())
 for role,count in sorted(roles.items(),key=lambda x:(-x[1],x[0])):
  d.text((30,y),role.replace("_"," "),font=small,fill=(47,57,69));length=round(count/max_count*650);d.rounded_rectangle((500,y+2,500+length,y+19),7,fill=(78,116,151));d.text((1165,y),str(count),font=small,fill=(47,57,69));y+=34
 d.text((25,930),"The bounded 49-candidate arm uses 13 repair slots = ceil(36 × observed 9/26 nonpass fraction); this is an allowance, not a forecast.",font=small,fill=(78,54,45));CHART.parent.mkdir(parents=True,exist_ok=True);im.save(CHART,optimize=False)
def main()->int:
 coverage=json.loads(COVERAGE.read_text(encoding="utf-8"));policy=json.loads(POLICY.read_text(encoding="utf-8"));effort=json.loads(EFFORT.read_text(encoding="utf-8"));decisions=json.loads(DECISIONS.read_text(encoding="utf-8"));remaining=[r for r in coverage["rows"] if r["coverage_state"]!="selected"];policy_by={r["panel_id"]:r for r in policy["rows"]};basis=effort["observed_basis"];repair_slots=math.ceil(len(remaining)*basis["engineering_warn_or_fail"]/basis["candidate_count"])
 scenario_specs=[("one_initial_per_remaining_plan",36,"denominator coverage before targeted repair"),("one_initial_plus_bounded_repairs",36+repair_slots,"recommended chapter-scale planning ceiling after staged review"),("two_arms_per_remaining_plan",72,"comparative upper arm; no additional repair allowance")]
 scenarios=[{"scenario_id":sid,"candidate_count":count,"purpose":purpose,"executed":False,"timing":timing(count,basis)} for sid,count,purpose in scenario_specs]
 roles=Counter(policy_by[r["panel_id"]]["scale_role"] for r in remaining);tiers=[]
 for tier in ("A","B","C"):
  rows=[r for r in remaining if r["coverage_state"]==tier];tier_roles=Counter(policy_by[r["panel_id"]]["scale_role"] for r in rows);tiers.append({"tier":tier,"plan_count":len(rows),"panel_ids":[r["panel_id"] for r in rows],"display_orders":[r["order"] for r in rows],"cadence_role_counts":dict(sorted(tier_roles.items())),"initial_candidate_count":12,"bounded_repair_slots":4,"tier_envelope_candidates":16,"prompts":0,"executable":False})
 rows=[{"panel_id":r["panel_id"],"display_order":r["order"],"priority_tier":r["coverage_state"],"narrative_function":r["narrative_function"],"motion_mode":r["motion_mode"],"cast_occupancy":r["cast_occupancy"],"scale_role":policy_by[r["panel_id"]]["scale_role"],"width_range_px":policy_by[r["panel_id"]]["width_range_px"],"initial_candidate_slot":1,"repair_slot_allocated":False,"prompt":None,"final_copy":None,"execution_ready":False,"owner_accepted":False} for r in remaining]
 chart(scenarios,dict(roles))
 envelope={"record_type":"ComicChapterScaleProductionEnvelope","schema_version":"1.0","record_id":"ng-ch05-chapter-scale-production-envelope-r1","state":"MEASURED_NONEXECUTABLE_OWNER_REVIEW_GATED","medium":"comic","denominator":{"comic_panel_plans":50,"selected_existing":14,"remaining":36,"tiers":{"A":12,"B":12,"C":12}},"observed_basis":{"candidate_count":basis["candidate_count"],"generation_seconds":basis["generation_seconds"],"p10_seconds":basis["p10_seconds"],"median_seconds":basis["median_seconds"],"p90_seconds":basis["p90_seconds"],"engineering_all_pass":basis["engineering_all_pass"],"engineering_warn_or_fail":basis["engineering_warn_or_fail"],"nonpass_fraction":round(basis["engineering_warn_or_fail"]/basis["candidate_count"],6)},"repair_allowance":{"formula":"ceil(36 * 9 / 26)","slots":repair_slots,"forecast":False,"allocation_rule":"Allocate only after an exact retained single-class failure; no speculative reroll."},"scenarios":scenarios,"recommended_planning_envelope":"one_initial_plus_bounded_repairs","tiers":tiers,"remaining_role_counts":dict(sorted(roles.items())),"rows":rows,"row_root_sha256":canonical(rows),"workflow":[{"stage":1,"name":"owner_review_current_29","required":True,"complete":False},{"stage":2,"name":"P010_P013_microsequence","required":True,"complete":False,"candidate_envelope":6},{"stage":3,"name":"Tier_A_remainder","required":True,"complete":False,"candidate_envelope":12},{"stage":4,"name":"Tier_B_after_sequence_review","required":True,"complete":False,"candidate_envelope":16},{"stage":5,"name":"Tier_C_after_chapter_cadence_review","required":True,"complete":False,"candidate_envelope":16},{"stage":6,"name":"chapter_layout_lettering_acceptance","required":True,"complete":False}],"required_per_candidate_records":["exact ComicPanelPlan snapshot/hash","exact prompt/hash and reference IDs/hashes","output path/hash/dimensions","elapsed time and exposed service metadata","engineering review dimensions and retained failure","phone preview and lettering-safe overlay","owner event state/minutes or explicit null","acceptance/commercial/reproducibility gates"],"gates":{"owner_completed_decisions":decisions["summary"]["completed_decisions"],"final_copy_bound":0,"prompts_compiled":0,"execution_ready_rows":0,"provider_calls":0,"uploads":0,"external_cost_usd":0,"human_review_minutes":None},"inputs":[{"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)} for p in (COVERAGE,POLICY,EFFORT,REPAIRS,PREFLIGHT,DECISIONS)],"animation_shot_plan":None,"e_conte":None,"boundary":"Generation-only planning envelope; no SLA, money estimate, review-time estimate, prompt, render, upload, acceptance, plan revision, or commercial clearance."}
 OUTPUT.parent.mkdir(parents=True,exist_ok=True)
 with OUTPUT.open("w",encoding="utf-8",newline="\n") as h:h.write(json.dumps(envelope,indent=2)+"\n")
 evidence={"record_type":"CH05ChapterScaleProductionEnvelopeEvidence","schema_version":"1.0","record_id":"ng-ch05-chapter-scale-production-envelope-evidence-r1","state":"REMAINING_36_MEASURED_ENVELOPE_READY","envelope":{"path":OUTPUT.relative_to(ROOT).as_posix(),"sha256":sha(OUTPUT),"row_root_sha256":envelope["row_root_sha256"]},"summary":{"total_plans":50,"selected_existing":14,"remaining_plans":36,"tier_count":3,"plans_per_tier":12,"scenario_count":3,"repair_allowance_slots":repair_slots,"recommended_candidate_envelope":49,"row_count":36,"prompt_count":0,"execution_ready_rows":0,"provider_calls":0,"uploads":0,"external_cost_usd":0,"human_review_minutes":None},"scenarios":scenarios,"remaining_role_counts":envelope["remaining_role_counts"],"chart":{"path":CHART.relative_to(ROOT).as_posix(),"sha256":sha(CHART),"bytes":CHART.stat().st_size},"limitations":["Candidate elapsed distributions are from 26 heterogeneous CH05 candidates and are not a service-level forecast.","Scenario seconds exclude queueing, retries beyond candidate counts, human review, packet construction, layout, lettering, and release validation.","Monetary cost and human review time remain unavailable/null.","The 13 repair slots are a bounded allowance derived from observed nonpass fraction, not predicted failures."],"activity":{"prompts":0,"renders":0,"provider_calls":0,"uploads":0,"plans_revised":0,"acceptances":0,"external_cost_usd":0},"boundary":envelope["boundary"]}
 with EVIDENCE.open("w",encoding="utf-8",newline="\n") as h:h.write(json.dumps(evidence,indent=2)+"\n")
 print(f"CH05 chapter-scale envelope: 50 = 14 selected + 36 remaining; scenarios 36/49/72; repair allowance {repair_slots}")
 print(f"median generation-only seconds {[s['timing']['median_generation_seconds'] for s in scenarios]}; prompts/renders/uploads/cost 0/0/0/$0")
 return 0
if __name__=="__main__":raise SystemExit(main())
