"""Compile strict null owner-disposition worksheet for 14 strongest CH05 candidates."""
from __future__ import annotations
import hashlib, json, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; LINKS=ROOT/"production/comic/review/ch05-review-artifact-link-manifest-r6.json"; TASKS=ROOT/"production/comic/review/ch05-owner-handoff-dependency-checklist-r1.json"; OUTPUT=ROOT/"production/comic/review/ch05-strongest-candidate-disposition-worksheet-r1.json"; GUIDE=ROOT/"docs/research/ch05-strongest-candidate-disposition-guide-r1.md"; EVIDENCE=ROOT/"docs/research/evidence/ch05-strongest-candidate-disposition-worksheet-r1.json"
CHECKS=["role_identity","hair_style_color","wardrobe_continuity","causal_action","hands","lettering_clearance","phone_readability","style_density_fit"]
DISPOSITIONS=["ADVANCE_TO_NEXT_COMPARISON","HOLD_AS_DIAGNOSTIC","REQUEST_ONE_TARGETED_REPAIR","REJECT_FROM_CH05_VISUAL_DIRECTION"]
REPAIRS=["ROLE_IDENTITY","HAIR_STYLE_COLOR","WARDROBE_CONTINUITY","CAUSAL_ACTION","HANDS","LETTERING_CLEARANCE","PHONE_READABILITY","STYLE_DENSITY_FIT"]
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def bind(path): return {"path":path.relative_to(ROOT).as_posix(),"absolute_path":path.resolve().as_posix(),"sha256":sha(path)}
def main():
    links=json.loads(LINKS.read_text(encoding="utf-8")); tasks=json.loads(TASKS.read_text(encoding="utf-8")); artifacts=[row for row in links["artifacts"] if "strongest_candidates" in row["categories"]]; task_by_id={row["subject_id"]:row for row in tasks["tasks"] if row["task_type"]=="CANDIDATE_REVIEW"}; rows=[]
    for artifact in sorted(artifacts,key=lambda row:Path(row["path"]).name.split("-")[0]):
        name=Path(artifact["path"]).name; match=re.match(r"(?P<candidate>[ch]\d{3})-(?P<panel>p\d{3})-(?P<style>.+)-r1\.png$",name); candidate=match.group("candidate") if match else ""; task=task_by_id.get(candidate)
        if not match or not task or task["artifact"]["sha256"]!=artifact["sha256"]: raise SystemExit(f"candidate/task mismatch: {name}")
        path=ROOT/artifact["path"]; rows.append({"candidate_id":candidate,"panel_id":match.group("panel").upper(),"style":match.group("style"),"artifact":bind(path),"checks":{key:None for key in CHECKS},"disposition":None,"targeted_repair_class":None,"reviewer":None,"human_review_minutes":None,"notes":None})
    worksheet={"record_type":"CH05StrongestCandidateDispositionWorksheet","schema_version":"1.0","record_id":"ng-ch05-strongest-candidate-disposition-worksheet-r1","state":"UNFILLED_TEMPLATE","valid_for_rollup":False,"medium":"comic","inputs":[{"path":LINKS.relative_to(ROOT).as_posix(),"sha256":sha(LINKS)},{"path":TASKS.relative_to(ROOT).as_posix(),"sha256":sha(TASKS)}],"candidate_count":14,"check_count_per_candidate":8,"allowed_check_values":["PASS","WARN","FAIL"],"allowed_dispositions":DISPOSITIONS,"allowed_targeted_repair_classes":REPAIRS,"candidates":rows,"shortlist_rollup":None,"route_decision":None,"candidate_acceptance":None,"commercial_clearance":None,"exact_base_selection":None,"comic_panel_plan_revision":None,"animation_shot_plan":None,"e_conte":None,"boundary":"Visual disposition for comparative review only. ADVANCE is not acceptance, commercial clearance, exact-base eligibility, plan revision, or production authority."}; OUTPUT.parent.mkdir(parents=True,exist_ok=True); OUTPUT.write_text(json.dumps(worksheet,indent=2)+"\n",encoding="utf-8",newline="\n")
    guide=["# CH05 strongest-candidate disposition guide r1","","Open each linked candidate and fill all eight checks with `PASS`, `WARN`, or `FAIL`. Then choose one visual disposition. Use `REQUEST_ONE_TARGETED_REPAIR` only with one repair class.","","`ADVANCE_TO_NEXT_COMPARISON` means keep comparing; it is not candidate acceptance, commercial clearance, or exact-base selection.",""]+[f"- [{row['candidate_id']} · {row['panel_id']} · {row['style']}]({row['artifact']['absolute_path']})" for row in rows]; GUIDE.write_text("\n".join(guide)+"\n",encoding="utf-8",newline="\n"); evidence={"record_type":"CH05StrongestCandidateDispositionWorksheetEvidence","schema_version":"1.0","record_id":"ng-ch05-strongest-candidate-disposition-worksheet-evidence-r1","state":"PASS_NULL_TEMPLATE","worksheet":{"path":OUTPUT.relative_to(ROOT).as_posix(),"sha256":sha(OUTPUT)},"guide":{"path":GUIDE.relative_to(ROOT).as_posix(),"sha256":sha(GUIDE)},"inputs":worksheet["inputs"],"summary":{"candidates":14,"checks_per_candidate":8,"total_checks":112,"filled_checks":0,"dispositions":0,"targeted_repairs":0,"reviewers":0,"human_review_minutes":None,"shortlist_rollup":0,"route_decisions":0,"candidate_acceptance":0,"commercial_clearance":0,"exact_base_selection":0,"plan_revisions":0},"animation_shot_plan":None,"e_conte":None}; EVIDENCE.parent.mkdir(parents=True,exist_ok=True); EVIDENCE.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n"); print("CH05 candidate worksheet: 14 candidates/112 null checks/0 dispositions; acceptance/rights/exact-base 0"); return 0
if __name__=="__main__": raise SystemExit(main())
