"""Compile non-gating triage for the full CH05 clear-line watercolor arm."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];PLAN=ROOT/"production/comic/ch05-sc01-panel-plans-v1.json";ASSEMBLY=ROOT/"production/comic/run-manifests/ch05-complete-chapter-clear-line-watercolor-assembly-r1.json";EXECUTION=ROOT/"production/comic/run-manifests/ch05-complete-chapter-clear-line-watercolor-execution-manifest-r1.json";OUTPUT=ROOT/"docs/research/evidence/ch05-complete-chapter-clear-line-watercolor-agent-triage-r1.json";MARKDOWN=ROOT/"docs/research/ch05-complete-chapter-clear-line-watercolor-agent-triage-r1.md"
ISSUES={1:("FAIL","departure_vector","The farmhouse is cold and unlit as required, but both adults still read as climbing toward it rather than traveling downhill away with it behind."),3:("WARN","track_overlap","The fresh boot print is clear, but its overlap with older trail traffic remains subtle at phone width."),32:("WARN","footprint_orientation","The far-bank prints begin on dry ground, but asymmetric heel/toe direction back toward Soren remains only partly legible at phone width."),39:("FAIL","three_mark_gate","The torn-edge third star mark is clear, but P039 does not simultaneously show all three distinct upstream marks required by the strict gate."),43:("FAIL","map_possession","The retreat leaves the creek map beside the open tin, conflicting with P046 where Sigrid carries the map.")}
def sha256(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def main()->int:
 plans=sorted(json.loads(PLAN.read_text(encoding="utf-8"))["plans"],key=lambda x:x["display_order"]);assembly=json.loads(ASSEMBLY.read_text(encoding="utf-8"));entries=sorted(assembly["entries"],key=lambda x:x["order"]);rows=[]
 if [x["panel_id"] for x in plans]!=[x["panel_id"] for x in entries]:raise ValueError("canonical order")
 for p,e in zip(plans,entries,strict=True):
  n=p["display_order"];status,issue,note=ISSUES.get(n,("PASS",None,"No blocking panel-local or cross-panel issue found in non-gating agent triage."));checks={k:"PASS" for k in ("role_binding","role_order","visible_adult_count","shared_set_and_blocking","target_change_behavior","causal_action_or_clue","hair_and_wardrobe","lettering_clearance","phone_readability","cross_panel_canon")}
  if status!="PASS":
   key="cross_panel_canon" if issue in {"departure_vector","three_mark_gate","map_possession"} else "causal_action_or_clue";checks[key]=status
   if status=="WARN":checks["phone_readability"]="WARN"
  rows.append({"display_order":n,"panel_id":p["panel_id"],"plan_revision_id":p["plan_revision_id"],"candidate_id":e["candidate_id"],"candidate_sha256":e["source"]["sha256"],"status":status,"primary_issue_class":issue,"note":note,"checks":checks,"human_review_state":"PENDING","human_review_minutes":None,"accepted":False,"commercially_cleared":False,"exact_production_base":False})
 counts={s:sum(x["status"]==s for x in rows) for s in ("PASS","WARN","FAIL")};doc={"record_type":"CH05CompleteChapterAgentTriage","schema_version":"1.0","record_id":"ng-ch05-complete-chapter-clear-line-watercolor-agent-triage-r1","display_title":"CH05 CLEAR-LINE WATERCOLOR R1 - AGENT TRIAGE","state":"NON_GATING_AGENT_TRIAGE_PENDING_OWNER_REVIEW","medium":"comic","planning_structure":"ComicPanelPlan","animation_shot_plan":None,"e_conte":None,"inputs":[{"path":x.relative_to(ROOT).as_posix(),"sha256":sha256(x)} for x in (PLAN,ASSEMBLY,EXECUTION)],"summary":{"chapter_panels":50,"pass":counts["PASS"],"warn":counts["WARN"],"fail":counts["FAIL"],"hair_and_wardrobe_pass":50,"cross_panel_gates_pass":5,"cross_panel_gates_partial_or_fail":3,"human_reviewed":0,"accepted":0},"gate_transfer":{"cold_farmhouse_until_reversal":"PASS_NEGATIVE_STATE","departure_vector":"FAIL","independent_entry_roles":"PASS","impossible_far_bank_prints":"WARN","continuous_leverage_force_path":"PASS","third_upstream_mark":"FAIL_STRICT_SIMULTANEOUS_COUNT","drum_fully_out":"PASS","map_possession":"FAIL"},"style_hypothesis_result":{"result":"PARTIAL","note":"Contours and value grouping are cleaner, especially in faces and props, but terrain and cloth remain medium/high texture rather than broad low-mark watercolor."},"rows":rows,"recommendation":"Use clear-line watercolor as the leading style-development arm and r6 as the stronger current semantic assembly. Promote neither wholesale; a future hybrid assembly may select only exact reviewed panels after owner disposition.","limitations":["Agent triage is non-gating.","Prompt gate presence does not prove visual compliance.","Built-in model, endpoint, request ID, usage, cost, and seed are unavailable.","No art is accepted, commercially cleared, or an exact production base."],"boundary":"Review evidence only; no acceptance, rights, canon replacement, or exact-base decision."}
 OUTPUT.write_text(json.dumps(doc,indent=2,ensure_ascii=False)+"\n",encoding="utf-8",newline="\n");issues="\n".join(f"| {x['display_order']:02d} | `{x['panel_id']}` | {x['status']} | {x['primary_issue_class']} | {x['note']} |" for x in rows if x["status"]!="PASS");MARKDOWN.write_text(f"# CH05 clear-line watercolor r1 agent triage\n\nThe complete arm measures **{counts['PASS']} PASS / {counts['WARN']} WARN / {counts['FAIL']} FAIL**. Hair and wardrobe hold 50/50.\n\n| Order | Panel | Status | Issue | Evidence |\n|---:|---|---|---|---|\n{issues}\n\nThe arm solves P029, P036, and P041 relative to alternate graphic, while P001 and P043 remain failures. P039 exposes a strict count/composition gap. Human acceptance and rights remain open.\n",encoding="utf-8",newline="\n");print(json.dumps({**doc["summary"],"output":OUTPUT.relative_to(ROOT).as_posix(),"sha256":sha256(OUTPUT)},sort_keys=True));return 0
if __name__=="__main__":raise SystemExit(main())
