"""Compile an exact current CH05 overnight delivery bundle without promoting art."""
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
START_COMMIT="e011cac";RENDER=ROOT/"production/comic/run-manifests/ch05-built-in-renderrecord-index-r1.json";ROUTE=ROOT/"production/comic/recommendations/ch05-pipeline-route-recommendation-r1.json";DECISIONS=ROOT/"production/comic/review/ch05-route-review-decision-matrix-r1.json";LINKS=ROOT/"production/comic/review/ch05-review-artifact-link-manifest-r2.json";BATCHES=ROOT/"production/comic/run-manifests/ch05-chapter-sequence-production-batches-r1.json";READINESS=ROOT/"production/comic/run-manifests/ch05-chapter-production-readiness-matrix-r1.json";LETTERING=ROOT/"production/comic/layout/ch05-lettering-semantics-readiness-matrix-r1.json";RELEASE=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r7.json";FROZEN=ROOT/"docs/research/evidence/frozen-gauntlet-baseline-integrity-r1.json";HUB=ROOT/"experiments/review-packets/ch05-owner-review-index-r4/index.html";CHECKLIST=ROOT/"docs/research/ch05-owner-handoff-checklist-r1.md";OUTPUT=ROOT/"production/comic/handoff/ch05-overnight-delivery-bundle-r1.json";EVIDENCE=ROOT/"docs/research/evidence/ch05-overnight-delivery-bundle-r1.json";SUMMARY=ROOT/"docs/research/ch05-overnight-delivery-summary-r1.md";CHANGED=ROOT/"docs/research/ch05-overnight-changed-files-through-release-r7.md"
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def binding(p:Path)->dict:return {"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)}
def git(*args:str)->str:return subprocess.run(["git",*args],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",check=True).stdout.strip()
def main()->int:
 render=json.loads(RENDER.read_text(encoding="utf-8"));route=json.loads(ROUTE.read_text(encoding="utf-8"));decisions=json.loads(DECISIONS.read_text(encoding="utf-8"));links=json.loads(LINKS.read_text(encoding="utf-8"));batches=json.loads(BATCHES.read_text(encoding="utf-8"));readiness=json.loads(READINESS.read_text(encoding="utf-8"));lettering=json.loads(LETTERING.read_text(encoding="utf-8"));release=json.loads(RELEASE.read_text(encoding="utf-8"))
 head=git("rev-parse","HEAD");origin=git("rev-parse","origin/main");commits=git("rev-list","--reverse",f"{START_COMMIT}^..{head}").splitlines();changed=git("diff","--name-only",f"{START_COMMIT}^",head).splitlines()
 dimensions=sorted({(r["output"]["width"],r["output"]["height"]) for r in render["records"]});strongest=[item for item in links["artifacts"] if "strongest_candidates" in item["categories"]]
 key_links=[{"id":"owner_hub_r4","path":HUB.relative_to(ROOT).as_posix(),"absolute_path":HUB.resolve().as_posix(),"sha256":sha(HUB)},{"id":"exhaustive_review_links_r2","path":"docs/research/ch05-review-links-r2.md","absolute_path":(ROOT/"docs/research/ch05-review-links-r2.md").resolve().as_posix(),"sha256":sha(ROOT/"docs/research/ch05-review-links-r2.md")},{"id":"owner_dependency_checklist","path":CHECKLIST.relative_to(ROOT).as_posix(),"absolute_path":CHECKLIST.resolve().as_posix(),"sha256":sha(CHECKLIST)}]
 limitations=["All 29 candidates remain unaccepted and commercially uncleared.","Built-in model, endpoint, request ID, provider usage, monetary cost, and seed are unavailable for every candidate.","Generation reproducibility is unproven.","Style/task samples are unbalanced and pass rates are run-specific.","Human review minutes remain null because prior review was not live-timed.","Final copy, fonts, tails, localization, accessibility, and lettering acceptance remain open.","The three non-canon LitRPG concepts do not revise CH05 canon, wardrobe, equipment, class, or monsters.","Absolute review links are valid only for the recorded workspace root."]
 bundle={"record_type":"ComicOvernightDeliveryBundle","schema_version":"1.0","record_id":"ng-ch05-overnight-delivery-bundle-r1","state":"ENGINEERING_HANDOFF_READY_OWNER_DECISIONS_PENDING","medium":"comic","source_lineage":{"start_commit":START_COMMIT,"base_release_commit":head,"origin_main_at_compile":origin,"base_remote_parity":head==origin,"commit_count":len(commits),"commits":commits,"changed_path_count":len(changed)},"inputs":[binding(p) for p in (RENDER,ROUTE,DECISIONS,LINKS,BATCHES,READINESS,LETTERING,RELEASE,FROZEN)],"key_links":key_links,"art":{"candidate_count":29,"ch05_candidates":26,"noncanon_concepts":3,"distinct_ch05_plans":14,"generated_sequence_count":3,"selected_sequence_panels":14,"observed_generation_seconds":1385.036,"reference_uses":39,"dimension_sets":[list(x) for x in dimensions],"strongest_candidate_count":len(strongest),"strongest_candidates":[{"path":x["path"],"absolute_path":x["absolute_path"],"sha256":x["sha256"]} for x in strongest],"accepted":0,"commercially_cleared":0},"pipeline":{"recommended_route":route["recommended_route"],"role_allocations":route["role_allocation"],"chapter_plans":50,"sequence_batches":12,"sequence_size_range":[3,5],"readiness_partition":{"selected":14,"dry_run":4,"tier_a":8,"backlog":24},"lettering_partition":{"silent_insert":16,"protected_action":14,"caption_or_silence":13,"speech_or_reaction":6,"attributed_unbound":1},"review_links":105,"integrated_effective_checks":release["summary"]["effective_command_count"],"next_experiment":"P010–P013 four-candidate role-aware continuity pilot with at most two one-class repair slots, only after all recorded gates resolve."},"remaining_decisions":{"count":decisions["decision_count"],"rows":decisions["decisions"]},"limitations":limitations,"activity":{"paid_api_calls":0,"external_uploads_this_delivery_bundle":0,"cloud_gpu_uses":0,"purchases":0,"disclosed_paid_spend_usd":0,"built_in_monetary_cost_usd":None,"owner_decisions_recorded":0,"human_review_minutes":None,"accepted_candidates":0,"executable_panels":0,"comic_panel_plan_revisions":0},"animation_shot_plan":None,"e_conte":None,"boundary":"Engineering handoff only. No art, route, lettering, commercial right, or exact production base is owner-accepted by this bundle."}
 OUTPUT.parent.mkdir(parents=True,exist_ok=True);OUTPUT.write_text(json.dumps(bundle,indent=2)+"\n",encoding="utf-8",newline="\n")
 changed_lines=["# CH05 changed files through integrated release r7","",f"Commit range: `{START_COMMIT}^..{head}`. This inventory intentionally ends at the release-r7 base commit; bundle/closeout files are subsequent append-only handoff records.",""]+[f"- `{path}`" for path in changed];CHANGED.write_text("\n".join(changed_lines)+"\n",encoding="utf-8",newline="\n")
 summary=["# CH05 overnight delivery summary r1","",f"Current review hub: [{HUB.name}]({HUB.resolve().as_posix()})",f"Exhaustive 105-link inventory: [ch05-review-links-r2.md]({(ROOT/'docs/research/ch05-review-links-r2.md').resolve().as_posix()})",f"Dependency-ordered owner checklist: [ch05-owner-handoff-checklist-r1.md]({CHECKLIST.resolve().as_posix()})","","## Measured result","",f"- 29 candidates: 26 CH05 + 3 explicitly non-canon concepts; 14 distinct CH05 plans; 3 generated sequences; 14 selected sequence panels.",f"- 1,385.036 observed seconds; 39 reference uses; paid API/cloud spend $0; built-in monetary cost unavailable.",f"- 12 coherent chapter batches cover 50 ComicPanelPlans; 46 integrated checks pass.","","## Recommendation","",f"{route['recommended_route']} This is an engineering recommendation, not owner acceptance.","","## Remaining decisions","",*[f"- `{row['decision_id']}` — {row['question']}" for row in decisions["decisions"]],"","## Limitations","",*[f"- {item}" for item in limitations]];SUMMARY.write_text("\n".join(summary)+"\n",encoding="utf-8",newline="\n")
 evidence={"record_type":"ComicOvernightDeliveryBundleEvidence","schema_version":"1.0","record_id":"ng-ch05-overnight-delivery-bundle-evidence-r1","state":"PASS_OWNER_PENDING","bundle":binding(OUTPUT),"summary_document":binding(SUMMARY),"changed_files_document":binding(CHANGED),"inputs":bundle["inputs"],"summary":{"candidates":29,"ch05_candidates":26,"noncanon_concepts":3,"distinct_ch05_plans":14,"selected":14,"chapter_plans":50,"sequence_batches":12,"review_links":105,"strongest_candidates":14,"remaining_decisions":10,"integrated_checks":46,"observed_seconds":1385.036,"reference_uses":39,"paid_spend_usd":0,"owner_decisions":0,"accepted_candidates":0,"executable_panels":0,"human_review_minutes":None},"base_remote_parity":head==origin,"animation_shot_plan":None,"e_conte":None};EVIDENCE.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n")
 print(f"CH05 delivery bundle: 29 candidates/50 plans/12 batches/105 links/10 decisions/46 checks; base parity {head==origin}");print(f"changed paths through r7 {len(changed)}; paid spend/decisions/accepted/executable $0/0/0/0");return 0
if __name__=="__main__":raise SystemExit(main())
