"""Compile non-executable prompt blueprints for the P010-P013 pilot."""
from __future__ import annotations
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; MANIFEST=ROOT/"production/comic/run-manifests/ch05-p010-p013-production-manifest-dry-run-r1.json"; UNLOCK=ROOT/"production/comic/review/ch05-p010-p013-owner-unlock-contract-r1.json"; OUTPUT=ROOT/"production/comic/run-manifests/ch05-p010-p013-prompt-blueprint-r1.json"; EVIDENCE=ROOT/"docs/research/evidence/ch05-p010-p013-prompt-blueprint-r1.json"
REFS={"p050_dual_identity_action":{"path":"experiments/review-packets/ch05-style-density-scale-exploration-r1/P050-wide-action-clean-graphic-r1.png","sha256":"cb1e7b496397ff0f37c07c241b7a4b5beec137d3d26c48c3cbfad60734b8c83d"},"p040_sigrid_face":{"path":"experiments/review-packets/ch05-style-density-scale-exploration-r1/P040-medium-close-cel-painted-r1.png","sha256":"c0a2be11cc9a51ecfbb490d490135df88e7b575b794240b002b1427ba64b6b4a"}}
PROMPTS={
"m001":"CH05 comic panel, premium cel-painted webcomic art with restrained painterly color, medium vertical character-clue panel. Sigrid is a clearly adult woman with mature proportions, dark-brown to near-black hair tied in a compact low bun with a few damp loose strands, never blond; mature angular face, dark brows, alert gray-blue eyes; practical dark blue-brown plaid wrap over gray-green expedition layers, dark trousers and wet-weather boots. She has stopped mid-step on a muddy forest trail because she hears rushing water before it is visible: weight settles onto her rear boot, head turns downhill, one hand lightly lifts the plaid away from wet brush, expression controlled and listening. Show causal environmental evidence—bent wet grass, faint spray catching cool light, leaves angling toward a hidden creek—without showing the creek itself. Strong readable silhouette, natural adult hands, calm deduction rhythm, lower visual density than an action anchor. Keep the upper-left 18 percent as quiet atmospheric negative space away from face, hands, and clues. No text, letters, captions, speech balloons, logos, UI, frame border, extra people, weapons, armor, or monsters.",
"m002":"CH05 comic panel, mature clear-line adventure art with light watercolor, compact causal-clue panel. Soren is a clearly adult man with mature proportions, short-to-medium wavy light-brown to dark-blond hair swept back with damp loose strands, never black or bright blond; weathered angular adult face with light stubble; pale oatmeal work coat over muted blue-gray work layers, dark trousers and practical wet-weather boots. He crouches beside a thorn at the trail edge and finds one soot-stained length of twine snagged there. Show one readable adult hand holding the folded map low and the other stopping just short of the taut twine; the twine, black soot smear, thorn, and downhill pull direction must be unmistakable. Practical balance, bent knee, coat hem reacting to his weight shift, wet mud compressed under one boot. No duplicate twine, no generic speed lines. Keep a quiet upper-right 18 percent away from his face, hands, map, thorn, and twine. No text, letters, captions, speech balloons, logos, UI, frame border, extra people, armor, weapons, or monsters.",
"m003":"CH05 comic panel, polished lower-density limited-ink webcomic insert with restrained flat color, small silent object panel and no people. Close view of one soot-stained length of rough twine caught on a thorn above wet mud. The twine points distinctly downhill as if it was pulled taut and released: fibers stretched along one direction, thorn flexed, a shallow straight groove in mud ending beneath it, two tiny displaced droplets. Exactly one twine strand and one thorn cluster; causal geometry is more important than texture. Strong simple silhouette, phone-readable object scale, quiet background, no decorative foliage clutter. Preserve a clean top band while keeping the twine and groove fully unobscured. No text, letters, captions, speech balloons, logos, UI, frame border, hands, people, faces, animals, armor, weapons, or monsters.",
"m004":"CH05 comic panel, mature clear-line adventure art with restrained watercolor, wide directional re-entry panel. Soren and Sigrid are clearly adult fictional characters with mature proportions, moving together downhill beside a newly revealed creek instead of following the fading tracks. Soren remains on viewer-left: short-to-medium wavy light-brown to dark-blond hair, weathered angular face with light stubble, pale oatmeal work coat over muted blue-gray layers, folded map secured low. Sigrid remains on viewer-right: dark-brown to near-black hair tied in a compact low bun with damp loose strands, mature angular face, practical dark blue-brown plaid wrap over gray-green layers. Show causal movement through careful foot placement on slick stones, forward weight shift, coat and plaid trailing with gravity, shallow water bending around boots, and the soot-stained twine direction aligning with the creek. Strong separated silhouettes and role order, readable adult hands, exciting purposeful movement without generic speed lines. Keep the upper-center 16 percent as quiet sky and mist away from heads, hands, creek direction, map, and twine. No text, letters, captions, speech balloons, logos, UI, frame border, extra people, armor, weapons, or monsters."}
CANVAS={"m001":[1024,1280],"m002":[1024,1024],"m003":[1024,768],"m004":[1536,1024]}
PROHIBITED=re.compile(r"\b(?:boy|girl|kid|child|teen|minor|real person|celebrity|photoreal likeness)\b",re.I)
def sha_bytes(v): return hashlib.sha256(v.encode()).hexdigest()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(p): return {"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)}
def main():
    manifest=json.loads(MANIFEST.read_text(encoding="utf-8")); unlock=json.loads(UNLOCK.read_text(encoding="utf-8")); rows=[]
    for source in manifest["rows"]:
        slot=source["candidate_slot"]; prompt=PROMPTS[slot]; refs=[{"reference_id":rid,**REFS[rid],"local_hash_verified":sha(ROOT/REFS[rid]["path"])==REFS[rid]["sha256"],"upload_authorized_only_for_openai_builtin_imagegen":True,"upload_performed":False} for rid in source["reference_ids"]]
        required=["No text","hands" if source["visible_adult_cast"] else "no people"]
        if source["visible_adult_cast"]: required.insert(0,"clearly adult")
        lint={"prohibited_person_age_likeness_terms":PROHIBITED.findall(prompt),"required_phrase_results":{term:term.casefold() in prompt.casefold() for term in required},"soren_hair_wardrobe":("SOREN" not in source["visible_adult_cast"] or all(x in prompt for x in ("light-brown to dark-blond","pale oatmeal work coat"))),"sigrid_hair_wardrobe":("SIGRID" not in source["visible_adult_cast"] or all(x in prompt for x in ("dark-brown to near-black","plaid wrap"))),"silent_no_lettering":all(x in prompt for x in ("No text","speech balloons")),"causal_motion_or_object":any(x in prompt.casefold() for x in ("weight","taut","pull","gravity","water bending","groove")),"reference_ids_match_manifest":[x["reference_id"] for x in refs]==source["reference_ids"],"passed":False}; lint["passed"]=not lint["prohibited_person_age_likeness_terms"] and all(lint["required_phrase_results"].values()) and all(lint[k] for k in ("soren_hair_wardrobe","sigrid_hair_wardrobe","silent_no_lettering","causal_motion_or_object","reference_ids_match_manifest")) and all(x["local_hash_verified"] for x in refs)
        rows.append({"candidate_slot":slot,"panel_id":source["panel_id"],"plan_revision_id":source["plan_revision_id"],"plan_canonical_sha256":source["plan_canonical_sha256"],"style_id":source["style_id"],"format_role":source["format_role"],"target_width_px":source["target_width_px"],"planning_canvas_px":CANVAS[slot],"visible_adult_cast":source["visible_adult_cast"],"draft_prompt":prompt,"draft_prompt_sha256":sha_bytes(prompt),"input_references":refs,"reference_count":len(refs),"lint":lint,"production_manifest_prompt_mutated":False,"execution_ready":False})
    out={"record_type":"ComicPromptBlueprint","schema_version":"1.0","record_id":"ng-ch05-p010-p013-prompt-blueprint-r1","state":"DRAFT_LINT_PASS_NOT_EXECUTABLE","medium":"comic","inputs":[bind(MANIFEST),bind(UNLOCK)],"summary":{"rows":4,"lint_pass":sum(x["lint"]["passed"] for x in rows),"reference_uses":sum(x["reference_count"] for x in rows),"unique_reference_ids":len({r["reference_id"] for x in rows for r in x["input_references"]}),"text_only_rows":sum(not x["input_references"] for x in rows),"production_prompts_mutated":0,"execution_ready_rows":0,"uploads":0,"provider_calls":0,"renders":0,"paid_spend_usd":0},"rows":rows,"production_manifest_prompt_null_count":sum(x["prompt"] is None for x in manifest["rows"]),"owner_unlock_state":unlock["state"],"repair_policy":manifest["repair_slots"],"animation_shot_plan":None,"e_conte":None,"boundary":"Draft text only. These hashes are blueprint hashes, not compiled production prompt hashes. No reference was uploaded and the prompt-null production manifest remains unchanged."}; OUTPUT.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8",newline="\n")
    ev={"record_type":"ComicPromptBlueprintEvidence","schema_version":"1.0","record_id":"ng-ch05-p010-p013-prompt-blueprint-evidence-r1","state":"PASS_NOT_EXECUTABLE","blueprint":bind(OUTPUT),"inputs":out["inputs"],"summary":out["summary"],"production_manifest_prompt_null_count":out["production_manifest_prompt_null_count"],"owner_unlock_state":out["owner_unlock_state"],"animation_shot_plan":None,"e_conte":None}; EVIDENCE.write_text(json.dumps(ev,indent=2)+"\n",encoding="utf-8",newline="\n")
    print(f"P010-P013 prompt blueprint: {out['summary']['lint_pass']}/4 lint pass; 3 reference uses/2 unique + 1 text-only; production prompts/execution/uploads/renders 0/0/0/0")
    return 0
if __name__=="__main__": raise SystemExit(main())
