"""Compile the fail-closed owner-review unlock contract for P010-P013."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
DECISIONS=ROOT/"production/comic/review/ch05-route-review-decision-matrix-r1.json"; TASKS=ROOT/"production/comic/review/ch05-owner-handoff-dependency-checklist-r1.json"; MANIFEST=ROOT/"production/comic/run-manifests/ch05-p010-p013-production-manifest-dry-run-r1.json"; REVIEW=ROOT/"production/comic/review/ch05-p010-p013-review-packet-contract-dry-run-r1.json"; TIMER=ROOT/"production/comic/review/ch05-human-review-time-instrumentation-contract-r1.json"; OUTPUT=ROOT/"production/comic/review/ch05-p010-p013-owner-unlock-contract-r1.json"; EVIDENCE=ROOT/"docs/research/evidence/ch05-p010-p013-owner-unlock-contract-r1.json"; SUMMARY=ROOT/"docs/research/ch05-p010-p013-owner-unlock-checklist-r1.md"
REQUIRED={"route_role_aware_hybrid":["CONFIRM_ROLE_AWARE_ROUTE","REQUEST_UNIFORM_FINISH_COMPARISON"],"c005_transition_density":["REQUEST_EXACT_DENSITY_REDUCTION","KEEP_CURRENT_DENSITY"],"c014_action_punctuation":["KEEP_AS_ACTION_PUNCTUATION","REQUEST_FINISH_DENSITY_REPAIR"],"lettering_semantics":["KEEP_ACTION_AND_INSERT_BEATS_SILENT","REQUEST_PLAN_LEVEL_COPY_SEMANTICS"],"p010_p013_finish_rhythm":["USE_ROLE_AWARE_FOUR_BEAT_FINISH","REQUEST_SHARED_FINISH_CONTROL"],"p010_p013_copy":["KEEP_SILENT_FOR_CAUSAL_TEST","REQUEST_PLAN_LEVEL_CAPTION_SEMANTICS"]}
DIRECT={"route_role_aware_hybrid":"CONFIRM_ROLE_AWARE_ROUTE","c005_transition_density":"REQUEST_EXACT_DENSITY_REDUCTION","c014_action_punctuation":"KEEP_AS_ACTION_PUNCTUATION","lettering_semantics":"KEEP_ACTION_AND_INSERT_BEATS_SILENT","p010_p013_finish_rhythm":"USE_ROLE_AWARE_FOUR_BEAT_FINISH","p010_p013_copy":"KEEP_SILENT_FOR_CAUSAL_TEST"}
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(p): return {"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)}
def main():
    matrix=json.loads(DECISIONS.read_text(encoding="utf-8")); checklist=json.loads(TASKS.read_text(encoding="utf-8")); manifest=json.loads(MANIFEST.read_text(encoding="utf-8")); review=json.loads(REVIEW.read_text(encoding="utf-8")); timer=json.loads(TIMER.read_text(encoding="utf-8")); by_id={x["decision_id"]:x for x in matrix["decisions"]}; task_by={x["subject_id"]:x for x in checklist["tasks"] if x["task_type"]=="ROUTE_DECISION"}
    roots=[]
    for i,(decision_id,allowed) in enumerate(REQUIRED.items(),1):
        row=by_id[decision_id]; task=task_by[decision_id]; roots.append({"order":i,"decision_id":decision_id,"question":row["question"],"allowed_decisions":allowed,"engineering_default":row["engineering_default"],"direct_compile_value":DIRECT[decision_id],"owner_decision":row["owner_decision"],"reviewer":row["reviewer"],"human_review_minutes":row["human_review_minutes"],"artifact":task["artifact"],"dependencies":task["dependencies"],"resolved":False})
    deferred=[]
    for decision_id in ("lettering_visual_arm","strongest_candidate_shortlist","noncanon_litrpg_direction","commercial_and_exact_base"):
        task=task_by[decision_id]; deferred.append({"decision_id":decision_id,"reason":"Not required to compile a silent new review pilot; remains required for lettering choice, exact-base/candidate promotion, non-canon direction, or commercial authority as applicable.","owner_decision":by_id[decision_id]["owner_decision"],"artifact":task["artifact"]})
    candidate_tasks=[{"task_id":x["task_id"],"subject_id":x["subject_id"],"decision":x["decision"],"required_for_pilot_prompt_compile":False,"required_before_exact_base_selection":True,"artifact":x["artifact"]} for x in checklist["tasks"] if x["task_type"]=="CANDIDATE_REVIEW"]
    contract={"record_type":"ComicOwnerUnlockContract","schema_version":"1.0","record_id":"ng-ch05-p010-p013-owner-unlock-contract-r1","state":"BLOCKED_EXACT_OWNER_DECISIONS_REQUIRED","medium":"comic","inputs":[bind(x) for x in (DECISIONS,TASKS,MANIFEST,REVIEW,TIMER)],"pilot":{"panel_ids":[x["panel_id"] for x in manifest["rows"]],"candidate_slots":[x["candidate_slot"] for x in manifest["rows"]],"candidate_count":4,"repair_slot_count":len(manifest["repair_slots"]),"planned_review_artifact_count":len(manifest["planned_review_artifacts"])},"exact_required_decisions":roots,"required_decision_count":6,"resolved_required_decisions":0,"direct_compile_decisions":DIRECT,"alternate_decision_rule":"Any allowed non-direct value requires the smallest applicable plan/preflight/finish revision before prompt compilation; it never silently maps to the engineering default.","deferred_decisions":deferred,"existing_candidate_reviews":candidate_tasks,"broad_prior_approval":{"recorded_as_positive_creative_direction":True,"structured_decision_ingested":False,"reason":"General approval and permission to continue do not identify exact values for the six dependency roots and do not constitute candidate acceptance, commercial clearance, or an exact-base decision."},"unlock_levels":{"metadata_prompt_compile":{"ready":False,"requirements":["six explicit structured owner decisions","all six equal their direct_compile_value, or every alternate has an exact prerequisite revision","four exact ComicPanelPlan hashes unchanged","three authorized reference hashes pass preflight","all prompt hashes and ignored output paths compiled"]},"built_in_imagegen_execution":{"ready":False,"requirements":["metadata prompt compile ready","built-in ImageGen available","only authorized hash-pinned references selected per row","zero paid API/cloud use","RenderRecord destination initialized"]},"candidate_promotion":{"ready":False,"requirements":["render completed","all 11 review checks per slot completed","live human-review event log valid","candidate and sequence decisions explicit","commercial and exact-base decisions remain separate"]}},"current_activity":{"prompts":0,"renders":0,"provider_calls":0,"uploads":0,"paid_spend_usd":0,"owner_decisions":0,"review_events":0,"human_review_minutes":None,"accepted_candidates":0,"commercially_cleared_candidates":0,"executable_panels":0,"comic_panel_plan_revisions":0},"animation_shot_plan":None,"e_conte":None,"boundary":"Broad creative approval is respected as direction but is not silently converted into exact route values, candidate acceptance, commercial authority, prompt compilation, or execution."}
    OUTPUT.write_text(json.dumps(contract,indent=2)+"\n",encoding="utf-8",newline="\n")
    lines=["# P010–P013 owner unlock checklist r1","","This checklist identifies the six exact decisions that can unlock the smallest four-panel pilot. Current state: **0/6 resolved; prompt compilation and rendering remain blocked.**","","General positive approval is preserved as creative direction; it is not candidate acceptance or commercial/exact-base authority.","","## Exact decisions",""]
    for x in roots: lines += [f"### {x['order']}. `{x['decision_id']}`","",x["question"],"",f"Engineering default: `{x['engineering_default']}`.","",f"Allowed exact values: {', '.join(f'`{v}`' for v in x['allowed_decisions'])}.","",f"Review: [{Path(x['artifact']['path']).name}]({x['artifact']['absolute_path']})",""]
    lines += ["## Boundary","","Fourteen existing candidate dispositions are not prerequisites for generating this new pilot, but remain mandatory before selecting any existing image as an exact base. Commercial clearance remains a separate later decision."]
    SUMMARY.write_text("\n".join(lines)+"\n",encoding="utf-8",newline="\n")
    evidence={"record_type":"ComicOwnerUnlockContractEvidence","schema_version":"1.0","record_id":"ng-ch05-p010-p013-owner-unlock-contract-evidence-r1","state":"PASS_BLOCKED","contract":bind(OUTPUT),"owner_checklist":bind(SUMMARY),"inputs":contract["inputs"],"summary":{"required_decisions":6,"resolved_required_decisions":0,"direct_compile_values":6,"deferred_decisions":4,"existing_candidate_reviews":14,"pilot_candidates":4,"repair_slots":2,"planned_review_artifacts":5,"prompts":0,"renders":0,"owner_decisions":0,"accepted":0,"commercially_cleared":0,"executable":0,"human_review_minutes":None},"animation_shot_plan":None,"e_conte":None}; EVIDENCE.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n")
    print("P010-P013 owner unlock: 6 exact roots/0 resolved; 4 deferred/14 candidate reviews; prompt/render/promotion 0/0/0")
    return 0
if __name__=="__main__": raise SystemExit(main())
