"""Compile the fail-closed lifecycle state machine for the P010-P013 pilot."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; UNLOCK=ROOT/"production/comic/review/ch05-p010-p013-owner-unlock-contract-r1.json"; PROMPTS=ROOT/"production/comic/run-manifests/ch05-p010-p013-prompt-blueprint-r1.json"; PACKET=ROOT/"production/comic/review/ch05-p010-p013-prerender-packet-blueprint-r1.json"; REVIEW=ROOT/"production/comic/review/ch05-p010-p013-review-packet-contract-dry-run-r1.json"; OUTPUT=ROOT/"production/comic/run-manifests/ch05-p010-p013-lifecycle-state-machine-r1.json"; EVIDENCE=ROOT/"docs/research/evidence/ch05-p010-p013-lifecycle-state-machine-r1.json"
STATES=["DRAFT_BLUEPRINTED","OWNER_ROOTS_RESOLVED","PRODUCTION_PROMPTS_COMPILED","BASE_RENDERED","PACKET_BUILT","HUMAN_REVIEW_COMPLETE","REPAIR_ALLOCATED","TARGETED_REPAIR_RENDERED","REPAIRED_PACKET_BUILT","PROVISIONALLY_ACCEPTED","RIGHTS_AND_EXACT_BASE_REVIEWED"]
EDGES=[("DRAFT_BLUEPRINTED","OWNER_ROOTS_RESOLVED","six exact owner roots resolved or exact alternate revisions bound"),("OWNER_ROOTS_RESOLVED","PRODUCTION_PROMPTS_COMPILED","four immutable production prompt hashes and exact reference preflights"),("PRODUCTION_PROMPTS_COMPILED","BASE_RENDERED","four complete RenderRecords and candidate output hashes"),("BASE_RENDERED","PACKET_BUILT","five deterministic ignored packet artifacts and measurements"),("PACKET_BUILT","HUMAN_REVIEW_COMPLETE","44 candidate checks, sequence review, decisions, and live timer log"),("HUMAN_REVIEW_COMPLETE","REPAIR_ALLOCATED","one exact failure class and available repair slot; passing rows preserved"),("REPAIR_ALLOCATED","TARGETED_REPAIR_RENDERED","one targeted repair RenderRecord; no broad reroll"),("TARGETED_REPAIR_RENDERED","REPAIRED_PACKET_BUILT","packet rebuilt with original passing rows and repair evidence"),("REPAIRED_PACKET_BUILT","HUMAN_REVIEW_COMPLETE","repaired row and sequence re-reviewed with live timer"),("HUMAN_REVIEW_COMPLETE","PROVISIONALLY_ACCEPTED","all candidate/sequence decisions explicit, no unresolved FAIL, WARN limitations disclosed"),("PROVISIONALLY_ACCEPTED","RIGHTS_AND_EXACT_BASE_REVIEWED","commercial clearance and exact-base eligibility decided separately by owner")]
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(p): return {"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)}
def main():
    unlock=json.loads(UNLOCK.read_text(encoding="utf-8")); prompts=json.loads(PROMPTS.read_text(encoding="utf-8")); packet=json.loads(PACKET.read_text(encoding="utf-8")); review=json.loads(REVIEW.read_text(encoding="utf-8")); edge_rows=[{"from":a,"to":b,"guard":g,"currently_enabled":False} for a,b,g in EDGES]
    current={"state":"DRAFT_BLUEPRINTED","resolved_owner_roots":unlock["resolved_required_decisions"],"production_prompt_hashes":0,"complete_base_renderrecords":0,"base_candidate_outputs":0,"packet_artifacts_built":packet["summary"]["artifacts_built"],"candidate_checks_completed":0,"sequence_review_completed":False,"live_review_log_valid":False,"candidate_decisions":0,"sequence_decision":None,"repair_slots_allocated":0,"targeted_repair_renderrecords":0,"provisional_acceptance":False,"commercial_clearance_decision":None,"exact_base_decision":None}
    out={"record_type":"ComicPilotLifecycleStateMachine","schema_version":"1.0","record_id":"ng-ch05-p010-p013-lifecycle-state-machine-r1","state":"PASS_CURRENT_DRAFT_FAIL_CLOSED","medium":"comic","inputs":[bind(x) for x in (UNLOCK,PROMPTS,PACKET,REVIEW)],"states":STATES,"state_count":len(STATES),"transitions":edge_rows,"transition_count":len(edge_rows),"repair_loop":{"entry":"HUMAN_REVIEW_COMPLETE -> REPAIR_ALLOCATED","maximum_total_slots":2,"one_failure_class_per_slot":True,"broad_reroll":False,"passing_rows_preserved":True,"exit":"REPAIRED_PACKET_BUILT -> HUMAN_REVIEW_COMPLETE"},"current":current,"current_enabled_transition_count":0,"promotion_separation":{"engineering_provisional_acceptance_state":"PROVISIONALLY_ACCEPTED","commercial_and_exact_base_state":"RIGHTS_AND_EXACT_BASE_REVIEWED","commercial_and_exact_base_automatic":False,"exact_base_implies_commercial_clearance":False,"commercial_clearance_implies_exact_base":False},"invariants":["ComicPanelPlan remains the only active production-planning structure.","No transition can create child/real-person/biometric material or expand authorized references.","Every render transition requires exact RenderRecords and ignored output paths.","Every human-review transition requires live, non-backfilled timer evidence.","FAIL evidence is preserved; repair changes exactly one failure class and never rerolls passing rows.","Provisional engineering acceptance cannot establish commercial rights or exact-base suitability."],"activity":{"prompts_compiled":0,"provider_calls":0,"uploads":0,"renders":0,"packet_artifacts":0,"review_events":0,"human_review_minutes":None,"accepted_candidates":0,"commercially_cleared":0,"executable_panels":0},"animation_shot_plan":None,"e_conte":None,"boundary":"State-machine definition and exhaustive synthetic checks only. No state transition is executed."}; OUTPUT.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8",newline="\n")
    ev={"record_type":"ComicPilotLifecycleStateMachineEvidence","schema_version":"1.0","record_id":"ng-ch05-p010-p013-lifecycle-state-machine-evidence-r1","state":"PASS_FAIL_CLOSED","state_machine":bind(OUTPUT),"inputs":out["inputs"],"summary":{"states":11,"legal_transitions":11,"state_pairs":121,"illegal_or_unconfigured_pairs":110,"current_state":"DRAFT_BLUEPRINTED","current_enabled_transitions":0,"repair_slots":2,"invariants":6,"prompts":0,"renders":0,"packet_artifacts":0,"review_events":0,"accepted":0,"commercially_cleared":0,"executable":0,"human_review_minutes":None},"animation_shot_plan":None,"e_conte":None}; EVIDENCE.write_text(json.dumps(ev,indent=2)+"\n",encoding="utf-8",newline="\n"); print("P010-P013 lifecycle: 11 states/11 legal edges/121 pairs; current DRAFT/0 enabled; repair loop max 2; promotion 0")
    return 0
if __name__=="__main__": raise SystemExit(main())
