"""Map the guarded pilot lifecycle across all 12 CH05 production batches."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
ROOT=Path(__file__).resolve().parents[2]; BATCHES=ROOT/"production/comic/run-manifests/ch05-chapter-sequence-production-batches-r1.json"; MACHINE=ROOT/"production/comic/run-manifests/ch05-p010-p013-lifecycle-state-machine-r1.json"; LETTERING=ROOT/"production/comic/layout/ch05-lettering-semantics-readiness-matrix-r1.json"; REFERENCES=ROOT/"production/comic/continuity/ch05-reference-use-and-continuity-risk-plan-r1.json"; OUTPUT=ROOT/"production/comic/run-manifests/ch05-chapter-batch-lifecycle-application-r1.json"; EVIDENCE=ROOT/"docs/research/evidence/ch05-chapter-batch-lifecycle-application-r1.json"; CHART=ROOT/"experiments/review-packets/ch05-chapter-batch-lifecycle-r1/ch05-chapter-batch-lifecycle-map-r1.png"
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(p): return {"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)}
def font(size,bold=False):
    p=Path("C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf")
    return ImageFont.truetype(str(p),size) if p.exists() else ImageFont.load_default()
def draw(rows,states):
    w,h=1900,1480; im=Image.new("RGB",(w,h),"#f4f0e8"); d=ImageDraw.Draw(im); d.text((55,35),"CH05 chapter batch lifecycle application r1",font=font(34,True),fill="#202528"); d.text((55,82),"Narrative order is fixed; production waves and lifecycle entry remain separate. No batch is executable.",font=font(20),fill="#485158")
    x0=430; cell=116; top=175; rowh=92
    short=["Draft","Roots","Prompts","Base","Packet","Review","Repair","Repair art","Repacket","Prov. accept","Rights"]
    for i,label in enumerate(short):
        x=x0+i*cell; d.rectangle((x,top-42,x+cell-5,top-3),fill="#28343b"); d.text((x+5,top-35),label,font=font(13,True),fill="white")
    for r,row in enumerate(rows):
        y=top+r*rowh; d.rectangle((45,y,1855,y+rowh-10),fill="#ffffff" if r%2==0 else "#ebe7df",outline="#b8b1a7"); d.text((60,y+10),f"{row['sequence_id']} · wave {row['production_wave']} · {row['panel_count']} panels",font=font(18,True),fill="#202528"); d.text((60,y+38),row["title"][:39],font=font(16),fill="#465057"); d.text((60,y+61),row["application_state"].replace("_"," ")[:46],font=font(12),fill="#76532e")
        for i,state in enumerate(states):
            x=x0+i*cell; fill="#d7d3ca"
            if row["lifecycle_current_state"]==state: fill="#64a97b"
            elif row["lifecycle_current_state"]=="NOT_ENTERED": fill="#e0ddd6"
            d.rectangle((x,y+10,x+cell-5,y+66),fill=fill,outline="#a09b92"); mark="CURRENT" if row["lifecycle_current_state"]==state else "—"; d.text((x+8,y+29),mark,font=font(11,True),fill="#163a24" if mark=="CURRENT" else "#77736d")
    d.text((55,1320),"Reusable across all batches: lifecycle schema · 11 checks · failure vocabulary · bounded repair · RenderRecord fields · live timer · ignored packet builder",font=font(18,True),fill="#26343a"); d.text((55,1355),"Batch-specific every time: exact plans · prompt hashes · reference selections · output hashes · safe-zone/density measurements · review decisions · rights/exact-base decisions",font=font(18),fill="#4a555c"); d.text((55,1405),"Current denominator: 50 plans / 12 batches / 49 planned review artifacts (48 baseline + one pilot density artifact) / 0 executable",font=font(17),fill="#76532e"); CHART.parent.mkdir(parents=True,exist_ok=True); im.save(CHART,optimize=False,compress_level=9)
def main():
    batches=json.loads(BATCHES.read_text(encoding="utf-8")); machine=json.loads(MACHINE.read_text(encoding="utf-8")); lettering=json.loads(LETTERING.read_text(encoding="utf-8")); refs=json.loads(REFERENCES.read_text(encoding="utf-8")); lettering_by={x["panel_id"]:x for x in lettering["rows"]}; ref_by={x["panel_id"]:x for x in refs["rows"]}; rows=[]
    for seq in batches["sequences"]:
        ids=[x["panel_id"] for x in seq["panels"]]; current="DRAFT_BLUEPRINTED" if seq["sequence_id"]=="seq03" else "NOT_ENTERED"; app="PILOT_BLUEPRINTED_UNLOCK_BLOCKED" if seq["sequence_id"]=="seq03" else ("NEXT_WAVE_PLAN_ONLY_WAIT_PILOT" if seq["production_wave"]==2 else "PLAN_ONLY_WAIT_EVIDENCE")
        rows.append({"sequence_id":seq["sequence_id"],"narrative_order":seq["narrative_order"],"production_wave":seq["production_wave"],"title":seq["title"],"panel_ids":ids,"panel_count":seq["panel_count"],"application_state":app,"lifecycle_current_state":current,"reusable_contracts":["11-state lifecycle","11 candidate/review checks","11 failure classes","two-slot targeted repair","16-field RenderRecord","live-only timer","ignored deterministic packet builder"],"batch_specific_gates":["exact ComicPanelPlan hashes","exact structured owner roots","immutable production prompt hashes","exact reference selection/preflight","candidate RenderRecords/output hashes","packet hashes/measurements","candidate and sequence human review","commercial and exact-base decisions"],"lettering_rows_requiring_semantic_choice":sum(lettering_by[x]["lettering_class"] in ("CAPTION_OR_SILENCE_PENDING","SPEECH_OR_REACTION_SEMANTICS_PENDING","ATTRIBUTED_SPEECH_UNBOUND") for x in ids),"high_or_critical_continuity_rows":sum(ref_by[x]["continuity_risk"] in ("HIGH","CRITICAL_GUARDED") for x in ids),"planned_review_artifacts":5 if seq["sequence_id"]=="seq03" else 4,"prompts":0,"renders":0,"accepted":0,"execution_ready":False})
    draw(rows,machine["states"]); out={"record_type":"ComicChapterBatchLifecycleApplication","schema_version":"1.0","record_id":"ng-ch05-chapter-batch-lifecycle-application-r1","state":"PASS_PLAN_ONLY","medium":"comic","inputs":[bind(x) for x in (BATCHES,MACHINE,LETTERING,REFERENCES)],"summary":{"plans":50,"batches":12,"lifecycle_states":11,"legal_transitions":11,"batches_entered":1,"batches_not_entered":11,"wave_1":1,"wave_2":2,"wave_3":5,"wave_4":4,"reusable_contracts":7,"batch_specific_gates":8,"planned_review_artifacts":49,"prompts":0,"renders":0,"accepted":0,"execution_ready_batches":0,"provider_calls":0,"uploads":0,"paid_spend_usd":0},"batches":rows,"chart":{"path":CHART.relative_to(ROOT).as_posix(),"sha256":sha(CHART),"dimensions":[1900,1480],"git_tracked":False},"reuse_rule":"Schemas, vocabulary, measurement algorithms, timer rules, and repair semantics may be reused. Plan, prompt, reference, output, packet, review, and rights evidence must be rebound for every batch.","animation_shot_plan":None,"e_conte":None,"boundary":"Lifecycle application is planning only. Seq03 has a draft blueprint but no enabled transition; all other batches have not entered the lifecycle."}; OUTPUT.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8",newline="\n"); ev={"record_type":"ComicChapterBatchLifecycleApplicationEvidence","schema_version":"1.0","record_id":"ng-ch05-chapter-batch-lifecycle-application-evidence-r1","state":"PASS_PLAN_ONLY","application":bind(OUTPUT),"chart":out["chart"],"inputs":out["inputs"],"summary":out["summary"],"animation_shot_plan":None,"e_conte":None}; EVIDENCE.write_text(json.dumps(ev,indent=2)+"\n",encoding="utf-8",newline="\n"); print("CH05 batch lifecycle: 50 plans/12 batches; 1 entered + 11 not; waves 1/2/5/4; 49 planned artifacts; 0 executable")
    return 0
if __name__=="__main__": raise SystemExit(main())
