"""Compile final pushed CH05 terminal record."""
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];R13=ROOT/"docs/research/evidence/ch05-final-integrated-release-r13.json";INTEGRITY=ROOT/"docs/research/evidence/ch05-final-post-pointer-integrity-r1.json";POINTER=ROOT/"docs/research/ch05-final-owner-review-start-here-r1.md";OUTPUT=ROOT/"docs/research/evidence/ch05-final-push-record-r1.json";SUMMARY=ROOT/"docs/research/ch05-final-push-record-r1.md";EXPECTED=["GITIGNORE_RECOMMENDED.txt","assets/","batch_generate.py","benchmarks/","garden/","get_ipadapter.cmd","run_batch.cmd","run_comfy.cmd","trainer/"]
def git(*args):return subprocess.run(["git",*args],cwd=ROOT,check=True,capture_output=True,text=True).stdout.strip()
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def bind(path):return {"path":path.relative_to(ROOT).as_posix(),"sha256":sha(path)}
def main():
    r13=json.loads(R13.read_text(encoding="utf-8"));integrity=json.loads(INTEGRITY.read_text(encoding="utf-8"));head=git("rev-parse","HEAD");origin=git("rev-parse","origin/main");untracked=sorted(line[3:].replace("\\","/") for line in git("status","--short").splitlines() if line.startswith("?? ") and line[3:].replace("\\","/") not in ("docs/research/ch05-final-push-record-r1.md","docs/research/evidence/ch05-final-push-record-r1.json","src/north_garden/compile_ch05_final_push_record.py","src/north_garden/validate_ch05_final_push_record.py"));output={"record_type":"CH05FinalPushRecord","schema_version":"1.0","record_id":"ng-ch05-final-push-record-r1","state":"PASS_FINAL_PUSH_OWNER_REVIEW_PENDING","inputs":[bind(R13),bind(INTEGRITY),bind(POINTER)],"source":{"recorded_commit":head,"origin_main":origin,"branch":git("branch","--show-current"),"remote":git("remote","get-url","origin"),"remote_parity":head==origin,"tracked_paths":len(git("ls-files").splitlines()),"unrelated_untracked_items":untracked,"unrelated_untracked_count":len(untracked)},"summary":{"release_commands":r13["summary"]["orchestrator_commands"],"release_domains":r13["summary"]["effective_domains"],"integrity_mutations":24,"review_steps":9,"review_links":134,"candidates":29,"plans":50,"worksheet_checks":112,"remaining_decisions":10,"provider_calls":0,"uploads":0,"owner_decisions_ingested":0,"visual_dispositions":0,"accepted":0,"commercially_cleared":0,"executable":0,"paid_spend_usd":0,"human_review_minutes":None},"animation_shot_plan":None,"e_conte":None,"boundary":"Final pushed terminal record. Owner review remains the only next action; no generation, upload, ingestion, disposition, acceptance, rights, exact-base, plan revision, or execution authority is granted."};OUTPUT.write_text(json.dumps(output,indent=2)+"\n",encoding="utf-8",newline="\n");SUMMARY.write_text("\n".join(["# CH05 final push record r1","",f"Recorded pushed commit: `{head}`.",f"Origin parity: `{head==origin}`. Tracked paths: {output['source']['tracked_paths']}.","","Start review: "+POINTER.resolve().as_posix(),"","R13 passes 9/9 commands across 18 domains. Nine unrelated user-owned items remain untracked. Owner decisions and all promotion/provider activity remain zero/null."])+"\n",encoding="utf-8",newline="\n");print(f"CH05 final push: {head[:7]}; parity {head==origin}; tracked {output['source']['tracked_paths']}; untracked {len(untracked)}; authority 0");return 0
if __name__=="__main__":raise SystemExit(main())
