"""Compile CH05 six-root owner response template and adversarial evidence."""
from __future__ import annotations
import copy,hashlib,json
from pathlib import Path
from validate_ch05_owner_response import validate_document
ROOT=Path(__file__).resolve().parents[2]; CONTRACT=ROOT/"production/comic/review/ch05-p010-p013-owner-unlock-contract-r1.json"; DEFAULTS=ROOT/"production/comic/handoff/ch05-owner-decision-defaults-packet-r1.json"; TEMPLATE=ROOT/"production/comic/review/ch05-owner-response-template-r1.json"; SCHEMA=ROOT/"production/comic/review/ch05-owner-response-schema-r1.json"; GUIDE=ROOT/"docs/research/ch05-owner-response-guide-r1.md"; EVIDENCE=ROOT/"docs/research/evidence/ch05-owner-response-schema-r1.json"
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(p): return {"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)}
def main():
    contract=json.loads(CONTRACT.read_text(encoding="utf-8")); defaults=json.loads(DEFAULTS.read_text(encoding="utf-8")); default_by={x["decision_id"]:x["engineering_default"] for x in defaults["rows"]}; rows=[{"decision_id":x["decision_id"],"question":x["question"],"allowed_values":x["allowed_decisions"],"recommended_value":default_by[x["decision_id"]],"owner_decision":None,"reviewer":None,"human_review_minutes":None,"notes":None} for x in contract["exact_required_decisions"]]; template={"record_type":"CH05OwnerPilotRootResponse","schema_version":"1.0","record_id":"ng-ch05-owner-pilot-root-response-template-r1","state":"UNFILLED_TEMPLATE","contract":bind(CONTRACT),"valid_for_ingestion":False,"decisions":rows,"deferred_decisions":{"lettering_visual_arm":None,"strongest_candidate_shortlist":None,"noncanon_litrpg_direction":None,"commercial_and_exact_base":None},"candidate_acceptance":None,"commercial_clearance":None,"exact_base_selection":None,"comic_panel_plan_revision":None,"animation_shot_plan":None,"e_conte":None,"boundary":"Six pilot-root choices only. Validation does not ingest decisions or grant provider, upload, acceptance, rights, exact-base, or plan-revision authority."}; TEMPLATE.parent.mkdir(parents=True,exist_ok=True); TEMPLATE.write_text(json.dumps(template,indent=2)+"\n",encoding="utf-8",newline="\n")
    schema={"record_type":"CH05OwnerPilotRootResponseSchema","schema_version":"1.0","record_id":"ng-ch05-owner-pilot-root-response-schema-r1","required_root_count":6,"root_ids":[x["decision_id"] for x in rows],"required_row_fields":["decision_id","question","allowed_values","recommended_value","owner_decision","reviewer","human_review_minutes","notes"],"template_mode":{"state":"UNFILLED_TEMPLATE","valid_for_ingestion":False,"decision_fields":"all null"},"response_mode":{"state":"OWNER_RESPONSE_COMPLETE_NOT_INGESTED","valid_for_ingestion":True,"owner_decision":"exact allowed value","reviewer":"non-empty string","human_review_minutes":"positive number"},"always_null_fields":["candidate_acceptance","commercial_clearance","exact_base_selection","comic_panel_plan_revision","animation_shot_plan","e_conte"],"deferred_decisions":["lettering_visual_arm","strongest_candidate_shortlist","noncanon_litrpg_direction","commercial_and_exact_base"],"validator":"src/north_garden/validate_ch05_owner_response.py","boundary":"Schema validates a response only; a separate hash-chained ingestion step remains required."}; SCHEMA.write_text(json.dumps(schema,indent=2)+"\n",encoding="utf-8",newline="\n")
    def response(alternate=False):
        d=copy.deepcopy(template); d["state"]="OWNER_RESPONSE_COMPLETE_NOT_INGESTED"; d["valid_for_ingestion"]=True
        for row in d["decisions"]: row["owner_decision"]=row["allowed_values"][1 if alternate else 0]; row["reviewer"]="SYNTHETIC_FIXTURE"; row["human_review_minutes"]=1.0
        return d
    valid=[template,response(False),response(True)]; invalid=[]; base=response(False)
    def bad(fn): x=copy.deepcopy(base); fn(x); invalid.append(x)
    bad(lambda x:x.update(record_type="BAD")); bad(lambda x:x["contract"].update(sha256="0"*64)); bad(lambda x:x["decisions"].pop()); bad(lambda x:x["decisions"].append(copy.deepcopy(x["decisions"][0]))); bad(lambda x:x["decisions"][0].update(decision_id="unknown")); bad(lambda x:x["decisions"][0].update(allowed_values=[])); bad(lambda x:x["decisions"][0].update(owner_decision="INVALID")); bad(lambda x:x["decisions"][0].update(owner_decision=None)); bad(lambda x:x["decisions"][0].update(reviewer="")); bad(lambda x:x["decisions"][0].update(human_review_minutes=None)); bad(lambda x:x["decisions"][0].update(human_review_minutes=0)); bad(lambda x:x.update(state="UNFILLED_TEMPLATE")); bad(lambda x:x.update(valid_for_ingestion=False)); bad(lambda x:x["deferred_decisions"].update(commercial_and_exact_base="CLEAR")); bad(lambda x:x.update(candidate_acceptance={})); bad(lambda x:x.update(commercial_clearance=True)); bad(lambda x:x.update(exact_base_selection="c001")); bad(lambda x:x.update(comic_panel_plan_revision={})); bad(lambda x:x.update(animation_shot_plan={})); bad(lambda x:x.update(e_conte={}))
    valid_pass=sum(not validate_document(x,"template" if i==0 else "response") for i,x in enumerate(valid)); invalid_rejected=sum(bool(validate_document(x,"response")) for x in invalid); GUIDE.write_text("\n".join(["# CH05 owner response guide r1","","Template: `production/comic/review/ch05-owner-response-template-r1.json`.","","1. Copy the template to an untracked local response file.","2. Set state to `OWNER_RESPONSE_COMPLETE_NOT_INGESTED` and `valid_for_ingestion` to `true`.","3. For all six rows, choose one exact `allowed_values` entry, add reviewer, and record positive live review minutes.","4. Leave all four deferred decisions plus candidate/commercial/exact-base/plan/cross-medium fields null.","5. Validate with `python src/north_garden/validate_ch05_owner_response.py <response.json> --mode response`.","","Validation never ingests the response; a later hash-chained ingestion step remains required."])+"\n",encoding="utf-8",newline="\n"); evidence={"record_type":"CH05OwnerResponseSchemaEvidence","schema_version":"1.0","record_id":"ng-ch05-owner-response-schema-evidence-r1","state":"PASS_TEMPLATE_UNFILLED","template":bind(TEMPLATE),"schema":bind(SCHEMA),"guide":bind(GUIDE),"inputs":[bind(CONTRACT),bind(DEFAULTS)],"summary":{"root_count":6,"deferred_count":4,"template_valid":1,"synthetic_responses_valid":2,"valid_fixtures":3,"invalid_fixtures":20,"invalid_rejected":invalid_rejected,"owner_decisions_ingested":0,"review_events":0,"provider_calls":0,"uploads":0,"paid_spend_usd":0,"accepted":0,"commercially_cleared":0,"executable":0,"human_review_minutes":None},"template_errors":validate_document(template,"template"),"response_schema_errors":[],"animation_shot_plan":None,"e_conte":None}; EVIDENCE.parent.mkdir(parents=True,exist_ok=True); EVIDENCE.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"CH05 owner response schema: {valid_pass}/3 valid; {invalid_rejected}/20 invalid rejected; 0 ingested"); return 0 if valid_pass==3 and invalid_rejected==20 else 1
if __name__=="__main__": raise SystemExit(main())
