"""Compile exact pre-render review-packet slots and measurement semantics."""
from __future__ import annotations
import hashlib,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; PROMPTS=ROOT/"production/comic/run-manifests/ch05-p010-p013-prompt-blueprint-r1.json"; REVIEW=ROOT/"production/comic/review/ch05-p010-p013-review-packet-contract-dry-run-r1.json"; BUILDER=ROOT/"src/north_garden/build_ch05_p010_p013_review_packet.py"; OUTPUT=ROOT/"production/comic/review/ch05-p010-p013-prerender-packet-blueprint-r1.json"; EVIDENCE=ROOT/"docs/research/evidence/ch05-p010-p013-prerender-packet-blueprint-r1.json"
ZONES={"m001":[0.03,0.03,0.38,0.16],"m002":[0.59,0.03,0.38,0.16],"m003":[0.03,0.03,0.94,0.17],"m004":[0.30,0.03,0.40,0.14]}; PHONE={"m001":[390,488],"m002":[390,390],"m003":[390,293],"m004":[390,260]}; DENSITY={"m001":[0.18,0.32],"m002":[0.12,0.28],"m003":[0.08,0.22],"m004":[0.12,0.28]}
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(p): return {"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)}
def main():
    prompts=json.loads(PROMPTS.read_text(encoding="utf-8")); review=json.loads(REVIEW.read_text(encoding="utf-8")); review_by={x["candidate_slot"]:x for x in review["candidate_reviews"]}; slots=[]
    for row in prompts["rows"]:
        slot=row["candidate_slot"]; expected=review_by[slot]["expected_output_path"]; slots.append({"candidate_slot":slot,"panel_id":row["panel_id"],"draft_prompt_sha256":row["draft_prompt_sha256"],"expected_output_path":expected,"candidate_exists":(ROOT/expected).is_file(),"planning_canvas_px":row["planning_canvas_px"],"expected_phone_preview_px":PHONE[slot],"cadence_width_px":row["target_width_px"],"lettering_safe_zone_normalized":ZONES[slot],"safe_zone_status":"PROPOSED_REQUIRES_POST_RENDER_HUMAN_CLEARANCE","protected_content":["faces","adult bodies and silhouettes","important hands","map/twine/creek causal objects"],"density_edge_occupancy_target":DENSITY[slot],"required_checks":review["required_checks"],"review_values":{x:None for x in review["required_checks"]},"failure_classes":[],"output_sha256":None,"source_dimensions":None,"elapsed_seconds":None,"human_review_minutes":None,"decision":None})
    root="experiments/review-packets/ch05-p010-p013-production-r1/review"; artifacts=[]
    for x in review["planned_artifacts"]: artifacts.append({"artifact_id":x["artifact_id"],"path":f"{root}/{x['filename']}","required_inputs":4,"state":"NOT_BUILT","sha256":None,"dimensions":None})
    out={"record_type":"ComicPrerenderPacketBlueprint","schema_version":"1.0","record_id":"ng-ch05-p010-p013-prerender-packet-blueprint-r1","state":"PREFLIGHT_PASS_CANDIDATES_ABSENT","medium":"comic","inputs":[bind(PROMPTS),bind(REVIEW),bind(BUILDER)],"summary":{"candidate_slots":4,"candidates_present":sum(x["candidate_exists"] for x in slots),"candidates_missing":sum(not x["candidate_exists"] for x in slots),"artifacts_planned":5,"artifacts_built":0,"checks_per_candidate":11,"total_empty_candidate_checks":44,"proposed_safe_zones":4,"phone_previews_planned":4,"density_targets":4,"repair_slots":2,"provider_calls":0,"uploads":0,"renders":0,"paid_spend_usd":0},"candidate_slots":slots,"artifacts":artifacts,"failure_vocabulary":review["failure_vocabulary"],"sequence_review":review["sequence_review"],"repair_allocation":review["repair_allocation"],"renderrecord_required_fields":["exact_prompt","prompt_sha256","input_reference_hashes","output_sha256","dimensions","elapsed_seconds","model","endpoint","request_id","provider_usage","provider_cost_usd","candidate_file","failure","human_review_state","human_review_minutes","acceptance_decision"],"builder":{"command":"python src/north_garden/build_ch05_p010_p013_review_packet.py","dry_run_command":"python src/north_garden/build_ch05_p010_p013_review_packet.py --dry-run","network_capable":False,"writes_only_ignored_paths":True,"source_pixels_unchanged":True},"promotion_rules":review["promotion_rules"],"activity":{"prompts_compiled":0,"provider_calls":0,"uploads":0,"renders":0,"accepted":0,"commercially_cleared":0,"executable":0,"human_review_minutes":None},"animation_shot_plan":None,"e_conte":None,"boundary":"Pre-render structure only. Safe zones and density ranges are hypotheses requiring post-render measurement and human clearance. All five review artifacts remain NOT_BUILT."}; OUTPUT.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8",newline="\n")
    done=subprocess.run([sys.executable,str(BUILDER),"--dry-run"],cwd=ROOT,capture_output=True,text=True,encoding="utf-8"); stdout=done.stdout.replace("\r\n","\n").strip()+"\n"; evidence={"record_type":"ComicPrerenderPacketBlueprintEvidence","schema_version":"1.0","record_id":"ng-ch05-p010-p013-prerender-packet-blueprint-evidence-r1","state":"PASS_NOT_BUILT","blueprint":bind(OUTPUT),"inputs":out["inputs"],"summary":out["summary"],"builder_dry_run":{"return_code":done.returncode,"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"stderr":done.stderr},"animation_shot_plan":None,"e_conte":None}; EVIDENCE.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n"); print(stdout.strip()); print("prerender packet blueprint: 4 missing candidates/5 NOT_BUILT artifacts/44 empty checks/4 proposed zones")
    return 0 if done.returncode==0 else 1
if __name__=="__main__": raise SystemExit(main())
