"""Compile the current CH05 overnight closeout without promoting art."""
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; START="e011cac"; LINKS=ROOT/"production/comic/review/ch05-review-artifact-link-manifest-r5.json"; DELIVERY=ROOT/"production/comic/handoff/ch05-overnight-delivery-bundle-r2.json"; REPRO=ROOT/"docs/research/evidence/ch05-final-evidence-reproducer-matrix-r2.json"; SAFE=ROOT/"docs/research/evidence/ch05-overnight-safe-source-parity-r2.json"; DEFAULTS=ROOT/"production/comic/handoff/ch05-owner-decision-defaults-packet-r1.json"; COST=ROOT/"docs/research/evidence/ch05-production-cost-ledger-r27.json"; FROZEN=ROOT/"docs/research/evidence/frozen-gauntlet-baseline-integrity-r1.json"; ROUTE=ROOT/"production/comic/recommendations/ch05-pipeline-route-recommendation-r1.json"; RENDER=ROOT/"production/comic/run-manifests/ch05-built-in-renderrecord-index-r1.json"; CAPACITY=ROOT/"production/comic/run-manifests/ch05-chapter-production-duration-capacity-r1.json"; HUB=ROOT/"experiments/review-packets/ch05-owner-review-index-r7/index.html"; LINKDOC=ROOT/"docs/research/ch05-review-links-r5.md"; OUTPUT=ROOT/"production/comic/handoff/ch05-overnight-closeout-bundle-r1.json"; SUMMARY=ROOT/"docs/research/ch05-overnight-closeout-r1.md"; CHANGED=ROOT/"docs/research/ch05-overnight-final-changed-files-r1.md"; EVIDENCE=ROOT/"docs/research/evidence/ch05-overnight-closeout-bundle-r1.json"
INPUTS=[LINKS,DELIVERY,REPRO,SAFE,DEFAULTS,COST,FROZEN,ROUTE,RENDER,CAPACITY]
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(p,absolute=False):
    x={"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)}
    if absolute: x["absolute_path"]=p.resolve().as_posix()
    return x
def git(*args): return subprocess.run(["git",*args],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",check=True).stdout.strip()
def main():
    links,delivery,repro,safe,defaults,cost,frozen,route,render,capacity=[json.loads(p.read_text(encoding="utf-8")) for p in INPUTS]; head=git("rev-parse","HEAD"); origin=git("rev-parse","origin/main"); changed=git("diff","--name-only",f"{START}^",head).splitlines(); commits=git("rev-list","--reverse",f"{START}^..{head}").splitlines(); adrs=[p for p in changed if p.startswith("docs/adr/ADR-")]; review={c:[{"path":x["path"],"absolute_path":x["absolute_path"],"sha256":x["sha256"],"git_state":x["git_state"]} for x in links["artifacts"] if c in x["categories"]] for c in ("contact_sheets","sequence_packets","lettering_overlays","strongest_candidates")}; limitations=delivery["limitations"]+["Safe-source r2 captures pushed commit 479f7ca; subsequent append-only evidence commits are validated by current tracked scope and remote lineage but are not inside that historical inventory.","The 18–30 autonomous candidate target was met at 29; no additional art was generated merely to increase volume after the measured body was sufficient."]
    closeout={"record_type":"CH05OvernightCloseoutBundle","schema_version":"1.0","record_id":"ng-ch05-overnight-closeout-bundle-r1","state":"ENGINEERING_CLOSEOUT_READY_OWNER_REVIEW_PENDING","medium":"comic","source_lineage":{"start_commit":START,"base_commit":head,"origin_main_at_compile":origin,"base_remote_parity":head==origin,"commit_count":len(commits),"changed_path_count":len(changed),"adr_count":len(adrs),"adrs":adrs},"inputs":[bind(p) for p in INPUTS],"primary_links":{"owner_hub":bind(HUB,True),"all_review_links":bind(LINKDOC,True),"owner_defaults":bind(ROOT/"docs/research/ch05-owner-decision-defaults-r1.md",True),"operator_playbook":bind(ROOT/"docs/research/ch05-chapter-production-operating-playbook-r1.md",True)},"review_links":{"effective_total":links["effective_unique_artifact_count"],"category_counts":links["category_counts"],**review},"measured_result":{"candidates":29,"ch05_candidates":26,"noncanon_concepts":3,"distinct_ch05_plans":14,"generated_sequences":3,"selected_candidates":14,"ch05_pass_warn_fail":{"pass":17,"warn":3,"fail":6},"all_candidate_elapsed_seconds":render["summary"]["total_elapsed_seconds"],"ch05_candidate_elapsed_seconds":capacity["observed_basis"]["generation_seconds"],"reference_uses":render["summary"]["input_reference_uses"],"dimensions":delivery["measured_art"]["dimension_sets"],"service_metadata_unavailable":{"model":29,"endpoint":29,"request_id":29,"usage":29,"monetary_cost":29,"seed":29},"paid_api_calls":0,"external_uploads":0,"cloud_gpu_uses":0,"paid_spend_usd":0,"built_in_monetary_cost_usd":None,"human_review_minutes":None,"accepted":0,"commercially_cleared":0,"executable":0},"chapter_pipeline":{"plans":50,"batches":12,"review_artifacts_planned":49,"review_links":122,"remaining_candidate_envelope":49,"fresh_arm_candidate_envelope":68,"release_effective_checks":66,"reproducer_domains":7,"zero_cost_milestones":68,"safe_capture_paths":835,"frozen_paths":16,"baseline_paths":4},"ranked_recommendations":route["role_allocation"],"recommended_route":route["recommended_route"],"remaining_decisions":{"count":10,"pilot_roots":6,"deferred":4,"resolved":0,"rows":defaults["rows"]},"next_high_information_experiment":"After exact decision ingestion only: P010–P013 four-candidate silent role-aware continuity/causality pilot, with at most two one-class repair slots and five deterministic review artifacts.","limitations":limitations,"activity":{"provider_calls":0,"uploads":0,"downloads":0,"purchases":0,"paid_spend_usd":0,"owner_decisions":0,"review_events":0,"accepted":0,"commercially_cleared":0,"executable":0,"comic_panel_plan_revisions":0,"human_review_minutes":None},"animation_shot_plan":None,"e_conte":None,"boundary":"Engineering closeout only. No art, route, prompt, right, exact base, or production panel is owner-accepted or commercially cleared by this record."}; OUTPUT.parent.mkdir(parents=True,exist_ok=True); OUTPUT.write_text(json.dumps(closeout,indent=2)+"\n",encoding="utf-8",newline="\n")
    CHANGED.write_text("\n".join(["# CH05 final changed-file inventory","",f"Commit range: `{START}^..{head}`. Base was at `origin/main` when compiled.","",f"Commits: {len(commits)}. Changed paths: {len(changed)}. ADRs: {len(adrs)}.",""]+[f"- `{p}`" for p in changed])+"\n",encoding="utf-8",newline="\n")
    lines=["# CH05 overnight closeout r1","",f"Current review hub: [owner review index r7]({HUB.resolve().as_posix()})",f"All 122 exact links: [review links r5]({LINKDOC.resolve().as_posix()})",f"Decision defaults: [owner defaults r1]({(ROOT/'docs/research/ch05-owner-decision-defaults-r1.md').resolve().as_posix()})",f"Changed files: [final changed-file inventory]({CHANGED.resolve().as_posix()})","","## Measured result","","- 29 candidates: 26 CH05 + 3 non-canon; 14 plans represented; 3 generated sequences; 14 selected engineering candidates.","- CH05 engineering review: 17 pass / 3 warn / 6 fail; every candidate remains pending and unaccepted.","- 1,385.036 seconds all-candidate generation; 1,230.058 seconds CH05; 39 authorized reference uses.","- Paid API/cloud spend $0; built-in monetary cost and human review minutes unavailable/null.","- 50 ComicPanelPlans / 12 batches / 122 review resources / 66 release checks / 7 reproducer domains.","","## Ranked engineering recommendations",""]+[f"{x['priority']}. `{x['mechanism']}` — {', '.join(x['roles'])}. {x['evidence']}" for x in route["role_allocation"]]+["",f"Recommended hybrid: {route['recommended_route']}.","","## Direct review links",""]
    for category in ("contact_sheets","sequence_packets","lettering_overlays","strongest_candidates"):
        lines += [f"### {category.replace('_',' ').title()}",""]+[f"- [{Path(x['path']).name}]({x['absolute_path']}) — `{x['sha256']}`" for x in review[category]]+[""]
    lines += ["## Remaining decisions","",f"Six pilot roots and four deferred choices remain un-ingested. Review [the exact defaults]({(ROOT/'docs/research/ch05-owner-decision-defaults-r1.md').resolve().as_posix()}).","","## Limitations",""]+[f"- {x}" for x in limitations]
    SUMMARY.write_text("\n".join(lines)+"\n",encoding="utf-8",newline="\n"); evidence={"record_type":"CH05OvernightCloseoutBundleEvidence","schema_version":"1.0","record_id":"ng-ch05-overnight-closeout-bundle-evidence-r1","state":"PASS_OWNER_PENDING","bundle":bind(OUTPUT),"summary_document":bind(SUMMARY),"changed_files_document":bind(CHANGED),"inputs":closeout["inputs"],"summary":{"candidates":29,"ch05_candidates":26,"noncanon_concepts":3,"plans":50,"represented_plans":14,"batches":12,"review_links":122,"direct_review_links":sum(len(v) for v in review.values()),"contact_sheets":10,"sequence_packets":9,"lettering_overlays":34,"strongest_candidates":14,"release_checks":66,"reproducer_domains":7,"safe_paths":835,"remaining_decisions":10,"resolved_decisions":0,"paid_spend_usd":0,"accepted":0,"executable":0,"human_review_minutes":None,"changed_paths":len(changed),"adrs":len(adrs)},"base_remote_parity":head==origin,"animation_shot_plan":None,"e_conte":None}; EVIDENCE.parent.mkdir(parents=True,exist_ok=True); EVIDENCE.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"CH05 closeout: 29 candidates/50 plans/12 batches/122 links/{sum(len(v) for v in review.values())} direct; {len(changed)} paths/{len(adrs)} ADRs; parity {head==origin}"); return 0
if __name__=="__main__": raise SystemExit(main())
