"""Run append-only integrated release r8 over delivery and source-parity evidence."""
from __future__ import annotations
import hashlib,json,subprocess,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; BASE=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r7.json"; OUTPUT=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r8.json"
COMMANDS=[("src/north_garden/validate_ch05_overnight_integrated_release_gate_r7.py",[]),("src/north_garden/validate_ch05_overnight_delivery_bundle.py",[]),("src/north_garden/validate_ch05_production_cost_ledger_r24.py",[]),("src/north_garden/validate_ch05_overnight_safe_source_parity.py",["--allow-unpushed-current"])]
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
    base=json.loads(BASE.read_text(encoding="utf-8")); results=[]; started=time.perf_counter()
    for i,(relative,args) in enumerate(COMMANDS,1):
        p=ROOT/relative; t=time.perf_counter(); done=subprocess.run([sys.executable,str(p),*args],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=360); elapsed=time.perf_counter()-t; stdout=done.stdout.replace("\r\n","\n").strip()+"\n"; stderr=done.stderr.replace("\r\n","\n")
        results.append({"path":relative,"arguments":args,"script_sha256":sha(p),"command":" ".join(["python",relative,*args]),"network_capable":False,"return_code":done.returncode,"elapsed_seconds":round(elapsed,6),"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"stderr":stderr}); print(f"[{i}/{len(COMMANDS)}] {'PASS' if done.returncode==0 else 'FAIL'} {relative} {elapsed:.3f}s")
    total=time.perf_counter()-started; passed=sum(x["return_code"]==0 for x in results)
    evidence={"record_type":"CH05OvernightIntegratedReleaseGate","schema_version":"1.7","record_id":"ng-ch05-overnight-integrated-release-gate-r8","state":"PASS" if passed==len(results) else "FAIL","medium":"comic","comic_panel_plan_revision_created":False,"animation_shot_plan":None,"e_conte":None,"supersedes":{"record_id":base["record_id"],"path":BASE.relative_to(ROOT).as_posix(),"sha256":sha(BASE)},"summary":{"base_effective_command_count":46,"extension_command_count":3,"effective_command_count":49,"orchestrator_commands":len(results),"passed":passed,"failed":len(results)-passed,"observed_total_seconds":round(total,6),"network_capable_commands":0,"provider_calls":0,"uploads":0,"downloads":0,"cost_usd":0,"accepted_candidates":0,"commercially_cleared_candidates":0,"executable_panels":0,"owner_decisions":0,"human_review_minutes":None},"results":results,"effective_state":{"candidates":29,"ch05_candidates":26,"noncanon_concepts":3,"comic_panel_plans":50,"represented_plans":14,"sequence_batches":12,"review_links":105,"strongest_candidates":14,"remaining_owner_decisions":10,"limitations":8,"observed_generation_seconds":1385.036,"reference_uses":39,"safe_source_capture_commit":"a1454db0ec0fbe80bda7c88a55764047c62618b4","safe_source_paths":735,"safe_source_bytes":11861823,"safe_source_generated_paths":0,"zero_cost_milestones":52,"next_prompts":0,"frozen_paths":16,"baseline_paths":4},"boundaries":["R7 remains immutable; r8 preserves 46 effective checks and adds delivery, cost-ledger, and commit-pinned safe-source validators.","Safe-source capture parity is historical; ancestry mode lets later append-only commits reproduce the captured inventory.","Passing does not ingest owner review, accept or clear art, compile prompts, upload, revise plans, or authorize production."]}
    OUTPUT.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"integrated release r8: {passed}/{len(results)} orchestrator commands, 49 effective checks in {total:.3f}s; {OUTPUT.relative_to(ROOT)} {sha(OUTPUT)}"); return 0 if passed==len(results) else 1
if __name__=="__main__": raise SystemExit(main())
