"""Run append-only CH05 integrated release r11 over final closeout evidence."""
from __future__ import annotations
import hashlib,json,re,subprocess,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; BASE=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r10.json"; COMPAT=ROOT/"docs/research/evidence/ch05-final-evidence-reproducer-matrix-r2.json"; OUTPUT=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r11.json"
COMMANDS=["src/north_garden/validate_ch05_final_evidence_reproducer_matrix_r2.py","src/north_garden/validate_ch05_overnight_safe_source_parity_r2.py","src/north_garden/validate_ch05_owner_decision_defaults_packet.py","src/north_garden/validate_ch05_owner_review_index_r7.py","src/north_garden/validate_ch05_review_artifact_link_manifest_r5.py","src/north_garden/validate_ch05_overnight_closeout_bundle.py","src/north_garden/validate_ch05_production_cost_ledger_r28.py","src/north_garden/validate_frozen_gauntlet_baseline_integrity.py","src/north_garden/validate_tracked_source_scope.py"]
ARGS={"src/north_garden/validate_ch05_overnight_safe_source_parity_r2.py":["--allow-unpushed-current"]}; NORMALIZED={"src/north_garden/validate_ch05_overnight_safe_source_parity_r2.py":"decimal tracked-path diagnostic only","src/north_garden/validate_tracked_source_scope.py":"decimal tracked-path diagnostic only"}
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def norm(path,text): return re.sub(r"\d+ tracked safe-source paths","<LIVE_COUNT> tracked safe-source paths",text) if path in NORMALIZED else text
def main():
    results=[]; started=time.perf_counter()
    for i,relative in enumerate(COMMANDS,1):
        p=ROOT/relative; args=ARGS.get(relative,[]); t=time.perf_counter(); done=subprocess.run([sys.executable,str(p),*args],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=900); elapsed=time.perf_counter()-t; raw=done.stdout.replace("\r\n","\n").strip()+"\n"; stdout=norm(relative,raw); results.append({"path":relative,"arguments":args,"script_sha256":sha(p),"command":" ".join(["python",relative,*args]),"network_capable":False,"normalization":NORMALIZED.get(relative),"return_code":done.returncode,"elapsed_seconds":round(elapsed,6),"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"stderr":done.stderr.replace("\r\n","\n")}); print(f"[{i}/{len(COMMANDS)}] {'PASS' if done.returncode==0 else 'FAIL'} {relative} {elapsed:.3f}s")
    total=time.perf_counter()-started; passed=sum(x["return_code"]==0 for x in results); out={"record_type":"CH05OvernightIntegratedReleaseGate","schema_version":"2.0","record_id":"ng-ch05-overnight-integrated-release-gate-r11","state":"PASS" if passed==9 else "FAIL","medium":"comic","comic_panel_plan_revision_created":False,"animation_shot_plan":None,"e_conte":None,"supersedes":{"record_id":"ng-ch05-overnight-integrated-release-gate-r10","path":BASE.relative_to(ROOT).as_posix(),"sha256":sha(BASE)},"base_compatibility":{"path":COMPAT.relative_to(ROOT).as_posix(),"sha256":sha(COMPAT),"domains":7,"state":"PASS"},"summary":{"base_effective_command_count":66,"extension_command_count":8,"effective_command_count":74,"orchestrator_commands":9,"passed":passed,"failed":9-passed,"observed_total_seconds":round(total,6),"normalized_live_diagnostics":2,"network_capable_commands":0,"provider_calls":0,"uploads":0,"downloads":0,"cost_usd":0,"accepted_candidates":0,"commercially_cleared_candidates":0,"executable_panels":0,"owner_decisions":0,"human_review_minutes":None},"results":results,"effective_state":{"candidates":29,"comic_panel_plans":50,"sequence_batches":12,"review_links":122,"current_owner_hub_links":5,"direct_closeout_links":67,"engineering_defaults":10,"resolved_decisions":0,"remaining_planning_candidates":49,"fresh_arm_candidates":68,"safe_source_capture_paths":835,"zero_cost_milestones":73,"frozen_paths":16,"baseline_paths":4,"production_prompts":0,"accepted_candidates":0,"executable_panels":0},"boundaries":["R10 remains immutable; final reproducer r2 is the compatibility/base reproduction path.","Two live decimal tracked-path diagnostics normalize; no inventory, hash, semantic state, or arbitrary stdout does.","All commands are local/no-network and all decision, render, rights, and promotion gates remain closed.","Passing does not authorize upload, generation, acceptance, commercial clearance, exact-base selection, or ComicPanelPlan revision."]}; OUTPUT.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"integrated release r11: {passed}/9 commands, 74 effective checks in {total:.3f}s; {OUTPUT.relative_to(ROOT)} {sha(OUTPUT)}"); return 0 if passed==9 else 1
if __name__=="__main__": raise SystemExit(main())
