"""Run the compact current CH05 evidence reproducer matrix r2."""
from __future__ import annotations
import hashlib,json,re,subprocess,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; OUTPUT=ROOT/"docs/research/evidence/ch05-final-evidence-reproducer-matrix-r2.json"
COMMANDS=[("integrated_release_r10","src/north_garden/validate_ch05_overnight_integrated_release_gate_r10.py",[]),("delivery_bundle_r2","src/north_garden/validate_ch05_overnight_delivery_bundle_r2.py",[]),("safe_source_capture_r2","src/north_garden/validate_ch05_overnight_safe_source_parity_r2.py",["--allow-unpushed-current"]),("frozen_gauntlet_baseline","src/north_garden/validate_frozen_gauntlet_baseline_integrity.py",[]),("current_tracked_scope","src/north_garden/validate_tracked_source_scope.py",[]),("zero_cost_ledger_r27","src/north_garden/validate_ch05_production_cost_ledger_r27.py",[]),("remote_lineage_r2","src/north_garden/validate_ch05_remote_lineage_r2.py",["--allow-unpushed-current"])]
INPUTS=["docs/research/evidence/ch05-overnight-integrated-release-gate-r10.json","docs/research/evidence/ch05-overnight-delivery-bundle-r2.json","docs/research/evidence/ch05-overnight-safe-source-parity-r2.json","docs/research/evidence/frozen-gauntlet-baseline-integrity-r1.json","docs/research/evidence/ch05-production-cost-ledger-r27.json"]
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def norm(domain,text): return re.sub(r"\d+ tracked safe-source paths","<TRACKED_COUNT> tracked safe-source paths",text) if domain in {"safe_source_capture_r2","current_tracked_scope"} else text
def git(*args): return subprocess.run(["git",*args],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",check=True).stdout.strip()
def main():
    results=[]; started=time.perf_counter()
    for i,(domain,relative,args) in enumerate(COMMANDS,1):
        p=ROOT/relative; t=time.perf_counter(); done=subprocess.run([sys.executable,str(p),*args],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=600); elapsed=time.perf_counter()-t; stdout=done.stdout.replace("\r\n","\n").strip()+"\n"; normalized=norm(domain,stdout); stderr=done.stderr.replace("\r\n","\n"); results.append({"domain":domain,"path":relative,"arguments":args,"script_sha256":sha(p),"command":" ".join(["python",relative,*args]),"normalization":"TRACKED_COUNT_ONLY" if normalized!=stdout else "NONE","network_capable":False,"return_code":done.returncode,"elapsed_seconds":round(elapsed,6),"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"normalized_stdout_sha256":hashlib.sha256(normalized.encode()).hexdigest(),"stderr":stderr}); print(f"[{i}/{len(COMMANDS)}] {'PASS' if done.returncode==0 else 'FAIL'} {domain} {elapsed:.3f}s")
    total=time.perf_counter()-started; passed=sum(x["return_code"]==0 for x in results); head=git("rev-parse","HEAD"); origin=git("rev-parse","origin/main"); out={"record_type":"CH05FinalEvidenceReproducerMatrix","schema_version":"2.0","record_id":"ng-ch05-final-evidence-reproducer-matrix-r2","state":"PASS" if passed==len(results) else "FAIL","base_commit":head,"origin_main_at_compile":origin,"base_remote_parity":head==origin,"inputs":[{"path":p,"sha256":sha(ROOT/p)} for p in INPUTS],"summary":{"command_count":7,"domain_count":7,"passed":passed,"failed":len(results)-passed,"release_effective_checks":66,"observed_total_seconds":round(total,6),"tracked_count_only_normalizations":sum(x["normalization"]=="TRACKED_COUNT_ONLY" for x in results),"network_capable_commands":0,"provider_calls":0,"uploads":0,"downloads":0,"paid_spend_usd":0,"accepted_candidates":0,"executable_panels":0,"owner_decisions":0,"human_review_minutes":None},"results":results,"required_domains":[x[0] for x in COMMANDS],"effective_state":{"candidates":29,"comic_panel_plans":50,"review_links":117,"safe_source_capture_paths":835,"frozen_paths":16,"baseline_paths":4,"zero_cost_milestones":68,"remote_lineage_pass":True},"animation_shot_plan":None,"e_conte":None,"boundary":"Local no-network reproduction only. Two declared normalizations affect only the live tracked-path diagnostic count, never captured inventory, hashes, state, or promotion fields."}; OUTPUT.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"final reproducer matrix r2: {passed}/{len(results)} domains in {total:.3f}s; {OUTPUT.relative_to(ROOT)} {sha(OUTPUT)}"); return 0 if passed==len(results) else 1
if __name__=="__main__": raise SystemExit(main())
