"""Run append-only CH05 integrated release r10 over current delivery hardening."""
from __future__ import annotations
import hashlib,json,re,subprocess,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; BASE=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r9.json"; OUTPUT=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r10.json"
COMMANDS=["src/north_garden/validate_ch05_overnight_integrated_release_gate_r9.py","src/north_garden/validate_ch05_chapter_production_duration_capacity.py","src/north_garden/validate_ch05_chapter_production_operating_playbook.py","src/north_garden/validate_ch05_overnight_delivery_bundle_r2.py","src/north_garden/validate_ch05_owner_review_index_r6.py","src/north_garden/validate_ch05_review_artifact_link_manifest_r4.py","src/north_garden/validate_ch05_production_cost_ledger_r27.py","src/north_garden/validate_frozen_gauntlet_baseline_integrity.py","src/north_garden/validate_tracked_source_scope.py"]
NORMALIZED={"src/north_garden/validate_tracked_source_scope.py":"decimal count in '<N> tracked safe-source paths' only"}
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def normalize(path,text):
    if path in NORMALIZED: return re.sub(r"\d+ tracked safe-source paths","<LIVE_COUNT> tracked safe-source paths",text)
    return text
def main():
    results=[]; started=time.perf_counter()
    for i,relative in enumerate(COMMANDS,1):
        p=ROOT/relative; t=time.perf_counter(); done=subprocess.run([sys.executable,str(p)],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=600); elapsed=time.perf_counter()-t; raw=done.stdout.replace("\r\n","\n").strip()+"\n"; stdout=normalize(relative,raw); results.append({"path":relative,"script_sha256":sha(p),"command":f"python {relative}","network_capable":False,"normalization":NORMALIZED.get(relative),"return_code":done.returncode,"elapsed_seconds":round(elapsed,6),"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"stderr":done.stderr.replace("\r\n","\n")}); print(f"[{i}/{len(COMMANDS)}] {'PASS' if done.returncode==0 else 'FAIL'} {relative} {elapsed:.3f}s")
    total=time.perf_counter()-started; passed=sum(x["return_code"]==0 for x in results); out={"record_type":"CH05OvernightIntegratedReleaseGate","schema_version":"1.9","record_id":"ng-ch05-overnight-integrated-release-gate-r10","state":"PASS" if passed==len(results) else "FAIL","medium":"comic","comic_panel_plan_revision_created":False,"animation_shot_plan":None,"e_conte":None,"supersedes":{"record_id":"ng-ch05-overnight-integrated-release-gate-r9","path":BASE.relative_to(ROOT).as_posix(),"sha256":sha(BASE)},"summary":{"base_effective_command_count":58,"extension_command_count":8,"effective_command_count":66,"orchestrator_commands":9,"passed":passed,"failed":9-passed,"observed_total_seconds":round(total,6),"normalized_live_diagnostics":1,"network_capable_commands":0,"provider_calls":0,"uploads":0,"downloads":0,"cost_usd":0,"accepted_candidates":0,"commercially_cleared_candidates":0,"executable_panels":0,"owner_decisions":0,"human_review_minutes":None},"results":results,"effective_state":{"candidates":29,"comic_panel_plans":50,"sequence_batches":12,"review_links":117,"current_owner_hub_links":5,"strongest_candidates":14,"route_decisions":10,"pilot_owner_roots":6,"resolved_pilot_roots":0,"production_prompts":0,"prerender_artifacts_built":0,"lifecycle_states":11,"chapter_batches_entered":1,"chapter_batches_not_entered":11,"chapter_review_artifacts_planned":49,"remaining_planning_candidates":49,"fresh_arm_candidates":68,"operating_steps":12,"shell_validation_commands":11,"zero_cost_milestones":68,"frozen_paths":16,"baseline_paths":4},"boundaries":["Historical r9 remains immutable; r10 adds eight independently validated current-delivery domains.","Only the live decimal tracked-path diagnostic is normalized; scope semantics, exit code, all other stdout, scripts, and input evidence remain exact.","All commands are local/no-network and keep production prompt, render, review, and promotion state closed.","Passing does not authorize upload, generation, candidate acceptance, rights clearance, exact-base selection, or a ComicPanelPlan revision."]}; OUTPUT.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"integrated release r10: {passed}/9 commands, 66 effective checks in {total:.3f}s; {OUTPUT.relative_to(ROOT)} {sha(OUTPUT)}"); return 0 if passed==9 else 1
if __name__=="__main__": raise SystemExit(main())
