"""Run append-only CH05 final-review integrated release r12."""
from __future__ import annotations
import hashlib, json, re, subprocess, sys, time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; BASE=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r11.json"; OUTPUT=ROOT/"docs/research/evidence/ch05-final-review-integrated-release-r12.json"; ATTEMPT1=ROOT/"docs/research/evidence/ch05-final-review-integrated-release-r12-attempt1.json"
COMMANDS=["src/north_garden/validate_ch05_integrated_release_r11_compatibility_r1.py","src/north_garden/validate_ch05_final_model_license_provenance_audit.py","src/north_garden/validate_ch05_owner_response_schema_evidence.py","src/north_garden/validate_ch05_pilot_root_review_timer_contract.py","src/north_garden/validate_ch05_final_review_session_starter.py","src/north_garden/validate_ch05_owner_ingestion_preflight_contract.py","src/north_garden/validate_ch05_owner_review_index_r8.py","src/north_garden/validate_ch05_review_artifact_link_manifest_r6.py","src/north_garden/validate_ch05_production_cost_ledger_r29.py","src/north_garden/validate_frozen_gauntlet_baseline_integrity.py","src/north_garden/validate_tracked_source_scope.py"]
NORMALIZED={"src/north_garden/validate_tracked_source_scope.py":"decimal tracked-path diagnostic only"}
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def normalize(path,text): return re.sub(r"\d+ tracked safe-source paths","<LIVE_COUNT> tracked safe-source paths",text) if path in NORMALIZED else text
def main():
    results=[]; started=time.perf_counter()
    for index,relative in enumerate(COMMANDS,1):
        path=ROOT/relative; tick=time.perf_counter(); done=subprocess.run([sys.executable,str(path)],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=1200); elapsed=time.perf_counter()-tick; raw=done.stdout.replace("\r\n","\n").strip()+"\n"; stdout=normalize(relative,raw); results.append({"path":relative,"arguments":[],"script_sha256":sha(path),"command":f"python {relative}","network_capable":False,"normalization":NORMALIZED.get(relative),"return_code":done.returncode,"elapsed_seconds":round(elapsed,6),"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"stderr":done.stderr.replace("\r\n","\n")}); print(f"[{index}/{len(COMMANDS)}] {'PASS' if done.returncode==0 else 'FAIL'} {relative} {elapsed:.3f}s")
    total=time.perf_counter()-started; passed=sum(row["return_code"]==0 for row in results); output={"record_type":"CH05FinalReviewIntegratedRelease","schema_version":"1.0","record_id":"ng-ch05-final-review-integrated-release-r12","state":"PASS" if passed==len(COMMANDS) else "FAIL","medium":"comic","comic_panel_plan_revision_created":False,"animation_shot_plan":None,"e_conte":None,"supersedes":{"record_id":"ng-ch05-overnight-integrated-release-gate-r11","path":BASE.relative_to(ROOT).as_posix(),"sha256":sha(BASE)},"summary":{"base_effective_command_count":74,"extension_command_count":10,"effective_command_count":84,"orchestrator_commands":11,"passed":passed,"failed":len(COMMANDS)-passed,"observed_total_seconds":round(total,6),"normalized_live_diagnostics":1,"network_capable_commands":0,"provider_calls":0,"uploads":0,"downloads":0,"cost_usd":0,"accepted_candidates":0,"commercially_cleared_candidates":0,"executable_panels":0,"owner_decisions_ingested":0,"response_files":0,"event_logs":0,"human_review_minutes":None},"results":results,"effective_state":{"candidates":29,"comic_panel_plans":50,"sequence_batches":12,"review_links":128,"current_owner_hub_links":6,"direct_closeout_links":67,"pilot_roots":6,"resolved_decisions":0,"remaining_planning_candidates":49,"fresh_arm_candidates":68,"safe_source_capture_paths":873,"zero_cost_milestones":82,"frozen_paths":16,"baseline_paths":4,"production_prompts":0,"accepted_candidates":0,"executable_panels":0},"boundaries":["R11 remains immutable; a narrow compatibility validator accepts only its one exact nested r10-lineage mismatch after later append-only commits.","Only the decimal live tracked-path diagnostic normalizes; no evidence inventory, hash, semantic state, or arbitrary stdout does.","All commands are local/no-network; owner inputs remain absent and ingestion/promotion gates remain closed.","Passing does not authorize upload, generation, ingestion, acceptance, commercial clearance, exact-base selection, or ComicPanelPlan revision."]}
    if OUTPUT.is_file() and not ATTEMPT1.exists():
        prior=json.loads(OUTPUT.read_text(encoding="utf-8"))
        if prior.get("state")=="FAIL": ATTEMPT1.write_text(json.dumps(prior,indent=2)+"\n",encoding="utf-8",newline="\n")
    OUTPUT.write_text(json.dumps(output,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"final review release r12: {passed}/{len(COMMANDS)} commands, 84 effective checks in {total:.3f}s; {OUTPUT.relative_to(ROOT)} {sha(OUTPUT)}"); return 0 if passed==len(COMMANDS) else 1
if __name__=="__main__": raise SystemExit(main())
