"""Run append-only integrated release r9 over post-r8 production hardening."""
from __future__ import annotations
import hashlib,json,subprocess,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; BASE=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r8.json"; COMPAT=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-r8-compatibility-r1.json"; OUTPUT=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r9.json"
COMMANDS=["src/north_garden/validate_ch05_overnight_integrated_release_r8_compat.py","src/north_garden/validate_ch05_final_evidence_reproducer_matrix.py","src/north_garden/validate_ch05_p010_p013_owner_unlock_contract.py","src/north_garden/validate_ch05_p010_p013_prompt_blueprint.py","src/north_garden/validate_ch05_prompt_blueprint_adversarial_fixtures.py","src/north_garden/validate_ch05_p010_p013_prerender_packet_blueprint.py","src/north_garden/validate_ch05_p010_p013_lifecycle_state_machine.py","src/north_garden/validate_ch05_chapter_batch_lifecycle_application.py","src/north_garden/validate_ch05_owner_review_index_r5.py","src/north_garden/validate_ch05_review_artifact_link_manifest_r3.py"]
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
    results=[]; started=time.perf_counter()
    for i,relative in enumerate(COMMANDS,1):
        p=ROOT/relative; t=time.perf_counter(); done=subprocess.run([sys.executable,str(p)],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=600); elapsed=time.perf_counter()-t; stdout=done.stdout.replace("\r\n","\n").strip()+"\n"; results.append({"path":relative,"script_sha256":sha(p),"command":f"python {relative}","network_capable":False,"return_code":done.returncode,"elapsed_seconds":round(elapsed,6),"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"stderr":done.stderr.replace("\r\n","\n")}); print(f"[{i}/{len(COMMANDS)}] {'PASS' if done.returncode==0 else 'FAIL'} {relative} {elapsed:.3f}s")
    total=time.perf_counter()-started; passed=sum(x["return_code"]==0 for x in results); out={"record_type":"CH05OvernightIntegratedReleaseGate","schema_version":"1.8","record_id":"ng-ch05-overnight-integrated-release-gate-r9","state":"PASS" if passed==len(results) else "FAIL","medium":"comic","comic_panel_plan_revision_created":False,"animation_shot_plan":None,"e_conte":None,"supersedes":{"record_id":"ng-ch05-overnight-integrated-release-gate-r8","path":BASE.relative_to(ROOT).as_posix(),"sha256":sha(BASE)},"base_compatibility":{"path":COMPAT.relative_to(ROOT).as_posix(),"sha256":sha(COMPAT),"state":"PASS_NARROW_DYNAMIC_DIAGNOSTIC_NORMALIZATION"},"summary":{"base_effective_command_count":49,"extension_command_count":9,"effective_command_count":58,"orchestrator_commands":10,"passed":passed,"failed":10-passed,"observed_total_seconds":round(total,6),"network_capable_commands":0,"provider_calls":0,"uploads":0,"downloads":0,"cost_usd":0,"accepted_candidates":0,"commercially_cleared_candidates":0,"executable_panels":0,"owner_decisions":0,"human_review_minutes":None},"results":results,"effective_state":{"candidates":29,"comic_panel_plans":50,"sequence_batches":12,"review_links":112,"owner_hub_links":7,"pilot_owner_roots":6,"resolved_pilot_roots":0,"prompt_blueprint_rows":4,"production_prompts":0,"adversarial_fixtures_rejected":28,"prerender_artifacts_planned":5,"prerender_artifacts_built":0,"lifecycle_states":11,"lifecycle_legal_edges":11,"lifecycle_illegal_pairs":110,"chapter_batches_entered":1,"chapter_batches_not_entered":11,"chapter_review_artifacts_planned":49,"final_reproducer_domains":7,"safe_source_capture_paths":735,"frozen_paths":16,"baseline_paths":4,"zero_cost_milestones":54},"boundaries":["Historical r8 remains immutable; r9 uses its narrow compatibility evidence as the 49-check base.","All extensions are local/no-network and keep production prompt, render, review, and promotion state closed.","Passing does not authorize upload, generation, candidate acceptance, rights clearance, exact-base selection, or a ComicPanelPlan revision."]}; OUTPUT.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"integrated release r9: {passed}/10 commands, 58 effective checks in {total:.3f}s; {OUTPUT.relative_to(ROOT)} {sha(OUTPUT)}"); return 0 if passed==10 else 1
if __name__=="__main__": raise SystemExit(main())
