"""Run append-only integrated release r7 over post-r6 CH05 evidence."""
from __future__ import annotations
import hashlib,json,subprocess,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];BASE=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r6.json";OUTPUT=ROOT/"docs/research/evidence/ch05-overnight-integrated-release-gate-r7.json"
COMMANDS=["src/north_garden/validate_ch05_overnight_integrated_release_gate_r6.py","src/north_garden/validate_ch05_chapter_sequence_production_batches.py","src/north_garden/validate_ch05_lettering_semantics_readiness_matrix.py","src/north_garden/validate_ch05_owner_review_index_r4.py","src/north_garden/validate_ch05_review_artifact_link_manifest_r2.py"]
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def main()->int:
 base=json.loads(BASE.read_text(encoding="utf-8"));results=[];start_all=time.perf_counter()
 for i,relative in enumerate(COMMANDS,1):
  p=ROOT/relative;start=time.perf_counter();done=subprocess.run([sys.executable,str(p)],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=300);elapsed=time.perf_counter()-start;stdout=done.stdout.replace("\r\n","\n").strip()+"\n";results.append({"path":relative,"script_sha256":sha(p),"command":f"python {relative}","network_capable":False,"return_code":done.returncode,"elapsed_seconds":round(elapsed,6),"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"stderr":done.stderr.replace("\r\n","\n")});print(f"[{i}/{len(COMMANDS)}] {'PASS' if done.returncode==0 else 'FAIL'} {relative} {elapsed:.3f}s")
 total=time.perf_counter()-start_all;passed=sum(x["return_code"]==0 for x in results)
 evidence={"record_type":"CH05OvernightIntegratedReleaseGate","schema_version":"1.6","record_id":"ng-ch05-overnight-integrated-release-gate-r7","state":"PASS" if passed==len(COMMANDS) else "FAIL","medium":"comic","comic_panel_plan_revision_created":False,"animation_shot_plan":None,"e_conte":None,"supersedes":{"record_id":base["record_id"],"path":BASE.relative_to(ROOT).as_posix(),"sha256":sha(BASE)},"summary":{"base_effective_command_count":42,"extension_command_count":4,"effective_command_count":46,"orchestrator_commands":len(COMMANDS),"passed":passed,"failed":len(COMMANDS)-passed,"observed_total_seconds":round(total,6),"network_capable_commands":0,"provider_calls":0,"uploads":0,"downloads":0,"cost_usd":0,"accepted_candidates":0,"executable_panels":0,"owner_decisions":0,"human_review_minutes":None},"results":results,"effective_state":{"candidates":29,"comic_panel_plans":50,"sequence_batches":12,"sequence_size_min":3,"sequence_size_max":5,"planned_sequence_artifacts":48,"lettering_silent_inserts":16,"lettering_protected_action":14,"lettering_caption_or_silence":13,"lettering_speech_or_reaction":6,"lettering_attributed_unbound":1,"review_links":105,"owner_hub_links":6,"owner_tasks":24,"next_prompts":0,"frozen_paths":16,"baseline_paths":4},"boundaries":["R6 remains immutable; r7 preserves 42 effective checks and adds sequence, lettering, owner-hub, and exact-link validators.","All commands are local and non-network-capable.","Passing does not bind copy, ingest review, compile prompts, upload, accept art, revise plans, or grant commercial clearance."]}
 OUTPUT.write_text(json.dumps(evidence,indent=2)+"\n",encoding="utf-8",newline="\n");print(f"integrated release r7: {passed}/{len(COMMANDS)} orchestrator commands, 46 effective checks in {total:.3f}s; {OUTPUT.relative_to(ROOT)} {sha(OUTPUT)}");return 0 if passed==len(COMMANDS) else 1
if __name__=="__main__":raise SystemExit(main())
