"""Run compact final CH05 review reproducer matrix r3."""
from __future__ import annotations
import hashlib,json,re,subprocess,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; OUTPUT=ROOT/"docs/research/evidence/ch05-final-review-reproducer-matrix-r3.json"
COMMANDS=["src/north_garden/validate_ch05_final_review_integrated_release_r12.py","src/north_garden/validate_ch05_final_safe_source_parity_r4.py","src/north_garden/validate_ch05_overnight_closeout_bundle_r3.py","src/north_garden/validate_ch05_final_handoff_consistency_matrix.py","src/north_garden/validate_ch05_strongest_candidate_disposition_worksheet.py","src/north_garden/validate_ch05_owner_review_index_r9.py","src/north_garden/validate_ch05_review_artifact_link_manifest_r7.py","src/north_garden/validate_frozen_gauntlet_baseline_integrity.py","src/north_garden/validate_tracked_source_scope.py","src/north_garden/validate_ch05_final_remote_parity_r2.py"]
NORMALIZED={"src/north_garden/validate_ch05_final_safe_source_parity_r4.py":"decimal tracked-path diagnostic only","src/north_garden/validate_tracked_source_scope.py":"decimal tracked-path diagnostic only"}
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def normalize(path,text):return re.sub(r"\d+ tracked safe-source paths","<LIVE_COUNT> tracked safe-source paths",text) if path in NORMALIZED else text
def main():
    results=[]; started=time.perf_counter()
    for index,relative in enumerate(COMMANDS,1):
        path=ROOT/relative; tick=time.perf_counter(); done=subprocess.run([sys.executable,str(path)],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=1800); elapsed=time.perf_counter()-tick; raw=done.stdout.replace("\r\n","\n").strip()+"\n"; stdout=normalize(relative,raw); results.append({"domain":Path(relative).stem.removeprefix("validate_ch05_").removeprefix("validate_"),"path":relative,"arguments":[],"script_sha256":sha(path),"network_capable":False,"normalization":NORMALIZED.get(relative),"return_code":done.returncode,"elapsed_seconds":round(elapsed,6),"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"stderr":done.stderr.replace("\r\n","\n")}); print(f"[{index}/{len(COMMANDS)}] {'PASS' if done.returncode==0 else 'FAIL'} {relative} {elapsed:.3f}s")
    total=time.perf_counter()-started; passed=sum(row["return_code"]==0 for row in results); output={"record_type":"CH05FinalReviewReproducerMatrix","schema_version":"3.0","record_id":"ng-ch05-final-review-reproducer-matrix-r3","state":"PASS" if passed==10 else "FAIL","medium":"comic","summary":{"domains":10,"commands":10,"passed":passed,"failed":10-passed,"observed_total_seconds":round(total,6),"normalized_live_diagnostics":2,"network_capable_commands":0,"candidates":29,"plans":50,"batches":12,"review_links":134,"priority_links":67,"worksheet_checks":112,"release_checks":84,"safe_paths":934,"zero_cost_milestones":82,"frozen_paths":16,"baseline_paths":4,"provider_calls":0,"uploads":0,"owner_decisions_ingested":0,"accepted":0,"commercially_cleared":0,"executable":0,"paid_spend_usd":0,"human_review_minutes":None},"results":results,"animation_shot_plan":None,"e_conte":None,"boundary":"Local no-network final review reproduction. Two narrow normalizations affect only live decimal tracked-path diagnostics; no inventory, hash, semantic state, or authority field is normalized."}; OUTPUT.write_text(json.dumps(output,indent=2)+"\n",encoding="utf-8",newline="\n"); print(f"final review reproducer r3: {passed}/10 domains in {total:.3f}s; {OUTPUT.relative_to(ROOT)} {sha(OUTPUT)}"); return 0 if passed==10 else 1
if __name__=="__main__":raise SystemExit(main())
