"""Run final CH05 integrated release r13."""
from __future__ import annotations
import hashlib,json,re,subprocess,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];BASE=ROOT/"docs/research/evidence/ch05-final-review-reproducer-matrix-r3.json";OUTPUT=ROOT/"docs/research/evidence/ch05-final-integrated-release-r13.json"
COMMANDS=["src/north_garden/validate_ch05_final_review_reproducer_matrix_r3.py","src/north_garden/validate_ch05_post_reproducer_safe_source_parity_r5.py","src/north_garden/validate_ch05_completion_readiness_audit.py","src/north_garden/validate_ch05_production_cost_ledger_r30.py","src/north_garden/validate_ch05_owner_review_index_r9.py","src/north_garden/validate_ch05_review_artifact_link_manifest_r7.py","src/north_garden/validate_frozen_gauntlet_baseline_integrity.py","src/north_garden/validate_tracked_source_scope.py","src/north_garden/validate_ch05_final_remote_parity_r2.py"]
NORMALIZED={"src/north_garden/validate_ch05_post_reproducer_safe_source_parity_r5.py":"decimal tracked-path diagnostic only","src/north_garden/validate_tracked_source_scope.py":"decimal tracked-path diagnostic only"}
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def normalize(path,text):return re.sub(r"\d+ tracked safe-source paths","<LIVE_COUNT> tracked safe-source paths",text) if path in NORMALIZED else text
def main():
    results=[];started=time.perf_counter()
    for index,relative in enumerate(COMMANDS,1):
        path=ROOT/relative;tick=time.perf_counter();done=subprocess.run([sys.executable,str(path)],cwd=ROOT,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=1800);elapsed=time.perf_counter()-tick;raw=done.stdout.replace("\r\n","\n").strip()+"\n";stdout=normalize(relative,raw);results.append({"path":relative,"arguments":[],"script_sha256":sha(path),"network_capable":False,"normalization":NORMALIZED.get(relative),"return_code":done.returncode,"elapsed_seconds":round(elapsed,6),"stdout":stdout,"stdout_sha256":hashlib.sha256(stdout.encode()).hexdigest(),"stderr":done.stderr.replace("\r\n","\n")});print(f"[{index}/{len(COMMANDS)}] {'PASS' if done.returncode==0 else 'FAIL'} {relative} {elapsed:.3f}s")
    total=time.perf_counter()-started;passed=sum(row["return_code"]==0 for row in results);output={"record_type":"CH05FinalIntegratedRelease","schema_version":"1.0","record_id":"ng-ch05-final-integrated-release-r13","state":"PASS" if passed==9 else "FAIL","medium":"comic","base":{"path":BASE.relative_to(ROOT).as_posix(),"sha256":sha(BASE),"domains":10},"summary":{"base_domains":10,"extension_domains":8,"effective_domains":18,"orchestrator_commands":9,"passed":passed,"failed":9-passed,"observed_total_seconds":round(total,6),"normalized_live_diagnostics":2,"network_capable_commands":0,"candidates":29,"plans":50,"batches":12,"review_links":134,"priority_links":67,"worksheet_checks":112,"release_checks":84,"safe_paths":971,"zero_cost_milestones":91,"frozen_paths":16,"baseline_paths":4,"provider_calls":0,"uploads":0,"owner_inputs":0,"owner_decisions_ingested":0,"visual_dispositions":0,"accepted":0,"commercially_cleared":0,"executable":0,"paid_spend_usd":0,"human_review_minutes":None},"results":results,"animation_shot_plan":None,"e_conte":None,"boundary":"Final local/no-network integrated handoff gate. Passing proves delivery integrity only and grants no generation, upload, owner ingestion, acceptance, rights, exact-base, or production authority."};OUTPUT.write_text(json.dumps(output,indent=2)+"\n",encoding="utf-8",newline="\n");print(f"final integrated release r13: {passed}/9 commands, 18 effective domains in {total:.3f}s; {OUTPUT.relative_to(ROOT)} {sha(OUTPUT)}");return 0 if passed==9 else 1
if __name__=="__main__":raise SystemExit(main())
