"""Validate current CH05 final review evidence and Git remote parity."""
from __future__ import annotations
import copy, json, subprocess, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; SAFE=ROOT/"docs/research/evidence/ch05-final-safe-source-parity-r4.json"; RELEASE=ROOT/"docs/research/evidence/ch05-final-review-integrated-release-r12.json"; CLOSEOUT=ROOT/"docs/research/evidence/ch05-overnight-closeout-bundle-r3.json"; CONSISTENCY=ROOT/"docs/research/evidence/ch05-final-handoff-consistency-matrix-r1.json"; LINKS=ROOT/"production/comic/review/ch05-review-artifact-link-manifest-r7.json"
def git(*args):return subprocess.run(["git",*args],cwd=ROOT,check=True,capture_output=True,text=True).stdout.strip()
def errors(state):
    expected={"branch":"main","remote":"https://github.com/LoFiGamerGuy/visual-narrative-compiler.git","head_origin_parity":True,"safe_capture_ancestor":True,"safe_paths":934,"release_checks":84,"closeout_links":128,"consensus_facts":12,"unexplained_conflicts":0,"current_links":134,"frozen_pass":True,"tracked_scope_pass":True,"provider_calls":0,"uploads":0,"ingested":0,"accepted":0,"commercially_cleared":0,"executable":0}; return [] if state==expected else ["remote/evidence state invalid"]
def main():
    safe=json.loads(SAFE.read_text(encoding="utf-8")); release=json.loads(RELEASE.read_text(encoding="utf-8")); closeout=json.loads(CLOSEOUT.read_text(encoding="utf-8")); closeout_bundle=json.loads((ROOT/closeout["bundle"]["path"]).read_text(encoding="utf-8")); consistency=json.loads(CONSISTENCY.read_text(encoding="utf-8")); links=json.loads(LINKS.read_text(encoding="utf-8")); head=git("rev-parse","HEAD"); origin=git("rev-parse","origin/main"); frozen=subprocess.run([sys.executable,"src/north_garden/validate_frozen_gauntlet_baseline_integrity.py"],cwd=ROOT,capture_output=True,text=True); tracked=subprocess.run([sys.executable,"src/north_garden/validate_tracked_source_scope.py"],cwd=ROOT,capture_output=True,text=True); state={"branch":git("branch","--show-current"),"remote":git("remote","get-url","origin"),"head_origin_parity":head==origin,"safe_capture_ancestor":subprocess.run(["git","merge-base","--is-ancestor",safe["captured_commit"],head],cwd=ROOT).returncode==0,"safe_paths":safe["summary"]["tracked_paths"],"release_checks":release["summary"]["effective_command_count"],"closeout_links":closeout["summary"]["review_links"],"consensus_facts":consistency["summary"]["consistent_facts"],"unexplained_conflicts":consistency["summary"]["unexplained_conflicts"],"current_links":links["effective_unique_artifact_count"],"frozen_pass":frozen.returncode==0 and not frozen.stderr,"tracked_scope_pass":tracked.returncode==0 and not tracked.stderr,"provider_calls":closeout_bundle["activity"]["provider_calls"],"uploads":closeout_bundle["activity"]["uploads"],"ingested":closeout_bundle["activity"]["owner_decisions_ingested"],"accepted":closeout_bundle["activity"]["accepted"],"commercially_cleared":closeout_bundle["activity"]["commercially_cleared"],"executable":closeout_bundle["activity"]["executable"]}; failures=errors(state); mutations=[]
    for key in state:
        altered=copy.deepcopy(state); altered[key]=not altered[key] if isinstance(altered[key],bool) else -1; mutations.append(altered)
    rejected=sum(bool(errors(altered)) for altered in mutations)
    if rejected!=len(mutations):failures.append(f"only {rejected}/{len(mutations)} mutations rejected")
    print(f"CH05 final remote parity r2: {len(failures)} failures; main/origin exact; release84/source934/closeout128/current-links134; frozen/scope pass; {rejected}/{len(mutations)} mutations rejected")
    for failure in failures:print(f"FAIL: {failure}")
    return 1 if failures else 0
if __name__=="__main__":raise SystemExit(main())
