from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[2];P=R/'production/encounter-lab'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
rows=json.loads((P/'candidates.json').read_text())['candidates'];by={x['attempt_id']:x for x in rows}
s=json.loads((P/'selected.json').read_text())
for c in rows:
 if c['attempt_id'].endswith('-F1') and c['id'] not in ['NG03','X03']:s['selected'][c['id']]=c['attempt_id']
s['selected']['NG03']='NG03-R1';s['selected']['X03']='X03-P'
(P/'selected.json').write_text(json.dumps(s,indent=2)+'\n')
obs={
'NG01':['The low weapon crossing and opposed stances establish the duel clearly. The finish calms paving and walls while retaining the cyan contact and intact opening guard.','This opening already shows contact; anticipation and the precise feint remain more implied than demonstrated. Outer feet are cropped.'],
'NG02':['Close framing makes the broken guard and strained face readable. The selected finish reduces cloth and ground noise.','The two visible glaive grip sections do not establish one unambiguous continuous shaft.'],
'NG03':['The repair moves cyan contact onto the haft and frees the blade tip, improving the reversal over the primary.','The actual haft-to-shoulder transfer is still not shown convincingly, and both guards appear cracked. Reviewers differed about handedness certainty; it is not certified.','The cleaner F1 reduces the explicitly protected shoulder burst to a small glint. R1 remains the default; F1 is retained in history with this weakened impact cue.'],
'NG04':['Separated, tired characters and the dropped glaive communicate a costly aftermath. The finish substantially quiets paving and architecture.','The damaged upper-arm skin opening is broader than the earlier forearm injury; exact damage continuity is imperfect. The quieter F1 floor also appears more polished and reflective.'],
'BP01':['The foundational repair restores an intact opening coat and clearer right-hand estoc. The finish preserves those changes and quiets ivory and paving.','The ineffective body strike that should teach the creature rule is not directly shown; the blade lies near a ground tendon instead.'],
'BP02':['The huge near claw, low escape and torn coat convey immediate threat. Finishing reduces the competing ivory crack network.','The creature silhouette remains imposing but its complete support anatomy is not established in this tight framing.'],
'BP03':['The separated dark tendon ends and raised claw make the target readable. The finish preserves the gap while calming floor and ivory.','The sword appears in the opposite hand from the opening, and an additional grounded ivory support complicates creature continuity. A full collapse is not yet visible.'],
'BP04':['The fallen mask, severed tendons and standing character give a strong quiet consequence. The finish preserves the coat tear and distant threat shape.','The exact limb construction and the causal importance of the tendon still need interpretation from the adjacent images.'],
'IO01':['The repair establishes four visible support legs and intact opening guards. The finish retains the brace and broad warm painting while reducing weathering.','The first beat already contains a locked collision rather than a separate anticipation pose.'],
'IO02':['The sliding boot near the canal and broken left guard show pressure and cost. Finishing removes distracting small scuffs and surface marks.','The broken forearm-to-hand chain is awkward, even though the overall effort reads.'],
'IO03':['A wide stance and collapsing front support make the balance change visible. The finish reduces airborne specks and ground noise.','This is a front collapse, not the requested full flank roll. Camera position stays close to the opening, and the shoulder break reads as cracking rather than a dent.'],
'IO04':['The seated fighter and fallen boar communicate weight, exhaustion and relief. The finish preserves the broad damage while calming rust and paving.','The complex collapsed creature plates make exact limb continuity difficult to verify; some mottling remains.'],
'ST01':['The grounded first impact reads strongly and the existing finish is relatively calm.','The mark is on the apparent right forearm rather than the planned left. R1 did not establish the correction and made the ring more complex; P remains the default.'],
'ST02':['The oversized passing fist, ducking head and expressive face give one of the clearest movement beats.','This frame puts the mark on the left rear arm, unlike the opening. A readable dodge does not establish the delayed-mark rule consistently.'],
'ST03':['The low physical sweep, opening hand and body lean read energetically; F1 keeps the contact while simplifying armor and dust.','The mark returns to the apparent right arm. The shaft meets the lower leg rather than clearly hooking behind the knee.'],
'ST04':['Laughter and the heavy seated opponent give the encounter personality and breathing room. Finishing preserves the expressions and visible hammer wear.','The specific hammer chip has become broader scuffing, and some mottled floor texture remains.'],
'SB01':['The selected repair restores the intact opening cape while preserving one spearhead and the high deflection.','This establishes a defense more clearly than it establishes the separate limitation of the power.'],
'SB02':['The repair removes the duplicate spearhead and the stray high active fire contact. The burned cape and startled face communicate the counter.','The low front continues off the right edge and its middle path is partly occluded; continued reachability is uncertain.'],
'SB03':['The low spear stance, large flame gesture and recoiling caster suggest a reversal.','The flame forms a branching shape near the caster rather than a continuous incoming path turning at the spearhead and returning. The intended rule is not demonstrated reliably.'],
'SB04':['The hurt caster and persistent cape burn make the consequence readable. F1 calms architecture and ground while keeping the charred trail.','The foreground scorch remains locally granular. A clear aftermath does not repair the preceding return-path ambiguity.'],
'X01':['Closer faces and crossed weapons heighten strain. The finish removes pervasive armor scratches while retaining contact and expressions.','This is primarily a close framing experiment, not full graphic abstraction. Both rival hands grip the weapon again, unlike the linked disarm moment. F1 smooths a conspicuous chipped edge on the raised sword-arm guard; that was already doubtful injury placement, so this changed damage is a finishing tradeoff rather than proven continuity improvement.'],
'X02':['The overhead claw and dark framing create strong scale pressure. F1 leaves a much calmer ground plane.','The blade hits a dark junction instead of showing the clean separated gap of BP03. Weapon hand and extent of coat damage differ from the opening.'],
'X03':['Extreme foreshortening and the huge near boot make this a useful radical comparison.','The hammer head meets the lower leg, not the intended shaft-to-knee sweep; the arm mark remains inconsistent.','F1 greatly calms armor and ground but erases visible pale damage on the orange hammer face. P remains the default to preserve this story detail; both attempts are available.'],
'X04':['The huge high and low fire lanes create a much stronger sense of encounter scale.','The low lane ends near the greave while the upper lane meets the raised spear. Those separate contacts do not form a readable single-point redirected loop.']}
notes={'schema':'EncounterLabReviewNotes/1','experiment_id':'EN-20260909-01','owner_approval':None,'entries':{}}
for id,aid in s['selected'].items():notes['entries'][id]={'attempt_id':aid,'sha256':by[aid]['sha256'],'observations':obs[id]}
(P/'review-notes.json').write_text(json.dumps(notes,indent=2)+'\n')
report={'schema':'EncounterLabRootFinalNativeReview/1','experiment_id':'EN-20260909-01','owner_approval':None,'method':'Actual native images viewed in built-in tool returns and local original-size view_image; all five complete uncaptioned phone strips viewed at held primary dataset 0e4cd7d6d749. Final selected phone review follows separately. Earlier source-bound reports retained.','attempts':[],'sequence_findings':{'NG':'Contact, counter and recovery read; feint, stored beat and exact shoulder transfer remain inferred.','BP':'Threat, escape, tendon cut and fallen mask read; discovery of load-bearing rule is not visually taught clearly enough.','IO':'Brace, slipping cost, front collapse and rest read; promised flank roll and camera change did not arrive.','ST':'Hit, dodge, low trip and shared laughter read strongly; arm mark continuity does not.','SB':'High defense, cape burn, low response and hurt caster read; the return-path topology does not.'}}
for c in rows:
 a=c['attempt_id'];item={'attempt_id':a,'path':c['path'],'sha256':c['sha256'],'native_inspected':True,'selected_for_review':s['selected'][c['id']]==a,'observations':obs[c['id']]}
 if a.endswith('-F1'):
  call=json.loads((R/c['call_path']).read_text());item['actual_source_references']=call['references'];item['finish_decision']='retained-history-regression' if c['id'] in ['NG03','X03'] else 'provisional-display-after-native-comparison';item['surface_result']='Broader calmer surfaces; no major identity, pose or contact regression observed, except the explicitly recorded NG03 weakened shoulder burst, X03 hammer damage loss and X01 smoothed guard chip; NG04 also appears more polished at ground level.'
 report['attempts'].append(item)
(R/'research/encounter-lab/root-native-review-final.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps({'native_attempts':len(rows),'selected_finishes':sum(x.endswith('-F1') for x in s['selected'].values()),'qualified_notes':len(notes['entries'])}))
