import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const script=readFileSync(new URL('../../../docs/encounter-lab/preferences.js',import.meta.url),'utf8');
const dims=['overall','drawing','impact','movement','power','causality','anatomy','scale','ground','texture'];
const sequences=['NG','BP','IO','ST','SB'].map(id=>({id,panel_ids:[1,2,3,4].map(i=>id+'0'+i)}));
const entries=[...sequences.flatMap(s=>s.panel_ids),...['X01','X02','X03','X04']].map(id=>({id,category:id[0]==='X'?'radical':'encounter',candidate:id==='SB04'?null:{attempt_id:id+'-P',sha256:'a'.repeat(64)}}));
const data={experiment_id:'EN-test',dataset_sha256:'d'.repeat(64),plan_sha256:'p'.repeat(64),entries,sequences,categories:['encounter','radical'].map(id=>({id,dimensions:dims})),source_bindings:entries.map(e=>({id:e.id,attempt_id:e.candidate?.attempt_id??null,sha256:e.candidate?.sha256??null}))};
const local=new Map();function make(d=data){const ctx={window:{},document:{getElementById:()=>({textContent:''})},localStorage:{getItem:k=>local.get(k),setItem:(k,v)=>local.set(k,v)},structuredClone,Date,Map,Set,JSON};vm.runInNewContext(script,ctx);return ctx.window.EncounterLabPreferences(d,()=>{})}
const s=make(),blank=s.exportChoices();assert.equal(Object.keys(blank.choices).length,24);assert.equal(Object.keys(blank.sequence_choices).length,5);assert(Object.values(blank.choices).every(c=>Object.values(c.ratings).every(v=>v===null)));assert(Object.values(blank.sequence_choices).every(c=>Object.values(c.ratings).every(v=>v===null)));
s.update('NG01','impact','like');s.updateSequence('NG','comprehension','yes');s.updateSequence('NG','continuity','unsure');s.updateSequence('BP','shortlist',true);assert.equal(s.get('NG02').ratings.impact,null);assert.equal(s.getSequences().IO.ratings.comprehension,null);assert.equal(s.updateSequence('SB','comprehension','yes'),false);assert.equal(s.update('SB04','overall','like'),false);const saved=s.exportChoices();assert.deepEqual(make().exportChoices().choices,saved.choices);assert.deepEqual(make().getSequences(),saved.sequence_choices);
const cases={dataset:x=>x.dataset_sha256='old',plan:x=>x.plan_sha256='old',schema:x=>x.schema='ImpactClarityChoices/1',binding:x=>x.source_bindings[0].sha256='old',order:x=>x.source_bindings.reverse(),extra:x=>x.owner_approval=true,dimension:x=>x.choices.NG01.ratings.extra='like',missing:x=>delete x.choices.NG01.ratings.scale,pending:x=>x.choices.SB04.ratings.power='na',sequence_missing:x=>delete x.sequence_choices.NG,sequence_extra:x=>x.sequence_choices.X={},sequence_dimension:x=>x.sequence_choices.NG.ratings.appeal='yes',sequence_value:x=>x.sequence_choices.NG.ratings.continuity='like',pending_sequence:x=>x.sequence_choices.SB.ratings.comprehension='na',sequence_note:x=>x.sequence_choices.NG.note='x'.repeat(4001),missing_bindings:x=>x.source_bindings.pop()};
for(const [name,mutate]of Object.entries(cases)){const copy=structuredClone(saved);mutate(copy);assert.throws(()=>s.importChoices(copy),name);assert.deepEqual(s.exportChoices().choices,saved.choices,name);assert.deepEqual(s.getSequences(),saved.sequence_choices,name)}
s.importChoices(blank);assert.deepEqual(s.getAll(),blank.choices);assert.deepEqual(s.getSequences(),blank.sequence_choices);s.markUnavailable('NG01');assert.equal(s.updateSequence('NG','continuity','yes'),false);assert.equal(make({...data,dataset_sha256:'new'}).getSequences().NG.ratings.continuity,null);console.log(JSON.stringify({pass:true,panels:24,sequences:5,atomic_rejection_cases:Object.keys(cases).length,checks:['blank independence','pending images/sequence','unavailable source','exact binding','atomic import','persistence','changed dataset']}));
