"""Build small attributed research excerpts; this does not edit or generate project artwork."""
from pathlib import Path
import hashlib,json,shutil
from PIL import Image
R=Path(__file__).resolve().parents[3];D=Path(__file__).parent;L=D/'local';O=R/'docs/impact-clarity/combat-references';(O/'images').mkdir(parents=True,exist_ok=True)
S={
'boxer':('The Boxer','JH','https://www.webtoons.com/en/sports/the-boxer/list?title_no=2027','Episode 1 — The Genius','local/boxer-source.json'),
'goh6':('The God of High School','Yongje Park','https://www.webtoons.com/en/action/the-god-of-high-school/list?title_no=66','Episode 6','local/goh6-source.json'),
'gosu':('GOSU','Giun Ryu (story); Mun Jeong Hoo (art)','https://www.webtoons.com/en/action/gosu/list?title_no=1099','Episode 14 — The rosy-cheeked sword devil So Hong (4)','gosu-source.json'),
'solo3':('Solo Leveling','Chugong (author); DUBU / REDICE STUDIO (art)','https://yenpress.com/titles/9781975336523-solo-leveling-vol-3-comic','Volume 3 — publisher Look inside preview',None),
 'towerlater':('Tower of God','SIU','https://www.webtoons.com/en/fantasy/tower-of-god/list?title_no=95','Season 2, Episode 304','local/towerlater-source.json'),
'jungle':('Jungle Juice','Hyeong Eun (story); JUDER (art)','https://www.webtoons.com/en/action/jungle-juice/list?title_no=2480','Episode 1','local/jungle-source.json'),
'orv':('Omniscient Reader','singNsong (original); UMI (adaptation); Sleepy-C (art)','https://www.webtoons.com/en/action/omniscient-reader/list?title_no=2154','Episode 0 — Prologue','local/orv-source.json'),
'doom':('Doom Breaker','Blue-Deep','https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197','Episode 1','doom-source.json')}
# Excerpts deliberately omit most dialogue and the rest of each episode. No redraw, retouch, enhancement or style transformation.
A=[
('boxer',52,(0,420,700,1000),'The face takes the punch','Contact','One blue glove, a compressed face and a black field. The target carries the impact; the setting contributes almost nothing.','Try a close peak-impact cut with deformed cheeks, rotated head and compressed shoulder. Keep only contact-bearing spray.','The contact crop does not explain the whole exchange; inspect the official episode for setup.'),
('boxer',51,(0,125,700,915),'A body slips out of the line','Evasion','Overhead angle separates a committed red-glove strike from the folded white-haired body. Diagonal speed lines replace floor detail.','Use the attacker’s reach to make the defender’s narrow escape measurable.','Dense lines are purposeful direction here, but their density may still exceed your comfort.'),
('goh6',14,(0,480,700,1000),'The throw has a center','Body mechanics','The airborne figure rotates around a planted thrower. One pale arc and one shadow describe the turn on quiet white ground.','Show a planted pivot and displaced center of mass instead of two hovering fighters.','The small figures trade facial acting for complete mechanical readability.'),
('goh6',18,(0,100,700,460),'The opponent becomes a projectile','Consequence','A stretched airborne body crosses a horizontal field; the environment becomes long bands aligned with travel.','Make the struck body’s trajectory dominate, with loose limbs lagging behind the torso.','The blow itself is outside this excerpt; this is a consequence reference.'),
('gosu',21,(0,90,700,1180),'Contact, then separation','Contact','A close guard impact is followed by separated fighters and a single large white shock shape. The broad blue field stays quiet.','Use a brief contact-to-recoil pair; preserve how the bodies separate, not only the flash.','A two-panel excerpt tests sequencing as well as the drawing; it is not a single-frame comparison.'),
('gosu',33,(0,45,700,1100),'A swing becomes a whole panel','Radical motion','Repeated sword-and-torso impressions and curved hatching turn the panel into one rotary movement.','Test a clearly intentional temporal smear for a special peak, with one readable terminal pose.','This is deliberately busy and distorts anatomy over time. Judge whether the motion is worth that cost.'),
('solo3',13,(0,55,830,415),'Speed cuts the monster into beats','Evasion','A monster’s orange mass is broken by sharp white-blue diagonals and small displaced fighter positions.','Let a repeated directional motif carry speed against broad creature color, without microtexturing the whole body.','The streaks do not alone prove a successful hit; this is an evasion-and-speed reference.'),
('solo3',15,(45,735,890,1290),'The teeth almost close','Threat','A huge open mouth and a tight face/teeth cut make danger personal. The background is largely warm flat color.','Alternate a readable size contrast with a close near-contact expression; keep the dangerous gap small.','The lower pair spans two moments. It demonstrates timing and proximity more than a complex ability.'),
('towerlater',23,(0,0,700,875),'The power owns the frame','Magic scale','A tiny readable fighter sits beneath a vast black sweep. A few cool wedges establish its direction and mass.','Allow a major ability to overwhelm the frame in one broad shape while retaining a small contrasting subject.','The source and target relationship needs adjacent panels; this excerpt alone is a scale image.'),
('towerlater',37,(0,65,700,1030),'Magic has a distinct shape language','Magic identity','Large yellow spheres with orbiting smaller forms read as a coherent family; a red cape marks the caster.','Design a power’s geometry and relative scale before adding particles or surface detail.','This is an ability reveal, not a demonstrated impact. The bright palette is an independent taste question.'),
('jungle',303,(0,0,800,685),'A rescue releases stored motion','Ability release','A compressed carrying pose explodes outward through large wing/light shapes, with buildings streaking past.','Tie a release to a concrete rescue and a carried person; make the emotional cost visible before the burst.','This rescue panel has intense bloom and line density. It is a useful boundary test, not a texture recommendation.'),
('jungle',256,(0,0,800,980),'The creature dives headfirst','Creature movement','The insect-like attacker folds into a steep downward spear; narrow highlights and vertical lines reinforce its fall.','Give monsters a recognizable attack posture with a committed direction and a readable leading body part.','The landing and victim are outside the excerpt. Darkness and line density may be too much for your preferred treatment.'),
('orv',36,(0,0,800,1000),'Collision reorganizes the space','Large impact','Two figures collide at the center of an enormous radial field of cracked mass and outward debris.','Borrow the single radial organization and large displaced slabs, then substantially reduce small fragments and glitter.','This is the densest reference here and deliberately tests your noise limit. Do not copy its texture density.'),
('orv',43,(0,0,800,1000),'A blade passes a face','Close conflict','A sharply tilted face sits immediately under the crossing weapon line; the crop removes safe distance.','Use expression, a tight dangerous gap and a tilted camera to make a near-miss physical.','Particles and prismatic highlights compete at the edges. The crop does not independently establish every grip.'),
('doom',11,(0,0,800,1000),'The body folds around the wound','Injury / cost','Bent legs, an arched torso and trailing blood make the strike a bodily event, even with much of the attacker outside frame.','Show the cost in a whole torso and failing leg structure, not only a wound decal or glow.','Injury and high effect density may be undesirable. This is a force/cost reference, not an endorsement of its detail load.'),
('doom',5,(0,0,800,1000),'A single axis makes a huge event','Power event','One vertical column of light dominates a broad orange field and a small rocky platform.','Use one dominant direction and a simple scale anchor for a large power event.','The caster and direct target are not visible; a bright beam alone is insufficient for our action-readability goal.')]
entries=[]
for n,(key,num,crop,title,kind,obs,adapt,limit) in enumerate(A,1):
 s=S[key];src=L/(('local/' if key in ['boxer','goh6','towerlater','jungle','orv'] else '')+f'{key}-{num:03}.jpg');raw=src.read_bytes();im=Image.open(src).convert('RGB');crop=(crop[0],crop[1],min(crop[2],im.width),min(crop[3],im.height));im=im.crop(crop);im.thumbnail((480,720));id=f'REF-{n:02}';dest=O/'images'/f'{id}.jpg';im.save(dest,quality=88)
 if s[4]:
  sj=json.loads((L/s[4]).read_text());url=sj['url'];asset=sj['images'][num-1];loc=f'Official reader image segment {num} (one-based; not a printed page number)'
 else:
  url=s[2];asset=f'https://yenpress.com/uploads/preview/9781975336523/single/{num:03}.jpg';loc=f'Look inside preview image {num:03} (preview index, not printed page number)'
 entries.append({'id':id,'title':title,'kind':kind,'series':s[0],'creators':s[1],'credit_url':s[2],'episode':s[3],'source_url':url,'asset_url':asset,'locator':loc,'publisher':'Yen Press / Ize Press' if key=='solo3' else 'WEBTOON','publication_date':None,'accessed_utc':'2026-09-09','source_sha256':hashlib.sha256(raw).hexdigest(),'excerpt_crop_pixels':list(crop),'excerpt_transform':'Limited crop and downscale only; no retouch or AI processing','image':f'images/{id}.jpg','sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'width':im.width,'height':im.height,'observation':obs,'experiment':adapt,'limitation':limit,'visual_inspection':'Actual source image inspected at native dimensions, not inferred from title or metadata','reference_role':'Owner visual selection and critical study only. Never a generation input.'})
data={'schema':'CombatReferenceBoard/1','experiment_id':'IC-REF-20260909-01','title':'What makes a fight feel powerful?','access_note':'Small attributed excerpts from official public readers and a publisher Look inside preview. Public viewing is not a reuse license. Full episodes remain on the linked services. These references are separate from original production art and are never image-generation inputs.','entries':entries}
b=json.dumps(data,ensure_ascii=False,indent=2)+'\n';(O/'data.json').write_text(b);h=hashlib.sha256(b.encode()).hexdigest();(O/'data.js').write_text('window.REFERENCE_DATA='+b.strip()+';\nwindow.REFERENCE_DATA_SHA256='+json.dumps(h)+';\n');(D/'shortlist.json').write_text(b);print(len(entries),h)
