from pathlib import Path
import hashlib,json,re
R=Path(__file__).resolve().parents[2];P=R/'production/pilot-chapters';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
styles={
'NG':'Thin controlled anime contours, elegant facial planes when faces are visible, angular grouped hair shapes and precise tailored clothing contours. Luminous glass translucency where glass occurs, layered inhabited navy architecture, selective warm/cyan light. Preserve the original integrated night atmosphere and depth through broad value groups. These are drawing qualities, not instructions to insert a person, creature or object absent from this shot.',
'BP':'Elegant softly modeled faces when visible, fine controlled hair edges, desaturated portrait illustration with broad translucent charcoal shapes and selective fine silver accents only on existing forms. Preserve intimate beautiful unease, graceful proportions and the original softly drawn treatment. These are medium qualities, not instructions to add petals or a creature in an absent-subject shot.',
'ST':'Rounded expressive cartoon contours, large eyebrows and elastic mouths when faces are visible, opaque block-painted shapes and broad warm/cool color masses. Preserve muscular charm, orange/coral/turquoise palette and generous open sky. Expressive personality belongs only to subjects actually specified in this panel.',
'RC':'Black and white directional pen hatching, bold silhouette blacks, angular planes, kinetic foreshortening and selected red accents. Preserve drawn muscle planes when bodies are visible, selective directional hatch groups and the original graphic contrast. Draw only the specified subject and current power state; style does not require a shark, red glow or key in every frame.',
'FL':'Strong black brush masses, scraped white edges and controlled broad grayscale planes, limited hot-magenta institutional lights. Graphic ink narrative with selective rough marks and mature face character when a face is actually shown. Preserve the original brush medium and dry dramatic clarity. Drawing treatment does NOT require an eel, reflected portrait, pole, person or infrastructure beyond this shot’s visible content.'}
js=json.loads((P/'jobs-remaining-v2.json').read_text());out=[];rows=[]
for j in js:
 assert not (P/'calls'/(j['attempt_id']+'.json')).exists()
 old=P/'job-revisions'/(j['attempt_id']+'-v2.json');prompt,n=re.subn(r'Drawing treatment: .*?\nWorld context:', 'Drawing treatment: '+styles[j['category']]+'\nWorld context:',j['prompt'],count=1,flags=re.S);assert n==1
 pp=P/'prompts'/(j['attempt_id']+'-input-v3.txt');jp=P/'job-revisions'/(j['attempt_id']+'-v3.json');assert not pp.exists() and not jp.exists();pp.write_text(prompt)
 z={**j,'prompt':prompt,'prompt_path':str(pp.relative_to(R)),'prompt_sha256':sha(pp),'input_revision':3,'supersedes_unsubmitted_job_path':str(old.relative_to(R)),'supersedes_unsubmitted_job_sha256':sha(old),'style_scope_revision_path':'research/pilot-chapters/refine_style_scope.py','style_scope_revision_sha256':sha(Path(__file__))}
 jp.write_text(json.dumps(z,indent=2)+'\n');out.append(z);rows.append({'id':j['id'],'original_v2_job':str(old.relative_to(R)),'original_v2_sha256':sha(old),'submitted_v3_job':str(jp.relative_to(R)),'submitted_v3_sha256':sha(jp)})
(P/'jobs-remaining-v3.json').write_text(json.dumps(out,indent=2)+'\n');(P/'style-scope-revisions.json').write_text(json.dumps({'reason':'Actual FL05 first panel exposed entity nouns in style clauses inviting absent cast; preserve medium and current visibility separately. No extra generation, frozen story unchanged.','entries':rows},indent=2)+'\n');print(len(out))
