from pathlib import Path
import json,hashlib,datetime
r=Path(__file__).resolve().parents[3];d=r/'docs/encounter-lab/reference-comparison';p=Path(__file__).parent
refs=json.loads((d/'prior-references.json').read_text());by={e['id']:e for e in refs['entries']}
rows=[
('M01-P','REF-01','Make the target carry the blow','Our planted lunge and lifted opponent already make force visible. Faces and weapons remain readable.','The target is still mostly an intact, posed silhouette. The Boxer excerpt spends nearly everything on compressed flesh, a turned head and one contact.','In one peak beat, let a shoulder collapse, a cheek compress or the grip fail. In the next, show the resulting loss of guard. Keep that consequence across the following action.','Different contact types: saber deflection versus a boxing punch. This is a bodily-consequence comparison, not a claim they should look identical.'),
('V01-P','REF-02','Make the escape answer a committed attack','The deep shaft, outstretched hand and wall departure create a readable route and exciting height.','The polished airborne silhouette can read as a travel pose. The reference makes an incoming arm and narrow evasion share one directional field.','Show the spear committing into the old position; cut closer to the near miss, then land somewhere that changes the next tactical choice.','The reference is an overhead boxing evasion, not the same power or setting. Borrow the spatial relationship, not anatomy or clothing.'),
('X01-P','REF-14','A close frame needs a dangerous gap','Our ink wedges, clenched expression and enlarged contact make a stronger peak than a distant neutral exchange.','The opposing torso and weapon can still feel staged around a flash. The reference brings a blade immediately beside a tilted face.','Use one tight reaction or guard-failure frame inside the encounter. Preserve the blade path and frightened or defiant eye without surrounding it with more microtexture.','The reference has glitter and prismatic edges we should not automatically adopt. Its tight crop does not establish all grips.'),
('X03-P','REF-09','A power can become the environment','The broad pale diagonal plane, displaced enemies and anchored caster give our ability a clear, unusual identity.','A reveal can look impressive before we understand its price or tactical use. The huge black sweep is also a scale reveal, not a complete action chain.','Let the power remove a specific option: turn safe ground into a fall, interrupt a charge, or divide allies. Show the limitation before its next use.','Both examples omit parts of the causal sequence in a single frame. Large area or bright contrast alone is not proof of combat readability.'),
('Y01-F1','REF-08','Keep horror quiet; make proximity costly','Our restrained grayscale, pale face and oversized masked creature already create a distinct horror language.','The low fencing pose and looming creature remain controlled. The reference’s mouth and tight face crop eliminate safe distance.','Keep the quiet surfaces. Show a failed escape, a weapon pinned against a claw, or a face reacting to a tiny remaining gap; then make the survivor change strategy.','The reference is colorful monster action, not a horror-style target. Its useful feature is proximity and reaction, not palette or creature design.'),
('Y02-F1','REF-03','Weight needs an understandable pivot','The warm painting, loaded legs and heavy construct give this direction a strong material and combat identity.','A huge creature can appear conveniently airborne if the load transfer is not explicit. The simple throw reference exposes a planted pivot and a displaced body center.','Before the heavy counter, show the construct committing weight onto a support. Let a visible leverage point or failed support explain the fall; retain the changed footing afterward.','Human throwing is not a literal mechanism for moving a giant machine. The transferable idea is an evident pivot and a cost-bearing stance.'),
('Y03-F1','REF-04','Let personality survive the impact','Our broad color shapes, laughing expression and large hammer produce an appealing, playful kind of power.','A smiling hero and floating armored target can read as a celebratory poster. The reference isolates the victim’s long ballistic trajectory.','Give the launch an awkward bodily follow-through or tumbling landing. Keep the hero’s exuberance while allowing the opponent to interrupt it in the next beat.','Comic exuberance and gritty violence are independent choices. This reference shows consequence after a blow, not the contact itself.'),
('Y04-F1','REF-10','A skill needs rules beyond its color','Our source-to-spear fire bend, separate caster and displaced defenders create a relatively understandable power interaction.','A beautiful arc can become a repeated decorative solution. The reference shows how large simple forms can establish a distinct power family.','Define what the redirect can and cannot bend, where the force exits and what exposes the user. Let the next enemy exploit that rule before an earned adaptation.','The reference is a magic reveal with luminous spheres, not a fire-deflection action. Borrow consistent visual grammar, not those forms or colors.')]
entries=[]
for i,(our,ref,title,have,gap,craft,limit) in enumerate(rows,1):
 f=d/'assets/our-art'/f'{our}.png';e=by[ref];entries.append({'id':f'COMP-{i:02}','title':title,'our_attempt_id':our,'our_image':f'assets/our-art/{our}.png','our_sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'reference_id':ref,'reference_image':f'assets/prior-references/{ref}.jpg','reference_sha256':e['sha256'],'reference_title':e['series']+' — '+e['episode'],'creators':e['creators'],'source_url':e['source_url'],'credit_url':e['credit_url'],'locator':e['locator'],'already_working':have,'remaining_gap':gap,'encounter_test':craft,'comparison_limit':limit,'owner_approval':None})
data={'schema':'EncounterReferenceComparison/1','experiment_id':'EL-REF-20260909-01','title':'From impressive moments to gripping encounters','entries':entries,'screenshot':{'path':'assets/user-screenshot.png','sha256':hashlib.sha256((d/'assets/user-screenshot.png').read_bytes()).hexdigest(),'status':'User supplied search-results screenshot; no per-thumbnail preference export','observations':['The visible page searches for amazing manwha fight scenes. The result grid mixes action excerpts, article collages, wallpaper-like character images and an animation-like frame.','Several thumbnails use huge diagonal cuts, faces next to danger, stretched moving bodies and bright effects against dark silhouettes. These are visible compositional traits, not verified rankings.','The upper row fourth card has a close blade/two-face motif visually consistent with our Omniscient Reader reference family. The exact screenshot crop and episode are not independently bound to its article.','The grid includes both quiet graphic panels and very dense effects. Its presence does not reverse the owner’s explicit low-texture preference or approve every result.'],'uncertainty':'Search result captions and image dimensions are not comic source verification. Individual series/episode identities remain unverified unless separately documented. No screenshot image is passed to image generation.'},'prior_references':[{**e,'local_image':f'assets/prior-references/{e["id"]}.jpg'} for e in refs['entries']],'prior_reference_dataset_sha256':hashlib.sha256((d/'prior-references.json').read_bytes()).hexdigest(),'interpretation':'All comparison findings are visual observations and proposed original craft tests. They are not user votes, matched-content experiments, or evidence that one drawing treatment is universally better.'}
b=json.dumps(data,ensure_ascii=False,indent=2)+'\n';(d/'data.json').write_text(b);h=hashlib.sha256(b.encode()).hexdigest();(d/'data.js').write_text('window.COMPARISON_DATA='+b.strip()+';\nwindow.COMPARISON_HASH='+json.dumps(h)+';\n')
(p/'findings.json').write_text(json.dumps({'schema':'EncounterComparisonFindings/1','created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'dataset_sha256':h,'findings':entries,'inspected':{'user_screenshot':'native size','prior_originals':[x[0] for x in rows],'prior_references':'All16native sources inspected in prior IC research; exact16excerpt bytes and metadata preserved and rechecked. No claim of repeating full16native-source review in this round.'},'high_value_recheck':['Official Omniscient Reader prologue and Yen Press Solo Leveling Vol3 pages reopened.','Two screenshot article-title discovery queries found IMDb syndication records; page opens returned403. No bypass or inferred episode matches.'],'stop_reason':'Existing verified excerpts already support all8craftcomparisons; further broadsearch does not resolve the critical preference/sequence questions.'},indent=2)+'\n')
print(h)
