import json,hashlib
from pathlib import Path
root=Path.cwd(); out=root/'research/world-components/independent-review'
j=json.loads((out/'findings.json').read_text()); reg={x['id']:x for x in json.loads((root/'production/world-components/candidates.json').read_text())['candidates']}
notes={
'13-C1':['Mature gap-toothed bowl-cut face and massive arms/thighs create a distinct muscular woman; fine contour and hatching persist at native and phone size.','Thick-waist brief became a strongly narrowed hourglass waist. Hand curls over the wedge upper rim rather than clearly entering the recessed grip; contact remains plausible and the tool and both feet are complete.'],
'15-C1':['Broad older bearded man, patient eyes and an open explaining palm remain readable at phone size; curved engraving convincingly describes wool and face.','Hand wraps the mallet shaft, with the full cylindrical head and both feet visible. Dense coat marks compress at phone size but preserve the large silhouette.'],
'17-C1':['Long angular mature face, silver wedge hair and long vest distinguish this slender adult; stride across two blocks and full triangular level frame remain clear on phone.','Frame is open as the actual-gear override permits; hand holds its apex and cord/weight separate cleanly. Near boot balances close to the block edge rather than resting with a full sole.'],
'18-C1':['Very broad soft belly, small feet, rounded dark face and delighted smile create a distinct adult design; whole ladle, vent and gripping hand remain clear on phone.','Bold rounded masses persist, with more painted surface texture than a strict two-step cel interpretation. Warm joyful affect shares a family with 02-C2 but does not erase the different hair, proportions and treatment.'],
'05-C2':['Lean adult bob-haired runner brakes in a wide step while a clearly grasped closed case counterbalances the open reaching hand; all equipment and feet are complete.','Matte broken paint and worn cloth match 05; native texture compresses to mottling on phone, while face, reach and case remain clear.'],
'06-C2':['Very tall gaunt adult with long nose, moustache and worried counting gesture contrasts strongly with compact 06-C1. Coarse dry brush persists.','Closed press gains a carry handle but is visibly held; full boots, counting fingers and prop remain legible on phone.'],
'13-C2':['Slender wide-legged figure holds a complete raised paddle with clear shaft grip; clean hatching and black-white-red grouping remain readable on phone.','Large eyes, small jaw and youthful face do not clearly establish the specified adult age22; this is age uncertainty, not proof of a child. White leggings are not clearly differentiated from exposed ink-shaded legs.'],
'15-C2':['Short strong adult woman, mature wedge face and wide culottes differ from the older heavy 15-C1; complete stance and long key remain readable on phone.','Hand grips the key bar at its middle rather than the rounded terminal grip. Closed square socket matches actual gear override. Engraving is dense but large pose and hand contact remain distinct.'],
'17-C2':['Broad round adult face, short heavy torso, asymmetrical crop and friendly open palm contrast with long angular 17-C1. Whole jack and boots are framed at native and phone size.','Carry grip is clear; actual jack mechanism still looks like a screw press without an obvious external lifting shoe. This is functional uncertainty inherited from G1, not malformed hand contact.'],
'13-M1':['Four separate hoof legs, two horns and a short tail are visible at native and phone size; fine hatching and red throat grouping remain coherent.','Mechanical bull-like linkage, outward horns and added dorsal spikes depart from the compact ram description. Extra spikes are a specification deviation, but the main body and limb count remain clear.'],
'15-M1':['Four jointed paws, two fan-like ears and one tail remain legible on phone, with dense curved bronze engraving and an unobscured barrel body.','Muzzle appears directly flanged into the pipe; separate mouth/pipe construction is unresolved, and a carry loop is added on the back. Clamping a pipe is permitted behavior, so this is a watch item rather than a certain anatomy failure.'],
'17-M1':['Only four separated legs resolve at native and phone size: three on one side and one on the other; six with separate feet were required.','Shovel face, slab load and simple mint stone body are clear, but the domed shell is more turtle-like than the requested non-turtle beetle form. Reveal all six attachment paths without adding clutter.'],
'19-C1':['Mature shaved-head dark-skinned woman, severe pale-over-black tailoring and long lean body clearly differ from the original youthful male anchor and heavy 19-C2. Full body and plausible shear grip remain readable on phone.','Lowered open pointed shears and a narrow standing/cross-step replace the specified closed-shear forward fencing action. Skin and cloth are more realistically textured than the silky stylized source, while its pale, black and crimson family persists.'],
'18-C2':['Long-legged angular adult, orange spikes, enormous grin and pointing hand contrast strongly with soft round 18-C1; full screen carry grip and both boots are clear on phone.','Pose is a broad standing brace with screen down at the side rather than diagonal shielding against a gust. Added lightning costume motif and earrings are deviations; no floating tool or cropped anatomy.'],
'19-C2':['Heavy mature man with receding gray hair, jowls, tired eyes and plain black coat creates a distinct quiet adult identity. Complete jar, grip and boots remain readable on phone.','Realistic skin and scuffed waxed cloth are less silky than the original illustration. Jar handle is pale rather than black, and red wax trails look wet/blood-like before context; this is a visual association, not depicted injury or an owner comfort finding.'],
'18-M1':['Four hooves, two horns, two ears and one thin tail are separately visible at native and phone size; broad turquoise body and round cheek pads remain clear.','Added orange dorsal tiles and all-over mottling make the body busier than smooth bison brief, but no cloud effects obscure its topology. Rounded cartoon volume remains distinct from 19.'],
'19-M1':['Four thick root legs resolve, with an upright closed dark bud and pale narrow face slit; native eyes become tiny on phone but full creature silhouette stays clear.','Pointed/split root tips and multiple overlapping bud edges deviate from blunt tips and a simple two-half body. One botanical sprig is present, consistent with the single-flourish treatment; no fringe or swarm obscures anatomy.']
}
for k,v in notes.items():
 r=reg[k];j['entries'][k]={'attempt_id':r['attempt_id'],'sha256':r['sha256'],'observations':v,'hard_retry_candidate':False,'hard_retry_reason':None}
priority=[('17-M1','Only four separated feet are visible where six are required; show all six with clear attachment paths.'),('01-M1','Only three feet fully separate; visible rear foot has four pads instead of three.'),('02-M1','Belly and rear foot-like forms obscure the four-leg topology; remove added harness/tool inventory.'),('18-E2','Four-sail rotor is not fully established: upper sail cropped and short/bare arms replace full cloth sails.'),('06-E2','Foreground pages contain visible printed/lettering-like rows under a no-text constraint; no decipherable words are claimed.'),('19-C1','Open lowered shears and narrow standing step replace the required closed-shear forward fencing action.')]
for k,reason in priority:j['entries'][k].update(hard_retry_candidate=True,hard_retry_reason=reason)
for k,e in j['entries'].items():
 r=reg[k];assert hashlib.sha256((root/r['path']).read_bytes()).hexdigest()==e['sha256']
 matches=sorted((root/'research/world-components/reader/phone-captures').glob('*/progressive-'+k+'-390.png'))
 assert matches,k
 e['native_path']=r['path'];e['phone_capture_path']=str(matches[-1].relative_to(root));e['reviewed_native']=True;e['reviewed_phone']=True
j.update(review_status='complete_primary_54_of_54',scope='Actual native PNGs and corresponding source-bound 390px phone captures reviewed for every primary. Character art renders360x540, other cards360x240. Owner choices and approval remain unknown; this is AI technical review, not owner acceptance.',retry_priority_note='Six bounded hard-failure candidates recommended in order; do not spend the remaining three slots on beauty variants. Preserve every primary. Later retry review must compare actual pixels before selection.',retry_priorities=[{'priority':i+1,'id':k,'attempt_id':reg[k]['attempt_id'],'sha256':reg[k]['sha256'],'reason':v}for i,(k,v)in enumerate(priority)])
j['phone_capture_note']='Preserved progressive batches are source-bound to unchanged primary PNGs; some screenshots include then-missing neighboring cards. This review concerns each complete target card, not a claim that every progressive screenshot showed all54.'
assert len(j['entries'])==54
(out/'findings.json').write_text(json.dumps(j,indent=2)+'\n')
with (out/'people-creatures-primary.md').open('a') as f:
 f.write('\n\nRemaining seventeen primary cards — final native and phone inspection\n\n')
 f.write('Each exact frozen prompt and actual native PNG was inspected, followed by the corresponding actual390px reader capture. The12-card batch uses preserved4a2dc973b1 captures; the final5 uses8bc3389319 captures. Source hashes and individual evidence paths are in findings.json. No lead preferred result was supplied. Original first-ten observations above are preserved.\n\n')
 for k,v in notes.items():f.write(k+'-P — '+' '.join(v)+'\n\n')
 f.write('Actual-gear overrides in the frozen character prompts explicitly permit the15 closed square socket and the17 open triangular frame; these are not character-transfer failures. All27 character/creature primaries now have actual native and phone inspection.\n')
report='''Independent final primary review — all54

All54 primary native images and their actual390px reader cards have been inspected. Existing progressive observations remain preserved. Each component has an attempt ID, exact native SHA256, native path, phone evidence path and concise observations in findings.json. No owner choices, comfort verdict or acceptance are inferred. No lead preferred result preceded inspection.

The study produces real alternatives: mature lined, bald, broad, gaunt, short heavy, muscular and long-legged characters with distinct facial construction and gestures. 06-C1/C2 and17-C1/C2 are especially clear counterexamples to a palette-swapped same-person result. Body diversity is imperfect:13-C1 substitutes a narrow hourglass waist for the requested thick waist, and13-C2 reads ambiguously youthful. Those deviations remain visible without claiming age from metadata.

Drawing systems remain broadly distinguishable:02 is warm outlined painting and05 matte textured paint;06 coarse dry brush,13 finer hatching,15 dense curved engraving;17 quiet thin-outline shape design and18 broader expressive cartoon mass.19 retains pale space, severe tailoring and dark material contrast but shifts its new adults toward realistic skin and weathered fabric. That shift deserves disclosure; it does not by itself justify erasing mature faces to recover the original young fashion model. Warm painted families overlap, particularly02/17/18, but their silhouette and mark choices do not collapse into one treatment.

All nine gear cards show three complete separated objects. Most character hand contacts are plausible and legible; functional deployment is still unproven in several designs, particularly17's press-like jack. Places retain identifiable workspaces and routes. Phone reduction preserves broad silhouettes, faces and major props, while05 mottling,15 fine engraving and dark01 creature facets lose small detail. These are comfort/readability risks for an eventual owner test, not measured fatigue or approval. The19 crimson wax/root imagery can suggest blood before context although no injury is depicted.

Recommended bounded repair order (six assets; no requirement to spend nine):

'''
for i,(k,v)in enumerate(priority):report+=f'{i+1}. {k}-P — {v}\n'
report+='''
The first three are clear count/separation problems or, for02, explicit unresolved attachment rather than a certain fifth limb.18-E2 is meaningful rotor framing/count, not arbitrary background cropping.06-E2 is visible pseudo-print contamination, not a claim of readable words.19-C1 is a missed functional pose/tool state, not a request for a prettier portrait.

Reserve the other three slots.15-M1's muzzle appears joined to its pipe, but clamping is permitted behavior, so a failure verdict would overstate the evidence.06-M1 has five obvious bands and an uncertain rear sixth, not a proven pass or certain extra appendage.13-M1's dorsal spikes and19-M1's pointed tips are deviations with clear overall topology. No other card has a stronger evidenced need for scarce correction than the six above.

Strongest counterexample to treating the entire study as failed:18-M1 and19-M1 both visibly resolve four separate feet in highly different bodies and materials, while18-C1/C2 show dramatically different broad/long adult builds with readable tool grips. Strongest counterexample to treating the study as finished production art:17-M1 still cannot demonstrate its stipulated six legs and19-C1 cannot demonstrate the requested fencing action. This is a reviewable component study, not a continuity-tested finished story or an owner-approved cast/world.
'''
(out/'primary-repair-priorities.md').write_text(report)
print('Wrote54 source-bound entries,17 appended observations and six-priority final primary review.')
