// Offline browser verification. No production mutation; restores original preferences.
import assert from'node:assert/strict';import{readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync}from'node:fs';import{resolve,dirname}from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import{connect,pause}from'./cdp.mjs';
const here=dirname(fileURLToPath(import.meta.url)),args=process.argv.slice(2),arg=(k,d)=>args.includes(k)?args[args.indexOf(k)+1]:d,root=resolve(arg('--root',resolve(here,'../../..'))),out=resolve(arg('--out',here)),docs=resolve(root,'docs/scale-conflict'),data=JSON.parse(readFileSync(resolve(docs,'data.json'))),smoke=args.includes('--smoke'),required=smoke||args.includes('--require-complete'),sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),c=await connect(Number(arg('--port','9381'))),receipt={schema:'ScaleConflictBrowserQA/1',utc:new Date().toISOString(),root,dataset_sha256:data.dataset_sha256,plan_sha256:data.plan_sha256,review_notes_sha256:data.review_notes_sha256,available:data.available_count,mode:smoke?'portable-smoke':'full',checks:[],screenshots:[],errors:c.errors},screens=resolve(out,'phone-captures','ui-'+data.dataset_sha256.slice(0,12)+'-'+sha(resolve(docs,'app.js')).slice(0,8));mkdirSync(out,{recursive:true});let original;
const check=(name,condition,detail)=>{receipt.checks.push({name,pass:!!condition,...detail});assert(condition,name)},ev=s=>c.ev(s),app='ScaleConflictApp',blank=`Object.values(${app}.exportChoices().choices).every(c=>Object.values(c.ratings).every(v=>v===null)&&c.comfort===null&&!c.note&&!c.shortlist)`,shot=async name=>{const p=resolve(screens,name+'.png');await c.screenshot(p);receipt.screenshots.push({path:p,sha256:sha(p)})},layout=()=>ev(`({overflow:document.documentElement.scrollWidth>innerWidth,images:[...document.querySelectorAll('#stage img')].map(i=>{const r=i.getBoundingClientRect();return{src:i.getAttribute('src'),loaded:i.complete&&i.naturalWidth>0,uncropped:Math.abs(r.width/r.height-i.naturalWidth/i.naturalHeight)<.01}})})`);
try{
 if(required)check('Complete24 selected',data.available_count===24&&data.entries.length===24);
 await c.navigate(resolve(docs,'index.html'));original=await ev(`${app}.exportChoices()`);check('Exact managed dataset',await ev(`${app}.getState().dataset_sha256`)===data.dataset_sha256);check('Initially blank owner preferences',await ev(blank));
 for(const[w,h]of(smoke?[[390,844],[1440,1000]]:[[390,844],[1024,768],[1440,1000]])){
  await c.viewport(w,h);await ev(`${app}.setMode('all')`);await c.decode();const l=await layout();check(`${w} all images decode uncropped`,l.images.length===data.available_count&&l.images.every(i=>i.loaded&&i.uncropped));check(`${w} no page overflow`,!l.overflow);check(`${w} missing cards disabled`,await ev(`[...document.querySelectorAll('[data-missing]')].every(p=>[...p.closest('.card').querySelectorAll('[data-choice],[data-shortlist],[data-note],[data-compare]')].every(b=>b.disabled))`));await ev('scrollTo(0,0)');await shot('all-'+w);
  if(data.available_count>=2){const ids=data.entries.filter(e=>e.candidate).slice(0,3).map(e=>e.id);await ev(`${JSON.stringify(ids)}.forEach(id=>${app}.selectCompare(id));${app}.openComparison()`);await c.decode('#compare-stage img');check(`${w} comparison images complete`,await ev(`document.querySelectorAll('#compare-stage img').length===${ids.length}&&[...document.querySelectorAll('#compare-stage img')].every(i=>i.complete&&i.naturalWidth)&&document.getElementById('compare-dialog').scrollWidth<=document.getElementById('compare-dialog').clientWidth`));await ev(`document.getElementById('compare-dialog').scrollTop=0`);await shot('compare-'+w);await ev(`document.getElementById('compare-dialog').close();document.getElementById('clear-compare').click()`)}
 }
 for(const kind of ['category','scale','subject','story']){const values=[...new Set(data.entries.flatMap(e=>kind==='subject'?e.subjects:[kind==='category'?e.category:kind==='scale'?e.scale:e.story_path]))];for(const value of values){await ev(`${app}.setFilter(${JSON.stringify(kind)},${JSON.stringify(value)})`);const expected=data.entries.filter(e=>kind==='subject'?e.subjects.includes(value):(kind==='category'?e.category:kind==='scale'?e.scale:e.story_path)===value).map(e=>e.id);check(`Browse ${kind}/${value}`,JSON.stringify(await ev(`[...document.querySelectorAll('#stage .card')].map(e=>e.dataset.entry)`))===JSON.stringify(expected))}}
 await ev(`${app}.setMode('all')`);check('All nine response dimensions',await ev(`[...document.querySelectorAll('#stage .card')].every(e=>e.querySelectorAll('.appeal').length===9)`));check('AI note count',await ev(`document.querySelectorAll('#stage .technical-notes').length`)===data.entries.filter(e=>e.ai_observations.length).length);check('Notes collapsed and separate',await ev(`[...document.querySelectorAll('#stage .technical-notes')].every(e=>!e.open&&!e.querySelector('[data-choice]'))`));check('Growth available',await ev(`document.querySelectorAll('#stage .power-growth').length`)===data.entries.filter(e=>e.power?.growth?.length).length);
 for(const e of data.entries.filter(e=>e.history.length)){await ev(`${app}.openHistory('${e.id}')`);await c.decode('#compare-stage img');check('History '+e.id,await ev(`document.querySelectorAll('#compare-stage img').length===${e.history.length}&&!document.querySelector('#compare-stage [data-choice]')`));await ev(`document.getElementById('compare-dialog').close()`)}
 await ev(`${app}.openAnchors()`);await c.decode('#compare-stage img');check('Reference library separate',await ev(`document.querySelectorAll('#compare-stage img').length===${data.references.length}&&!document.querySelector('#compare-stage [data-choice]')`));await ev(`document.getElementById('compare-dialog').close()`);
 if(data.previous){await ev(`${app}.openPrevious()`);check('Previous choices exact and read-only',await ev(`document.querySelectorAll('[data-previous]').length===${Object.keys(data.previous.export.choices).length}&&!document.querySelector('#previous-stage [data-choice]')&&document.getElementById('previous-download').getAttribute('href')===${JSON.stringify(data.previous.download_src)}`));check('Previous export exact bytes',sha(resolve(root,data.previous.path))===data.previous.sha256);await ev(`document.getElementById('previous-dialog').close()`);const oldReject=await ev(`(()=>{try{${app}.importChoices(${JSON.stringify(data.previous.export)});return false}catch{return true}})()`);check('Previous export cannot import',oldReject)}
 const available=data.entries.filter(e=>e.candidate),first=available[0];if(first){await ev(`${app}.openImage('${first.id}')`);await c.decode('#zoom-stage img');await ev(`document.getElementById('zoom-toggle').click()`);check('Native zoom',await ev(`document.getElementById('zoom-stage').classList.contains('native')`));await c.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await c.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'});check('Escape closes zoom',await ev(`!document.getElementById('zoom-dialog').open`));if(available.some(e=>e.id!==first.id&&e.subjects.some(s=>first.subjects.includes(s)))){await ev(`${app}.openRecognition('${first.id}')`);await c.decode('#compare-stage img');check('Shared subject full scenes',await ev(`document.querySelectorAll('#compare-stage img').length>=2&&document.getElementById('compare-title').textContent.startsWith('Shared subjects')`));await ev(`document.getElementById('compare-dialog').close();document.getElementById('clear-compare').click()`)}
 if(!smoke){
  await ev(`${app}.showEntry('${first.id}');document.querySelector('#stage [data-entry="${first.id}"] .scene-response').open=true;document.querySelector('#stage [data-entry="${first.id}"] [data-choice="overall"][data-value="like"]').focus()`);await c.send('Page.bringToFront');await c.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await c.send('Input.dispatchKeyEvent',{type:'char',text:'\r',unmodifiedText:'\r',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await c.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await ev(`${app}.updateChoice('${first.id}','drawing','dislike');${app}.updateChoice('${first.id}','creature','na');${app}.updateChoice('${first.id}','recognition','unsure');${app}.updateChoice('${first.id}','comfort','no');${app}.updateChoice('${first.id}','note','QA roundtrip');`);if(available[1])await ev(`${app}.updateChoice('${available[1].id}','shortlist',true)`);let marked=await ev(`${app}.exportChoices()`);check('Keyboard independent nine dimensions',marked.choices[first.id].ratings.overall==='like'&&marked.choices[first.id].ratings.action===null&&marked.choices[first.id].ratings.creature==='na');
  for(const[k,v]of[['experiment_id','old'],['dataset_sha256','old'],['plan_sha256','old']]){const bad=structuredClone(marked);bad[k]=v;check('Atomic reject '+k,await ev(`(()=>{const before=JSON.stringify(${app}.exportChoices().choices);try{${app}.importChoices(${JSON.stringify(bad)});return false}catch{return before===JSON.stringify(${app}.exportChoices().choices)}})()`))}
  for(const kind of ['attempt','hash','order','approval','rating','missing']){const bad=structuredClone(marked);if(kind==='attempt')bad.source_bindings[0].attempt_id='old';if(kind==='hash')bad.source_bindings[0].sha256='bad';if(kind==='order')bad.source_bindings.reverse();if(kind==='approval')bad.owner_approval=true;if(kind==='rating')bad.choices[first.id].ratings.overall='approved';if(kind==='missing')delete bad.choices[first.id];check('Atomic reject '+kind,await ev(`(()=>{const before=JSON.stringify(${app}.exportChoices().choices);try{${app}.importChoices(${JSON.stringify(bad)});return false}catch{return before===JSON.stringify(${app}.exportChoices().choices)}})()`))}
  const download=resolve(out,'.scratch/downloads',String(Date.now()));mkdirSync(download,{recursive:true});const oldFiles=new Set(readdirSync(download));await c.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:download});await ev(`document.getElementById('export').click()`);let file;for(let i=0;i<50;i++){file=readdirSync(download).find(f=>!oldFiles.has(f)&&f.endsWith('.json'));if(file)break;await pause(100)}check('Actual file export',!!file);const exported=JSON.parse(readFileSync(resolve(download,file)));check('Export preserves choices',JSON.stringify(exported.choices)===JSON.stringify(marked.choices));await ev(`${app}.importChoices(${JSON.stringify(original)})`);const doc=await c.send('DOM.getDocument'),input=await c.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'#import-file'});await c.send('DOM.setFileInputFiles',{nodeId:input.nodeId,files:[resolve(download,file)]});await pause(200);check('Actual file import',await ev(`JSON.stringify(${app}.exportChoices().choices)===${JSON.stringify(JSON.stringify(marked.choices))}`));await c.navigate(resolve(docs,'index.html'));check('Reload preserves exact choices',await ev(`JSON.stringify(${app}.exportChoices().choices)===${JSON.stringify(JSON.stringify(marked.choices))}`));await ev(`${app}.importChoices(${JSON.stringify(original)})`);
  const errorStart=c.errors.length;await ev(`${app}.showEntry('${first.id}');document.querySelector('#stage [data-entry="${first.id}"] img').src='intentionally-missing-qa-source.png'`);await pause(150);check('Missing source disables new responses',await ev(`!!document.querySelector('#stage [data-entry="${first.id}"] .image-failure')&&[...document.querySelectorAll('#stage [data-entry="${first.id}"] [data-choice]')].every(b=>b.disabled)&&${app}.updateChoice('${first.id}','overall','like')===false`));const expectedErrors=c.errors.splice(errorStart);check('Only intentional image error',expectedErrors.every(e=>String(e.url||e.text||JSON.stringify(e)).includes('intentionally-missing-qa-source.png')));await c.navigate(resolve(docs,'index.html'));check('Missing source test leaves preferences unchanged',await ev(`JSON.stringify(${app}.exportChoices().choices)===${JSON.stringify(JSON.stringify(original.choices))}`));
 }
 }
 for(const e of data.entries)for(const asset of e.history){check('Native source hash '+asset.attempt_id,sha(resolve(root,asset.path))===asset.sha256);if(asset.call_path)check('Call hash '+asset.attempt_id,sha(resolve(root,asset.call_path))===asset.call_sha256)}for(const e of data.entries)for(const f of e.service_failures||[]){check('Failure record hash '+f.attempt_id,sha(resolve(root,f.record_path))===f.record_sha256);check('Failure raw tool output hash '+f.attempt_id,sha(resolve(root,f.tool_output_path))===f.tool_output_sha256)}for(const r of data.references)check('Reference hash '+r.id,sha(resolve(root,r.path))===r.sha256);for(const link of data.report_links)check('Report link '+link.label,existsSync(resolve(docs,link.path)));check('Choices unchanged',await ev(`JSON.stringify(${app}.exportChoices().choices)===${JSON.stringify(JSON.stringify(original.choices))}`));check('Clean console',!c.errors.length);receipt.pass=true;
}catch(error){receipt.pass=false;receipt.failure=String(error.stack||error);process.exitCode=1}finally{if(original)try{await ev(`${app}.importChoices(${JSON.stringify(original)})`)}catch{}receipt.code_bindings=['index.html','style.css','app.js','preferences.js','data.json'].map(n=>({path:'docs/scale-conflict/'+n,sha256:sha(resolve(docs,n))}));const filename=smoke?'portable-reader-qa.json':data.available_count===24?'browser-qa.json':'pending-'+data.available_count+'-browser-qa.json';writeFileSync(resolve(out,filename),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({pass:receipt.pass,path:resolve(out,filename),sha256:sha(resolve(out,filename)),failure:receipt.failure}));await c.close()}
