"""Write the first complete Chapter6 manuscript; never overwrite an earlier draft."""
import json, hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[5]
OUT=ROOT/'production/nightglass-longform/scripts'
panels=[]
def p(action, copy, camera, state):
    panels.append(dict(id=f'N6-{len(panels)+1:02d}', action=action, copy=[dict(speaker=s,text=t) for s,t in copy], camera=camera, current_state=state, reuse=None, lettering='Exact copy stays editable outside raster. Compose for390px without generated text or balloons. Protect faces, hands, contact, supports and entrusted objects.'))
p('At Lower Post after his completed fourth collection run, Aren puts the ordinary morning fee into his ONE open cream wallet on the counter. Ossa stands beside him; his empty closed gray bag rests on the counter, both brown shoulder straps slack with it.', [('Caption','Fourth morning. After the collection run.'),('Ossa','The bindery, after closing?'),('Aren','I’ll be there.')], 'Warm familiar working two-shot; actual payment and bare shoulders clear.', 'Fourth completed paid recurring morning, not full week. No duplicate waist wallet or worn harness. Old LEFT tear, sole RIGHT sheath. Yesterday’s RUST answer has departed with outgoing post; no daughter receipt or reply claimed. Wallet closes at waist and bag is worn before02.')
p('Aren and Sera reach Ilen’s ordinary public loft doorway. Ilen has paused beside her supported paper frame to greet them. Sera keeps her own brown ledger closed.', [('Aren','Your answer is on its way.')], 'Early return to the person affected, eye-level doorway and dry working aisle.', 'Fourth day after paid round. Confirmation is departure only. Ilen’s received sheet and OPEN CREAM/broken VIOLET envelope remain in her closed dry drawer; no RUST object returns. Aren’s bag empty and closed on his back; wallet closed at waist.')
p('Ilen indicates the dry receiving board beside her work without abandoning the supported frame. Sera listens from the clear visitor aisle.', [('Ilen','The loft. I’ll be here most days.')], 'Medium occupational scene; receiving choice belongs to Ilen.', 'Ilen chooses this current receiving stop for ordinary mail. No claim of a permanent legal address or family reconciliation. Neither visitor reads her private papers.')
p('On the ordinary public stair immediately outside Ilen’s door, Sera writes her own observation in her open brown ledger. Aren waits clear of passing workers; the uninterrupted stair and actual loft entrance are visible.', [('Sera','The public stair is clear all the way to this door.')], 'Oblique view ties witnessed approach to exact door; both feet supported.', 'She records only the approach actually seen. One LIGHTBLUE permitted operational copy stays inside her ledger, distinct from her own written pages. No citywide safety certification or repaired bridge claim.')
p('At Kiva’s blue-awning workshop, Kiva rests a brass hinge on her bench and points to the familiar collection spot. Sera records this second receiving choice in her own ledger. Aren waits with his empty closed bag.', [('Kiva','Lower Post can keep my returns. Collections here.')], 'Lively workshop medium-wide, clear ordinary approach.', 'Existing care-of Lower Post and market-day collection offer are confirmed, not newly invented. WHITE closure copy, old refusal slip and dispatch receipt remain Kiva’s. TAN/GREEN acceptance is away; buyer outcome still unknown. Crate belongs Venn; barrow is back at Kiva.')
p('Aren and Sera walk the broad ordinary market route toward the existing office. Sera carries her own closed brown ledger; Aren’s hands are empty.', [('Sera','We can name these two stops. The rest will need its own visit.')], 'World depth and ordinary walking after two close work scenes.', 'Scope is Ilen’s loft and Kiva’s collection/Lower Post return contact, with observed approaches. LIGHTBLUE copy inside ledger. No new power, unsafe shortcut or district-wide reopening.')
p('They arrive at the already-established Office of Route Closures through its ordinary public entrance. Maret is visible at her familiar desk beyond the doorway.', [('Caption','Office of Route Closures.')], 'Re-establish the actual office and public route before its decision.', 'Same office from Chapter2 and same Maret who processed the Chapter3 record. Maret is the woman with cropped dark curls, round glasses, moss vest and cream blouse; not Toma. No new official or authority invented.')
p('At Maret’s desk, Sera hands her ONE LIGHTBLUE operational copy while opening her own brown ledger to the freshly witnessed stops. Aren stands aside with his empty closed bag still worn.', [('Sera','The current direction, and the two approaches I’ve seen.')], 'Desk three-shot; LIGHTBLUE transfer separate from retained brown ledger.', 'LIGHTBLUE copy passes to Maret and stays at the office. Sera retains ownership of her ledger and field observations. Office already has its original old closure and yellow petition. Toma retains original request, signed WHITE receipt and release at Ninth Store.')
p('Maret compares the LIGHTBLUE current operational copy with the standing direction in the office’s own archive on her desk. Sera’s open ledger remains nearer Sera.', [('Maret','Until this office replaces it, Ninth Store must use it.')], 'Measured close occupational explanation; distinct documents on supported desk.', 'Explains current binding instruction without inventing who authored it or making Toma obstructive. No new custody of Kiva’s certified WHITE closure copy; it stays at her bench.')
p('Maret signs ONE pale GREEN replacement notice on the desk, beside the LIGHTBLUE copy and archived standing direction.', [('Maret','For these two stops, route through Lower Post. Effective on receipt.')], 'Working hand and calm decision; no dramatic stamp spectacle.', 'Maret’s office replaces its standing routing direction only for Ilen’s current loft and Kiva’s collection/Lower Post return contact. Original archives and LIGHTBLUE stay Office. GREEN is the single transportable notice. No all-city reopening, rank change or new postal powers.')
p('Maret hands the folded pale GREEN notice to Aren’s LEFT glove in visible contact. Aren’s RIGHT glove holds the rim of his empty gray bag on the desk; its two shoulder straps lie slack beside it.', [('Aren','I’ll take it to Toma.')], 'Hand-level single public sheet transfer; bare shoulders visible.', 'ONE GREEN notice, no envelope or duplicate notice. Bag OFF his back, no worn harness. Sera has her own closed ledger, LIGHTBLUE now archived with Maret. Wallet closed at waist, sole RIGHT sheath.')
p('Aren and Sera take the ordinary public route back to Ninth Store’s established green door. His closed gray bag is worn again and holds the folded GREEN notice.', [], 'Street transition with ordinary grounded walking and recognizable green destination.', 'GREEN packed, hands empty. No shortcut, teleportation or power. Sera’s closed brown ledger contains her own observations, no LIGHTBLUE copy.')
p('Inside Ninth Store, Aren’s LEFT glove gives Toma the folded GREEN notice in actual contact. His RIGHT glove holds the rim of the now-empty gray bag on the dry table, both straps slack with it.', [('Aren','The replacement direction.')], 'Recognizable receiving table, green door and Toma; object contact clear.', 'GREEN changes custody to Toma. Bag OFF back, shoulders bare. Toma’s original request, signed WHITE Chapter5 receipt and release remain in his own file. ONE closed cream wallet at waist.')
p('Toma places the GREEN notice with his current routing entry and marks that entry before releasing any mail. Aren and Sera wait across the table.', [('Toma','I’ll use this direction for those stops.')], 'Close procedural cause, brief and legible.', 'Effective notice has actually been received and applied. GREEN remains in Toma’s file; no copy returned to Sera. This changes only the named stops, not all held letters or all Bell Basin routes.')
p('Toma slides ONE modest tied brown mail batch into Aren’s open gray bag on the supported dry table. Aren steadies the bag rim; the bag’s own brown straps lie slack.', [('Toma','For Lower Post’s next round.')], 'One supported loading action; no floating parcel or second bag.', 'Unopened ordinary private mail inside one outer batch. No inventory claim that all stored mail is freed. Bag OFF back, no worn harness; GREEN and original WHITE records stay Toma. Sera owns her closed ledger.')
p('Following the ordinary public route, Aren and Sera reach the existing UPPER landing of the local goods circuit. Aren wears the closed gray bag containing the tied batch.', [('Caption','At the upper goods landing.')], 'Established local geography, visible separate public stair and goods gate.', 'Ninth Store does NOT have a newly direct lift to Lower Post. This is the existing two-stop MAIL-ONLY circuit from Chapter3. No new repair, isolation, test or magical operation.')
p('With the existing goods car STOPPED at its upper landing, Aren places the closed gray bag inside it. The bag and both shoulder straps are off his body. Sera waits beside the separate public stair.', [('Sera','I’ll take the stair with you.')], 'Wide enough for stopped car, grounded Aren and separate public stair.', 'Only mail and bag ride, never people. Aren’s shoulders bare. Gate can close after loading; actual operation is routine. Existing supports intact, no active power or extra bag.')
p('At Lower Post after the goods car has stopped below, Aren arrives from the adjoining public stair. Ossa has removed the ONE tied brown mail batch onto her sorting table; Aren’s now-empty gray bag rests on the counter.', [('Ossa','Tomorrow’s Bell Basin round.')], 'Lower receiving hatch and public stair together, calm completed transport.', 'Same existing lower landing, not a new circuit. Batch now Ossa’s custody for the two authorized stops. No claim every piece is already delivered. Empty bag OFF Aren’s back, its straps with it. Sera’s closed ledger remains hers.')
p('After the bindery has closed, Kiva accompanies Aren to Venn’s door beneath the already-established cream-curtain window and fern box. Venn welcomes them from the workroom.', [('Caption','After closing.'),('Venn','Come up.')], 'Warm dusk street and familiar bindery; fulfilled appointment.', 'Still FOURTH day, honoring Chapter5 tomorrow-after-closing. Kiva accompanies as promised. Venn owns the single plain brass room key; Aren has none. No rent, lease or reservation yet. Aren’s empty bag worn, wallet closed at waist.')
p('At the top of the bindery’s ordinary side stair, Venn uses his ONE plain brass key to open the room door. Aren and Kiva wait on the supported landing.', [], 'Door, lock and owner’s key readable; visitors stand outside.', 'First actual room-door/landing establishment. Key remains Venn’s, not passed to Aren. Side stair is ordinary access from the street, not a magical shortcut. Current daylight fading toward evening.')
p('From the doorway, reveal the modest room: narrow wooden bed, small wooden desk at the cream-curtain window with its fern, plain chair, washstand and basin. Venn stands aside so Aren and Kiva can look in.', [], 'Full room establishing view, quiet air and lived-in city depth through window.', 'First authoritative actual room interior; selected source must condition later room images. No luxury, second room, lease, luggage already moved in or unearned ownership. Key still Venn’s.')
p('Venn indicates the ordinary side-stair entrance from inside the room. Aren listens near the small desk while Kiva looks toward the window.', [('Venn','Weekly rent. Use the side stair whenever you need it.')], 'Human terms in the same established room; modest furnishings remain consistent.', 'Weekly arrangement and usable early hours offered before any later payment. No arbitrary price, invented balance or deposit. This arrangement can fit Aren’s existing morning job.')
p('Aren looks back to Venn from the room, considering the offer. Venn answers without pressing him.', [('Aren','I want to finish the week before I promise.'),('Venn','I understand.')], 'Unhurried two-shot with Kiva at the edge or outside crop.', 'Waiting is Aren’s voluntary choice. Venn has not imposed Ossa’s separate first-week condition. No key handover, rent payment, binding lease or guaranteed hold yet.')
p('At the window, Aren rests an empty gloved hand on the sill. Kiva stands beside the plain chair; the room has space around them.', [('Aren','I want the quiet. I’m not used to it.'),('Kiva','You know where to find me.')], 'Quiet medium-wide; a positive wish with one honest uncertainty.', 'Still a visitor, not yet resident. One empty bag worn, wallet closed at waist, sole RIGHT sheath. Key remains with Venn off frame. Known Kiva workshop nearby, no invented family history.')
p('At Lower Post after the fifth paid morning round, Ossa gives Aren ONE WHITE business envelope with a SEA-GREEN seal. Aren’s LEFT glove receives it while his RIGHT holds his empty gray bag rim on the counter.', [('Caption','Fifth morning. After the paid Lower Post round.'),('Ossa','Ilen, on the new round.')], 'Distinct fresh envelope and familiar receiving hands.', 'FIFTH completed paid morning explicit. Ordinary fee already secured in ONE closed waist wallet. Bag OFF back with slack straps. This is business mail from the released routing batch, NOT the daughter’s answer or old CREAM/VIOLET invitation. New WHITE/SEA-GREEN letter goes in bag before26.')
p('Aren walks the ordinary public stair to Ilen’s familiar loft door, wearing his closed gray bag. Workers pass with supported materials, leaving the visitor aisle clear.', [], 'Short recognizable arrival, no repeated bureaucracy.', 'ONE WHITE/SEA-GREEN business letter sealed inside bag. Sera is at other work, no need to recertify the route or accompany routine delivery. No power or unknown shortcut.')
p('At Ilen’s dry receiving board, Aren’s LEFT glove passes the sealed WHITE/SEA-GREEN envelope into Ilen’s RIGHT hand with visible contact. His RIGHT glove holds his empty gray bag rim on the board.', [('Aren','On the regular round.')], 'Clear single-envelope delivery, recipient face visible.', 'Ilen now owns the new business letter. Bag OFF back, two slack straps, bare shoulders. Old private received sheet and OPEN CREAM/brokenVIOLET remain in her closed dry drawer. No RUST return, new signature or receipt required in this routine delivery.')
p('Ilen opens her own WHITE/SEA-GREEN business envelope and reads its single new sheet at her dry board. Aren waits clear of the paper frame, eyes away from the page.', [('Ilen','The next paper order.')], 'Close recipient recognition and practical anticipation.', 'This explicitly concerns paper work, NOT a daughter response or family reconciliation. Envelope opened by its owner only. Aren’s empty bag now closed and worn again; her private Chapter5 originals remain in drawer.')
p('Ilen sets the new business sheet and opened SEA-GREEN envelope safely on the dry working board, then turns to her supported paper frame with renewed purpose.', [('Ilen','I can start this today.')], 'Work resumes; ordinary delivered information causes a useful action.', 'New order belongs with Ilen’s work, distinct from private originals in closed dry drawer. She keeps the next-season work she chose in Chapter5. Aren can leave with empty bag; no invented commission payment or new receipt.')
p('At Lower Post after the sixth paid collection, Ossa gives Aren ONE BLUE-GRAY envelope with a COPPER seal for Kiva. He receives it in his LEFT glove, RIGHT hand steadying his empty bag rim on the counter.', [('Caption','Sixth morning. After the paid collection.'),('Ossa','Kiva’s care-of reply. From the buyer.')], 'One distinct reply and practical handoff.', 'SIXTH completed paid morning. Existing care-of Lower Post, established in Chapter4, brought this reply; do NOT credit the new routing notice for that older contact. Morning fee retained in ONE closed waist wallet. Bag OFF back/slack straps; BLUE-GRAY/COPPER packs before31.')
p('After his Lower Post obligation, Aren takes the familiar ordinary market route to Kiva’s workshop, his closed gray bag on his back.', [], 'Brief world movement toward blue awning.', 'Buyer reply sealed inside one bag. No abandoned morning shift, new fee or active power. Kiva’s previously dispatched TAN/GREEN acceptance remains away; this is a distinct incoming object.')
p('At Kiva’s bench, Aren’s LEFT glove passes the sealed BLUE-GRAY/COPPER envelope into Kiva’s RIGHT hand. His RIGHT glove holds his empty gray bag rim on the bench, shoulder straps slack.', [('Aren','From your buyer.')], 'Actual hand contact with recognizable workshop and Kiva.', 'Reply now Kiva’s. Bag OFF back, shoulders bare. Her WHITE certified closure copy, old refusal slip and dispatch receipt stay in safe bench space. Crate remains Venn’s; borrowed barrow is already home at workshop.')
p('Kiva opens the BLUE-GRAY/COPPER envelope herself and reads its one sheet, letting a small relieved smile interrupt her working concentration.', [('Kiva','They kept me on the order.')], 'Recipient close-up; a held chance finally confirmed.', 'Buyer response now confirms commission continuation, not finished manufacture or buyer payment. No other character reads her sheet. Aren waits aside with reclosed empty bag worn again.')
p('Kiva looks from the buyer’s letter to Aren beside her bench. Her tools and unfinished hinges make the next collection concrete.', [('Kiva','Next market day. After the morning post?'),('Aren','After the morning post.')], 'Workmates settle a practical time, no triumph pose.', 'Confirms the already-offered market-day collection work from Chapter4. Not a newly awarded client or repeat reward. No extra fee is paid now, no conflict with recurring morning job.')
p('Kiva lays the buyer’s sheet and opened BLUE-GRAY/COPPER envelope in dry space and returns to assembling a hinge. Aren leaves the blue awning toward the familiar lane, the bindery window beyond.', [], 'Quiet consequence and familiar neighborhood, supported ordinary labor.', 'Reply remains Kiva’s alongside her own papers. Aren’s bag empty and closed, wallet closed, one RIGHT sheath. No new crate commission or added transport detour. Sixth day continues.')
p('After completing his seventh morning round, Aren adds the ordinary fee to his ONE open cream wallet at Lower Post. Ossa faces him across the counter; his empty bag and both straps rest beside it.', [('Caption','Seventh morning. The round complete.'),('Ossa','Your first week’s done.')], 'Earned ordinary payment bookends01; one wallet, bare shoulders.', 'SEVENTH completed paid recurring morning now explicit: Chapter3 first,4 second,5 third,6 fourth through seventh. No duplicate waist wallet. All prior pay retained except ordinary stated spending; no invented numeric balance. No rank or power upgrade.')
p('With his wallet closed and secured at his waist, Aren listens as Ossa leans comfortably against the familiar Lower Post table.', [('Ossa','Shall we talk about our room?'),('Aren','I’ve chosen the bindery.')], 'Warm familiar two-shot; choice rather than rejection.', 'Ossa honors the promised conversation after first week. She has not offered a free key or rescinded housing. Aren chooses Venn’s weekly offer voluntarily; no payment there yet. Empty bag worn again.')
p('Aren looks toward the ordinary stair that leads back through his working neighborhood. Ossa gestures to their shared table with an easy welcome.', [('Aren','I can sleep there and still make the first round.'),('Ossa','You’ll have a place at this table.')], 'Connection and practical early hours justify the choice.', 'Ossa’s kindness remains part of Aren’s life. No new room entitlement here or claim that bindery is superior housing. Wallet closed at waist, empty bag worn; no rent paid until40.')
p('Later that seventh day, Aren returns through the familiar bindery door. Venn looks up from his workbench of unfinished books.', [('Caption','Later that day.')], 'Short grounded return to the actual landlord and workroom.', 'Room offer first seen fourth day; this is a new seventh-day meeting, not a retroactive lease. ONE plain brass key still Venn’s. Empty bag closed and worn; one closed cream wallet at Aren’s waist.')
p('At Venn’s workbench, Aren holds his ONE open cream wallet in his LEFT glove while his RIGHT places the agreed rent coins into Venn’s waiting hand over the supported table.', [('Aren','The week’s rent, as agreed.')], 'Actual paid exchange; only one wallet and no waist duplicate.', 'Uses retained earned savings for the previously offered weekly terms. No invented numerical price or exact balance. Rent is paid now, not a free room reward; remaining savings stay in wallet. Empty bag worn, sole RIGHT sheath.')
p('Venn records the received rent in his own book at the workbench. Aren has reclosed his ONE cream wallet and secured it at his waist.', [('Venn','The room is yours for the week.')], 'Brief binding acceptance, ordinary landlord record.', 'Weekly agreement now effective, not property ownership or permanent lease. Venn’s rent book stays his; no extra paper receipt unless later explicitly authored. ONE key still Venn’s until42, remaining savings retained.')
p('Venn’s RIGHT hand passes his ONE plain brass room key into Aren’s LEFT glove in visible contact across the bindery bench.', [('Aren','Thank you.')], 'Close tangible earned key, both owners’ hands legible.', 'Same actual key from20, one object changes custody. Plain brass key is distinct from Aren’s red-cord brass courier badge. Closed cream wallet at waist, empty bag worn; no second key or keyring.')
p('On the familiar upper side-stair landing, Aren’s LEFT glove turns the new brass key in the same room-door lock. Both boots are supported on the landing.', [], 'Actual use of earned access, clearly grounded anatomy.', 'Same key/lock/door from20, now Aren’s. LEFT forearm retains old tear; sole RIGHT sheath and intact RIGHT sleeve. Key stays in lock for this action, no duplicate key elsewhere. Bag closed and worn, wallet closed at waist.')
p('The room door opens inward and Aren takes an ordinary supported step over the threshold. His LEFT glove now holds the removed brass key; the modest room is the same one he viewed.', [], 'Open threshold, daylight and continuous interior geography.', 'Actual room from21, no upgrade or added furniture. Seventh-day later afternoon. ONE key in LEFT, closed cream wallet at waist, one empty gray bag worn, sole RIGHT sheath. Door remains open by choice.')
p('Beside the narrow bed, Aren sets his ONE empty gray bag and its two shoulder straps onto the floor with his RIGHT hand. His LEFT glove still holds the brass key.', [], 'Setting down a day’s work; bare shoulders and one bag clearly visible.', 'Bag/harness now OFF body and stays beside bed. Sole RIGHT sheathed weapon remains on Aren’s hip, not duplicated with bag. Wallet still closed at waist. Room furniture, cream curtain and fern follow actual21.')
p('At the small window desk, Aren’s LEFT glove places his ONE brass key beside his ONE closed cream wallet, which he has just removed from his waist.', [], 'Quiet close still life, ordinary key and retained money in his own paid space.', 'Wallet now on desk, NONE at waist. Remaining savings preserved after rent without numerical balance. Bag/harness remains on floor by bed, shoulders bare. One RIGHT sheath still on body; key and wallet remain here through47.')
p('In a tall view of the same modest room, Aren turns toward its OPEN doorway and welcomes Sera at the threshold. She carries her own CLOSED brown ledger. The fern and cream curtain frame city depth; the gray bag rests by the bed, key and cream wallet on the small desk.', [('Aren','Come in.')], 'Tall room-and-world ending: an open door chosen by its new paid resident.', 'Same seventh-day later afternoon and actual room. Bag/harness on floor, no worn straps. ONE RIGHT sheath on Aren; old LEFT tear/RIGHT intact. ONE key and ONE closed wallet on desk, no waist duplicate. Sera retains her own ledger/observations; LIGHTBLUE copy remains Office. No new notice, disaster, daughter reunion or citywide fix. Paid work becomes a usable room and room for companionship.')
assert len(panels)==47
script=dict(schema='NightglassChapterScript/1', chapter=6, title='A Door Left Open', premise='Two receiving stops become a working route. Four more paid mornings let Aren choose a room, pay for it, and open its door to someone else.', reading_premise='Aren can finally choose a room. First he wants to finish the week he promised.', status='complete-draft-awaiting-independent-review', owner_approval=None, panels=panels)
target=OUT/'chapter-6.json'
assert not target.exists(),target
target.write_text(json.dumps(script,ensure_ascii=False,indent=2)+'\n')
md=['# Chapter 6 — A Door Left Open','', 'Complete 47-panel draft. Independent full-script review and portable FiveChapters delivery review are required before art. No Chapter6 image calls made. Owner approval remains unknown, not inferred from autonomous production authorization.','']
for panel in panels:
    md += ['## '+panel['id'],'',panel['action'],'']
    md += [f"- **{c['speaker']}**: {c['text']}" for c in panel['copy']] or ['*Silent.*']
    md += ['', '**Camera:** '+panel['camera'], '', '**Current state:** '+panel['current_state'],'']
(OUT/'chapter-6.md').write_text('\n'.join(md)+'\n')
print(json.dumps(dict(path=str(target),sha256=hashlib.sha256(target.read_bytes()).hexdigest(),panels=len(panels))))
