/* Exact image-bound character choices; viewing state never implies canon. */
window.CombatExplorationPreferences = function(data,onChange){
 'use strict';const ids=data.entries.map(e=>e.id),entries=new Map(data.entries.map(e=>[e.id,e]));
 const storageKey=`combat-exploration:${data.experiment_id}:${data.dataset_sha256}`;let choices=Object.fromEntries(ids.map(id=>[id,{character:null,style:null,weapon:null,power:null,comfort:null,note:'',shortlist:false}])),storageAvailable=true;const unavailable=new Set();
 const hasChoices=()=>Object.values(choices).some(c=>['character','style','weapon','power','comfort'].some(k=>c[k]!==null)||c.note||c.shortlist);
 const status=text=>document.getElementById('save-status').textContent=text;
 function exact(value,keys,label){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).sort().join('|')!==[...keys].sort().join('|'))throw Error(`Invalid ${label}.`)}
 function exportChoices(){return{schema:'CombatExplorationChoices/1',experiment_id:data.experiment_id,dataset_sha256:data.dataset_sha256,plan_sha256:data.plan_sha256,source_bindings:structuredClone(data.source_bindings),exported_at:new Date().toISOString(),choices:structuredClone(choices)}}
 function validate(draft){exact(draft,['schema','experiment_id','dataset_sha256','plan_sha256','source_bindings','exported_at','choices'],'choice file');if(draft.schema!=='CombatExplorationChoices/1'||typeof draft.exported_at!=='string'||!Number.isFinite(Date.parse(draft.exported_at)))throw Error('Invalid choice-file format.');for(const k of ['experiment_id','dataset_sha256','plan_sha256'])if(draft[k]!==data[k])throw Error('These choices belong to a different or older image set. Nothing was changed.');if(!Array.isArray(draft.source_bindings)||draft.source_bindings.length!==data.source_bindings.length)throw Error('The complete image binding list is required.');draft.source_bindings.forEach((b,i)=>{exact(b,['id','attempt_id','sha256'],'image binding');for(const k of ['id','attempt_id','sha256'])if(b[k]!==data.source_bindings[i][k])throw Error('An image or source hash has changed. Nothing was imported.')});exact(draft.choices,ids,'character choices');for(const id of ids){const c=draft.choices[id];exact(c,['character','style','weapon','power','comfort','note','shortlist'],'character choice');if(['character','style','weapon','power'].some(k=>![null,'like','dislike','unsure'].includes(c[k]))||![null,'yes','no','unsure'].includes(c.comfort)||typeof c.shortlist!=='boolean'||typeof c.note!=='string'||c.note.length>4000)throw Error('Invalid response or note longer than 4,000 characters.');if(!entries.get(id).candidate&&(['character','style','weapon','power','comfort'].some(k=>c[k]!==null)||c.note||c.shortlist))throw Error('A missing image cannot have a response.')}return structuredClone(draft.choices)}
 function save(){try{localStorage.setItem(storageKey,JSON.stringify(exportChoices()));storageAvailable=true;status(hasChoices()?'Saved in this browser':'No choices yet')}catch{storageAvailable=false;status('Storage unavailable · export to keep')}}
 function importChoices(draft){const next=validate(draft);choices=next;save();onChange();return true}
 function update(id,key,value){if(!entries.get(id)?.candidate||unavailable.has(id))return false;if(['character','style','weapon','power'].includes(key)&&[null,'like','dislike','unsure'].includes(value)||key==='comfort'&&[null,'yes','no','unsure'].includes(value)||key==='shortlist'&&typeof value==='boolean'||key==='note'&&typeof value==='string'&&value.length<=4000)choices[id][key]=value;else throw Error('Invalid character choice');save();onChange();return true}
 try{const saved=localStorage.getItem(storageKey);if(saved){choices=validate(JSON.parse(saved));status(hasChoices()?'Your saved choices are restored':'No choices yet')}}catch{status('Saved choices could not be restored · import a saved copy')}
 return Object.freeze({exportChoices,importChoices,validate,save,update,get:id=>structuredClone(choices[id]),getAll:()=>structuredClone(choices),markUnavailable:id=>{unavailable.add(id);onChange()},isUnavailable:id=>unavailable.has(id),getStorage:()=>({key:storageKey,available:storageAvailable})});
};
