"""Freeze a separate no-generation correction proof after the structural screen failed."""
from pathlib import Path
import datetime,hashlib,json
P=Path(__file__).resolve().parent
sources={}
for panel,aid in [('P09','A00010'),('P11','A00013'),('P13','A00006'),('P14','A00012')]:
 r=json.loads((P/'calls'/f'{aid}-registered.json').read_text())['candidate']
 sources[panel]={'candidate_id':r['id'],'path':r['path'],'sha256':r['sha256']}
spec={'experiment_id':'CF-20260907-02','frozen_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'parent_experiment':'SC-20260907-01','trigger':'Final allowed G P09 retry still has a visible staff-to-toe gap in independent native and390px inspection. No expanded new-sequence generation is earned. S fixed-layer finishing remains a separate bounded proof.','hypothesis':'Explicit local source-bound masks, texture repair and drawn contours can close small causal relationship failures while retaining finished adult drawing and the rest of the image.','mechanism':'Agent-authored conventional raster cloning/matting and editable SVG paths/masks. No image-generation or hidden inpainting call. Geometry anchors inform contact but final pixels must be independently inspected.','sources':sources,'edit_panels':['P09','P11','P13'],'reference_only_panel':'P14','targets':{'P09':'Replace separated staff endpoint/toe relation with explicit wooden end compressed against metal forefoot on same dry ridge. Preserve both hands, body pose, three limbs, flask and west-release/right-shutter geography.','P11':'Make ascent-stop-descending attack path legible with drawn motion and preserve ongoing sweep/eastward escape; resolve any visible flask-cap ambiguity without changing ownership.','P13':'Improve visibility of the foreleg pinned under lowered shutter while preserving three legs, physical separation, right wound and left broken staff.','P14':'Carry selected generated retry unchanged as comparison reference if actual inspection confirms aftermath state; do not claim a conventional correction that was not performed.'},'exact_copy':{'P09':[],'P11':['AIR BRAKE · PULSE 2 → 1'],'P13':[],'P14':['ODO: Steady.','NERA: I am.']},'allowances':{'new_generation_calls':0,'primary_authoring_minutes_per_edit_panel':40,'correction_rounds_per_edit_panel':1,'correction_minutes_per_edit_panel':20,'attribution':'Agent wall time, never claimed human labor','record_all_versions':True},'gates':['Direct pixel comparison shows target relationship improved without introducing a new anatomy/contact/state error.','Independent actual-art review at native and390px; required lettering separately browser-tested.','Drawing integration and adult acting must remain credible; texture/edge artifacts remain failures.','This is a bounded correction proof in unchanged surrounding story context, not a newly coherent14-panel production sequence. Context design transitions and prior context failures remain visible.','No human comprehension, owner preference or commercial acceptance inferred.'],'direct_spend_usd':0,'provider_model_snapshot':None,'seed':None,'usage':None,'billing_allocation':None,'human_reviews_run':0,'owner_acceptance':None,'commercial_clearance':None}
out=P/'correction-experiment.json'
with out.open('x') as f:f.write(json.dumps(spec,indent=2)+'\n')
(P/'correction-experiment.sha256').write_text(hashlib.sha256(out.read_bytes()).hexdigest()+'\n')
print(out)
