"""Reserve one SC-20260907-01 call using the retained attempt ledger.

This prepares exact supported text/image inputs; it does not call an API.
Run from checkout: PYTHONPATH=src python production/structural-pilot/prepare_call.py P09 S control/v3/P09-full.png
"""
from pathlib import Path
import argparse, hashlib, json, struct
from sequence_pilot.cli import Workspace, locked

P = Path(__file__).resolve().parent
BEATS = {
 'P09': 'The sentinel pivots around the very same restrained forefoot while its separate side leg sweeps left toward Odo at the west release. Nera keeps both boots on the dry ridge and braces the ONE intact staff against that fixed foot; one capped flask is upright in her chest sling. Odo has one hand on the west cord and his other hand free. The east shutter is closed. Exactly three sentinel limbs: anchored foreleg, leftward sweeping side leg, rear supporting leg. Do not turn the sweep into a fourth appendage. No injury yet.',
 'P11': 'One Nera is airborne above the STILL EXTENDED SWEEPING SIDE LEG, using Air Brake to halt at the apex and turn down/east into her next strike. One intact wooden staff; no break or injury yet. A tapered upward cyan arc ends in a sharp horizontal brake accent, then one short redirected accent points east/down; no duplicate body or ghost body. The sentinel still has exactly three legs, including that ongoing horizontal sweep, not three planted feet. Odo pulls the trailing west-release cord while beginning to RUN EAST/RIGHT toward the raised east shutter; his leading foot, hips and torso must show rightward escape. One sealed upright flask in Odo other hand; Nera sling empty. Keep quiet space at top for separate Air Brake lettering.',
 'P13': 'After escape the lowered shutter physically divides the west/left flooded gallery from the east/right corridor. Living sentinel body west, BOTH adults east beyond that separating plane. Exactly THREE sentinel legs total, one foreleg pinned under the shutter bottom and two other supporting legs; absolutely no fourth leg. Nera holds a short splintered staff remnant in her anatomical LEFT hand and exposes a small scrape on the BACK of her anatomical RIGHT hand, inherited from P12. No left-hand wound, no cheek wound. Odo holds one upright sealed flask; the released cable hangs slack. The missing staff section stays a broken section, never a second intact staff. Make the barrier, pinned contact and survivors separation unmistakable.',
 'P14': 'Quiet adult two-shot beyond the shutter. Odo gently supports Nera anatomical RIGHT hand, whose BACK has the small abrasion from P12. Her RIGHT arm must be traceable from its right shoulder/sleeve across toward Odo, even if it crosses her torso. Nera anatomical LEFT hand holds the visibly splintered short staff remnant. Odo other hand holds one upright sealed flask. Mature expressive reciprocal gaze: relief, pain held under composure, restrained wry warmth. No new wounds and no left-hand injury. Corridor background and lowered shutter remain behind them. Leave quiet upper margins for two separate short dialogue balloons.'
}
COMMON = '''Use case: illustration-story. Transform the first input, a newly authored original 3D scene guide, into original finished comic art. Input 1 controls camera, composition, placements and contact; input 2 is a newly generated original cast reference controlling adult identities and economical ink/cel drawing, NOT poses. Do not reproduce extra reference studies or robots/mannequins. Nera is a31-year-old lean female courier with warm brown skin, mature long angular face, short black curls, straw-yellow asymmetric rain cape, charcoal practical clothes and boots. Odo is a38-year-old broad male keeper with tan skin, cropped silver hair, ultramarine work jacket and cream cuffs. Both are fictional mature adults, no real likeness. Deliberate energetic tapered ink, appealing adult faces, controlled broad two-tone shadows, sharp silhouettes, motivated expressive posture. Palette: warm ivory stone, cool slate shadows, charcoal ink, straw cape, ultramarine jacket and violet threat slit; tiny cyan braking accents only where required. No global sepia, dense distressed textures, fog, spark clouds, photorealism, glossy3D, decorative armor or generic ornamental detail. Keep action contact and faces clear. No lettering, captions, SFX words, UI, symbols resembling writing, watermark, page borders or balloons. Preserve all story events and object ownership. No named artist, comic or franchise imitation.\n'''

def main():
 ap=argparse.ArgumentParser();ap.add_argument('panel',choices=list(BEATS));ap.add_argument('route',choices=['S','G']);ap.add_argument('guide');ap.add_argument('--retry-of');ap.add_argument('--failure');ap.add_argument('--retry-instruction');a=ap.parse_args()
 guide=(P/a.guide).resolve()
 if not guide.is_relative_to(P) or not guide.is_file():raise ValueError('Guide must exist inside experiment')
 manifest=P/'refs/manifest.json'; refs=json.loads(manifest.read_text());sha=hashlib.sha256(guide.read_bytes()).hexdigest();gid=f'guide-{a.panel}-{sha[:12]}'
 if not any(v['id']==gid for v in refs['references']):
  refs['references'].append({'id':gid,'path':guide.relative_to(P).as_posix(),'sha256':sha,'original':True,'rights_status':'original-created-for-pilot','commercial_clearance':None,'acceptance':'structural-guide-not-art-acceptance'})
  manifest.write_text(json.dumps(refs,indent=2)+'\n')
 cast=next(v for v in refs['references'] if v['id']=='cast')
 role='''Output ONLY the two adult CHARACTER LAYERS on a genuinely transparent background, with the exact same full canvas and exact actor placements/scale/hand and foot positions as the first guide. Preserve the empty space around them; do not crop/center/enlarge them. Draw expressive natural adult anatomy in the guide poses. Include their clothes, hands, faces and hair; include the small right-hand abrasion only in P13/P14. OMIT ALL environment, water, monster, staff, bottle, rope, floor, shadows on the floor, arrows and motion effects. These are separately composited fixed editable scene/prop layers. Hands still form the exact shown grips/support gestures; empty grips are deliberate compositing inputs. The guide threat and props show interaction geometry only; never include them in this transparent character output. No white/colored/checkerboard background.''' if a.route=='S' else '''Output ONE complete finished illustrated panel. Preserve the guide camera and framing, the full gallery architecture and actor/threat silhouettes, exact contact and layer order. Replace simple geometry with coherent economical drawn forms. Sentinel is an original slate kite body with one narrow violet gill slit and exactly three articulated legs. Keep the ridge, west release, overhead cable and east shutter visibly connected where in frame. This is a full-frame instruction-conditioned render; do not copy guide arrows as diagram lines. Translate force into economical drawn motion accents. No multi-panel page or contact sheet.'''
 width,height=struct.unpack('>II',guide.read_bytes()[16:24])
 prompt=COMMON+f'\nCanvas aspect ratio {width}:{height}; match the full guide frame and normalized actor placements.\nPANEL '+a.panel+'. '+BEATS[a.panel]+'\n\n'+role+'\n'
 if a.retry_instruction:prompt+='\nTARGETED HARD-FAILURE CORRECTION: '+a.retry_instruction+'\n'
 name=f'prompts/{a.panel}-{a.route}-'+('retry' if a.retry_of else 'primary')+'.txt';path=P/name
 if path.exists():raise ValueError('Never overwrite a reserved prompt')
 path.write_text(prompt)
 with locked(P):
  w=Workspace(P);row=w.reserve(a.panel,a.route,name,retry_of=a.retry_of,hard_failure=a.failure,refs=[gid,'cast'])
 call={'attempt_id':row['id'],'panel':a.panel,'route':a.route,'prompt':prompt,'prompt_path':name,'referenced_image_paths':[str(guide),str(P/cast['path'])],'references':row['references'],'status':'reserved','provider_model':None,'seed':None,'usage':None,'billing_allocation':None,'direct_spend_usd':0}
 calls=P/'calls';calls.mkdir(exist_ok=True);(calls/(row['id']+'.json')).write_text(json.dumps(call,indent=2)+'\n');print(json.dumps({'attempt_id':row['id'],'call_path':str(calls/(row['id']+'.json'))}))

if __name__=='__main__':main()
