"""Register lead actual-raster observations, separately from file/geometry checks."""
from pathlib import Path
import json
from sequence_pilot.cli import Workspace,locked
P=Path(__file__).resolve().parent
# p/f/u mean pass/fail/not_assessed. Unknown is never promoted to pass.
rows={
1:{'actors':('p','Two expressive mature adults, but enlarged/recentered relative to guide.'),'event':('u','Character-only output; no scene event can be accepted from this layer.'),'contact':('f','Only one low grip is visible; left arm is hidden, so required two-hand axis is unavailable.'),'props':('f','Prohibited flask remains on cape; layer request required all props omitted.'),'state':('u','No injury visible, but raw RGB checkerboard is not a usable native-alpha layer.')},
2:{'actors':('p','Two mature adults with readable threat-facing pose.'),'event':('p','Distinct side leg sweeps left toward Odo at release; three limbs and closed right shutter visible.'),'contact':('f','Staff crosses shin and continues past foot; two-hand restraint not visible, forward boot appears over blue water band.'),'props':('f','Flask diagonal on back/cape rather than upright chest sling.'),'state':('f','P08 dry forefoot restraint does not persist visibly.')},
3:{'actors':('p','One airborne Nera and east-striding Odo; expressive adults.'),'event':('u','Character-only image cannot establish sweep/shutter relations.'),'contact':('u','Hands pose around generated shaft, but exact fixed-scene correspondence requires actual composite.'),'props':('f','Staff, flask and rope appear despite separate-prop request.'),'state':('u','RGB checkerboard, zero alpha, shifted scale/placements; no native layer-control acceptance.')},
4:{'actors':('p','One airborne Nera, one right-moving Odo, credible adult drawing.'),'event':('p','Ongoing leftward sweep under Nera and Odo eastward escape visible.'),'contact':('u','Cyan ascent/apex reads as continuing jump; redirected strike toward required forelimb not clear.'),'props':('p','One intact staff and upright capped flask with Odo; release cord extends back.'),'state':('u','Right shutter raised; precise brake-and-redirect relation unresolved.')},
5:{'actors':('p','Two adults, front-rotated/recentered from side guide.'),'event':('u','Character-only image does not establish physical separation.'),'contact':('u','Raw hand positions are not aligned to fixed props.'),'props':('f','Prohibited staff/flask remain; injury/staff ownership hands reversed.'),'state':('f','Wound visibly on anatomical LEFT hand and staff in RIGHT; RGB checkerboard lacks alpha.')},
6:{'actors':('p','Two adults beyond separating shutter, mature worried acting.'),'event':('p','Exactly three threat legs; body west and adults east; lowered shutter intersects foreleg.'),'contact':('u','Pinned endpoint meets edge, but dark exact pressure/contact is less clear at390.'),'props':('p','Short broken staff in LEFT hand, single upright flask with Odo; discarded section visible west.'),'state':('p','Dorsal RIGHT wound persists; no invented additional wound. Exact flask design differs from adjacent candidates.')},
7:{'actors':('p','Adult pair with traceable nearer RIGHT arm and supported hand; expressive gaze.'),'event':('u','Character-only output cannot establish closed shutter.'),'contact':('p','Right-hand support visible, left hand wraps broken staff.'),'props':('f','Staff/flask included despite deliberate separate-prop layer request.'),'state':('u','Correct right dorsal injury, but RGB checkerboard and changed placement require conventional matting/composition.')},
8:{'actors':('p','Adult reciprocal gaze, supported right hand.'),'event':('f','Shutter reopened to walking-height gap with freely standing sentinel beyond.'),'contact':('f','Left hand hangs empty while broken staff appears separately leaning/floating.'),'props':('f','Broken staff not visibly held; single flask upright with Odo.'),'state':('f','Correct right wound but barrier state contradicts P13.')},
9:{'actors':('p','Both adult arms visible, still recentered.'),'event':('u','Character-only image cannot establish scene action.'),'contact':('f','Nera hands hang on separate off-axis arms, not both on staff axis; conventional arm redraw needed.'),'props':('p','Major props omitted as requested; empty grips are intended layer inputs.'),'state':('u','No premature wound, but RGB checkerboard remains zero alpha.')},
10:{'actors':('p','Two-handed bracing and adult acting clearer.'),'event':('p','Three limbs, distinct side sweep, west release and closed east shutter visible.'),'contact':('f','Enlarged actual pixels show paving between pointed toe and staff endpoint; spark implies unsupported contact.'),'props':('p','Two visible grips, one intact staff, upright chest flask, both boots on cream dry ridge.'),'state':('f','Same-forefoot lock still unresolved after final allowed retry.')},
11:{'actors':('p','Side/back Nera with traceable anatomicalRIGHT forearm; two adults.'),'event':('u','Character-only output, geometry event not established.'),'contact':('u','Empty LEFT grip and raised RIGHT injury available, but positions still need fixed-prop alignment.'),'props':('p','Staff/flask omitted this time; intended empty grips available.'),'state':('u','Correct right wound, but RGB bakedcheckerboard and scale shift remain hard layer-contract failures.')},
12:{'actors':('p','Appealing mature reciprocal gaze and reassuring hand contact.'),'event':('p','Closed shutter behind adults, no open gap or renewed free threat.'),'contact':('p','AnatomicalRIGHT hand supported and LEFT fingers visibly grip broken staff.'),'props':('p','One upright visibly capped amber flask with Odo; broken staff held by Nera.'),'state':('p','Right dorsal injury persists, no extra wound. Exact scratch/flask design differs across surrounding source images.')},
13:{'actors':('p','One dynamic airborne adult Nera and east-striding Odo.'),'event':('p','Three limbs including distinct ongoing sweep, raised shutter, eastward escape.'),'contact':('u','Ascent/brake/downward mark stronger, but down-right arrow targets doorway region rather than required forelimb.'),'props':('u','One intact staff and upright flask; flask silver rim has dark center, sealed-cap state uncertain.'),'state':('u','No premature wound/break; complete brake-to-contact path unresolved.')},
}
P.joinpath('observations').mkdir(exist_ok=True)
with locked(P):
 w=Workspace(P)
 for i,checks in rows.items():
  cid=f'C{i:05d}';c=w.get('registered',cid);out=P/'observations'/f'{cid}-lead.json'
  obs={'candidate_id':cid,'image_sha256':c['sha256'],'plan_sha256':w.plan_sha,'reviewer':'Lead AI actual-art inspection','method':'Actual native rasters; phone diagnostic/browser review only where separately recorded. Independent reviews retained separately. No human/owner acceptance.','checks':{k:{'verdict':{'p':'pass','f':'fail','u':'not_assessed'}[v[0]],'observation':v[1]} for k,v in checks.items()}}
  if not out.exists():out.write_text(json.dumps(obs,indent=2)+'\n')
  if not any(r['candidate_id']==cid and r['reviewer']==obs['reviewer'] for r in w.records('observed')):w.observe(cid,str(out.resolve()))
 for aid,reason in {'A00009':'Final S09 retry still has off-axis hanging grips and RGBcheckerboard; fixed staff requires conventional arm redraw.','A00010':'Independent enlarged finalG09retry shows actual paving gap between staff endpoint and toe; spark does not establish restraint.','A00011':'Final S13retry corrects hand laterality but remains RGBcheckerboard/zeroalpha with recentered actors; conventionalmatting/compositionrequired.','A00013':'FinalG11retry leaves down-right arrow aimed toward doorway, not clear forelimb contact; sealed flask cap uncertain from dark open-looking ellipse.'}.items():
  if not any(r['attempt_id']==aid for r in w.records('failed')):w.fail(aid,reason)
print('13 actual-raster observations registered; failure history preserved')
