from pathlib import Path
import json,hashlib,shutil
R=Path(__file__).resolve().parents[2]; P=R/'production/anchor-return'
for d in ['references','previous','prompts','calls','candidates','controls']:(P/d).mkdir(parents=True,exist_ok=True)
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,o):p.write_text(json.dumps(o,indent=2)+'\n')
OLD=Path('/mnt/c/AgentWorkspaces/anime-pipeline-directions-20260907-1230')
styles={
'01':('Nightglass','Economical fine anime ink and softly modeled handsome faces; tailored light clothing against deep navy inhabited vertical city, cyan architectural light, elegant sweeping creature silhouette. Selective sharp edges and calm values, not glossy armored fantasy.'),
'02':('Sunbreak Lancer','Warm lively ink contours with angular opaque painted planes, bright azure/cream/coral/green, expressive appealing faces and colorful cloth sails over stacked sunlit architecture. Preserve painterly edge variation, not vector-flat or glossy.'),
'05':('Iron Orchard','Matte opaque gouache brush shapes, muted earthy olive/rust/cream and smoky blue, confident adult faces, industrial orchard rails and broad rust insect-machine forms. Soft painted edges and weight, not shiny cel armor.'),
'06':('Floodline Detective','Bold coarse black-and-white brush masses, expressive dry ink selectively at contours, one hot-pink accent, monumental concrete flood architecture. Broad black water with a few deliberate white ripples. Not gray photoreal textures.'),
'13':('Red Current','Energetic manga nib contours and selective directional hatching, white paper and strong solid black shapes, sparse red combat accent. Extreme concrete ramps and angular predatory forms; retain drawing energy without covering surfaces in hatch.'),
'15':('Cathedral Engine','Antique sepia engraving on clean pale parchment; curvature-following engraved line groups model form, confident adult faces, tall bell-engine city and grand mechanical ecology. Quiet unmarked fields between selective hatch, never flatten into cel shading.'),
'17':('Hollow Cartographer','Thin even warm outlines, flat muted peach/teal/cream storybook colors, soft atmospheric distance, immense salmon aqueduct arches and walking garden ecology. Clear charming adult faces and spacious architecture, no glossy rendering.'),
'18':('Soft Thunder','Rounded exaggerated hand-painted cartoon volumes, large expressive eyes and mouth, playful shape rhythm and appealing adult bodies, turquoise/orange/coral/cream palette, blue cloud creatures and windmill hills. Broad clean color and expressive contour, not rigid armored realism.'),
'19':('Black Petal','Refined soft near-real anime facial gradients, spare black tailored silhouettes and white collars, charcoal/ivory with restrained maroon, translucent black botanical petals and elegant oval negative spaces in a glasshouse. Selective petal translucency, no opaque ivory monster armor or pervasive veins.')}
refs=[]
for sid,(name,treatment) in styles.items():
 stem=sid+('-retry' if sid=='19' else '-primary');src=OLD/'production/visual-directions/candidates'/(stem+'.png');dest=P/'references'/('anchor-'+sid+'.png');shutil.copyfile(src,dest)
 sp=OLD/'production/visual-directions/prompts'/(stem+'.txt'); dp=P/'references'/('anchor-'+sid+'-prompt.txt');shutil.copyfile(sp,dp)
 refs.append(dict(id=sid,title=name,path=str(dest.relative_to(R)),sha256=sha(dest),source_path=str(src),source_sha256=sha(src),prompt_path=str(dp.relative_to(R)),prompt_sha256=sha(dp),role='original drawing benchmark; no cast or canon approval'))
write(P/'references.json',dict(schema='AnchorReturnReferences/1',references=refs))
EN=Path('/mnt/c/AgentWorkspaces/anime-pipeline-encounter-lab-20260909-0430')
for name in ['ce-selection.json','owner-feedback.json']:shutil.copyfile(EN/'production/encounter-lab/previous'/name,P/'previous'/name)
write(P/'previous/current-feedback.json',dict(exact_latest_instruction='Go ahead and make the changes, then lets see if we can trend back towards the original artwork image of nightglass and all of hte other art styles, but with our new and improved implementations',interpretation='Global direction approval only. Prior choices are preserved byte-for-byte; new preferences remain blank. No subjects are canon.'))
subjects={
'NG':dict(anchor='01',title='The bridge that pulls back',hero='Aren Vale',opponent='Sera Voss',identity='Aren: light-skinned adult man age28, narrow angular face, gray eyes, swept midnight-blue hair with short side undercut; off-white sleeveless asymmetric knee-length split vest over fitted black high collar and tapered black trousers, a single red fastening cord at chest, slim black boots, NO plate armor. RIGHT hand carries one solid 60cm crescent-edged short sword, black straight hilt, small cyan ring in pommel. Sera: light-skinned adult woman age33, strong square face, short copper bob, burgundy sleeveless thigh-length combat coat, charcoal fitted trousers and boots, straightforward black spear with pale triangular steel point, held two-handed. Distinct mature faces and silhouettes.',world='An inhabited deep-navy vertical city skybridge: broad matte gray deck, one simple rail on each side, lift tower at frame-left end, open round doorway at frame-right end, a few cyan vertical window strips, green hanging plants and distant lower pedestrian bridges. One huge distant glass-wing ray with a broad crescent silhouette and sparse cyan nodes in the opening/ending views only. No cathedral courtyard, wet paving or pebble texture.',power=dict(name='Tension Line',description='The sword pommel casts one rigid-looking thin cyan tether to a metal anchor. It can pull along that line, never push; a slack curved line carries no force.',limitation='Closing the distance makes the tether slack; pulling also loads Aren’s shoulder and stance.',growth='Redirect the same pull around a new anchor while preserving momentum.')),
'BP':dict(anchor='19',title='When the flower takes root',hero='Ilyra Sen',opponent='The Mourning Bloom',identity='Ilyra: pale adult woman age30, elegant long oval face, narrow gray eyes, chin-length smooth dark-brown hair with one ivory underlayer visible at the nape; black fitted long split-tail coat, high white standing collar, dark pleated combat trousers, smooth silver LEFT forearm guard, slim black boots. RIGHT hand holds one slender silver single-edge saber with a simple open oval black guard; readable complete blade, no ornamental tangle. Mourning Bloom: enormous floating translucent charcoal flower, oval empty center, broad soft black petals with sparse silver edging; a long stout tapering black root descends to a single wide planted thorn foot when it attacks. No human mask, hands, ivory armor or bundles of threadlike roots. Its weight hangs above that root.',world='A tall abandoned glasshouse, black curved structural ribs against pale mist, one white doorway on the left and a broken glass arch on the right. Broad matte maroon moss floor, a few large leaves only; no wet reflections, tiled rubble or repetitive veins. The flowering creature and human face are the detailed focal forms.',power=dict(name='Root-Lock',description='The bloom must plant its thick root to launch a heavy petal strike; it cannot turn while that root remains planted; it must lift and reset the root before changing its facing.',limitation='Petals close into armor against frontal steel. The exposed weight-bearing root is vulnerable only while committed.',growth='Ilyra learns to bait the planted strike and cut its support from the flank.')),
'ST':dict(anchor='18',title='Borrow a breath',hero='Tavi Ember',opponent='The Gale Ram',identity='Tavi: light-skinned athletic adult woman age27, broad expressive face, large teal eyes, short curly coral hair tied into a high forward tuft, solid shoulders and powerful thighs; cropped turquoise sleeveless combat jacket over cream top, loose orange fighting trousers, red ankle wraps and broad cream boots. Paired rounded red combat gauntlets; LEFT gauntlet has a large cream crescent painted on its back, RIGHT gauntlet has a smooth cream circular pressure plate. Gale Ram: large living blue cloud ram, cream broad muzzle, orange circular cheeks, thick curled blue horns, four stout legs and one cloud tuft tail, readable animal construction; elastic body can squash, never duplicate legs. About twice Tavi’s standing height, expressive angry eyebrows, no armor.',world='A broad dry cream chalk ledge above green windmill hills, coral-and-cream cloud banks, simple wooden safety post at left and rounded blue boulder at right. Grass as a few broad masses, no soil grain, reflective ground or stone tiling.',power=dict(name='Stored Breath',description='Tavi’s RIGHT gauntlet compresses one wind pulse while both boots brace on solid ground. Release drives a short broad air wedge through the fist and kicks her backward.',limitation='It cannot charge while airborne; the recoil must be managed with her stance.',growth='Turn the recoil into a controlled pivot and use the next landing to reload.'))}
# Only the current beat state is sent to each generation. Later injuries and outcomes never enter earlier prompts.
beats={
'NG':[
('A city between them','extreme wide high diagonal','setup','Aren at left and Sera at right stand full figure several body lengths apart on the skybridge; her spear blocks the doorway. The distant giant glass-wing ray and city establish scale. Aren’s sword is in his RIGHT hand, no tether yet. Both have intact clothing and equipment.','no damage; no tether','two grounded adult silhouettes; separated weapons; lift left / doorway right'),
('Set the line','medium low side','preparation','Aren braces LEFT boot forward and RIGHT boot back, RIGHT sword hand close to waist. A thin straight cyan tether joins sword pommel to the metal rail post behind him at left. Sera at right advances behind a two-handed spear guard. Show the tether’s exact two endpoints and both boots.','no damage; taut tether to left rail post','sword pommel to left rail; both feet support'),
('Into the spear','wide low oblique','commitment','Aren drives forward with his legs from left toward Sera at right, overcoming the backward tether rather than being propelled by it; sword cuts outward from RIGHT hand. Sera pivots, spear shaft intercepts the sword at one crisp contact in front of her torso; both hands grip the same shaft. Aren’s backward tether is stretched straight to the left rail. Show hip rotation, bent supporting knees and compressed expressions rather than a static crossed-weapon pose.','no damage; tether stretched','one blade-to-shaft contact; Sera supports on rear foot'),
('Too close to pull','close side at torso height','counter','Sera steps hard inside Aren’s sword reach and drives the blunt spear shaft across his LEFT upper arm. His shoulder folds inward, face recoils; RIGHT sword hand remains outside her guard. The cyan tether sags in a clearly loose curve as he is crowded back toward its anchor. The off-white vest tears at the LEFT shoulder seam at this contact.','fresh tear at LEFT shoulder; slack tether','shaft against LEFT upper arm; right weapon hand traceable'),
('Give her the line','wide overhead diagonal','adaptation','Aren drops into a low turn under the spear and moves toward the right rail, RIGHT hand holding sword extended behind him; LEFT arm kept close to torn shoulder. A new straight cyan tether runs from sword pommel to the right rail post beside Sera. Sera is midway through a committed spear thrust past his former position, front foot far forward. No contact yet; show the changed line angle and gap.','LEFT shoulder seam torn; tether reanchored right','low planted pivot; missed spear clear of Aren; new right endpoint'),
('Pull across the stance','very low wide three-quarter','reversal','Aren at left plants both boots and braces against the cyan tether pulling his RIGHT sword hand toward the right rail anchor. His solid sword edge hooks beneath the middle of Sera’s spear shaft at one clear contact; the pull rotates her shaft sideways and twists her shoulders across her planted front knee. Her rear heel lifts and face reacts, not a floating ragdoll. Aren’s LEFT shoulder seam remains torn. One small concentrated cyan contact accent, broad clean ground.','LEFT shoulder torn; taut tether; Sera losing balance','sword under spear midpoint; lateral torque; rear heel lifting'),
('Catch the price','medium intimate side','recovery','Sera falls to one knee at right and catches herself with her left palm on the matte deck; spear remains in RIGHT hand pointing safely outward. Aren at left has slid into a kneel, RIGHT sword hand grounded beside his boot, LEFT arm tucked protectively against torn shoulder. Tether fades to a single short dim line at pommel; no action flare. Faces show effort and wary respect.','LEFT shoulder tear persists; tether spent; neither defeated','each body has knee/foot/hand supports; complete owned weapons'),
('The next crossing','extreme wide rear three-quarter','consequence','Aren and Sera now separated by the open doorway, both small but recognizable: off-white split vest/red cord versus burgundy coat/copper bob. Aren holds sword in RIGHT hand and guards torn LEFT shoulder; Sera leans on her intact spear. Huge quiet navy city and glass-wing ray behind them, distant people on lower bridges. No celebration, effects or repaired costume.','LEFT shoulder tear persists; no tether','quiet scale and silhouette identity; doorway remains right')],
'BP':[
('A bloom above the path','extreme wide low','setup','Ilyra stands small at left with saber in RIGHT hand, facing the enormous open Mourning Bloom hovering at right. Its thick root hangs above the floor, not planted. Pale doorway left, broken glass arch right, vast quiet maroon floor and luminous mist. Show elegant petal translucency and the oval empty center.','coat and saber intact; root unplanted','large creature versus grounded human; clear hovering gap'),
('Steel meets a closed flower','medium close oblique','failed approach','Ilyra lunges from left and strikes the bloom’s front petals with her RIGHT saber. The broad petals fold together into one dark shield and the blade visibly skids across a single silver edge. Her face reads alarm, front knee bent, rear boot drives. No cut root, no cloak tear and no flying debris.','petals closed; intact coat; root hanging','blade edge against closed petal; one planted lunging stance'),
('The root takes weight','wide side','warning','The bloom has planted its single thick root and wide thorn foot at right; the root bows under load. Petals open and draw backward to wind up a lateral sweeping strike. Ilyra retreats left, saber RIGHT, eyes on the planted root, both feet visible. A broad shadow explains the suspended mass, no attack streak yet.','root planted; petals winding up; intact coat','single support root; one visible intended sweep direction'),
('A door closes behind her','close low diagonal','counter','One broad petal edge sweeps past Ilyra’s back as she ducks and lunges forward toward the camera. It catches and tears the trailing LEFT coat tail; the torn black cloth remains attached with a clear missing triangular corner. Her RIGHT saber is held low ahead, LEFT silver guard protects her head. Creature root remains firmly planted in the background.','LEFT coat tail newly torn; root planted','petal-to-cloth contact; ducking continuous torso and limbs'),
('Outside its turn','wide overhead','recognition','Ilyra has reached the creature’s left flank near the pale doorway. She crouches with RIGHT saber beside her hip and torn LEFT coat tail visible. The planted bloom still points its closed front toward her old position at bottom-right and cannot rotate around its bowed root. Show a large open path from her to the exposed root, no attack contact.','LEFT tail torn; root fixed; bloom facing old position','clear facing mismatch and reachable exposed root'),
('Commit to the opening','medium side near ground','commitment','Ilyra pushes from her rear boot into a low sliding lunge along the open flank. RIGHT hand drives the saber toward the thick root just above the planted thorn foot; LEFT forearm guard crosses close to ribs. Blade is a handspan short of contact. Bloom petals are still extended toward the wrong side. Torn LEFT coat tail streams backward as one broad cloth shape.','LEFT tail torn; root intact but exposed','blade approaching root; supported slide, no severing yet'),
('Remove the support','wide low impact','reversal','The RIGHT saber has cut completely through the bloom’s single thick root just above the thorn foot. Show a clean readable gap between severed ends, planted stump below and creature body tilting heavily sideways above. Ilyra finishes the low cut with both boots skidding in one direction, torn LEFT coat tail behind. Broad petal mass buckles toward the floor, a few large maroon leaves displaced, no blood or confetti.','root severed; LEFT tail tear persists','clean cut gap; heavy tilted center of mass; follow-through'),
('A living thing, fallen','wide quiet eye level','consequence','Mourning Bloom rests collapsed on its side at right, broad translucent petals folded on the matte moss; the severed root stump remains upright nearby. Ilyra at left kneels with RIGHT saber tip resting on the ground and torn LEFT coat tail pooled behind. Her face is shaken, not triumphant. Pale doorway and broken arch retain geography; empty oval center still visible within folded petals.','root severed; creature down; LEFT tail torn','resting mass grounded; intact sword and anatomical arms')],
'ST':[
('The ram owns the ridge','extreme wide bright low','setup','Tavi stands at left facing the towering blue Gale Ram at right on the chalk ledge. Her RIGHT gauntlet circular pressure plate and LEFT cream crescent mark are visible. Four ram legs all clearly grounded, cheeks relaxed. Tiny windmills and green hills below establish size, playful menace and open air.','gauntlets intact and uncharged; ram relaxed','two sizes; four ram feet; Tavi both boots'),
('Plant before the breath','medium low frontal three-quarter','preparation','Tavi widens her stance, both boots flat, bends knees and draws RIGHT gauntlet to her ribs; its cream circle compresses a small clean white wind disk. LEFT crescent-marked glove guards her chin. Gale Ram in background puffs orange cheeks and lowers its head. Big expressive determined grin, no all-over aura.','RIGHT gauntlet charging; intact; ram inhales','two braced boots; right pressure plate; left guard'),
('The floor leaves her','wide profile airborne','counter','Gale Ram exhales one broad pale wedge of wind from its mouth toward Tavi. Tavi is knocked backward into the air, knees tucked and mouth shocked open. RIGHT pressure disk visibly disappears, both gauntlets intact; LEFT crescent clearly remains on LEFT glove. Ram keeps four legs planted and inflated body tilts forward. Quiet background, one wind wedge.','airborne; charge lost; equipment intact','mouth-source wind to torso; no phantom support'),
('Make a landing','close low dynamic','recovery','Tavi lands with her RIGHT boot scraping a broad chalk streak, LEFT boot coming down behind, hips turning to absorb the blow. LEFT crescent glove braces flat on ground and receives a large chip at its knuckle edge; RIGHT circular glove stays near chest. Face clenched, a single broad dust ribbon trails from her right boot. Ram blurred only by simplified distance, no surface grain.','LEFT crescent gauntlet newly chipped; RIGHT intact; no charge','right foot + left hand support; true anatomical side'),
('An empty breath','wide high oblique','opening','Ram’s cheeks are visibly deflated and mouth open as it finishes its long straight exhale toward Tavi’s old position. Tavi has pivoted beside its flank at left, both boots planted, RIGHT gauntlet at ribs rebuilding one small white pressure disk; chipped LEFT crescent glove guards face. Ram cannot immediately inhale again. Clear empty blast lane away from her.','LEFT chip persists; RIGHT recharging; ram exhale ending','side position outside wind lane; both boots grounded'),
('Hit the weight','very low close wide impact','reversal','Tavi’s RIGHT circular gauntlet drives into the Gale Ram’s lower cheek at one clear contact. Her forward boot remains planted, rear leg drives, hips and shoulders turn. One short broad white air wedge at the fist compresses the ram’s cheek and lifts its near front hoof; its eyes bulge, horns tilt with skull, four legs remain traceable. Chipped LEFT crescent glove stays tucked by Tavi’s ribs.','RIGHT pulse released; LEFT chip persists','right fist-to-cheek compression; planted driving stance'),
('Ride the recoil','wide diagonal','cost','The recoil sends Tavi sliding backward on both boots, knees bent, RIGHT glove pulled back from spent punch. Chipped LEFT crescent glove extends for balance. Ram stumbles sideways with forelegs crossing awkwardly but anatomically traceable, rear feet catching its mass; cheeks deflated and expression indignant. Two broad opposed movement arcs, no particles.','pulse spent; LEFT chip persists; ram off balance','opposed recoil directions; grounded sliding feet'),
('Nobody looks dignified','medium warm eye level','consequence','Tavi sits on the quiet chalk ledge laughing breathlessly, inspecting chipped LEFT crescent gauntlet with intact RIGHT glove. Gale Ram sits a few paces away with all four limbs naturally folded, flattened cheek and sulky raised eyebrow, clearly alive. Windmill hills and coral clouds return, no effects. Tavi still visibly an athletic adult, no childlike proportions.','LEFT chip persists; RIGHT intact; no charge; ram recovering','quiet readable hands, resting ram anatomy, personality')]
}
entries=[]
for seq,rows in beats.items():
 for n,(title,scale,beat,brief,state,contact) in enumerate(rows,1):
  entries.append(dict(id=f'{seq}{n:02d}',title=title,category='encounter',group='encounter',sequence_id=seq,sequence_order=n,beat=beat,scale=scale,drawing_direction=styles[subjects[seq]['anchor']][0],anchor_id=subjects[seq]['anchor'],subjects=[subjects[seq]['hero'],subjects[seq]['opponent']],caption=title+'. '+brief,brief=brief,current_state=state,contact_contract=contact,power=subjects[seq]['power'],references=[subjects[seq]['anchor'],seq+'-SHEET',f'{seq}{n:02d}-CONTROL'],continuation_dependencies=[f'{seq}{n-1:02d}'] if n>1 else [],paired_ids=[],owner_approval=None))
singles=[
('SB','02','Turn the sunlight','wide low rooftop diagonal','A new light-skinned adult male lancer with a freckled long face, wavy auburn hair tied back, cream short battle cape over coral light armor and green fitted trousers vaults a broad blue-and-green spear across the shoulder of a huge mirror-glass feline lunging past him. His two hands grip a single complete shaft; one boot pushes from a cream rooftop edge, the other leg folds naturally. The spear’s broad sunlit blade projects one flat warm wedge that redirects the cat’s next leap toward an empty sail rather than distant pedestrians. Colorful suspended cloth sails and stacked cream city against azure sky. Cat built from a few large angular transparent planes, no tiny shattered facets.','Sun Wedge: a spear can redirect a leap only while its blade catches direct sunlight; shade cancels it. Growth: choose the angle rather than increase glare.'),
('IO','05','Brace the orchard gate','wide ground-level side','A new imposing light-skinned adult woman age40 with strong brow, short silver undercut and warm dark eyes, ochre sleeveless padded combat coat, olive trousers and broad rust-red armored gauntlets braces one boot against a rail sleeper and catches the thick forelimb of a huge rust beetle-machine with both gauntlets. Her shoulder drives under its joint, twisting it sideways until the near leg buckles. A short broad combat cleaver remains sheathed at her hip, readable complete silhouette. Orchard rows, elevated rail truss and industrial gate recede in broad painted masses; dry matte earth, no grit speckle. Beetle has readable paired mechanical legs and a single green face lamp.','Load Turn: gauntlets grip one joint and redirect weight only while her stance is braced; she cannot lift the machine outright. Growth: chain balance breaks.'),
('FL','06','Close the floodgate','extreme wide steep diagonal','A new lean light-skinned adult woman age38 with severe cheekbones and short swept black hair, white high-collared short combat coat over black armor and high boots, drives a straightforward long hooked battle spear with both hands through the open hinge of an enormous black umbrella-serpent emerging from broad black floodwater. Both feet planted on a concrete gate ledge, torso twists under the load. The serpent’s broad umbrella ribs fold inward where the hook catches, white face recoils. One hot-pink rectangular gate signal only; stark monumental concrete arches and broad water blacks, sparse white ripples, no repetitive spray.','Hinge Bind: the hook locks a moving joint only at full extension; mistiming lets it close on the shaft. Growth: read the release rather than overpower the creature.'),
('RC','13','Break the spiral','wide extreme foreshortened manga angle','A new light-skinned athletic adult man with an angular smiling face and long black hair in a compact braid, white sleeveless combat jacket over black fitted trousers, red rigid fighting gauntlets, punches a giant folded white ray-shark’s jaw upward as it dives through a concrete spiral ramp. His RIGHT fist visibly compresses the lower jaw at one contact, LEFT guards ribs, rear foot drives and front knee bends. Red is limited to gauntlets and one decisive impact wedge. The creature’s wings are broad black-and-white sheets with a few purposeful fold lines; distant ramp spirals give scale, no shard storm or all-over hatching.','Rising Fault: the punch redirects an incoming downward force upward; weak against a stationary target. Growth: exploit faster threats with better timing.'),
('CE','15','Unseat the bell','wide low theatrical','A new regal light-skinned adult woman age45 with an aquiline face, silver braid, dark fitted long coat with cream lapels and split riding skirt over trousers, holds a large plain brass round shield in LEFT hand and compact flanged war mace in RIGHT. She drives the shield beneath a giant walking bell engine’s bent front leg while striking its pivot with the mace; her knees bend and both boots brace. The bell tilts bodily and one leg lifts, not a weightless explosion. Vast engraved bell-city towers rise behind in pale atmospheric layers. Sepia line groups curve around brass forms; broad untouched parchment ground, no checkerboard or metallic glints.','Counterweight: shield catches a loaded leg while mace releases its hinge; it requires the enemy’s own step. Growth: interrupt several linked machines through their rhythm.'),
('HC','17','Hold the walking garden','extreme wide airy side','A new appealing light-skinned adult woman with a round determined face and a mass of warm brown curls, teal short cloak over cream light combat armor, orange sash and blue trousers, uses a plain long silver spear and small round teal forearm shield to pin a thick root-serpent against an aqueduct parapet. Both hands hold the spear; shield is strapped to LEFT forearm. Her feet brace on the salmon walkway, serpent neck bends visibly at spear pressure, no puncture gore. Beyond the enormous salmon arches, an immense walking garden tortoise carries a few trees and a small white tower through blue air; its long rootlike legs remain simple and readable. Spacious warm storybook flat colors, calm floor and thin even outlines.','Root Still: planted spear can halt a moving root briefly while both hands hold pressure; leaving the brace frees it. Growth: create safe passages through living terrain.')]
for sid,anchor,title,scale,brief,power in singles:
 entries.append(dict(id=sid+'01',title=title,category='anchor-study',group='anchor-study',sequence_id=None,sequence_order=None,beat='decisive moment',scale=scale,drawing_direction=styles[anchor][0],anchor_id=anchor,subjects=[title],caption=title+'. '+power,brief=brief,current_state='Standalone original moment; no prior cast or canon selected.',contact_contract='Visible support, clear weapon construction and causal target reaction.',power=dict(name=power.split(':')[0],description=power,limitation='See description.',growth='See description.'),references=[anchor],continuation_dependencies=[],paired_ids=[],owner_approval=None))
plan=dict(schema='AnchorReturnPlan/1',experiment_id='AR-20260909-01',base_commit='4ce4ba4f01e507bdd5c0253351250ce5030441b7',hypothesis='Original drawing systems and world appeal can return without surrendering clean surfaces or the clarity of controlled eight-beat action. Cast sheets and editable layout controls are tested as aids, not evidence of successful generated anatomy or owner approval.',budget=dict(primary=30,support=3,repair=6,texture=30,total_native=69,no_art_retries=2,total_invocations=71,direct_paid_spend_usd=0,max_repair_per_image=1,max_texture_per_image=1),styles={k:dict(name=v[0],treatment=v[1]) for k,v in styles.items()},subjects=subjects,sequences=[dict(id=k,title=v['title'],entries=[e['id'] for e in entries if e['sequence_id']==k]) for k,v in subjects.items()],entries=entries,support_entries=[dict(id=k+'-SHEET',title=v['title']+' — cast and equipment',category='support',sequence_id=k,anchor_id=v['anchor'],brief=v['identity'],owner_approval=None) for k,v in subjects.items()],policy=dict(current_state_only=True,protected_damage=True,matte_ground=True,prior_choices_readonly=True,new_preferences_blank=True,canon=None,primary_reference_roles=['original drawing system','compact subject identity','editable pose/contact/geography control'],external_comic_generation_references=False))
assert len(entries)==30 and len({e['id'] for e in entries})==30
write(P/'plan.json',plan);(P/'plan.sha256').write_text(sha(P/'plan.json')+'\n')
print(json.dumps(dict(entries=len(entries),support=3,plan_sha256=sha(P/'plan.json'),references=len(refs))))
