from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[2];P=R/'production/anchor-return';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();rows=[]
repairs={
'ST-SHEET':('Native main figure has crescent on anatomical RIGHT and circle on LEFT; hairstyle repeats the original rope-like locks instead of the new compact curls. Correct foundation before eight linked scenes.','Edit this cast sheet using the attached image as the sole source. Preserve the face, adult athletic build, outfit, rounded painted drawing, colors, full body pose, ram design and clear four legs. Make this targeted identity/equipment correction: on the MAIN front-facing woman, the glove at VIEWER LEFT is her anatomical RIGHT and must have the plain cream CIRCLE pressure plate; the glove at VIEWER RIGHT is her anatomical LEFT and must have the cream CRESCENT. Swap only those glove-back symbols, do not mirror the woman or swap her limbs. Keep one circle and one crescent in the two separate equipment close-ups. Replace her long rope-like coral locks with SHORT rounded coral curls gathered into a compact high forward tuft, retaining the shaved side and expressive face. The new hairstyle must not hang across the shoulder. No chipped gloves, injuries or activated magic. Everything else stays the same; one complete corrected sheet, no labels.'),
'NG-SHEET':('Native sheet adds a wrist crescent blade and separate cyan wrist ring, competing with the sole sword-pommel power origin. Correct foundation before linked scenes.','Edit this cast sheet using this image alone. Preserve both adult identities and faces, hair, tailored off-white and burgundy clothing, poses, long city-ray creature silhouette, and the actual fine Nightglass drawing. Remove ALL hard plated forearm armor, the large crescent blade attached to the man’s RIGHT wrist, and all cyan wrist-ring devices. Both people wear simple smooth black gloves and plain fitted dark wrist cuffs. His RIGHT hand continues holding the SAME complete curved short sword; the cyan circle in its POMMEL is the sole magical ring and must remain clearly visible. Preserve the woman’s single complete spear and her two correct grips. Remove the two floating wrist/gauntlet detail inserts from the center entirely, leaving quiet background there; retain the complete standalone sword and spear details below. Do not add replacement equipment or ornament. Do not mirror, change faces, redesign weapons, or simplify the drawing treatment. Return one corrected sheet, no labels.'),
'BP-SHEET':('Native duplicate back view puts guard and sword on inconsistent anatomical sides, offering contradictory identity conditioning. Main front view is the usable reference.','Edit this cast sheet using the attached source alone. Keep the LEFTMOST FRONT-VIEW woman exactly: same compelling adult face, soft drawing, short dark hair, black tailored coat, pale white collar, RIGHT hand holding the saber at viewer left, silver guard on anatomical LEFT forearm at viewer right. Remove the entire duplicate BACK-VIEW woman in the middle. Remove the two floating glove/gauntlet detail inserts above the center. Leave quiet neutral ground in those areas; do not add a new pose or replacement objects. Keep the complete single saber detail and the entire flowering creature at right with its oval void, broad translucent petals and one thick root terminating in a thorn foot; it remains a neutral unplanted reference pose with a visible gap under the foot. Preserve all remaining silhouettes, faces, material qualities and colors. One clean corrected cast reference sheet, no lettering or new ornament.')}
for id,(reason,prompt) in repairs.items():rows.append(dict(source_attempt_id=id+'-P',attempt_id=id+'-R1',phase='repair',reason=reason,prompt=prompt))
master=(Path('/home/gosnerp/.codex/skills/texture-refinement/references/master-prompt.txt')).read_text()
surfaces={
'SB01':('the expressive freckled lancer face and hair silhouette, both spear grips and continuous shaft, planted foreground boot and folded leg, airborne feline anatomy and glass material, all colorful sails and layered city depth','the feline’s many tiny triangular mosaic facets: replace their interiors with a few broad translucent angled light planes inside exactly the same animal contour; remove dense scratches from cream walls, cloth sails, cape, armor and trousers. Keep warm angular painted edges and joyful saturation. The foreground roof must stay matte cream, with only structural seams and broad shadow, not a polished wet slab.'),
'IO01':('the strained mature face, both gauntlet grips around the same bent insect joint, wide braced legs and rail contact, the beetle’s readable legs and green face lamp, orchard/rail silhouettes and opaque gouache treatment','repeated tiny rust flecks and scratches over every metal plate; retain large rust-versus-painted-metal color patches and meaningful joints. Quiet ground pebbles, tiny grass and orchard leaf stippling into broad earth/foliage masses. Preserve dry earthy matte materials and visible painted brush shapes; never turn this into glossy cel-shaded armor.'),
'FL01':('expressive angular adult face, both hands on the continuous hooked spear and actual open-mouth contact, braced boots on ledge, umbrella ribs and serpent silhouette, pink signal and monumental concrete scale','all-over vertical scratch streaks on concrete, garment micro-scuffs and repeated spray marks. Keep bold coarse brush contour edges and selected expressive dry-brush accents, but interior walls should be broad paper-white/black masses. Water should remain broad black with a few existing purposeful white ripples, never gray gloss or fine rippled reflection. Preserve this rough brush drawing’s identity.'),
'RC01':('the grinning face and long braid, actual punching arm and clenched glove-to-jaw contact, red impact wedge, guarded second hand, wide braced stance and creature jaw compression, immense spiraling ramp composition','pervasive concrete scrape lines, floor crack/scratch texture and noisy cloth highlights. Retain selected energetic nib strokes and directional hatch at form turns, solid blacks and clean white areas. Keep the few decisive red marks sharp; do not reduce the contact to a faint glow or add a general aura. Ground stays drawn matte concrete.'),
'CE01':('regal mature face, silver braid, shield grip and right mace contact at mechanical pivot, braced boots, lifted machine leg, huge bell silhouette, sepia engraved medium and city depth','all-over small engraved ornament, equal-weight distant city lines and densely marked floor stones. Use quiet unmarked parchment ground inside existing perspective and broad atmospheric intervals between the architecture. Keep purposeful curvature-following line groups on bell, shield and clothing so this remains engraving, not smooth cel art. Do not erase mechanical joints or change brass to plastic.'),
'HC01':('determined adult face and curly hair outline, two hands holding one spear and strapped left forearm shield, boots and stance, spear pressure against root-serpent neck, huge walking garden-tortoise and salmon arch scale','the root-serpent’s many tiny bark strips and leaflets into a few broad twisting wood masses with selective large leaves; quiet leaf stippling everywhere and floor microcracks/grain. Keep thin warm contours, flat storybook colors, soft distance and broad matte peach walkway; no glossy shadows, airbrushed realism or uniformly blank environment.')}
for id,(protected,focus) in surfaces.items():
 prompt=master.replace('[name the features you love and must keep]',protected).replace('[name the specific surfaces or effects that feel too busy]',focus)
 rows.append(dict(source_attempt_id=id+'-P',attempt_id=id+'-F1',phase='texture',reason='Actual native source inspected: distracting repeated surface marks compete with face/contact. Targeted source-preserving finishing preserves this direction’s own medium; no structural edits.',prompt=prompt))
for e in rows:e['source_sha256']=sha(P/'candidates'/(e['source_attempt_id']+'.png'))
out=R/'research/anchor-return/first-edit-evidence.json';out.write_text(json.dumps(rows,indent=2)+'\n');print(out)
