from pathlib import Path
import json,hashlib,sys
R=Path(__file__).resolve().parents[2];P=R/'production/anchor-return';plan=json.loads((P/'plan.json').read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert sha(P/'plan.json')==(P/'plan.sha256').read_text().strip()
refs={x['id']:x for x in json.loads((P/'references.json').read_text())['references']}
def bind(path,role):return dict(path=str(path),sha256=sha(R/path),role=role)
jobs=[]
for id in sys.argv[1:]:
 support=id.endswith('-SHEET');e=next(e for e in plan['support_entries' if support else 'entries'] if e['id']==id);a=e['anchor_id'];style=plan['styles'][a]['treatment'];references=[bind(refs[a]['path'],'Original drawing treatment and world benchmark; not existing character identity or board layout')]
 base='Create a NEW original progression-fantasy illustration, with adult subjects. The first reference is an original drawing-direction benchmark. Preserve its actual medium, line quality, face appeal, color hierarchy and atmosphere. Do not reproduce its character, costume, weapon, layout or scenery literally. This is a new cast and a new moment, not selected canon.\nDRAWING TREATMENT: '+style+'\nSURFACE HIERARCHY: broad quiet material shapes and readable silhouettes; concentrate detail on faces, signature equipment and the action contact. Preserve medium-specific marks selectively. Matte ground, no wet reflections, pebble grids, micro-scratches, all-over grain, pervasive veins or particle confetti. Rich world design is welcome; surface noise is not.\n'
 if support:
  s=plan['subjects'][e['sequence_id']]
  prompt=base+'Make one compact landscape cast-and-equipment reference sheet on a plain warm-neutral ground, not a scene or comic page. Show the two described subjects fully and separately, each once, plus a small uncluttered close view of the hero signature weapon/gauntlets only. Clear full silhouettes, readable adult faces, calm neutral combat-ready stance, complete weapon construction and unmistakable ownership. For a creature, show its entire construction with clear attachment points. No injury, tears, chips, activated magic, future outcomes, captions, lettering or diagrams. A neutral cast sheet should preserve the original drawing personality instead of generic glossy concept-art rendering.\nSUBJECTS: '+s['identity']+'\nFor paired gauntlets, show the LEFT crescent and RIGHT circular plate on their correct anatomical hands. Botanical root unplanted; ram cheeks relaxed. No world background.'
 else:
  prompt=base+'Deliver one complete cinematic narrative artwork, no panels, collage, text, labels or diagrams. Camera: '+e['scale']+'.\n'
  if e['sequence_id']:
   s=plan['subjects'][e['sequence_id']];cands=json.loads((P/'candidates.json').read_text())['candidates'];sel=json.loads((P/'selected.json').read_text())['selected'];sheet=next(c for c in cands if c['attempt_id']==sel[e['sequence_id']+'-SHEET']);controls=json.loads((P/'controls/manifest.json').read_text())['controls'];ctl=next(c for c in controls if c['id']==id)
   references+=[bind(sheet['path'],'New cast/equipment identity reference only; draw a genuinely new composition'),bind(ctl['png_path'],'Editable pose, support, contact and geography layout; staging only, never copy labels or diagram rendering')]
   prompt+='The SECOND reference fixes our new subject identities, faces, costumes, creature construction and equipment. The THIRD is a simple action-layout control: use its geography, support, limb chains and contact intent; its perspective is schematic. Honor the explicit cinematic camera and framing above, rather than flattening every scene into a side-view stage. Finish everything in the FIRST reference’s drawing treatment. Labels, arrows, colored diagram joints and text must not appear in the artwork. Refine a schematic pose into convincing anatomy; do not treat a diagram as permission for dislocated anatomy.\nSUBJECT IDENTITY: '+s['identity']+'\nWORLD: '+s['world']+'\n'
  if e['sequence_id']=='ST':prompt+='For handed equipment, the full-body subject in the SECOND reference is authoritative: anatomical RIGHT circle, LEFT crescent. The isolated glove inserts show symbol surfaces only and must not determine handed anatomy.\n'
  prompt+='THIS MOMENT ONLY: '+e['brief']+'\nCURRENT VISIBLE STATE ONLY: '+e['current_state']+'\nCONTACT AND SUPPORT: '+e['contact_contract']+'\nThe image must communicate the immediate physical cause and reaction without needing its caption. Keep weapon shafts continuous, hands correctly attached, grip consistent, feet or deliberate flight readable, creature construction stable. Faces should be compelling and expressive. Complete main forms unless camera cropping is deliberate; no accidental missing limbs. Do not add damage or effects not described in this moment.'
 attempt=id+'-P';path=P/'prompts'/(attempt+'.txt');assert not path.exists();path.write_text(prompt+'\n')
 jobs.append(dict(id=id,attempt_id=attempt,phase='support' if support else 'primary',prompt=prompt+'\n',prompt_path=str(path.relative_to(R)),prompt_sha256=sha(path),plan_sha256=sha(P/'plan.json'),references=references))
out=P/('jobs-'+sys.argv[1]+'-'+sys.argv[-1]+'.json');out.write_text(json.dumps(jobs,indent=2)+'\n');print(out)
