"""Small actual-art before/after handoff; no generated thumbnails or acceptance scores."""
from pathlib import Path
import json,hashlib,html,os
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/research/structural-pilot';OUT.mkdir(exist_ok=True)
routes={}
for name,path in [('B','reader/route-B.json'),('G','correction-reader/route-G.json'),('CF','correction-reader/route-CF.json')]:
 p=OUT/path;routes[name]={r['id']:(r,p.parent) for r in json.loads(p.read_text())['panels']}
notes={'P09':('The staff now meets the forefoot.','Two grips, dry footing and the separate sweep remain. Exact same-machine/same-room continuity is still weakened by the surrounding design changes.'),'P11':('The sweep and eastward escape are readable.','A thin body-motion trace points toward the forelimb, and the flask has a closed cap. The lower trajectory is subtle at phone size.'),'P13':('Three legs and the correct injury side persist.','The lowered barrier divides threat and adults; a small local correction clarifies the pinned endpoint. The phone-scale gain is modest.'),'P14':('The aftermath keeps the right hand and closed shutter.','Nera visibly holds the broken staff in her left hand. This is the unchanged generated retry, included as a reference; no local art correction is claimed.')}
bindings=[];sections=[]
for pid in ['P09','P11','P13','P14']:
 cards=[]
 for name,label in [('B','Before · preserved baseline'),('CF','After · selected experimental proof')]:
  panel,base=routes[name][pid];c=panel['candidate'];p=base/c['src'];sha=hashlib.sha256(p.read_bytes()).hexdigest()
  if sha!=c['sha256']:raise ValueError('Actual display source mismatch')
  src=os.path.relpath(p,OUT).replace(os.sep,'/');bindings.append({'panel':pid,'version':name,'path':p.relative_to(ROOT).as_posix(),'sha256':sha})
  cards.append(f'<figure><figcaption>{label}</figcaption><a href="{src}" aria-label="Open {pid} {label} at native resolution"><span class="canvas" style="--h:{panel["target_css_height_at390"]};height:{panel["target_css_height_at390"]}px"><img src="{src}" alt="{pid} {html.escape(panel["function"])} — {label}" width="390" loading="lazy"></span></a></figure>')
 panel,base=routes['G'][pid];c=panel['candidate'];p=base/c['src'];src=os.path.relpath(p,OUT).replace(os.sep,'/');sha=hashlib.sha256(p.read_bytes()).hexdigest()
 if sha!=c['sha256']:raise ValueError('Generated source mismatch')
 bindings.append({'panel':pid,'version':'G','path':p.relative_to(ROOT).as_posix(),'sha256':sha})
 title,note=notes[pid]
 source_label='Unchanged generated reference' if pid=='P14' else 'Generated source before local correction'
 source_note='This source is identical to the selected after image. No local art correction is claimed.' if pid=='P14' else 'The generated source is preserved alongside the editable local correction versions.'
 sections.append(f'<section id="{pid}"><h2>{pid} · {title}</h2><p>{note}</p><div class="pair">'+''.join(cards)+f'</div><details><summary>{source_label}</summary><img class="source" src="{src}" alt="{pid} — {source_label}" loading="lazy"><p>{source_note}</p></details></section>')
style='''body{margin:0;background:#f5f3ec;color:#202a2e;font:16px/1.5 system-ui,sans-serif}main{max-width:1160px;margin:auto;padding:24px}h1{font-size:clamp(26px,4vw,42px);line-height:1.12;max-width:850px}h2{font-size:22px;margin-top:0}p{max-width:820px}a{color:#174e87}nav{display:flex;gap:16px;flex-wrap:wrap;margin:20px 0}.pair{display:flex;gap:22px;flex-wrap:wrap}figure{margin:0;width:390px;max-width:100%}figcaption{font-weight:650;padding:10px 0}.canvas{display:flex;width:390px;max-width:100%;align-items:center;justify-content:center;background:#fff;box-shadow:0 0 0 1px #c8cec9;overflow:hidden}.canvas img{width:100%;height:100%;object-fit:contain}.source{display:block;width:390px;max-width:100%;height:auto}section{margin:30px 0;padding:24px 0;border-top:1px solid #bdc6c4}details{margin-top:18px}summary{cursor:pointer}footer{border-top:1px solid #bdc6c4;margin-top:32px;padding-top:16px;color:#536061}.kicker{font-size:13px;letter-spacing:.1em;text-transform:uppercase;color:#536061}.callout{padding:16px;background:#e4ebe9;border-left:4px solid #456e70;max-width:820px}@media(max-width:430px){main{padding:14px}.canvas{width:100%;height:auto!important;aspect-ratio:390/var(--h,390)}.canvas img{height:100%}.pair{gap:16px}figure{width:100%}}'''
# Phone comparison stays native-width up to390 and uncropped. Dedicated reader retains
# exact planned390px canvases/lettering; this compact page is explicitly art-only.
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Before and after · Three Charges, One Dose</title><style>'''+style+'''</style><main><p class="kicker">Original webtoon experiment · September 7, 2026</p><h1>Better local action and damage continuity. The sequence still needs a consistent drawing pass.</h1><p>These are actual preserved images. The local corrections use explicit editable masks, source-pixel repair and drawn paths. No quality score or geometry check substitutes for the visible result.</p><nav><a href="correction-reader/index.html">Read the proof in context</a><a href="correction-reader/index.html?view=compare">Compare local corrections with lettering</a><a href="reader/index.html?view=compare">Inspect all three original screen routes</a><a href="../../../research/structural-pilot/START_HERE.md">Handoff and evidence</a></nav><p class="callout">Art-only comparison below. Exact original copy and editable lettering are in the reader. All versions remain unaccepted; no independent human comprehension or owner-preference test has run.</p>'''+''.join(sections)+'''<footer>Generated rasters remain local and ignored; source hashes, exact instructions and editable drawing recipes are tracked. A fresh clone needs the local art bundle. <a href="comparison-bindings.json">Image bindings</a> identify files, not artistic acceptance.</footer></main></html>'''
(OUT/'comparison.html').write_text(page);(OUT/'comparison-bindings.json').write_text(json.dumps({'schema':'ActualArtComparison/1','bindings':bindings,'art_acceptance':None},indent=2)+'\n');print(OUT/'comparison.html')
