from pathlib import Path
import hashlib,json
R=Path(__file__).resolve().parents[2];P=R/'production/scale-conflict'
entries=[]
def add(id,title,category,scale,subjects,path,caption,brief,refs,power=None):
    entries.append(dict(id=id,title=title,category=category,scale=scale,subjects=subjects.split(),story_path=path,caption=caption,brief=brief,references=refs.split(),power=power,owner_approval=None))
def power(name,description,limitation,growth):return dict(name=name,description=description,limitation=limitation,growth=growth)
seam=power('Borrowed Horizon','A saber stroke opens a short seam between two visible edges; Riven steps across the missing distance.','Both ends must be visible and the exit must support his weight; one seam at a time.','Move an ally through a held seam, then redirect a committed attack through a carefully placed exit.')
harbor=power('Quiet Harbor','Neris catches one pressure front against her braced crescent shield and returns it through a shield drive.','She must brace and face it; a broken stance or open flank spills the stored force.','A momentary still pocket for a team; later a precisely aimed return of a colossal pressure front.')
winter=power('Deep Winter','Kellan draws a continuous blade stroke through existing water, raising a directed ice restraint or ramp from its path.','Needs connected water and blade contact; cannot freeze dry air or distant targets.','Sculpt stronger flowing water into a temporary bridge, then redirect a larger charge with its shape.')
axis=power('Downfall Writ','Ilyra plants her Axis Lance in stone and turns the direction of weight inside one broad bounded plane.','The planted lance anchors the effect; she must remain within reach, and allies inside the plane are affected too.','Tilt a small attack corridor, then redirect a giant limb or falling district at greater physical cost.')

add('V01','The Gate Below the Clouds','vista','extreme-wide','riven neris','arrival','A city big enough to make two fighters feel like arrivals again.',
'Extreme-wide rear three-quarter view from a high causeway. Riven and Neris are SMALL complete figures, about 8 percent of image height, separated against a broad pale approach road at lower center. Their silver hair/petrol cropped jacket/saber and ivory shoulder cape/teal tunic/crescent shield distinguish them without face close-ups. They walk toward Vesper Reach: an immense vertical inhabited city whose vast open ring gate bridges a gulf beneath cloud level. Huge connected charcoal façades, pale structural ribs, sparse grouped cyan windows, a few clear bridges; foreground/middle/distant planes. Cool early dawn with a warm strip inside the gate. Let architecture occupy most of the frame. No giant foreground hero, portrait inset or texture carpet.','riven neris')
add('V02','A Road Across the Sleeper','vista','aerial-wide','riven kellan','arrival','What looked like a ridge takes its first breath.',
'Very high oblique aerial view, looking down across a vast living slate-backed leviathan half submerged in a clear teal inland sea. A narrow old causeway runs over a broad smooth section of its back toward distant inhabited towers. SMALL Riven and Kellan, each about 6 percent of frame height, stand apart on the pale causeway; identify silver/petrol/saber versus black curls/sand cobalt coat/straight sword. A single enormous eye opens below and to the side of their path. Broad dark hide plates and coherent pale shoreline shapes, calm water reflection bands, immense organic scale, no dense scales or rubble. This is discovery, no attack or random particle magic.','riven kellan')
add('V03','The River Overhead','vista','vertical-wide','riven','arrival','The city carries its river above the street.',
'Portrait vertical composition looking up through an enormous open-bottom aqueduct district. Riven is a small complete three-quarter figure at the bottom, roughly 10 percent of picture height, staring upward with saber sheathed at his hip. Above him a single wide suspended river passes between massive pale arches; the transparent underside shows a few enormous soft fish silhouettes. Dark inhabited platforms and a broad shaft of late afternoon light establish miles of depth. Character remains identifiable through silver hair, cropped petrol coat, dark trousers and saber silhouette; no portrait inset. Calm large stone and water forms, a specific usable stair toward the river edge.','riven')
add('V04','The Orchard Above the Drop','vista','wide','neris kellan','arrival','A place worth defending needs room for an ordinary morning.',
'Broad sunlit horizontal view of terraced gardens cantilevered over a huge city gulf. Neris and Kellan are complete figures about 14 percent of frame height, walking together along a pale terrace path with weapons carried safely, white/teal/crescent against sand/cobalt/straight blade. A small flock of wide-winged pale seed gliders grazes among a few sweeping orchard tree masses. Warm cream stone, dusty green foliage, cool shadow depths and quiet red fruit clusters; far inhabited towers visible through the open edge. Convey ease and character chemistry, not posed combat. Group foliage and stone into large designed shapes; no individual-leaf carpet.','neris kellan')
add('V05','Under the Bell of Teeth','vista','extreme-wide','riven neris bellmaw','fracture','The thing beneath the bridge is large enough to answer the city.',
'Extreme-wide threat reveal inside the open lower basin of Vesper Reach. Riven and Neris, SMALL at about 7 percent height, stand on a pale bridge in the lower left with clear separate silhouettes. Across the basin towers the Bellmaw: an immense four-legged organic predator, long weight-bearing forelegs, lower powerful hindlegs, low wedge face beneath a broad smooth black mantle, pale throat pouch like the underside of a deep-sea ray, one long heavy tail. Its open mouth is a broad dark crescent with a few great pale teeth; not a humanoid, not a machine. One massive forefoot rests beside a bridge pier to prove scale. City arches are dwarfed by its back. Quiet dark plates, no mosaic cracks. Side-lit evening with pale water and violet shadow masses. Mouth is open but no beam yet. One coherent panoramic scene.','riven neris')
add('V06','The City Moves at Dawn','vista','extreme-wide','riven neris ilyra','fracture','A victory can still leave a city moving beneath your feet.',
'An immense wide sunrise panorama after a district shift. Riven, Neris and Ilyra stand as three SMALL distinct adults, 8 percent picture height, on an intact observation shelf overlooking a whole inhabited district sliding slowly sideways across an enormous smooth fault. Separation is shown by two broad architectural masses and a single luminous cyan seam, not rubble chaos. The moving district carries bridges, gardens and canal levels; warm dawn touches its edges. Identify silver/petrol/saber, brown/ivory shoulders/crescent and copper bob/burgundy/ivory long lance. They face different parts of the problem with wary body language; no celebration, no canon ending.','riven neris @A05')

add('T01','Three at the Threshold','ensemble','medium-wide','riven neris ilyra','arrival','The gatekeeper offers passage on terms they cannot yet accept.',
'Complete mid-distance three-person confrontation on a wide quiet gate stair. Riven and Neris stand together on the lower left, Ilyra alone one step higher at right with Axis Lance planted beside her. Figures are about 30 percent of height with space around each full weapon and feet. Riven wears a restrained crooked smile; Neris assesses the guard without flinching; Ilyra is cool, regal and unimpressed. A huge partially open pale gate frames far city depth. Early morning amber light against clean blue shadows. No attacking yet, no duplicated faces or copied reference panel layout.','riven neris @A05')
add('T02','The Price of Stillness','ensemble','medium-wide','kellan ilyra','fracture','Holding one district still means choosing what moves instead.',
'An inhabited elevated canal exchange with five clearly separated adults: Kellan at left, Ilyra at right, and three adult residents listening farther back under a broad arch. Kellan gestures angrily with his EMPTY free hand while holding the lowered sword safely in the other; Ilyra keeps her lance vertical and points her gaze toward the district beyond. Main figures 35 percent height, supporting adults smaller and distinct, no overlapping faces or hands. One broad cracked expansion joint separates two paving slabs; distant homes across water motivate the argument. Flat overcast light, restrained burgundy, sand and cool stone colors. No holographic maps, text, floating UI or particle display.','kellan @A05')
add('T03','Crossed Lines on the Canal','ensemble','medium-wide','riven kellan','fracture','One opening is enough if both fighters can read it.',
'Crisp lateral four-adult fight on a broad canal bridge: Riven at left parries one adult masked guard’s spear at an explicit single blade-shaft contact; Kellan at right ducks a SECOND distinct adult guard’s horizontal spear, his sword low and clear as he steps inside its reach. Two separated action lanes, all combatants complete about 38 percent height, full spear tips within frame. A broad low bridge rail and still water fix geography. One sharp contact accent only at Riven’s actual parry; no general sparks or motion blur. Clear hands gripping real hilts, no blade gripped by fingers. Pale side light keeps dark costumes apart.','riven kellan')
add('T04','A Hand Before the Fall','ensemble','wide','riven neris','fracture','Power matters when somebody else has run out of ground.',
'A steep three-quarter view of a separated elevated transit platform. Neris braces on the intact near edge, her shield carried on her outer arm, and firmly grips one adult passenger’s wrist with her free hand as that passenger steps across a short visible gap. Riven stands farther along the intact ledge guiding two more adult passengers toward safety with his saber sheathed. Five adults total, distinct poses, main figures around 25 percent height. Empty city gulf below, broad pale platform slabs and one tilted rail reveal danger without flying debris. The rescue contact is visible and believable; no extra hands, no bridge magically completed already.','riven neris')
add('T05','The Ground Takes Sides','ensemble','medium-wide','neris ilyra','fracture','A defender who trusts her footing meets someone who can turn it.',
'Two-adult duel with complete bodies and weapons at 45 percent height. Ilyra on the right plants the butt of her Axis Lance into a flat pale stone slab; one broad translucent violet rectangular plane spreads low across that slab. Neris on the left braces her crescent shield, one boot still planted on ordinary stone outside the plane while her other leg is pulled sideways inside it; her body visibly strains against changed weight. No airborne rubble field, no double crescent or missing lance endpoint. Side view makes the boundary, lance source and unequal footing legible. Huge quiet training court with a distant city wall.','neris @A05',axis)
add('T06','Nobody Calls It Fear','ensemble','close','riven neris kellan','fracture','The joke lands because all three know how close it was.',
'Intimate candid three-adult chest-up scene at a sheltered low wall after conflict, no portrait sheet. Riven left leans back with a small exhausted crooked smile; Neris center gives him a skeptical sideways look; Kellan right laughs breathlessly, black curls tousled. Keep three distinctive faces, hairlines and costume collars: silver/petrol, brown/ivory shoulder cape/teal, black curls/sand cobalt. Hands are few and visible resting naturally, weapons set safely below the crop rather than entering faces. Broad dusk city lights far behind, clean facial planes and specific expressions; no all-over scratches, glamorous beauty-filter replacement faces or generic serious stare.','riven neris kellan')

add('A01','The Inch That Matters','ability','close','riven','fracture','His blade wins the angle before his power buys the distance.',
'Dynamic close three-quarter action shot of Riven from thighs up at about 75 percent of picture height. His narrow saber meets an adult armored opponent’s straight blade at ONE clear contact in front of them, both real hilt grips visible behind their guards. Riven’s silver-haired face is sharp and intent, eyes looking along the opponent’s opening. A small cyan seam begins on the nearby wall edge behind him, not a giant portal or aura. Opponent shown enough to understand resistance, face partly guarded, no extra weapons. Broad calm charcoal wall and pale side light. Crisp anatomy and contact, no motion blur, no blanket speed lines.','riven',seam)
add('A02','A Step Through the Wrong Distance','ability','medium','riven','fracture','The exit is chosen before the enemy commits.',
'One complete Riven at 45 percent image height stepping out from the far end of a single narrow cyan spatial seam along a broken stone doorway, emerging to the SIDE of an enormous forelimb sweeping past the doorway’s original position. The connected seam is a restrained kink of space between two visible masonry edges, not two glowing circular portals or duplicate Riven bodies. His lead boot reaches real dry stone, saber held clear and ready; the huge creature limb crosses his abandoned approach behind. Show the safe exit and dangerous missed sweep in a readable oblique composition. Broad simple stone planes, clear claws and no debris cloud.','riven',seam)
add('A03','Return to Sender','ability','medium','neris','fracture','A pressure front becomes one devastating step forward.',
'Side-on decisive shield strike. Neris lunges from a visibly planted rear boot, driving the OUTER navy face of her one solid crescent shield into the chest plate of a large adult armored foe. Her forearm approaches the shield from its REAR side, connected to the rear handle; show her bent elbow behind it, never a hand on the enemy-facing surface. One broad compressed pale pressure crescent releases from the contact, pushing the foe backward with feet losing purchase. Complete Neris 60 percent height, complete shield and opponent, no gore or particle storm. A quiet broad stone court and one long cast shadow.','neris',harbor)
add('A04','Winter Has an Edge','ability','medium','kellan','fracture','The water becomes a weapon exactly where his blade passes.',
'Low lateral view of Kellan in a committed two-hand sword stroke, all fingers around the hilt behind the oval guard. The blade’s lower tip is visibly touching a shallow continuous water channel. Immediately along the completed stroke behind that contact rises ONE smooth opaque pale-blue ice wedge, catching a lunging four-legged small black armored predator under its chest and lifting it off its charging line. Source water, blade contact, growing wedge and displaced animal read in one glance. Complete Kellan around 55 percent height and complete beast, three broad reflections rather than splashing glitter. No distant dry-air ice, icicle forest or random snow.','kellan',winter)
add('A05','The Woman Who Tilted the Rain','ability','full-figure','ilyra','arrival','She does not stop the storm. She changes where down is.',
'Design one NEW original adult woman Ilyra Vale, age34, pale complexion, striking angular face, straight narrow brows, amber eyes and a blunt copper-red chin-length bob with one side tucked behind ear. Regal measured expression, tall lean powerful build. Burgundy fitted combat coat with a single broad ivory shoulder mantle, black trousers and solid boots. Signature Axis Lance: a complete long straight ivory shaft, dark middle grip and one broad dark triangular spearhead with a bronze edge; no floating pieces, extra tips or filigree. In a new full-body scene she plants the blunt butt on stone beside her and holds the middle securely in one hand; other hand open at waist. Her figure about65 percent height. On ONE side of the shaft a broad translucent violet plane makes a coherent sheet of rain curve sideways; the other side falls straight. Source and consequence legible through large water shapes, no dense raindrop speckles. Massive open city balcony, distant storm, crisp adult face. Use supplied reference for drawing finish only; do not copy its subjects, shields, snow or composition. One single landscape illustration, no reference sheet, no portrait inset.','finish',axis)
add('A06','An Answer to a Giant','ability','wide','ilyra bellmaw','fracture','She cannot lift the beast. She can make one planted foot betray it.',
'Wide side view with Ilyra SMALL at 16 percent frame height on a pale bridge end, full Axis Lance planted beside her. Bellmaw towers across the right of the frame, one immense forefoot loaded onto a broad flat stone shelf. ONE low violet plane runs from the lance base beneath that forefoot only; the enormous foreleg visibly tilts sideways as its weight is redirected, while the other three legs brace outside the plane. Its low wedge head swings in surprise, not a weightless levitation pose. Quiet opaque black mantle and pale throat; huge city piers scale it. One clear source/affected region/consequence, no rune circles or particle storm.','@A05 @V05',axis)
add('A07','The Borrowed Opening','ability','medium-wide','riven neris','fracture','Her defense makes the space his next attack needs.',
'Dynamic two-adult team counter in a broad city passage. Neris crouches on the left with her crescent shield angled upward, its rear grip and bent arm correctly behind it. A single broad white sonic pressure ribbon strikes the outer shield face and is redirected over both heads. Riven lunges low from beside her at right, saber held forward through the visibly protected quiet wedge under that ribbon toward one distant armored attacker. Two distinct bodies and complete weapons, approximately40 percent height; no sword passing through Neris or duplicated motion bodies. Mouth of a distant horn implement identifies enemy source. Smooth stone and restrained cyan/violet light, one readable combined maneuver.','riven neris',harbor)
add('A08','The River Becomes a Road','ability','vertical-wide','kellan','fracture','The same narrow stroke now carries somebody home.',
'Portrait composition looking down a vertical city gorge. Kellan, a complete small adult about18 percent of picture height, kneels on the near broad canal lip and drags the blade tip through a stream spilling into the gap. Behind the contact, one continuous pale-blue frozen ramp curves across toward a lower far landing where two adult residents wait safely. His hands grip the hilt, never the blade. Unfrozen water still flows beside the new road. Huge broad stone supports and calm deep-blue void show risk; distant architecture sparse and purposeful. Depict one credible experimental crossing, not a completed continent-wide ice spell.','kellan',winter)

add('Q01','Underbridge — The First Note','sequence','extreme-wide','riven neris bellmaw','underbridge','The bridge is the only way out; the creature has already found them.',
'First beat of a four-image encounter. Wide lateral basin view: an intact pale bridge crosses left to right, anchored to a square support at LEFT and a huge round arch at RIGHT. Riven and Neris are two SMALL distinct complete adults 10 percent height on the LEFT end, Bellmaw fills the RIGHT basin beyond the bridge with all four limbs plausible and huge pale throat beginning to swell. Its mouth faces left along bridge direction. A single broad dark restraint band runs from the creature’s nearest front ankle to the right arch; no ornamental chain web. Cool twilight, flat calm water, clean broad black mantle, meaningful scale architecture. No attack beam yet.','riven neris @V05')
add('Q02','Underbridge — Hold the Line','sequence','medium','riven neris bellmaw','underbridge','She catches the first note while he watches the restraint.',
'Second beat, same pale bridge, square LEFT support and round RIGHT arch, same Bellmaw right facing left. Closer lateral framing: Neris braced on the left with proper REAR shield grip, shield outer face aimed RIGHT toward monster. One broad pale horizontal pressure front from the beast’s clearly open mouth on right strikes the shield and divides around a quiet wedge behind Neris. Riven crouches just behind her left, looking toward the dark restraint on the creature’s near front ankle. Complete adult silhouettes around40 percent height, no surface glitter or particle spray. Preserve bridge intact and geography, one shield, one saber, no reversed sides.','@Q01 neris riven',harbor)
add('Q03','Underbridge — Cut the Tether','sequence','close','riven bellmaw','underbridge','The strongest strike is aimed at what keeps the monster trapped.',
'Third beat, close oblique decisive contact at the Bellmaw’s near FRONT ANKLE beside the round RIGHT bridge arch. Riven is one complete figure around65 percent height, silver hair/petrol coat, both boots on the intact pale arch footing, saber cutting ONE taut broad dark restraint band at an explicit visible contact. The band has two newly separated thick ends springing apart, one still around ankle, other attached to arch; no gore and no sword entering flesh. Huge opaque dark living foot dwarfs him. A narrow fading cyan seam lies along the footing behind his heel, suggesting how he reached it without a duplicate body. Preserve one connected saber and correct grip; restrained cut accent, clean calm shapes.','riven @Q01',seam)
add('Q04','Underbridge — A Different Enemy','sequence','wide','riven neris bellmaw','underbridge','Freed, the creature turns away. The city’s mechanisms keep pulling.',
'Fourth beat, wide elevated view from the same LEFT bridge end looking across to the round RIGHT arch. Riven and Neris stand together SMALL 12 percent height on the intact pale bridge, recognizable by silver/petrol/saber and ivory shoulder cape/teal/crescent. The huge four-legged Bellmaw now turns AWAY to the far right into the basin, mouth closed; a short severed dark band remains at its near front ankle and the matching loose end hangs from the round arch. No corpse, celebration or repaired band. In the far background a whole dark city district begins shifting across one cyan seam, implying the next problem. Warm first dawn above quiet blue water. Large clean masses, no dust cloud.','riven neris @Q01')

plan={'schema':'ScaleConflictPlan/1','experiment_id':'SC-20260908-01','expected_count':24,'title':'Vesper Reach — Scale and Conflict','provisional_story':'A moving city, a group learning what their powers cost, and a threat restrained beneath its bridges. Three exploratory story paths, not canon or a serial chapter.','budget':{'primary':24,'texture_passes':12,'structural_repairs':4,'maximum_total':40,'per_image':'At most one separate structural repair and one separate texture redraw; no loops or allowance padding. A texture pass can follow a structural repair only after structural inspection.','direct_paid_spend_usd':0},'acceptance':{'scale':'Show actual different figure-to-frame ratios; do not add portrait insets to evade wide-shot recognition. Small-shot recognition uses silhouette/hair/costume/weapon, not impossible facial detail.','action':'Inspect source, contact, target, force and consequence; distinguish an attractive frozen pose from a clear action.','texture':'Apply saved source-only surface redraw when observed busy marks compete. Preserve design, anatomy, material and depth.','preferences':'All new ratings blank; previous exact export separate. Owner approval is global direction/texture, not individual canon.'},'reference_library':json.loads((P/'reference-library.json').read_text()),'prior_choices':json.loads((P/'previous/ce-source-binding.json').read_text()),'entries':entries}
assert len(entries)==24
out=P/'plan.json';raw=json.dumps(plan,indent=2)+'\n'
if out.exists():assert out.read_text()==raw
else:out.write_text(raw)
(P/'plan.sha256').write_text(hashlib.sha256(raw.encode()).hexdigest()+'\n')
print(json.dumps({'entries':len(entries),'plan_sha256':hashlib.sha256(raw.encode()).hexdigest()}))
