from pathlib import Path
import json,hashlib
r=Path(__file__).resolve().parents[4]; o=Path(__file__).parent
cs={x['attempt_id']:x for x in json.loads((r/'production/pilot-chapters/candidates.json').read_text())['candidates']}
def bind(i):return {k:cs[i][k] for k in ['id','attempt_id','path','sha256']}
def save(name,d):
 p=o/name;p.write_text(json.dumps(d,indent=2)+'\n');print(name,hashlib.sha256(p.read_bytes()).hexdigest())
bp={'BP03':'Intact root pins closed doorway; horizontal door hardware may suggest a lock although later loose-stump release resolves it.','BP08':'Clear duck beneath sweeping petal and first torn cloth at tip; dangerous response to failed voice test is visible.','BP14':'Actual black button and nursery slip in opened packet, two concerned faces. Exact clue attribution depends on editable dialogue, not generated slip lettering.','BP15':'Clue retained; skeptical determination rather than claiming brother is alive. Packet remains in hands.','BP16':'Two adults leave; inert severed bloom foreground distinct from a separate living bloom behind distant glass. Coat hem damage less visible.'}
st={'ST03':'Open left crescent palm and unloaded right circle; ram and horn bell present. Close muzzle proximity is less cautious than intended.','ST05':'Strong actual airborne displacement from ram mouth gust, both boots off ground and right circle unlit. The failure has visible physical consequence.','ST06':'Right boot/left gauntlet landing and chipped left edge are visible; right uncharged.','ST07':'Ram wince, moving bell and Tavi concern communicate sound sensitivity.','ST09':'Detached cloth offered, plain cream belt, horn bell retained; negotiation has a legible practical solution.','ST11':'Bell now on peg, cloth padding and two grounded boots; right circle contains charge.','ST12':'Small puff actually comes from LEFT hand while previous charge was RIGHT. Bell reaction and relaxed ram make gentle test readable, but anatomical rule transfer fails.','ST13':'Mara holds padded bell; low ram permits mounting. Chip continuity weak.','ST14':'Tavi mounts broad bare ram back behind horns; Mara assists boot. No harness or shafts.','ST15':'Tavi seated astride ram, right circle handshake with Mara, warm partnership payoff.','ST16':'Tavi moves to caravan bench and ram becomes harnessed draft animal: this contradicts the negotiated independent ride. Narrow structural repair proposed separately.'}
rc={'RC03':'One key with Vexa; warning and proud attitude legible, right black plate unlit, no early mark.','RC04':'Overhead anticipation and shark approach readable; right arm position differs from planned raised block.','RC06':'Actual seated skid with hand ground support gives force consequence and first vest tear. Stored plate appears unlit.','RC07':'Right black plate holds red charge; Vexa retains one key.','RC08':'Large returning shark versus small braced man; charge not visibly present from this angle.','RC09':'Right plate wound back but unlit despite stored charge. No early debt band.','RC11':'Shark expelled upward away from planted Ren, localized ground force; anatomical left arm remains punching. Right black plate down/unlit.','RC12':'Visible iron key handed to left glove, earned victory exchange. Vexa also retains folded permit, distinct second prop.','RC13':'Right wrist branching red debt and strained hand clearly first appear; LEFT hand mistakenly holds white folded permit instead of iron key.','RC14':'Right red debt band and awkward hand plus worried Vexa support cost. Left again holds proper iron key.','RC15':'Lender silhouette beneath water and Vexa pointing support reveal. Key shifts to right black gauntlet; busy water partly hides silhouette.','RC16':'Ascent with retained reward and enormous red eye is strong hook. Key/permit hybrid and wrist/plate side switching persist; debt visible.'}
for name,notes in [('bp-final-five-native-review.json',bp),('st-final-eleven-native-review.json',st),('rc-final-twelve-native-review.json',rc)]:
 save(name,{'schema':'PilotEditorialNativeReview/1','scope':'Actual native images inspected by script author; no owner preference inferred.','items':[{'source':bind(i+'-P'),'observation':v} for i,v in notes.items()],'generation_or_display_mutations':False})
p=r/'research/pilot-chapters/reader/phone-captures/bp-complete-v1/readthrough/receipt.json';rec=json.loads(p.read_text())
save('BP-complete-chapter-first-read.json',{'schema':'PilotEditorialCompleteChapterRead/1','chapter_id':'BP','dataset_sha256':rec['dataset_sha256'],'readthrough_receipt_path':str(p.relative_to(r)),'readthrough_receipt_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'read_start_utc':'2026-09-09 15:00:10 UTC','read_end_utc':'2026-09-09 15:00:34 UTC','elapsed_seconds':24,'timing_scope':'Informed script-author read of 10 actual overlapping 390x844 captures, all 16 natives previously inspected. Includes tool overhead; no unrelated task in interval. Not a naive human-reader duration or evidence of a 3–5 minute chapter.','complete_16_panels_read':True,'production_captions_hidden':True,'selected_sources':rec['source_bindings'],'strengths':['Hope at a familiar voice becomes a precise failed recognition test; repeated identical wording exposes imitation.','Ilyra rejects intoxicating bait without falsely resolving whether her brother lives. Dry exchanges with Neris add adult personality.','Root lift insert, attack dodge, sever, then actual loose stump and freed caretaker give a local action payoff.','Button and nursery slip are visible and dialogue earns the next investigative destination. Final inert/living blooms separate immediate victory from ongoing danger.'],'weaknesses':['Root/door geography drifts across wide action panels; lifting-to-turn rule is mostly inferred rather than perfectly demonstrated.','Dense red ground and greenhouse detail still compete at phone size.','Some name labels make attribution functional but less fluid than mature comic tails; no clipped copy seen.','Cloth damage and equipment anatomical sides vary.'],'repair_priority':'No additional BP structural repair prioritized over NG08, RC01, ST16 or a broken FL rescue.','next_decision':'Ask whether the deliberate eerie repetition, adult dry voice and nursery mystery are compelling enough to pursue; do not treat technical coherence as owner approval.','owner_approval':None})
