from pathlib import Path
import json,hashlib
r=Path(__file__).resolve().parents[4];o=Path(__file__).parent
cs={x['attempt_id']:x for x in json.loads((r/'production/pilot-chapters/candidates.json').read_text())['candidates']}
def save(n,d):
 p=o/n;p.write_text(json.dumps(d,indent=2)+'\n');print(n,hashlib.sha256(p.read_bytes()).hexdigest())
for ch,start,end,elapsed,strong,weak in [('ST','15:02:39','15:02:54',15,['The loud confrontation fails visibly: charge, airborne recoil, unlit landing. The heroine changes tactics after noticing the ram wince.','Cloth removed from waist becomes actual bell padding, successful quiet test leads to returned bell and an independent ride.','Playful adult acting and jokes make negotiated partnership distinct from the other pilots.'],['Final panel contradicts independent ride by harnessing ram to caravan and seating Tavi on bench; structural repair pending.','Ram scale varies sharply between opening and close encounters.','Right charge becomes left release, and glove chip disappears in later frames.','Frequent textured vegetation competes, although color hierarchy and silhouettes remain clear.']),('RC','15:03:06','15:03:22',16,['The visible blocked hit, skid, charge, return approach, punch and expelled shark create a complete action exchange with consequence.','Earned key is actually transferred; the numb wrist appears only after victory, making cost an effective reversal.','Brash rivalry survives the dangerous reveal; ascending while the sea eye opens preserves ambition rather than replacing victory with sacrifice.'],['Duplicate Vexa in opening; repair pending.','Black plate switches anatomical arms across block/charge/punch/debt sequence. Stored charge is inconsistently visible.','RC13 swaps earned key for spectator permit, later restores key; final reward becomes a hybrid.','High-frequency floor lines and white water compete with force and lender silhouette.'])]:
 p=r/f'research/pilot-chapters/reader/phone-captures/st-rc-complete-v1/{ch}-readthrough/receipt.json';rec=json.loads(p.read_text())
 save(f'{ch}-complete-chapter-first-read.json',{'schema':'PilotEditorialCompleteChapterRead/1','chapter_id':ch,'dataset_sha256':rec['dataset_sha256'],'readthrough_receipt_path':str(p.relative_to(r)),'readthrough_receipt_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'read_start_utc':'2026-09-09 '+start+' UTC','read_end_utc':'2026-09-09 '+end+' UTC','elapsed_seconds':elapsed,'timing_scope':'Rapid informed script-author chronological visual/copy check of ten overlapping 390x844 actual captures. Every native and all copy already familiar. Tool overhead included. This is not a naive human read or a claim of normal audience reading time; it does not establish 3–5 minute length.','complete_16_panels_read':True,'production_captions_hidden':True,'selected_sources':rec['source_bindings'],'strengths':strong,'weaknesses':weak,'lettering':'No clipped copy observed. Below-image balloons and occasional speaker labels preserve contact visibility but remain less natural than consistently tailed comics.','owner_approval':None})
notes={'FL02':'Ada presents coat onto Corin forearm/notebook rather than dropping immediately; next panel grounds it. Both gloves still worn. Acting establishes skeptical investigator and worried sibling.','FL03':'One footprint beside ledge and coat grounded; both gloves. Finger points at evidence.','FL04':'Actual bare LEFT hand poised above stone-bounded ground pool, glove removed nearby and pole grounded. Ada visible, no early eel or memory.','FL06':'Ripples erase memory and Corin restrains Ada. Bare/gloved anatomical sides reverse. Pool changes shape but stays ground water.','FL07':'Eel rises below dry ledge, Corin between threat and Ada, no visible Lio yet. Pole uses straight butt toward creature.','FL08':'Eel mouth below edge and Corin retreats/holds height advantage. Dry-ledge limitation reads, though mouth appears near boot.','FL09':'Lio in mouth with key and boot brushing ledge gives actual footprint explanation. Clear danger and two adults above.','FL10':'Corin braces pole at upper lip only, not a two-jaw prop; victim inside. Lower contact missing.','FL11':'Two vertically stacked C sections replace single head; upper contact outside rim and lower section at ledge. Causal jaw-prop construction fails despite braced stance. Prioritize structural repair.','FL12':'Ada actively hauls Lio shoulders while he crawls onto dry ledge; spatial rescue reads. Pole again shows upper contact only, unresolved even if FL11 repaired.','FL13':'All three safely on ledge, eel visibly retreats, coat stays ground. Immediate danger resolved.','FL14':'Lio speaks exhausted, triangular key still necklace; no premature transfer.','FL15':'One matching triangular key transferred from Lio partial arm to Corin bare LEFT palm; investigative gate behind.','FL16':'Two siblings leave together while detective faces huge sluice with retained triangular key. Key shifts to RIGHT, but story direction and sole ownership clear.'}
save('fl-final-fourteen-native-review.json',{'schema':'PilotEditorialNativeReview/1','scope':'Actual native images inspected by story author; FL01 and FL05 covered in earlier reports.','items':[{'source':{k:cs[i+'-P'][k] for k in ['id','attempt_id','path','sha256']},'observation':v} for i,v in notes.items()],'generation_or_display_mutations':False,'owner_approval':None})
