from pathlib import Path
import json,hashlib,datetime
R=Path(__file__).resolve().parents[4];O=Path(__file__).parent;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
reg=json.loads((R/'production/pilot-chapters/candidates.json').read_text())['candidates']
N={
'NG03':('Ray beak actually clamps thick support cable directly above coupling; enclosed car remains suspended. Mechanical cause of danger reads.','Ray microfacets and hardware surface wear are dense; lift enclosure differs from later open-top car, so exact construction continuity is approximate.','No structural repair priority.'),
'NG04':('Aren above/right looks down toward visibly harnessed Pell in skewed car, with ray nearby. Rescue need and separation read. Wallet remains correctly on Aren before transfer.','More than one vertical cable/rail element is visible, and the precise sole support is not as simple as script. No full future rescue has occurred.','No structural repair priority.'),
'NG05':('ONE cream wallet transfers from Aren LEFT hand to Sera open palm; Aren RIGHT holds drawn crescent, belt no duplicate. Clear choice transition.','New blade has circular cutouts and differs from plain source geometry; dense jacket facets remain. These do not erase transfer.','Strong story transfer; protect this beat.'),
'NG06':('Aren right hand owns weapon and single line visibly reaches heavy post; no wallet. Setup of anchored pull is understandable.','Line starts at forward guard/pivot circle rather than pommel. Left hand holds near that junction. One knee grounded instead of both boots braced.','Keep endpoint/support caveat; reserve scarce structural repairs for larger causal failures.'),
'BP01':('Small heroine faces monumental sealed glasshouse with large eerie bloom silhouette beyond glass; opening scale and unease work.','Bloom detailed rather than a vague distant silhouette; dense red ground fibers compete, but no captive reveal.','No structural repair priority.'),
'BP02':('Hopeful listening face at door, no visible voice source or brother apparition. Supports bait and anonymous offscreen copy.','Saber sheathing not fully visible in crop; do not count invisibility as absence. Fine hair detail remains.','No structural repair priority.'),
'BP05':('Heroine moves beside planted bloom; one root extends to right threshold. Right saber and left guard visible.','Dense petal filament webs and red carpet fibers; a single still cannot prove face did not rotate across its movement.','Need adjoining BP06 root-lift frame before continuity acceptance.'),
'BP11':('Actual root separation with open air gap and follow-through sells severing, rather than an intact root under effects.','Stump sits in open floor far from the right-background door, weakening threshold-release cause. Blade appears in guarded LEFT hand here versus right earlier; hem not distinctly torn.','Causal geography watch: evaluate BP12 before proposing scarce repair.'),
'ST01':('Bell visibly strapped to near horn, huge grounded ram blocks route, protagonist approaches against caravan and cliff scale.','Ram appears several times human size versus later closer-to-human-height shots; heroine is running before conversation but no power or damage. Ground is busy.','No immediate structural repair; scale consistency remains approximate.'),
'ST04':('Anatomical RIGHT circle charges, LEFT crescent guards; both boots grounded. Horn bell remains present, no chip yet.','Ram stands immediately beside her, not meaningfully separated/wary opponent; warm friendly proximity reduces imminent confrontation. Ram size reduced from opening.','No repair solely for appeal; follow ST05 blast consequence.'),
'ST08':('Seated quiet reversal, detached cloth is visibly held across hands with plain cream belt, bell still horn-attached. Cooperative ram acting supports negotiation.','Left knuckle chip is not distinctly readable; large close two-shot instead of prescribed generous-distance wide.','Strong inventory transfer; no structural repair priority.'),
'ST10':('Right circle hand supports rim, left crescent hand pads visible clapper with detached cloth; horn strap and one bell retained. Source-action-target tactile solution reads.','Chip is small/ambiguous against general glove wear; texture is dense.','Strong causal solution; protect this beat.'),
'RC01':('Small protagonist against enormous angular flying shark and rising ring architecture establishes ambition and scale.','Two near-identical key-holding Vexa silhouettes occur on separate upper walkways: duplicate principal. Dense ring/shark hatch lines.','Potential repair candidate for obvious duplication, but defer behind unresolved payoff failures.'),
'RC05':('Black-plate glove blocks actual shark fin/jaw-plane edge; contact spark and emerging red load are localized, opposite hand clear.','Loaded arm appears anatomical LEFT, opposing specified right. Both gauntlets otherwise distinct; no premature debt band.','Power loading reads; track consistency with later debt instead of repairing sidedness alone.'),
'RC10':('Loaded black-plate fist visibly dents/folds lower jaw plane, with body extension and grounded legs. It pays off earlier block as physical counter.','Same anatomical LEFT arm is used as RC05, while script requires right. Vest tear is harder to distinguish amid dense faceted folds; debris/hatching may compete.','Strong impact transfer; compare later wrist-cost/payoff before any repair.')}
rows=[]
for i,(strong,gap,priority) in N.items():
 c=next(x for x in reg if x['attempt_id']==i+'-P');assert sha(R/c['path'])==c['sha256']
 rows.append({'id':i,'attempt_id':c['attempt_id'],'path':c['path'],'sha256':c['sha256'],'prompt_sha256':c['prompt_sha256'],'call_sha256':c['call_sha256'],'native_inspected':True,'phone_inspected':False,'story_strength':strong,'remaining_weakness':gap,'repair_priority':priority})
o={'schema':'PilotEditorialProgressiveNativeReview/1','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'plan_sha256':sha(R/'production/pilot-chapters/plan.json'),'scope':'Fifteen actual new primary natives. Author/editorial review of sequence clues, current props and consequences; no full chapter or owner acceptance. Four remaining structural repairs should prioritize broken story over minor handedness.','reviews':rows}
p=O/'batch-two-15-native-review.json';p.write_text(json.dumps(o,indent=2)+'\n');print(sha(p))
