from pathlib import Path
import json,hashlib,datetime
R=Path(__file__).resolve().parents[4];O=Path(__file__).parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
reg=json.loads((R/'production/pilot-chapters/candidates.json').read_text())['candidates']
notes={
'NG09-R1':{'improvements':['Wallet removed from belt. Sleeves restored, with coherent left hand supporting body on roof lip.','Force line now exists and native beak/blade contact remains clear.'],'residuals':['Line starts at guard/blade base, while cyan pommel ring behind grip remains visibly separate. Exact power endpoint is still wrong.','Lower hem damage is not clearly established; do not count restored sleeve as complete damage continuity success.'],'assessment':'Partial repair; retain as an improvement only with endpoint/damage caveats.'},
'NG12-R1':{'improvements':['Wallet removed. Upper post endpoint and single taut cyan line are clear. Rescue/clasp and empty falling car remain readable.'],'residuals':['Cyan ring has moved to blade/guard base rather than true pommel behind grip.','Sword arm still appears anatomical LEFT and rescue clasp RIGHT; requested sides remain unresolved.','Clasp reads hand/wrist rather than requested forearm, and lower hem damage is subtle.'],'assessment':'Partial repair; core rescue reads but weapon geometry and sidedness still fail exact contract.'},
'ST02-R1':{'improvements':['Reachable fence bell is removed. Mara points toward a distant ram carrying one bell, restoring retrieval premise.','Faces, correctly sided gloves, intact costume and attached waist cloth retained.'],'residuals':['Distant ram bell hangs at throat/mouth rather than unambiguously from horn by strap.','Added ram is beyond original two-person visible-cast list, though it supports the requested distant situation and does not obscure principal acting.','Dense wood/vegetation marks remain.'],'assessment':'Major story improvement with horn-strap continuity still approximate; source is not an exact contract pass.'},
'FL05-R1':{'improvements':['Actual stone-bounded ground pool is focal, separate from canal. No coat pocket, oversized portrait, pole or early eel.','Awake Lio reaching wheel is legible within pool. Bare fingertips contact water.'],'residuals':['Several concentric finger ripples coexist with a sharp memory, conflicting with the strict ripple-erases rule.','Hand appears anatomically RIGHT by thumb orientation; requested left cannot be claimed verified.','Concrete speckling and fragmented water reflection remain strong finish candidates.'],'assessment':'Power medium/reveal restored; ripples and possible hand side remain unresolved.'},
'NG01-F1':{'improvements':['Broad city planes, less ray microfacet scatter and grouped distant detail retain original opening staging and small protagonist.'],'residuals':['Some fine foliage and window light detail persists; no new story blocker observed.'],'assessment':'Useful quieter finish, not evidence of owner preference.'},
'NG02-F1':{'improvements':['Simpler jacket planes and quieter setting retain faces, held wallet, pointing gesture and intake beyond gate.'],'residuals':['Selective folds/foliage remain. Opposing speaker image positions still require reader attribution treatment.'],'assessment':'Useful finish; no new native story blocker observed.'}}
rows=[]
for aid,n in notes.items():
 c=next(x for x in reg if x['attempt_id']==aid);assert sha(R/c['path'])==c['sha256']
 s=next(x for x in reg if x['attempt_id']==c['id']+'-P')
 rows.append({'attempt_id':aid,'path':c['path'],'sha256':c['sha256'],'prompt_sha256':c['prompt_sha256'],'call_sha256':c['call_sha256'],'source_attempt_id':s['attempt_id'],'source_sha256':s['sha256'],'native_inspected':True,'phone_inspected':False,**n})
o={'schema':'PilotEditorialEditReview/1','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'plan_sha256':sha(R/'production/pilot-chapters/plan.json'),'scope':'Actual native source/edit comparisons, author review, not blind. Root endpoint/pool concerns were known beforehand. No preferred display mutation or owner approval.','reviews':rows}
p=O/'first-six-edit-native-review.json';p.write_text(json.dumps(o,indent=2)+'\n');print(sha(p))
