from pathlib import Path
import json,hashlib,datetime
R=Path(__file__).resolve().parents[4]; O=Path(__file__).parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
reg=json.loads((R/'production/pilot-chapters/candidates.json').read_text())['candidates']
notes={
'NG01':{'strengths':['Actual extreme-wide city arrival makes Aren a small readable white silhouette on the long diagonal bridge. Scale supports the ambitious inhabited-city opening.','No premature injury or active power visible.'],'gaps':['Some leaf/window fleck detail persists, but geography and quiet bridge mass dominate. Sword inventory cannot be independently resolved at this scale.'],'story_status':'Opening works; no local causal blocker observed.'},
'NG02':{'strengths':['Aren visibly holds the cream wallet; Sera points toward a lit intake booth beyond the turnstile. The qualification destination is physically legible.'],'gaps':['Sera is image-right while her first dialogue item defaults earlier in reading order; actual lettering attribution/tail placement still needs review.','White jacket has dense faceted folds and city foliage detail: possible later finish evidence, not a story failure.'],'story_status':'Setup works natively; lettering pending.'},
'NG09':{'strengths':['Right-hand crescent blade visibly opposes the pointed ray beak at close range; determined face and proximity sell immediate danger.'],'gaps':['Cream wallet remains on Aren belt despite prior transfer to Sera.','Visible pommel ring has no cyan tether; unrelated dark roof cable cannot be credited as the specified force source.','Visible jagged cloth loss is around the sleeve/forearm near the dark pillar rather than a clearly lower rear hem tear.'],'story_status':'Strong danger image with material prop/power/damage continuity failures.'},
'NG12':{'strengths':['Airborne adult rescue and physically separate empty falling car give the action an understandable consequence. Pell still wears the body harness.'],'gaps':['Cyan line attaches to blade tip rather than cyan pommel ring.','Raised sword arm appears anatomical left and rescue clasp right in this frontal three-quarter body; conflicts with right-weapon/left-rescue contract.','Cream wallet remains visible on Aren despite Sera possession.','Clasp reads closer to wrist/hand than the requested forearm. Small-scale hem state cannot be reliably verified.'],'story_status':'Rescue concept reads; exact power route and inventory do not.'},
'ST02':{'strengths':['Expressive warm two-person banter and correct visible right-circle/left-crescent gauntlets support the comic personality.','Cloth is visibly waist-attached and gauntlets uncharged/intact, appropriate to this beat.'],'gaps':['The single bell is hanging from the nearby fence over Mara pointing hand, already accessible. This defeats the coming horn retrieval problem.','No ram is visible; omission itself is acceptable for this two-shot, but the bell must then also remain offscreen with the ram.','Woodgrain, vegetation and tiny distant details are active surface-noise candidates.'],'story_status':'Bell placement is a material story blocker; do not infer that appealing banter resolves it.'},
'FL05':{'strengths':['The reflected Lio is awake and reaching toward the wheel, so the clue action itself reads. Bare left and gloved right hands are visible.'],'gaps':['Memory occupies the lifted white coat like a liquid garment pocket, not a still ground puddle. Corin left hand pinches cloth rather than placing two fingertips into ground water.','Pole is upright in the right hand rather than set aside for the pool touch.','Large ribbed eel body is already visible in the canal before the planned reveal.','Large detective portrait and elaborate moving canal reflections displace the intended concentrated clue insert.'],'story_status':'Clue subject reads, but the power medium and reveal timing are materially wrong.'}}
rows=[]
for k,n in notes.items():
 c=next(v for v in reg if v['attempt_id']==k+'-P'); assert sha(R/c['path'])==c['sha256']
 rows.append({'id':k,'attempt_id':c['attempt_id'],'image_path':c['path'],'image_sha256':c['sha256'],'prompt_sha256':c['prompt_sha256'],'call_sha256':c['call_sha256'],'native_inspected':True,'phone_lettering_inspected':False,**n})
obj={'schema':'PilotEditorialNativeReview/1','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'plan_sha256':sha(R/'production/pilot-chapters/plan.json'),'scope':'First six actual native panels, inspected at original detail. This is editorial author review. Root supplied initial NG wallet/tether and ST bell/FL pool concerns before review; these are corroborated observations, not claimed blind independent findings. No owner preferences inferred; no complete-chapter reading or phone lettering acceptance claimed.','reviews':rows}
p=O/'first-six-native-review.json';p.write_text(json.dumps(obj,indent=2)+'\n');print(sha(p))
