"""One-time freeze of six evidence-selected semantic repairs; refuses overwrites."""
from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[2]; P=R/'production/visual-refinement'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
out=P/'sequence-retry-jobs.json'; assert not out.exists(),'Frozen repair plan already exists'
fixes={
'13-P02':('P02','Both hands grip iron and leave the wooden crank untouched, removing the cause of the snap.', '''Repair the pulling action. Show exactly ONE intact short wooden crank fixed to the iron rim at3 o'clock. Iven's anatomical RIGHT hand must wrap that wooden grip, visibly pulling it outward; his anatomical LEFT hand directly braces the iron rim at10 o'clock. Trace each arm from its own shoulder through sleeve to hand. The near right arm reaches across his front toward the wooden grip; the far left arm reaches to the upper rim. There are exactly two human hands and one continuous wooden grip, no detached wood, no second handle. Show his strained face and the complete wheel. Gate remains fully closed. Preserve the fine manga hatch treatment and pale background grouping.'''),
'19-P02':('P02','Two full wooden handles appear, one held in each hand, instead of one crank and one rim brace.', '''Repair the pulling action and remove the invented second handle entirely. There is exactly ONE intact short wooden crank fixed to the rim at3 o'clock. Iven's anatomical RIGHT hand wraps that one wooden grip. His anatomical LEFT hand touches bare iron rim at10 o'clock, with absolutely no wood beneath that hand. Trace both arms from shoulder to fingers, near right arm across his front toward wood, far left arm to upper rim. Exactly two hands and one continuous wooden grip in the entire panel; no detached piece. Preserve his strained expression, same adult face, refined smooth modeling, and closed gate.'''),
'18-P03':('P03','An extra long airborne wood segment makes three pieces instead of the frozen two-piece break.', '''Remove the extra airborne wooden segment between Mara and the wheel. Reconstruct that area as clean background/clothing. Keep exactly TWO wooden pieces in the whole image: one short jagged stub attached at the rim's3 o'clock point, and one longer matching jagged remnant inside Iven's anatomical RIGHT fist. His anatomical LEFT hand remains on the upper iron rim. No floating wood, no loose chips or splinters. Match both snapped ends in diameter and wood color, with a clear air gap. Keep both startled faces, existing body positions, closed gate and bold cartoon drawing. The held piece is a short broken crank remnant, not a large club.'''),
'18-P04':('P04','Mara grips an invented long horizontal lever outside the wheel instead of opposite rim points.', '''Remove the long horizontal iron lever projecting left from the wheel. Reposition Mara's anatomical LEFT hand directly around the bare iron rim near9 o'clock; her anatomical RIGHT hand directly grips the opposite upper-right rim near2 o'clock. Both hands contact the circumference itself, neither a spoke nor a wooden handle. Keep a clear full-body hip/shoulder twist, two grounded sandals on the same connected dry ledge and her powerful mature plus-size body. The wheel has one short jagged wooden stub at4:30, not a full capped handle. Iven at frame left holds one matching broken wooden remnant in his anatomical RIGHT hand; other hand empty. Gate is only partly lifted and the creature waits beyond it, not already passing underneath. Preserve bold cartoon contour, warm colors and identifiable adult faces.'''),
'13-P05':('P05','Iven holds two wood pieces; creature travels backward and gate staging changes during the passage beat.', '''Repair the passage and prop state. Remove every wood piece from Iven's anatomical LEFT hand and leave that hand visibly empty. His anatomical RIGHT hand alone holds ONE short jagged broken wooden remnant. The upright vertical iron wheel has only one short jagged mounted stub at6 o'clock, no full wooden handle. Restore one broad arched gate opening consistent with the same canal location: gate fully raised, clear water beneath, no additional arch/tunnel in the opening. Stage the whole jellyfish-turtle fully downstream to the right of the gate, its HEAD at screen-RIGHT and its FOUR broad tentacles trailing left, all four complete inside the frame. No extra legs, no cropped creature. Mara stands with both sandals on the same connected dry stone ledge and rests an open anatomical LEFT palm on the low near slate-blue shell EDGE beneath the lavender dome, not atop the dome. Widen framing if needed, retaining both complete adult bodies. Preserve exact adult identities, fine manga hatch treatment and pale spacious value grouping.'''),
'19-P05':('P05','Mara appears unsupported over canal water; Iven holds two wood pieces and creature travel reverses.', '''Repair dry support, the prop count and passage direction. Broaden the EXISTING connected stone landing beneath Mara so BOTH sandals visibly rest flat on dry stone connected to Iven's walkway, not water, a floating island or a hidden support. Retain her powerful plus-size body and mature brown face. Remove all wood from Iven's anatomical LEFT hand, leaving it visibly empty. His anatomical RIGHT hand alone holds ONE short jagged broken wooden remnant; wheel has only a short jagged mounted stub at6 o'clock. Keep wheel vertical and gate fully raised. Show the entire same jellyfish-turtle downstream of the gate with HEAD at screen-RIGHT and FOUR broad tentacles trailing left, all complete in frame, no extra legs. Mara's open anatomical LEFT palm gently touches the low near slate-blue shell EDGE below the lavender dome, not its top. All contact and feet must be visible. Preserve refined smooth face/material modeling, costumes and quiet canal scene; do not add ornamental objects.''')}
jobs=[]
for id,(panel,reason,fix) in fixes.items():
    guide='P05-clearance.png' if panel=='P05' else panel+'.png'
    refs=['production/visual-refinement/sequence-candidates/'+id+'-P.png','production/visual-refinement/sequence-design/shot-controls/v5/'+guide]
    prompt='''Use case: targeted semantic image edit.
Output: ONE finished single comic panel, no lettering, captions, labels, arrows, signature or watermark.
Image1 is the actual panel to correct and the sole reference for adult identities, costume and drawing treatment. Image2 is only a schematic action/state guide: do not copy its flat diagram style, gray figures, labels, anatomy shortcuts or colors. Preserve image1's drawing language and recognizable adults while making the specified corrections. Do not add a second panel or comparison layout.
'''+fix+'\nThe scene remains a quiet daylight canal. Preserve the large simple background masses and clear facial hierarchy. This is one bounded continuity repair, not a beauty variant or a new character design.\n'
    pp=P/'prompts'/(id+'-R.txt'); assert not pp.exists(); pp.write_text(prompt)
    source=json.loads((P/'sequence-jobs.json').read_text())['jobs']; old=next(x for x in source if x['id']==id)
    jobs.append({'id':id,'attempt_id':id+'-R','phase':'sequence','style_id':id[:2],'panel_id':panel,'retry_of':id+'-P','retry_reason':reason,'prompt_path':pp.relative_to(R).as_posix(),'prompt_sha256':sha(pp),'references':[{'path':p,'sha256':sha(R/p)} for p in refs],'requested_aspect_ratio':old['requested_aspect_ratio'],'copy_source':old['copy_source']})
plan={'schema':'RefinementRetryPlan/1','experiment_id':'VR-20260907-01','decision':'After all18 primary native images and all three actual continuous phone routes were reviewed, independent art and sequence reviewers separately selected the same six failures. Lead agrees. Two repairs per treatment prioritize causal readability and unsupported/duplicated objects.','mechanism_change':'Primary panel as exact edit target plus its same v5 action/state guide; remove selected A/B comparison-board inputs. This changes conditioning and does not establish identical-input causal isolation.','remaining_limits':'Unrepaired hand ownership, P06 wheel/wood regeneration, early passage, cropped establishment creatures and spatial/scale drift remain disclosed. These six repairs cannot guarantee a production-coherent sequence.','allowance':{'total_retry_limit':10,'comparison_retries_already_used':4,'this_phase':6,'remaining_after_calls':0,'max_retry_per_asset':1,'absolute_call_ceiling':50},'jobs':jobs}
out.write_text(json.dumps(plan,indent=2)+'\n'); out.with_suffix('.json.sha256').write_text(sha(out)+'  production/visual-refinement/sequence-retry-jobs.json\n'); print('Frozen six final repairs; no further image calls after these.')
