from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[2];P=R/'production/visual-refinement';refs=json.loads((P/'references.json').read_text());rd={x['id']:x for x in refs}
styles=[
('01','Nightglass Courier','Clean action manhwa','Precise tapered digital contours, elegant stylized adult faces, crisp two-step cel shadows, smooth broad color areas and restrained cool edge light. Prioritize line economy and dark-versus-light clothing shapes. No extra neon architecture.','Cool blue-gray, ivory, plum and muted magenta costume accents.'),
('02','Sunbreak Lancer','Warm outlined adventure painting','Lively hand-drawn comic contours and warm opaque painted color planes, expressive eyebrows and clear athletic posing. Mild broad paper/paint texture within forms; keep sky and masonry quiet. Match the actual warm outlined reference, not photoreal rendering.','Warm cream stone, clear blue-gray water, plum and magenta costumes, sunny skin tones.'),
('05','Iron Orchard','Textured painted adventure','Robust adult anatomical drawing, sculptural angular facial planes, matte opaque painted shapes, selective broad dry-paint edge character. Preserve handmade paint masses, but no rusty scrap texture on every surface and no decorative machinery.','Muted olive and blue-gray setting, cream clothing and plum/magenta accents; warm skin.'),
('06','Floodline Detective','Graphic brush-ink noir','Large decisive brush-ink black masses against quiet white shapes, selective dry-brush edge and gray facial modeling only where needed. Rugged expressive mark construction, accurate distinct faces. Preserve white channels separating body, creature and background.','Black, white, gray and one restrained hot-pink accent on plum/magenta garment zones only.'),
('13','Red Current','Angular action manga','Sharp precise muscular manga contours, tapered angular hatch clusters limited to form shadows, graphic white areas and black clothing masses. Expressive adult eyes and brows. No surrounding speed-line storm in these calm controlled poses.','Black, white, gray with vermilion as the only spot color on plum/magenta garment zones.'),
('15','Cathedral Engine','Controlled copperplate engraving','Authentic fine engraved contour and orderly crosshatch following volume, line-density sculpted faces and tailored clothing, restrained ornamental craft. Keep broad unhatched or lightly hatched negative space behind silhouettes. Do not substitute sepia digital painting or fill everything with equal dense hatch.','Warm parchment, black engraved ink and restrained aged-brass value accents. Map garment colors to distinct stable light/dark values.'),
('17','Hollow Cartographer','Soft clear-line adventure comic','Clean rounded expressive adult contour drawing, readable stylized noses and brows, gentle planar shading and warm flat color organization. Sparse intelligible masonry seams, generous quiet color areas. Not hyperreal or thick caricature.','Warm terracotta-gray stone, pale blue-gray water, ivory, plum and muted magenta clothing.'),
('18','Soft Thunder','Bold animation cartoon','Bold changing contour weight, clear adult cartoon shape rhythm, large expressive faces and brows, simple grouped cel shadows. Exaggerate gesture and face within the retained slender male or powerful plus-size mature female silhouettes, never turn either into a child or change their hair/wardrobe.','Clean clear blue-gray water, warm ivory stone, plum/magenta clothing accents and warm skin.'),
('19','Black Petal','Refined fashion-horror illustration','Refined nearly realistic fashion facial drawing, razor-clean fine contours, silky restrained value gradients, elegant graphic black shapes and sparse surreal detail. Beautiful recognizable adult facial structure. Preserve facial specificity; do not replace the man with the split-haired reference model, and do not slim the woman.','Bone white, soft slate gray, black, plum and deep muted magenta accents. Restrained daylight, no luminous particles.')
]
chars=[
{'id':'A','title':'Velvet Duelist / Iven','source_direction':'04','description':'Retained adult male27 character, long delicate oval face, wine-red tied hair, slender dancer build; simplified plum waistcoat and ivory poet sleeves.','subject':'Iven, the adult male27 from the LEFT side of the shared cast sheet: slim elegant dancer build, long oval face, delicate nose, violet eyes, long wine-red hair loosely tied low, small pearl earring. Ivory poet sleeves, plain plum waistcoat, high-waisted slim black trousers and plain black boots. Friendly raised-brow half-smile, no beard. No weapon or extra jewelry.','pose':'LEFT portrait: waist-up three-quarter view, friendly raised-brow half-smile. RIGHT scene: complete full body standing relaxed on the near canal ledge, face turned toward the creature, one open palm offered toward it across a clearly visible gap, other arm relaxed. Both feet fully visible.'},
{'id':'B','title':'Tidewalker / Mara','source_direction':'16','description':'Retained adult female38 character, broad mature joyful face, powerful plus-size body, blue-black braid; simplified ivory vest and magenta trousers.','subject':'Mara, the adult woman38 from the RIGHT side of the shared cast sheet: powerful plus-size body with broad waist and strong limbs, warm brown skin, broad nose, full lips, thick blue-black braid, expressive mature face. Plain ivory ceramic cropped vest, high-waisted loose magenta trousers, wrapped sandals and one simple blue upper-arm band. Delighted confident open smile. Do not slim her waist or make her young. No weapon or extra jewelry.','pose':'LEFT portrait: waist-up three-quarter view, delighted confident open smile. RIGHT scene: complete full body in a planted wide stance on the near canal ledge, one hand resting naturally on the circular iron handwheel rim on its post, the other open toward the creature across a visible gap. Both feet fully visible.'}
]
entries=[]
for sid,title,display,render,palette in styles:
 for c in chars:entries.append({'id':sid+'-'+c['id'],'kind':'controlled','style_id':sid,'character_id':c['id'],'title':title+' · '+c['title'],'caption':'Same '+c['id']+' character, pose, creature and canal brief; drawing treatment and declared palette vary.'})
entries.extend([
{'id':'X1','kind':'exploratory','title':'Moonward keeper × Hollow / Floodline','style_id':'17','source_direction':'11','caption':'Character11 in17 clear-line rendering with06 broad canal architecture and dark shape grouping. Exploratory mix; outside controlled ranking.'},
{'id':'X2','kind':'exploratory','title':'Astral tailor × Black Petal / Nightglass','style_id':'19','source_direction':'14','caption':'Character14 in19 refined facial rendering with01 economical cel-shadow grouping and one19 orchid creature. Exploratory mix; outside controlled ranking.'}
])
plan={'schema':'RefinementComparisonPlan/1','experiment_id':'VR-20260907-01','styles':[{'id':sid,'title':title,'display_style':display,'rendering':render,'palette':palette,'reference':{'path':rd[sid]['path'],'sha256':rd[sid]['sha256']}} for sid,title,display,render,palette in styles],'characters':chars,'entries':entries,'owner_status':'Nine prior stars unranked; all new image judgments unknown.','control_limits':'A controlled brief, not an exact pixel/pose lock: stylization and palette are deliberate treatments; actual identity/pose/creature drift must be reported.'}
(P/'comparison-plan.json').write_text(json.dumps(plan,indent=2)+'\n')
print('Comparison plan written:18 controlled+2 exploratory.')

