import{readFileSync,writeFileSync,mkdirSync,existsSync}from'node:fs';
import{resolve,dirname}from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import{connect}from'./cdp.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../..'),out=resolve(root,'research/combat-depth/reader'),page=resolve(root,'docs/combat-depth/index.html'),hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const dataPath=resolve(root,'docs/combat-depth/data.json'),data=JSON.parse(readFileSync(dataPath)),notesPath=resolve(root,'production/combat-depth/review-notes.json'),notes=JSON.parse(readFileSync(notesPath)),checks=[],screens=[];
function check(name,pass){checks.push({name,pass:!!pass});if(!pass)throw Error(name)}
const c=await connect(9382);let before;
try{
check('final dataset',data.dataset_sha256==='7d50da6e380457e4ee25daea3b652797bf1fd9be374cd1a3dfbae4bd475502ad');check('notes file binding',data.review_notes_sha256===hash(notesPath));check('24 selected F1',data.entries.length===24&&data.entries.every(e=>e.candidate.attempt_id.endsWith('-F1')));check('54 native attempts',data.entries.reduce((n,e)=>n+e.history.length,0)===54);check('one separate no-art failure',data.entries.reduce((n,e)=>n+e.service_failures.length,0)===1);check('two final report links',data.report_links.length===2);
for(const e of data.entries){const n=notes.entries[e.id];check(e.id+' observation binding',n.attempt_id===e.candidate.attempt_id&&n.sha256===e.candidate.sha256&&JSON.stringify(n.observations)===JSON.stringify(e.ai_observations))}
await c.navigate(page);before=await c.ev('JSON.stringify(CombatDepthApp.getState().choices)');check('blank choices',await c.ev('Object.values(CombatDepthApp.getState().choices).every(x=>Object.entries(x).every(([k,v])=>k==="ratings"?Object.values(v).every(t=>t===null):k==="shortlist"?v===false:k==="note"?v==="":v===null))'));
for(const [w,h]of[[390,844],[1024,768],[1440,1000]]){await c.viewport(w,h);await c.ev('CombatDepthApp.setMode("all")');check(w+' all observations exact and collapsed',await c.ev('COMBAT_DEPTH_DATA.entries.every(e=>{const n=document.querySelector(`#stage [data-entry="${e.id}"] .technical-notes`);return n&&!n.open&&JSON.stringify([...n.querySelectorAll("li")].map(x=>x.textContent))===JSON.stringify(e.ai_observations)})'));const links=await c.ev('[...document.querySelectorAll("#report-links a")].map(a=>({label:a.textContent,url:a.href}))');for(const l of links)check(w+' report '+l.label,existsSync(fileURLToPath(l.url)));await c.decode();await c.ev('(()=>{CombatDepthApp.showEntry("D10"); const d=document.querySelector("#stage [data-entry=D10] .technical-notes");d.open=true;d.scrollIntoView({block:"center"})})()');const p=resolve(out,`phone-captures/final-metadata-${hash(dataPath).slice(0,12)}/notes-${w}.png`);await c.screenshot(p);screens.push({path:p.slice(root.length+1),sha256:hash(p)});check(w+' no overflow',await c.ev('document.documentElement.scrollWidth<=innerWidth'));await c.ev('CombatDepthApp.setMode("read-war")');check(w+' narrative excludes observation controls',await c.ev('!document.querySelector("#stage .technical-notes")'));}
await c.ev('CombatDepthApp.openHistory("W06")');check('W06 failure distinct from native images',await c.ev('document.querySelectorAll(".history-card img").length===2&&document.querySelectorAll(".service-failure-card").length===1&&!document.querySelector(".service-failure-card img")'));check('W06 changed input links explicit',await c.ev('document.querySelector(".service-failure-card").textContent.includes("six references to five")&&[...document.querySelectorAll(".service-failure-card a")].some(a=>a.textContent==="Revised five-reference request")'));
check('choices preserved',before===await c.ev('JSON.stringify(CombatDepthApp.getState().choices)'));check('clean console',c.errors.length===0);
}finally{await c.close()}
const receipt={schema:'CombatDepthFinalMetadataQA/1',pass:checks.every(x=>x.pass),dataset_sha256:data.dataset_sha256,data_sha256:hash(dataPath),review_notes_sha256:hash(notesPath),plan_sha256:data.plan_sha256,code_sha256:Object.fromEntries(['app.js','style.css','preferences.js'].map(n=>[n,hash(resolve(root,'docs/combat-depth',n))])),reports:data.report_links.map(l=>({path:resolve(dirname(page),l.path).slice(root.length+1),sha256:hash(resolve(dirname(page),l.path))})),checks,screenshots:screens,browser_port:9382,preferences_unchanged:true};writeFileSync(resolve(out,'final-metadata-qa.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({pass:receipt.pass,checks:checks.length,data_sha256:receipt.data_sha256,receipt_sha256:hash(resolve(out,'final-metadata-qa.json'))}));
