"""Author the approved six-shot sequence contract; preserve existing frozen outputs."""
from pathlib import Path
import json,hashlib,datetime
P=Path(__file__).resolve().parent;ROOT=P.parents[2];R=ROOT/'research/visual-refinement/sequence-design'
def write(path,text):
 with path.open('x',encoding='utf-8') as out:out.write(text)
def dump(path,value):write(path,json.dumps(value,ensure_ascii=False,indent=2)+'\n')
def line(panel,n,speaker,text,kind='dialogue'):return dict(id=f'{panel}-L{n:02}',speaker=speaker,text=text,kind=kind)
panels=[
 dict(id='P01',title='The expert',story='Iven steps toward the handwheel with an easy raised-brow smile. Mara waits beside him. The calm creature faces the closed gate from upstream.',copy=[line('P01',1,'IVEN','I know this gate.')],target_height_at392=261,aspect_ratio='3:2',shot='Wide eye-level establishment, full bodies and all four creature tentacles visible.',camera=dict(location=[-4.9,-7.8,3.25],target=[-.65,.55,1.1],lens_mm=43),blocking=dict(iven=[-1.3,-1.0,.35],mara=[-2.2,-.9,.35],creature=[-2.8,1.2,0]),required_visible=['Both adults, complete feet on dry ledge','One waiting pony-scale creature with four broad tentacles','Closed gate seated at waterline inside one broad arch','Handwheel with one intact short wooden grip at3 o’clock'],action='Iven takes one small step toward wheel; right hand remains empty and open. Mara looks from him to the creature.',expression='Iven friendly confidence; Mara patient mild doubt; creature calm.',continuity='No broken wood. Equal calm water level on both sides. Nothing already passes beneath the gate.'),
 dict(id='P02',title='A little force',story='Iven braces the iron rim with his left hand and pulls the wooden grip with his right. His confident smile tightens; the gate does not move.',copy=[line('P02',1,'IVEN','Just a little—')],target_height_at392=392,aspect_ratio='1:1',shot='Medium three-quarter south-side view, Iven from upper thighs through face plus entire wheel.',camera=dict(location=[-2.8,-4.0,2.5],target=[-.85,-.55,1.58],lens_mm=58),blocking=dict(iven=[-1.05,-.95,.35],mara=[-2.2,-.9,.35],creature=[-2.8,1.2,0]),required_visible=['Iven anatomical LEFT hand visibly bracing iron rim at10 o’clock','Iven anatomical RIGHT hand wrapped around intact wooden grip at3 o’clock','Single continuous wooden grip from rim to right fist','Iven face, shoulder origins and wheel mounting'],action='Left shoulder/arm leads to iron rim; right shoulder/arm leads to wooden grip. The grip is pulled outward toward the south camera, not turned yet.',expression='Iven strained smile, pursed concentration; a sliver of Mara may watch from frame left.',continuity='Gate fully closed, wheel orientation unchanged. No separate wooden fragment or pre-existing crack gap.'),
 dict(id='P03',title='The snap',story='The wooden grip breaks. Iven’s left hand stays on the iron rim while his right hand recoils with the detached long piece. His eyes widen. A short wooden stub remains fixed to the same rim point.',copy=[line('P03',1,'','KRAK','sfx')],target_height_at392=294,aspect_ratio='4:3',shot='Tight three-quarter detail of both hands, rim, clear break gap and Iven’s startled eyes/upper face.',camera=dict(location=[-2.15,-3.1,2.23],target=[-.76,-.67,1.66],lens_mm=72),blocking=dict(iven=[-1.05,-.95,.35],mara=[-2.2,-.9,.35],creature=[-2.8,1.2,0]),required_visible=['Exactly two wooden pieces:0.05m mounted stub and0.13m detached remnant','Visible air gap between matching jagged ends, not a merely drawn seam','Left fingers still around iron rim at10 o’clock','Right fist and detached remnant visibly separate from wheel','Traceable sleeve origins and startled Iven eyes'],action='The right fist recoils southward and slightly upward. Stub stays at3 o’clock. Show one clean snapped joint; no spray of loose splinters that could be mistaken for extra fragments.',expression='Iven startled embarrassment; his boast visibly collapses.',continuity='Gate remains closed; wheel has not rotated. Remnant stays in anatomical right hand thereafter.'),
 dict(id='P04',title='Use the rim',story='Iven has stepped aside with the broken grip. Mara plants a wide stance and turns the iron rim with both hands. The gate begins to rise; the creature still waits upstream.',copy=[line('P04',1,'MARA','Use the wheel.')],target_height_at392=490,aspect_ratio='4:5',shot='Low-to-eye-level full-body action view of Mara, both planted sandals, wheel and lifting gate in one frame.',camera=dict(location=[-3.6,-5.5,2.45],target=[-.62,-.12,1.25],lens_mm=45),blocking=dict(iven=[-1.9,-1.12,.35],mara=[-.85,-.96,.35],creature=[-2.8,1.2,0]),required_visible=['Mara’s complete powerful plus-size body, grounded wide stance and both sandals','Both palms/fingers touching opposite iron rim positions, not wooden stub','Wheel has turned45° clockwise viewed from south; stub at4:30','Gate bottom visibly lifted0.75m from waterline','Iven clear at frame left with right-hand wooden remnant','Creature still upstream, not beneath half-open gate'],action='Mara leans through a clear hip-and-shoulder twist, turning clockwise. Her left hand is near9 o’clock and right near2 o’clock at this depicted instant; neither hand uses the wooden stub.',expression='Mara focused, matter-of-fact effort; Iven sheepish, watching.',continuity='Mid-action state only: total quarter-turn is not complete. No extra lever or new gate. Water level unchanged; only a few small ripples.'),
 dict(id='P05',title='A clear passage',story='The gate is fully raised. The creature has passed downstream. Mara has walked around the south pier and rests one open palm gently on its near shell edge as it glides by. Iven still holds the remnant.',copy=[],target_height_at392=261,aspect_ratio='3:2',shot='Wide south-side view, same travel direction asP01, all of creature and clear opening visible.',camera=dict(location=[-3.8,-8.0,3.1],target=[.45,.65,1.05],lens_mm=40),blocking=dict(iven=[-1.4,-1.05,.35],mara=[1.45,-.22,.35],creature=[1.85,1.2,0]),required_visible=['Gate fully raised with1.5m clear opening and visible water beneath','Wheel at90° clockwise; fixed short stub now at6 o’clock','All four broad creature tentacles completely downstream of gate','Mara’s feet on ledge, open anatomical LEFT palm gently touching near shell edge','Iven and his right-hand remnant still present at frame left'],action='Creature travels left-to-right; Mara touches shell at[1.65,.55,.92] without pulling it or standing in water. Its nearest tentacle remains in canal. Passage follows the wheel action.',expression='Mara soft satisfied smile; creature calm and receptive; Iven subdued.',continuity='Opening remains raised. Creature is the same size/design and has not duplicated. No new wound, wet-clothing gag, loose wood or extra prop.'),
 dict(id='P06',title='Credit where due',story='Iven joins Mara downstream and displays the broken grip in his right hand with a small defensive smile. Mara answers with one raised brow. The gate remains raised behind them; the creature continues rightward.',copy=[line('P06',1,'IVEN','I loosened it.'),line('P06',2,'MARA','Obviously.')],target_height_at392=294,aspect_ratio='4:3',shot='Medium two-shot, faces and right-hand remnant prominent; open gate readable in quiet background left.',camera=dict(location=[-1.75,-4.8,2.2],target=[.95,-.48,1.68],lens_mm=55),blocking=dict(iven=[.55,-.86,.35],mara=[1.35,-.44,.35],creature=[3.3,1.2,0]),required_visible=['Iven’s refined adult face and Mara’s broad adult face, different readable expressions','Same0.13m detached wooden remnant displayed in Iven anatomical RIGHT hand','Open gate remains behind at left; no reclosed barrier','Mara stands relaxed with empty hands; creature may be partly visible exiting frame right'],action='Iven raises the remnant only to chest height; left hand empty. Mara turns her head toward him without taking the wood.',expression='Iven sheepish self-justification; Mara deadpan raised brow, slight amused mouth.',continuity='No repaired crank, replacement wheel, identity/costume change or owner-favorite implication.')
]
plan=dict(schema='VisualRefinementSequencePlan/1',experiment_id='VR-20260907-01',title='I loosened it.',status='Frozen story and copy; provisional technical styles pending; not owner-approved artwork.',provisional_styles=[],lettering_policy='No raster lettering. Exact copy below each panel in separate HTML/SVG until candidate-specific placement is reviewed. No default overlay bounds.',panels=panels)
world=dict(schema='SimpleCanalSequenceControl/1',experiment_id='VR-20260907-01',units='metres; Z up; canal/worldX flows left-to-right; all cameras stay south(Y<0)',coordinate_use='Authoring/camera contract only, not claimed recovery of generated 3D geometry.',water=dict(y_range=[0,2.4],surface_z=0,level_change=0),south_ledge=dict(y_range=[-1.4,0],top_z=.35),arch_gate=dict(plane_x=0,opening_y=[0,2.4],opening_height=2.2,gate_motion='Vertical; upper gate retracts behind arch masonry',south_pier='At canal edge; dry walkway remains south of it. No second gate.',closed_bottom_z=0,mid_bottom_z=.75,raised_bottom_z=1.5),wheel=dict(center=[-.8,-.55,1.4],radius=.4,plane='XZ, facing south',rotation_direction='Clockwise as seen from south',plain_mount='One post/box. Optional single unobtrusive cable to adjacent gate jamb; no elaborate linkage.'),wooden_grip=dict(intact_length=.18,mounted_stub_length=.05,held_remnant_length=.13,grip_direction=[0,-1,0],intact_axis_endpoints=[[-.4,-.55,1.4],[-.4,-.73,1.4]],break_point=[-.4,-.60,1.4],P03_stub_endpoints=[[-.4,-.55,1.4],[-.4,-.60,1.4]],P03_remnant_endpoints=[[-.4,-.93,1.48],[-.4,-1.06,1.48]],P04_stub_endpoints=[[-.517157,-.55,1.117157],[-.517157,-.60,1.117157]],P05_P06_stub_endpoints=[[-.8,-.55,1.0],[-.8,-.60,1.0]],ownership='Iven anatomical RIGHT hand, P03 throughP06; never Mara or left hand.',no_debris=True),creature=dict(count=1,tentacles=4,body_length=1.7,body_width=1.3,dome_top_z=1.05,calm_round_face=True,movement='UpstreamX−2.8 P01–P04; downstreamX+1.85 P05; continuingX+3.3 P06',near_shell_touch=[1.65,.55,.92]),states=[dict(panel=f'P{i:02}',gate_bottom_z=z,wheel_clockwise_degrees=rotation,grip=grip,creature_side=side) for i,z,rotation,grip,side in [(1,0,0,'intact','upstream'),(2,0,0,'intact','upstream'),(3,0,0,'broken','upstream'),(4,.75,45,'broken','upstream'),(5,1.5,90,'broken','downstream'),(6,1.5,90,'broken','downstream')]])
assert len(panels)==6 and sum(len(p['copy']) for p in panels)==6
assert abs(world['wooden_grip']['intact_length']-world['wooden_grip']['mounted_stub_length']-world['wooden_grip']['held_remnant_length'])<1e-9
assert all(p['camera']['location'][1]<0 for p in panels)
dump(P/'panel-plan.json',plan);dump(P/'scene-control.json',world)
common='''Use the two frozen common identity/setup sheets for Iven, Mara, the single jellyfish-turtle and this simple canal landing. Apply only the selected provisional rendering treatment. Both people remain unmistakably adult. Iven27: slim dancer build, refined long oval face, wine-red low-tied long hair, pearl earring, ivory poet sleeves/plain plum waistcoat/black slim trousers/black boots. Mara38: powerful plus-size body, warm brown skin, broad nose/full lips, thick blue-black braid, plain ivory ceramic cropped vest/magenta trousers/wrapped sandals/one simple blue upper-arm band. Creature: one large-pony jellyfish-turtle, broad low shell/translucent umbrella dome/calm round face/exactly four broad tentacles. One broad arch, one straight canal, one low dry ledge, one plain handwheel post and one sluice. Quiet daylight, large open value areas. No captions, dialogue, SFX, signatures, annotations, labels or diagram arrows inside the raster. Keep the frozen panel composition and physical state identical across the three rendering treatments. Do not turn the blocking specification into technical diagram artwork.'''
text=['# Frozen panel briefs','',common,'']
for p in panels:
 text += [f'## {p["id"]} — {p["title"]}',f'Raster aspect: {p["aspect_ratio"]}. Shot: {p["shot"]}',p['story'],'Action: '+p['action'],'Expressions: '+p['expression'],'Continuity: '+p['continuity'],'Required visible: '+'; '.join(p['required_visible'])+'.','Exact separately lettered copy: '+(' / '.join((c['speaker']+': ' if c['speaker'] else '')+c['text'] for c in p['copy']) if p['copy'] else '(silent)'), '']
write(P/'panel-briefs.md','\n'.join(text)+'\n')
# Camera/blocking overhead SVG: editable vector planning only, never proposed finished panels.
svg=['<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="960" viewBox="0 0 1440 960"><rect width="1440" height="960" fill="#fffdf7"/><title>Sequence camera and blocking plan — schematic only</title>']
for i,p in enumerate(panels):
 x=(i%3)*480;y=(i//3)*480;svg.append(f'<g transform="translate({x} {y})"><rect x="12" y="12" width="456" height="456" rx="8" fill="#faf8ef" stroke="#adb5b9"/><text x="30" y="45" font-family="sans-serif" font-size="20">{p["id"]} · {p["title"]}</text><g transform="translate(240 180) scale(35 -35)"><rect x="-5" y="0" width="10" height="2.4" fill="#cee2e6"/><rect x="-5" y="-1.4" width="10" height="1.4" fill="#d7d1be"/><path d="M0 0 V2.4" stroke="#46515b" stroke-width=".16"/><circle cx="-.8" cy="-.55" r=".16" fill="#555e65"/>')
 for actor,color in [('iven','#754157'),('mara','#b54b78'),('creature','#688c9c')]:
  a,b,_=p['blocking'][actor];radius=.20 if actor!='creature' else .55;svg.append(f'<circle cx="{a}" cy="{b}" r="{radius}" fill="{color}"/>')
 cx,cy,_=p['camera']['location'];tx,ty,_=p['camera']['target'];svg.append(f'<path d="M{cx} {cy} L{tx} {ty}" stroke="#947a33" stroke-width=".06" stroke-dasharray=".12 .1"/><circle cx="{cx}" cy="{cy}" r=".14" fill="#947a33"/></g><text x="30" y="405" font-family="sans-serif" font-size="14">Purple Iven · rose Mara · slate creature · gold camera</text><text x="30" y="433" font-family="sans-serif" font-size="14">South camera; water travel left → right; schematic only</text></g>')
svg.append('</svg>');write(P/'blocking-cameras.svg','\n'.join(svg)+'\n')
manifest=dict(schema='FrozenSequenceSourceManifest/1',at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),approved_by='Lead internal story approval, not owner art acceptance',experiment_source_sha256=hashlib.sha256((ROOT/'research/visual-refinement/experiment.md').read_bytes()).hexdigest(),files=[dict(path=p.relative_to(ROOT).as_posix(),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),bytes=p.stat().st_size) for p in [P/'panel-plan.json',P/'scene-control.json',P/'panel-briefs.md',P/'blocking-cameras.svg']],generation_calls=0,paid_spend_usd=0)
dump(P/'source-manifest.json',manifest)
print(json.dumps({'panels':6,'copy_items':6,'plan_sha256':manifest['files'][0]['sha256'],'state_sha256':manifest['files'][1]['sha256'],'generation_calls':0},indent=2))
